### ISSUE TITLE
Exporting Provides Only Styles

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#10]
When using the export function on the demo site I only get files with styles. The created content doesn't appear to be added to the download.

**Comment by bagrinsergiu** [comment]
@CJKrets - can you give me Brizy Demo url.

Thanks for reporting.

**Comment by CJKrets** [comment]
Hi,

I tried exporting from your own demo. Didn't see any way to export on my self install, but that is acting up so that could be why.

http://g0pemv3n21d4q82.brizydemo.com/editor

**Comment by bagrinsergiu** [comment]
Hi Corey,

We added a new update. 

PC + Chrome Test: http://dl3.joxi.net/drive/2018/05/10/0028/0732/1860316/16/8014f7b8d6.jpg

Can you confirm if the export is working for you?

Thank you

**Comment by bagrinsergiu** [comment]
Reply: Just writing to confirm that I've tested the Brizy website demo from here and the export functionality appears to be working fine now.
