### ISSUE TITLE
[ERROR] Your theme must use the the_content filter in order for Brizy to work

### ISSUE THREAD

**Issue by jwarnox** [ThemeFuse/Brizy#1002]
**Brizy Editor will not load on any page now.**

Your theme must use the the_content filter in order for Brizy to work

![screen shot 2018-12-19 at 11 34 03](https://user-images.githubusercontent.com/35316/50219249-872ec100-0386-11e9-91fa-ce8d6f632252.png)

This error is in the console:

editor.js?ver=1.0.78:1 Editor Bootstraps error TypeError: Cannot read property 'project' of null
    at globals (editor.js?ver=1.0.78:1)
    at editor.vendor.js?ver=1.0.78:66
    at editor.js?ver=1.0.78:1
    at y (editor.vendor.js?ver=1.0.78:66)
    at editor.js?ver=1.0.78:1
    at editor.js?ver=1.0.78:1
    at a (editor.js?ver=1.0.78:1)
    at o (editor.js?ver=1.0.78:1)
    at Object.dispatch (editor.vendor.js?ver=1.0.78:87)
    at Promise.resolve.then.then.then.o (editor.js?ver=1.0.78:1)

Please feedback ASAP as this is a dev site and client is requiring changes to be made.

Thanks.

**Comment by jwarnox** [comment]
![image](https://user-images.githubusercontent.com/35316/50217920-1c7b8680-0382-11e9-8f0a-0a422d8a8d23.png)

**Comment by NataliaBB** [comment]
Hey Jamie @jwarnox

Natalia here. 
The message: "Sorry, Brizy could not load" refers to a template who hasn't "the_content" filter. 
You need to change the template.

Next, when you will change the template - https://jmp.sh/vSezY9m , the editor may keep loading, then you will see in the console the message "Cannot read property 'project' of null". If you the console have this error, then send me a message via our facebook chat in order to fix it.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by abdul1903** [comment]
@NataliaBB can this issue be re-opened...? I am facing the issue even though Brizy template is chosen.
[Click here](https://cl.ly/d5d4f55d09e1)

**Comment by codeclinic** [comment]
Me too!

**Comment by akwright** [comment]
@abdul1903 @codeclinic Are you both using WooCommerce themes? I'm getting this issue when I attempt to use Brizy to edit the Shop page.

**Comment by jason-yankee** [comment]
Yes, I am using it. And You need to create a New Page ( WIth the name of your Product ) and in wooCommerce go to settings and Products change the setting to the New page that you created.  
This will allow you to continue to edit your page.  
![image](https://user-images.githubusercontent.com/30211425/59284913-af490e00-8c9f-11e9-9548-867e08db61b9.png)

**Comment by trick3d0ut** [comment]
Hello Natalia,  I just got this error message today 11/18/2019 is there a solution for it? I am using the Astra Theme making a blog page...I tried switching between the default template and Brizy template, but I get the same error message as you can see in the link...thanks in advance for the help!  

![Brizy the_content filter issue] 
(https://user-images.githubusercontent.com/52720427/69065831-2dd77380-09d5-11ea-9173-310f466585ab.PNG)

**Comment by codeclinic** [comment]
Oh look, the ticket was closed without resolution. Again.

**Comment by JGV1545** [comment]
I received the same error as trick3d0ut. It occurs while I am trying to apply the template to my Posts Page. I've tried to create a separate blog posts page and applying the Brizy template with no luck. The page that contains my blog posts uses the default layout from the Astra Theme. It does the same thing with Page Builder Framework. Is there a resolution for this?

> Hello Natalia, I just got this error message today 11/18/2019 is there a solution for it? I am using the Astra Theme making a blog page...I tried switching between the default template and Brizy template, but I get the same error message as you can see in the link...thanks in advance for the help!
> 
> ![Brizy the_content filter issue]
> (https://user-images.githubusercontent.com/52720427/69065831-2dd77380-09d5-11ea-9173-310f466585ab.PNG)

**Comment by sanks20** [comment]
Any updates on this?! I followed Brizy's Youtube tutorial on creating templates for a Blog post (found here: https://www.youtube.com/watch?v=cWJEetL4f-s) and now I have the same issue as  JGV1545 and trick3d0ut. I'm also using the Astra theme.

Please help!
