### ISSUE TITLE
Brizy update wipe put all content 

### ISSUE THREAD

**Issue by purewaterman** [ThemeFuse/Brizy#1005]
Hello 

I upgrade the builder from 1.0.18 to 1.0.53 and it wiped all content. I was able to use a backup so no harm was done. Can you please let me know how this can be fixed? 

Thanks for your help 

Heinrich

**Comment by NataliaBB** [comment]
Hello @purewaterman 
Natalia here, Brizy team

Please send me a message via our Facebook chat and mention this issue number #1005  inside.  We will try to recover all content.

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
