### ISSUE TITLE
Editor content doesn't match web content/ keeps spinning

### ISSUE THREAD

**Issue by oneofonedesign** [ThemeFuse/Brizy#1006]
Our client has WP 5.0.1 and currently the 1.0.35 version of Brizy does not allow for edits to be updated/ published. We tried updating to 1.0.53 and the site dies / throws a 500 error.

msofc.org 
<img width="1330" alt="500 error after updating brizy plugin" src="https://user-images.githubusercontent.com/46009700/50252345-53ff2880-03ac-11e9-9700-3acc69f5fa43.png">
<img width="1116" alt="faq section on website" src="https://user-images.githubusercontent.com/46009700/50252346-5497bf00-03ac-11e9-86f3-21919cd8085d.png">
<img width="1304" alt="q cannot be found to edit in brizy" src="https://user-images.githubusercontent.com/46009700/50252348-5497bf00-03ac-11e9-8126-aa2a60bfa923.png">

**Comment by NataliaBB** [comment]
Hello @oneofonedesign 
Natalia here, Brizy team!
Please send me your wp and fttp credentials via our facebook chat, please mention this issue number inside - #1006 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by oneofonedesign** [comment]
Hi Natalie,

We don't have a FB account, so I'm unable to discuss via Messenger. Please let me know if we can coordinate over email — thanks!

**Comment by oneofonedesign** [comment]
Natalia* -- sorry about that!
