### ISSUE TITLE
Editor mode has issues with dynamic urls for custom page templates

### ISSUE THREAD

**Issue by andrew-lof** [ThemeFuse/Brizy#101]
Hello, I have purchased the Pro version but have run into an issue.

I was working on a custom post type page template. Where I want to show some dynamic content based on the URL. I am using the PHP code "isset( $_GET['typage']" to show the body content which is created with Brizy otherwise the page will not show the body content and show some custom ACF values for the page instead. This works well. 

https://corporateweb.wpengine.com/resources/webinar-on-ehr/?typage

But this issue arrises when a User is logged in to wordpress and wants to edit the page with Brizy. When you go into editor mode it appends "?brizy-edit" to the page url. The editor does not appear and the admin wrapper disappears as well. I even check for the "brizy-edit" variable in the page template to default to showing the body content. See my code below:

`// Check to see if page is in Brizy editor mode  
			if(isset( $_GET['brizy-edit'])) { 
			echo "brizy-edit";
		    	//Editable body content that is coming from Brizy
			the_content();
		   // Populate the Post body conten if the 'typage' value is in the URL 
=} `

Is there a way around this issue?

Thanks

**Comment by bagrinsergiu** [comment]
Hi Andrew @andrew-lof, 

Thanks for reporting.
I will back latter with details

Sorry for the inconvenience.

Sergiu

**Comment by andrew-lof** [comment]
Thanks for looking into it @bagrinsergiu. Let me know if you have any questions.

**Comment by andrew-lof** [comment]
I found a work-a·round for my issue by checking if the user is logged in to always load the body content so that Brizy loads at the start. Here is some more info on what I discovered:

It looks like that you can not check if a page is in Brizy editor mode based on the URL parameter “?brizy-edit” once Brizy is loaded.  In PHP, the code “if(isset( $_GET['brizy-edit']))“ will still return false if the Brizy Editor is already loaded on a page. My guess is that it is caused by the way React effects the URL routing of a page once the editor is loaded.   Another example is that if you have other page links on a page loaded from the template content and click on them while the Brizy editor is loaded, the url won’t change even though the content changes.  Once the editor is loaded URL parameter checking with PHP no longer works. 

Feel free to close this Issue. Thanks
