### ISSUE TITLE
Blank Page in Preview and Live Mode

### ISSUE THREAD

**Issue by anant9200** [ThemeFuse/Brizy#1012]
Hi,

Home Page and all other pages are currently blank in preview and live mode.

Can you help me here?
proimage.in

Cheers,
Anant

**Comment by NataliaBB** [comment]
Hello Anant! @anant9200 
I have sent a message to you via our Facebook chat. Waiting for your reply.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
