### ISSUE TITLE
Mobile view bugs

### ISSUE THREAD

**Issue by WillowTree1** [ThemeFuse/Brizy#1015]
Some of the adjustments to the templates are not showing on the mobile view. For example, background images have not updated. Background colours are not the same as desktop and nor is the text colour. You can see the differences on this page https://soulexpressionalchemy.com/2019-energetics-academy/
In some blocks the default template is showing on mobile but not on desktop. This means that some blocks are not showing key information on mobile or the visuals are inconsistent.

**Comment by dannymarkbrown** [comment]
Hi, 
I had the same issue, I found a fix. 
You have the view icon on the side, change the view to mobile and then change the photo on the block for the mobile view. 

Hope this helps :)

**Comment by WillowTree1** [comment]
Thank you! Much appreciated.

**Comment by NataliaBB** [comment]
Hello @WillowTree1 

Natalia here!
If you still need help on this issue, please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

@dannymarkbrown Thanks!


Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
