### ISSUE TITLE
Popup Anchor Link

### ISSUE THREAD

**Issue by allardo** [ThemeFuse/Brizy#1016]
I would like to use an anchor link in my popup to an block on the page. The link works but the popup stays in place where it should close automatically. Could this get fixed?

**Comment by NataliaBB** [comment]
Hey @allardo 
Thanks for reporting this. 
I've created an issue with this bug, and @bagrinsergiu will look up into it
My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
