### ISSUE TITLE
[BUG] Unable to set numbers higher than slider range

### ISSUE THREAD

**Issue by adegbengaagoro** [ThemeFuse/Brizy#1017]
I would like to display more than 10 rows for the posts while using the WP Posts Component but every time I set a number higher than 10, it just jumps back to 10. I used to be able to do this in earlier versions of Brizy but I can't any more. I am using Brizy Pro

Here is a screenshot of what I am referring to:

<img width="334" alt="screen shot 2018-12-30 at 9 28 33 am" src="https://user-images.githubusercontent.com/5008453/50545483-6e8b9a00-0c15-11e9-9764-8fb88a4b7785.png">

I have also set "**Blog pages show at most 20 posts**" under "**Settings -> Reading Settings**" in WordPress but this doesn't have any effect whatsoever on the situation.

**Comment by NataliaBB** [comment]
Hey @adegbengaagoro 

Natalia here, Brizy team!
Please send me a message via our Facebook chat and mention this issue inside - #1017

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
