### ISSUE TITLE
Cannot access affiliates area on the Brizy website

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#102]
I have bought Pro Lifetime license and I am trying to access the affiliates area while logged in to my existing account but I don't see anything affiliate related in there. Is the affiliate area not ready yet?

**Comment by quantumleap33** [comment]
Sorry, just saw info on page about contacting you first!

**Comment by bagrinsergiu** [comment]
Affiliates Link: https://brizy.io/affiliates/

**Comment by quantumleap33** [comment]
I did that, then messaged you on Facebook giving you my email, Bogdan replied and gave me the exact same link. I told him again that the reason I contacted you in the first place was to give you my email because you need to activate my affiliate status manually! Haven't gotten a reply yet. I think you need to sort that one and communicate it better between your team. You mention on the website that people should contact you giving you their email for affiliate status activation and when they do that, you redirect them to the same link that says the exact same thing!

**Comment by alexluncashu** [comment]
Hi,

sorry for late response. Please try now. You should see affiliate link in the menu. You should add your PayPal email for the payments.

**Comment by DimiBaitanciuc** [comment]
@quantumleap33 Hey, we just launched the Affiliate program. Please excuse us for the little issues in regards to the communication. I've modified the page to better reflect what the process entails. 

1. you subscribe
2. receive and email from us (your affiliate status at this point is pending)
3. you reply with the details we ask for there (your website URL and a short description on how you plan to promote us)
4. we read the email and activate your account (or not)

This is the process (starting from yesterday our time GMT+2)

If you subscribed before that, I'm not sure the emails will come. If you would like give me these details here and let me know your ThemeFuse email as well and I'll activate your account. 

If you don't want to share them here: email me on hello@themefuse.com ;) 
Hope this helps. 

Thanks for choosing to promote Brizy.

**Comment by quantumleap33** [comment]
No change, same as before...
[https://ibb.co/fYN5Xo](url)

**Comment by alexluncashu** [comment]
ah, ok .. give me your email at hello[at]themefuse.com

**Comment by quantumleap33** [comment]
Ok done!
