### ISSUE TITLE
Unwanted Links when previewing edits of pages

### ISSUE THREAD

**Issue by Supo65** [ThemeFuse/Brizy#1020]
Hi, maybe this has been answered didn't find anything when I did a search but I'm starting to get unwanted links when preview my page from somewhere called PackTrackPlus Promotions. While they don't seem to show when viewing my site online it makes me think that I've been hacked or back linked somehow. It's starting to get annoying and make me worry that they are trying to get free traffic from my site somehow. Has this happened to any?? I am attaching a screenshot so that you can see what I mean. 

![screen shot 2018-12-31 at 1 14 21 pm](https://user-images.githubusercontent.com/40869456/50566447-c1418080-0cff-11e9-9b66-b4e7aef8e19b.png)

**Comment by NataliaBB** [comment]
Hey @Supo65 
Natalia here, Brizy team.
What is your page URL? Could you please check what plugins do you have installed? Please disable them and try to find where it came this spam. 

Thanks, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
