### ISSUE TITLE
Homepage has gone off format

### ISSUE THREAD

**Issue by robbieroche** [ThemeFuse/Brizy#1023]
I logged onto my wordpress site today and my homepage looks all different, It seems as if the theme is gone but its wokring fine on all other pages

**Comment by NataliaBB** [comment]
Hello @robbieroche 
Natalia here, Brizy team
Apologizes for my late reply. 
Please send me a message via our Facebook chat and mention this issue inside - #1023

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
