### ISSUE TITLE
Brizy live page error

### ISSUE THREAD

**Issue by hesovay1** [ThemeFuse/Brizy#1024]
Hi,

When i added the eighth blank, page looks corrupted on the live. Have you ever experienced this problem before? BTW. In localhost everything looks normal.

https://i.hizliresim.com/v65ANA.png

Thanks,

**Comment by NataliaBB** [comment]
Hello!
Natalia here!
If you still have this issue, please submit a ticket here: https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia
