### ISSUE TITLE
Keyboard shortcuts [enhancement]

### ISSUE THREAD

**Issue by UniversalDesignz** [ThemeFuse/Brizy#1027]
Hi @NataliaBB 
We would love to get the **Keyboard shortcuts** as soon as possible to exhilarate speeding work. 

Kindest Regards
Jay Vijay

**Comment by NataliaBB** [comment]
Hello @UniversalDesignz 
I've created an issue for @bagrinsergiu. He will look over it.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
