### ISSUE TITLE
Edit Mode can't see symbols or delete [Bug]

### ISSUE THREAD

**Issue by UniversalDesignz** [ThemeFuse/Brizy#1028]
Hi @NataliaBB 

We can't seen any symbole in edit mode or delete.

Kindest Regards
Jay Vijay

**Comment by NataliaBB** [comment]
Hello Jay @UniversalDesignz 
I've sent you a message via our facebook chat regarding this question

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by UniversalDesignz** [comment]
Sorry but we do not trust Facebook at all with especially with credentials. You guy seriously need to look for an alternative.
