### ISSUE TITLE
Form button link redirect to select from existing page

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#103]
It would be nice if the **Go to** field on a submit form button link would act as a dropdown where a particular existing page could be selected instead of manually typing it in. It would be musch easier for beginners and clients as it would keep them on the builder page as they woudn't have to go to a different page to find out what that link is.

**Comment by bagrinsergiu** [comment]
Hi @quantumleap33 - This feature is in our to do list. Right now our list is so long :)

Thank you for suggestion.
Sergiu

**Comment by quantumleap33** [comment]
Ok just thought I would ask anyway!

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
