### ISSUE TITLE
Pro Form not working on tablet, i.e. iPad.

### ISSUE THREAD

**Issue by gittyap** [ThemeFuse/Brizy#1030]
Pro forms not submitting emails on iPad. Is there a fix? Will it ever come to work??

**Comment by NataliaBB** [comment]
Hello @gittyap 
Can you please give us more details? I've tried to test on our Ipad and everything works ok.
Could you please send me a project url?

You can also send a message via our facebook chat. Please mention the #1030 number in your message.

Thank you!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
