### ISSUE TITLE
Wordpress Widgets insert option not available!

### ISSUE THREAD

**Issue by manusstar** [ThemeFuse/Brizy#1031]
Hi, Surprised to see that Wordpress Widget insert option is not available in Brizzy builder, whereas all other page builders have this feature in free version itself. Here we could see only 'Sidebar', 'Shortcode' and 'Menu' options available in widgets area. But in some plugins, we would surely need calling 'widgets' into the page using builder, as they have some customization options. Here calling widgets using shortcodes will not work. Please provide some solutions. For time being i am uninstalling the pagebuilder as i am not able to use some of my plugins.

**Comment by NataliaBB** [comment]
Hello @manusstar 
Natalia here!
We do have WP widget in our to do list. https://trello.com/c/guXtVHgE/68-wp-widgets
A little more time, and those widgets will be added in the sidebar.

My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
