### ISSUE TITLE
URL not saving when trying to link

### ISSUE THREAD

**Issue by mamionajourney** [ThemeFuse/Brizy#1033]
I keep trying to change the link associated with a button on my homepage however, it keeps reverting back to an old link.

**Comment by NataliaBB** [comment]
Hello @mamionajourney 
Natalia here, Brizy team

Apologizes for the late reply. Could you please send me a message via our Facebook chat and mention this issue inside - #1033

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
