### ISSUE TITLE
Brizy editor icon keeps spinning, can't edit wordpress pages

### ISSUE THREAD

**Issue by fbadtargeting** [ThemeFuse/Brizy#1036]
Continuing problems with Brizy editor... first it was that the pages weren't saving using the save button where it was just keep processing, now, I can't load the editor. Am frantic because I have a book launch tomorrow and my website can't be updated with the latest information. Please help!!!

**Comment by NataliaBB** [comment]
Hello @fbadtargeting 
Natalia here!
What plugin version do you have installed? What other plugins do you have installed? Did you tried to disable them and check the editor.
Also, please send me your wp credentials via our Facebook chat I will check this issue and fix it asap.

![Uploading 3uoxxwMt5_xNeBnahZaJYrYjU-adBjy_YhJv8QOwLGwWVtnzaCXwfnphXC42yneuWJuLaaHEF8s6hqr82aHVdd0Iq-_ZMIwlJNqsu6s4bO0F1kR3dMUjedqC16uBUu85.png…]()

Please, mention this number issue inside  - #1036
Thank you!
Regards, Natalai

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by fbadtargeting** [comment]
Hello! I'm having the same problem again with the editor not loading. I open one of my pages that I edited with Brizy and I get a spinnng circle that won't stop. Can you please help and can you figure out what the problem is that this keeps happening. I have the editor loaded on several sites and it happens with each site until you do something with the code in each site. Can you please help me as I am up against a deadline and can't finish because of problems with the editor.
