### ISSUE TITLE
Face-Icons do not have eyes when loaded

### ISSUE THREAD

**Issue by lalare67** [ThemeFuse/Brizy#1037]
Icons showing a face do have eyes in the overview where you pick them. Once picked and loaded the eyes get lost and the icons are not recognizable anymore, therefore not usable.
Please make the eyes stay.

**Comment by NataliaBB** [comment]
Hello @lalare67 
Natalia here!
Could you please give me a screenshot of the icons who don't show yes in preview mode?
I've tested all of them, they don't change in the preview mode.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
