### ISSUE TITLE
#1006 & #1007

### ISSUE THREAD

**Issue by oneofonedesign** [ThemeFuse/Brizy#1039]
My issues (#1006  and #1007 ) keep getting "closed to keep the database slim" but we have not heard back from Natalia on the Brizy team regarding any solutions to our issues. It's now been 20 days since the first post, we've emailed multiple times (natalia@brizy.io), and our site is still broken and unable to be edited through Brizy or any other way. 

Please reply directly to my email from rashina@oneofonedesign.co as soon as possible, so our client's business is no longer on hold while this issue persists. 

Thank you.

**Comment by NataliaBB** [comment]
Hello Rashina!
The issue has been fixed already. 
Sorry again for my late reply.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
