### ISSUE TITLE
Blog on Homepage

### ISSUE THREAD

**Issue by mamionajourney** [ThemeFuse/Brizy#104]
I am loving this editor. Truly. However, I can't figure out how to add my blog feed to my homepage. I want to have multiple items on my homepage, including the blog feed. How do I do that?

**Comment by ash-f** [comment]
blog(posts) element is not implemented yet.

**Comment by github52341123** [comment]
I am also missing this feature.

**Comment by bjergca** [comment]
This feature would make Brizy way more interesting for me.

**Comment by NataliaBB** [comment]
Brizy Roadmap Link: https://trello.com/c/rGs87TDQ/48-posts

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
