### ISSUE TITLE
Update fails when clicked on update

### ISSUE THREAD

**Issue by UniversalDesignz** [ThemeFuse/Brizy#1040]
Hi @NataliaBB 

We received the following message "There is a new version of Brizy Pro available. View version 0.0.16 details or update now."
But when we try to click on update now it throws an error "Update Failed: Download failed. Unauthorized"

![brizy failed to update](https://user-images.githubusercontent.com/15095585/50917431-61508580-1435-11e9-966b-2e0883a1f21f.png)

**Comment by NataliaBB** [comment]
Hi Jay  @UniversalDesignz 
Waiting for some details on the chat...

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by UniversalDesignz** [comment]
Hi @NataliaBB 

Once again

The update process is starting. This process may take a while on some hosts, so please be patient.

Enabling Maintenance mode…

Updating Plugin Brizy Pro (1/1)
An error occurred while updating Brizy Pro: No activation found for this installation

Disabling Maintenance mode…

All updates have been completed.
