### ISSUE TITLE
email form failing "Your email was not sent"

### ISSUE THREAD

**Issue by lbackstrom** [ThemeFuse/Brizy#1045]
In Version 1.0.55 and Pro 0.0.16 getting this error on email form submit "Your email was not sent".
Using SMTP. Is it Brizy or my SMTP plugin "WP MAIL SMTP"?

Here is the stack trace:
[12-Jan-2019 06:22:50 UTC] PHP Fatal error:  Uncaught Error: Call to a member function hasIntegrations() on null in /home4/debbilermond/public_html/wp-content/plugins/brizy/editor/api.php:322
Stack trace:
#0 /home4/debbilermond/public_html/wp-includes/class-wp-hook.php(286): Brizy_Editor_API->submit_form('')
#1 /home4/debbilermond/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#2 /home4/debbilermond/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /home4/debbilermond/public_html/wp-admin/admin-ajax.php(99): do_action('wp_ajax_brizy_s...')
#4 {main}
  thrown in /home4/debbilermond/public_html/wp-content/plugins/brizy/editor/api.php on line 322

**Comment by NataliaBB** [comment]
Hi @lbackstrom!

Natalia here, Brizy team!
I would like to check and test the form from your page. Could you please send me a message via our Facebook chat and mention this issue inside - #1045

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by Ivanov-Anton** [comment]
So how resolve this problem? NataliaBB
