### ISSUE TITLE
My mobile view doesn't show in browsers

### ISSUE THREAD

**Issue by BrijeshGarg** [ThemeFuse/Brizy#1047]
Hello, I finished creating a website with brizy using the WP Bridge theme and I noticed my mobile view doesn't show in browsers.

Here is my website: https://www.theimpactmedia.com/ebook/

I have no issues with desktop just mobile for some reason.

**Comment by BrijeshGarg** [comment]
If you fill the form and submit the download button.  Getting the below error in Safari and IOS.

Resource violated directive 'script-src 'self' ms-appx-web:' in meta http-equiv="Content-Security-Policy">: script eval. Resource will be blocked.

Please help!

**Comment by NataliaBB** [comment]
Hey @BrijeshGarg 
I filled the form in Safari/iOs and the message has been sent successfully: I've received "Your eBoook is ready for download".

![image_from_ios_720](https://user-images.githubusercontent.com/36154919/51106160-a426aa80-17f3-11e9-82ee-878141ee07f8.png)
![image_from_ios](https://user-images.githubusercontent.com/36154919/51106165-a6890480-17f3-11e9-9d83-a81f4cec79e7.png)

Please, let me check the form and try to run some tests on your wp dashboard. 
Please send me a message via our Facebook chat and mention this issue inside - #1047


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by BrijeshGarg** [comment]
![whatsapp image 2019-01-14 at 3 33 46 pm](https://user-images.githubusercontent.com/46645065/51106821-e90e0980-1812-11e9-94e1-3fe0849cc414.jpeg)

I have tried on iphone6 .. It's not working. Please attached the screenshot.

**Comment by NataliaBB** [comment]
@BrijeshGarg 
Ok, let me check the form please. 
Waiting for your message on our chat. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by BrijeshGarg** [comment]
Ipad screenshot.

![whatsapp image 2019-01-12 at 10 48 22 am](https://user-images.githubusercontent.com/46645065/51107344-903f7080-1814-11e9-8d04-af683d5b0946.jpeg)

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
