### ISSUE TITLE
My Theme Is Overwritten

### ISSUE THREAD

**Issue by ntrend70** [ThemeFuse/Brizy#1048]
Noticing when using the editor it over powers my theme headers and menus. This isn't good due to I like my theme that I have I am using socrates 5 is there a way to stop it from overpowering the theme so I can use the settings in my theme as they are designed to be used?

**Comment by NataliaBB** [comment]
Hello Jeremy! @ntrend70 
Natalia here.
Received your message via our chat,  therefore let's continue to work there

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
