### ISSUE TITLE
Brizy just doesn't work

### ISSUE THREAD

**Issue by RicardoRG** [ThemeFuse/Brizy#1049]
It's absolutely impossible to add images WHEN I SELECT IMAGES from the wordpress library or directly uploaded from my computer.

I've never had the chance to use Brizy to build a single page on my blog, the images just don't load and at the preview it's impossible to see the images i've used or even worse, can't see anything at all, just a blank page.

The idea of Brizy is pretty cool but it just don't work, what a waste of time.

BTW, my template includes Brizy and other front-end editors, I've tried deactivating and uninstalling the other plugins, can't really find the problem for the images and several other elements when I try to build a page... Hope you guys fix it but really doubt it, since the begining Brizy is just not working, totally dissapointed.

BTW, I've already tried removing .htaccess file, and modifying it, also checked that rewrite modis enabled and even checked that my .conf file at the domain configuration file is all good. Even tried changing the permalinks structure and going back to my prefered permalinks structure, nothing of that worked, dont' know what else can I do but ask you guys for make it work properly.

The image shows what I'm talking about, it always happens, no matter what image i use...

![x](https://user-images.githubusercontent.com/1551695/51095383-5160da80-1782-11e9-86c9-863539644632.png)

**Comment by NataliaBB** [comment]
Hello @RicardoRG 
Natalia here! 
Sorry for the inconvenience. I assume you have the 404 error in the console, but I would like to check it directly from your dashboard.

Please send me a message via our Facebook chat and mention this issue inside - #1049


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by RicardoRG** [comment]
I don't use Facebook and won't open it for a chat.

I've found that probably is something happening with my server, will deploy a new server and relocate my blog so I hope it works.

> Hi!
> 
> I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
> 
> Regards. Natalia
