### ISSUE TITLE
Contact form issue

### ISSUE THREAD

**Issue by BrijeshGarg** [ThemeFuse/Brizy#1055]
add contact form using Brizy But when I submitted the contact form with all the details like email id name and phone number with msg and hit the send button then I got blank screen with 0

Total Blank and top left corner with 0 sign
I also add the email id on that button
Anyone help me in this case

**Comment by NataliaBB** [comment]
Hey @BrijeshGarg 
Natalia here!
As we spoke on the chat, I've made an issue for our team. I Will let you know when it will be fixed.
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by BrijeshGarg** [comment]
Hey Natalia,

 

When Can I expect the solutions?

 

Regards

Brijesh.
