### ISSUE TITLE
Slider Background and Elements in Brizy PRO [Enhancement]

### ISSUE THREAD

**Issue by UniversalDesignz** [ThemeFuse/Brizy#1057]
Hi @NataliaBB 

Can you please give us options:
1. Carousel Background to remain (load only once) the same, if we don't require to change the background on all slides no point of calling in the same background multiple times.
2. Only the individual Elements (text, content, Buttons and additional images and icons ) can slide, fade, bounce etc. the effect we chose slides and not the background.
3. Let us rotate elements.

**Comment by NataliaBB** [comment]
Hey Jay! @UniversalDesignz 
Thank you!
I already create an issue for @bagrinsergiu and he will look over his requirements.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
