### ISSUE TITLE
Transparent Header  

### ISSUE THREAD

**Issue by jervisdent** [ThemeFuse/Brizy#1059]
Is there  a way to make the header transparent and overlapping the content?

**Comment by pageoneclick** [comment]
+1 on this. I would like an option for a transparent sticky header menu, just as you have implemented on the Brizy.io homepage. Negative margin options for blocks are needed, to shift the block up and fill the space from the header. I was able to accomplish this with CSS, however, when I apply negative margin to the block below the header, I lose the ability to edit the block. The header block covers the edit button. I'm sure there's a way this can be neatly done.

**Comment by NataliaBB** [comment]
Hello @jervisdent , @pageoneclick 
Natalia here!
We do have in our list an improvement for the menu which will include a transparent header. 
For the moment, I recommend to use a CSS code for the block under the header.
Search the block ID, and write margin-top value, according to the height of the block (this is my example,but the code should be placed in the additioanl css from theme settings)
https://jumpshare.com/v/PoKYXVqR0z37ZKfRYpsX

The header block should also have the Overly set to 0%: https://jumpshare.com/v/M1DBbItytYNR10Lg2OUI

**Comment by Neneh** [comment]
Natalia,
Wanted to know the progress of this?
I believe this is a separate issue from the 'Transparent Toolbar' therefore should really have its own Trello Card on the Public Roadmap so we vote and monitor the progression.
Many thanks.

**Comment by spinmortgage** [comment]
+1

**Comment by NataliaBB** [comment]
Hello @Neneh 
Transparent toolbar and transparent header  are in our roadmap: 
https://trello.com/c/4TVixrLX/128-transparent-toolbar
https://trello.com/c/lUmCMpRd/216-transparent-header

Regards, Natalia

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
