### ISSUE TITLE
Intermittent "An error happened while trying to display this block" error

### ISSUE THREAD

**Issue by madrockxvx** [ThemeFuse/Brizy#1064]
I've updated all active plugins and the Wordpress install, but am still having issues. Sometimes the editor will load, more frequently it will not. I thought it may be related to SSL, but now I'm not sure as turning SSL off sitewide didn't work.

**Comment by NataliaBB** [comment]
Hello @madrockxvx 
Unfortunatly this error can be solved only by our dev team. 
Please send me a message via our Facebook chat and mention this issue inside - #1064

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
