### ISSUE TITLE
Images won't display

### ISSUE THREAD

**Issue by raemacias** [ThemeFuse/Brizy#1065]
Images either won't show in the Brizy editor or if they do show, they still won't display on any browser. 
One of the pages is here:
https://friendsforevercolorado.org/our-team/

**Comment by benydc** [comment]
I'm having the exact same issue, the link to the images is weird.

**Comment by NataliaBB** [comment]
Hello Rae @raemacias!
I've received your  request throught our Facebook chat, the issue will be fixed asap.

Ben @benydc  - in your case the php-gd was not enabled in your dashboard. Please check your page now, it should be all fine.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by yourbestdrink** [comment]
I'm dealing with this as well. Any help???
