### ISSUE TITLE
Carousel column element position

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#1069]
In the carousel, I set the column element position to the middle. In the backend it works fine but in the frontend the position is back to top.

**Comment by NataliaBB** [comment]
Hello @estraatios 
Natalia here, Brizy team!
Apologizes for the late reply. 

I've reproduced this issue at my end and I had the same results - no align in preview mode. 
Forwarded to our team already and they will check + fix this issue.

My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
