### ISSUE TITLE
Fatal Error: Uncaught Exception

### ISSUE THREAD

**Issue by srikat** [ThemeFuse/Brizy#107]
After I installed Brizy from within the WP plugins page in my localhost (powered by Laravel Valet) and activated it, the following appeared:

![Screenshot](https://d.pr/i/mIUi6n+)

I changed the URL in the address bar to /wp-admin/plugins.php and everything looks normal.

You may want to do some testing about this.

**Comment by srikat** [comment]
Link to view the screenshot in bigger resolution: https://d.pr/i/mIUi6n

**Comment by srikat** [comment]
With the default twentyseventeen theme being active, I created a Page and built the page using the blocks. But when I preview the page or update and view it on the frontend, it's all just white/blank.

Same problem with Genesis theme as well. I suspect something is wrong with the site running locally.

**Comment by bagrinsergiu** [comment]
@srikat 

Hi Sridhar,

Thanks for reporting. Sorry for the inconvenience. Can you give me more details ( Plugin Version, PHP, Server, MYSQL, PHPinfo() )?  We use Cloud Brizy Api in order to get Images from Cloud or to compile page. It is a problem with remote connection. I need to check what is limited on your configurations

Sergiu

**Comment by bagrinsergiu** [comment]
Can you try with a different server Wamp, Mamp, Xamp?

**Comment by srikat** [comment]
Here's a PDF of the `phpinfo()` output: https://cl.ly/0F283K1W3u1Y

I will try on Local by Flywheel on another Mac tomorrow.

It would be great if you can find out the solution by going through the phpinfo output.

Link to Laravel Valet: https://laravel.com/docs/5.6/valet

**Comment by bagrinsergiu** [comment]
Thank you for details.

**Comment by srikat** [comment]
I have installed Local by Flywheel and created a local site on my Mac with PHP 7.1.7, MySQL 5.6.37 and nginx server.

While there was no fatal error when installing/activating the plugin, pages built with Brizy continue to be blank/white on the frontend. Appears fine in the Brizy editor.

Any pointers to troubleshoot @bagrinsergiu?

**Comment by blitzgeek** [comment]
@srikat 
Ist the whole site blank/white on frontend? On my Flywheel test-site the 1st block/row is okay, the next one is unformatted html and all blocks/rows below are blank/white.

**Comment by srikat** [comment]
No.

Pages not built with Brizy are fine on the frontend.

Can you check your environment settings in the SITE SETUP tab in Local and type out the version numbers of your PHP and MySQL?

For me, the Brizy pages are just completely blank (well, I other than the admin bar).

**Comment by blitzgeek** [comment]
I just created a new Brizy page....and this time it works!!
Safari Technology Preview 58,
Wordpress 4.9.6.
Local by Flywheel 2.2.4
PHP 7.2.0
MySQL 5.6.34

**Comment by bagrinsergiu** [comment]
It a remote connection problem in order to receive assets from our Api (static.brizy.io). Your interner connection is on when you try to compile pages?

**Comment by alexadark** [comment]
I work with local flywheel, and everything works correctly so far

**Comment by srikat** [comment]
> Your interner connection is on when you try to compile pages?

Yes.

**Comment by bagrinsergiu** [comment]
In 1.0.19 we added 3 fixes for page compiler/ preview mode

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thanks for reporting
Sergiu
