### ISSUE TITLE
Display of page corrupted in Chrome

### ISSUE THREAD

**Issue by jmc-nabb** [ThemeFuse/Brizy#1071]
Brizy has a problem where it corrupts pages, Firefox is fine here is an example page https://naturallygfy.com/about-us-we-strive-to-offer-naturally-good-products-for-you/
Note sure what it's like on the horrible MS products.
It's not a local problem as I was visiting a friend and it was the same.

**Comment by NataliaBB** [comment]
Hello @jmc-nabb!
Natalia here, Brizy team
Sorry for the late reply.

I've tested your page on Chrome, Firefox, Microsoft Edge and Internet Explorer. 
I didn't find any problems with your page. Please give me more details, maybe some screenshots. 
Please, give me all these details on our facebook chat. Please mention the number issue inside - #1071


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
