### ISSUE TITLE
Mobile Navbar Text/Background color change

### ISSUE THREAD

**Issue by joshbmartin** [ThemeFuse/Brizy#1072]
Can someone explain if this is possible or not? I've searched around everywhere. It seems I can't differentiate in the css between mobile/desktop views which is killing me. Please help?

**Comment by NataliaBB** [comment]
Hello Josh! 
I've sent you a message via our Facebook chat. Could you please check? I will need your page URL in order to check the css code and to try to write additional code for your block ID
Thanks!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
