### ISSUE TITLE
Image Not Uploading

### ISSUE THREAD

**Issue by yourbestdrink** [ThemeFuse/Brizy#1074]
When using a Brizy block, I am unable to load a new image into a column. 

<img width="819" alt="screen shot 2019-01-25 at 4 13 52 pm" src="https://user-images.githubusercontent.com/47045829/51779449-4a0fca00-20bc-11e9-8743-0d5f5cce97bf.png">

It's getting this far:
<img width="876" alt="screen shot 2019-01-25 at 4 14 03 pm" src="https://user-images.githubusercontent.com/47045829/51779458-5005ab00-20bc-11e9-9c96-fe9254b37987.png">

But then doing nothing else. I've tried multiple pages and styles of blocks with no luck.

**Comment by NataliaBB** [comment]
Hello @yourbestdrink 

Natalia here!
We fixed this bug in the update Version 1.0.58. 
Please, check your version and try again to load the image in the column.  

Thank you!
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
