### ISSUE TITLE
Need to add anchor to a differnt page on menu

### ISSUE THREAD

**Issue by KMej** [ThemeFuse/Brizy#1075]
Hello
I am in need of the capability to add an anchor to the menu - which will link to different pages. Please advise.

**Comment by NataliaBB** [comment]
Hi @KMej 
If you want to add external links to your menu, you need to add a custom links from wp menu tab:
https://jumpshare.com/v/htZHPykELpI3RCLJJorL 

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
