### ISSUE TITLE
Issue with Image Save

### ISSUE THREAD

**Issue by drufus** [ThemeFuse/Brizy#1076]
Please watch this video: https://cl.ly/a77e5229f49f

**Comment by TheCrucible** [comment]
Yep, same here, the latest version of Pro has actually broken a client website!!! Really frustrating

**Comment by peleroberts** [comment]
Can confirm also, nearly uploaded a video also but i will post here : https://www.useloom.com/share/eac39af15fd74ba1a6b3760f7c8e5117

**Comment by peleroberts** [comment]
> Yep, same here, the latest version of Pro has actually broken a client website!!! Really frustrating

Roll back to previous build, if need be.

**Comment by peleroberts** [comment]
New Build today has fixed that issue - swift work by team brizy. Making progress.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
