### ISSUE TITLE
Form is unable to send email

### ISSUE THREAD

**Issue by kewlfaraz** [ThemeFuse/Brizy#1078]
I have been using brizy for quite sometime, forms work like charm. Recently, they stopped working. I have checked email from other plugins, wordpress system and servers are working fine. There has to be some sort of bug that is stopping the emails from being delivered. I am getting email sent successfully response, but the email never lands.

**Comment by allardo** [comment]
Same here!

**Comment by hkindermann** [comment]
Have the same problem here. Send form is in the leads but no mail send to any adress used.

**Comment by Darktimr** [comment]
Same here.

**Comment by ViorelEremia** [comment]
Hi guys,
please update the free version of the plugin. If it still doesn't work please check your server mail configurations or contact your hosting provider.

**Comment by Darktimr** [comment]
It works, thanks!

**Comment by allardo** [comment]
Doesn't do it for me, my server mail and hosting provider did not change anything so it should be due to the update of Brizy.. Everything is updated perfectly now but still no emails but still a success notification when I try...

**Comment by renriquegs** [comment]
I have the same problem. I have wordpress 5.1 and Brizy 1.0.64.

I followed the youtube tutorials to be sure I was doing configuration properly.

The contact form doesn't´t redirects and the email never reach. I try deactivating all the other plugins and still nothing.

I installed Contact Form 7 and worked fine so I can´t find the problem.
