### ISSUE TITLE
Brizy on iPad (iOS)

### ISSUE THREAD

**Issue by badcat** [ThemeFuse/Brizy#108]
From what I've seen, none of the peer front-end Page Builders work at all on iPad, except Brizy - well mostly working. (Here's where Gutenburg might shine.) I realize you're only at v 1.0.8 - and lots of the Admin UI seems to work OK on iOS, but enough of it fails that I would not be able to release this to a client who would only use a tablet like iPad. 

So.. will the UI/UX issues be resolved so that Brizy can work well on iOS?

**Comment by bagrinsergiu** [comment]
I'm not sure this will be possible (100%). We need to rewrite a lot of libraries for touch screens 

Thanks for suggestion. 

Sergiu
