### ISSUE TITLE
line height issue in chrome

### ISSUE THREAD

**Issue by TheCrucible** [ThemeFuse/Brizy#1081]
Latest version of Chrome and Brizy, last version had same issue. Cannot save (change) line height in the editor, it just closes, no change in text. See here https://www.screencast.com/t/FRrUOwcmlq9T

**Comment by NataliaBB** [comment]
Hey @TheCrucible 
I've tested on different wp dashboards, the latest version for Brizy and Chrome, I don't have this bug. 
Could you please give me access to your dashboard?

Thank you!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
