### ISSUE TITLE
Form Email-to

### ISSUE THREAD

**Issue by hitorclick** [ThemeFuse/Brizy#1083]
I need to be able to add two or more email addresses to the Email To form fields.

**Comment by NataliaBB** [comment]
Hi @hitorclick 
Natalia here!
Thanks for your suggestion! I've added your request to our to do list.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
