### ISSUE TITLE
Issue with Webform Redirect

### ISSUE THREAD

**Issue by drufus** [ThemeFuse/Brizy#1084]
I'm having an issue with the redirect option on the button. It is still showing the message when I have chosen redirect. 

Please watch this video: https://cl.ly/16a2ffffb8aa

**Comment by NataliaBB** [comment]
Hi @drufus 
Unfortunately, you can not edit only the redirect tab. I've added this request as a feature in our to do map:
https://trello.com/c/mdwVidu5/203-form-redirect-tab 

You can add a simple button, in which you can add an external link, but in this case you will not collect the user's emails.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
