### ISSUE TITLE
Dropdown menu for image/text elements won't hold for change

### ISSUE THREAD

**Issue by lsdphoto** [ThemeFuse/Brizy#109]
creating this site in a client's GoDaddy account with a Themefuse template (Core) which I'm using for header/footer but created all pages in Brizy (first time user for this). I like the ease of the drag/drop but integrating it into the template on GoDaddy and then going back into it in Brizy to edit text or change a photo and it won't let me. when I hover over the image or text edit bar, it just flashes and won't let me go into the popup to make the changes to text color/font or change an image out. It doesn't show up in the visual editor on GoDaddy so I can't change anything once the page is built. Suggestions?

**Comment by bagrinsergiu** [comment]
Hi @lsdphoto,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by lsdphoto** [comment]
I sent you that in FB chat. And videos of what it's doing. I can't finish these pages without changes and I can't find a way to change it.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
