### ISSUE TITLE
Bug video drop shadow

### ISSUE THREAD

**Issue by cowdar** [ThemeFuse/Brizy#1090]
Hi
When adding a drop shadow to a video then clicking the alpha leave 
the block disappears "An error happened while trying to display this block
You can open an issueorremove this block"

<img width="1624" alt="screenshot 2019-01-31 at 17 11 34" src="https://user-images.githubusercontent.com/26721162/52071675-5cd24500-257b-11e9-955a-57964fde5a39.png">

**Comment by NataliaBB** [comment]
Hello @cowdar 
Natalia here!
Please send me a message via our Facebook chat and mention this issue inside - #1090

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
