### ISSUE TITLE
I can not log in.

### ISSUE THREAD

**Issue by madebydong** [ThemeFuse/Brizy#1092]
I bought a pro.

In the received mail, I clicked the download path and entered the ID and password, but I can not log in.

I received a message that my account was not approved.

When can I download it?

Message from login
"Your account has not yet been approved. You will be notified via email once a site administrator has reviewed your account and enabled access."

Please refund or login.

**Comment by NataliaBB** [comment]
Hello @madebydong 
As Alexandru wrote you, your account was in pending mode because of the affiliate request.
Issue solved.
Best Regards. Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
