### ISSUE TITLE
Sub  Menu Not Showing

### ISSUE THREAD

**Issue by ezeenet** [ThemeFuse/Brizy#1096]
I have created Menu & submenu . there are 4  submenu but it is showing only 1,

**Comment by NataliaBB** [comment]
Hello @ezeenet !

Usually, it is a theme issue, but let me check please your page from your dashboard
Please send me a message via our Facebook chat and mention this issue inside - #1096 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by ezeenet** [comment]
Hello,
Thanks for writing , i have gone through the issue and understood &
resoveled it.

Thanks Again
