### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#11]
I installed the plugin on WP. The **builder seems to work fine**, but there's **no preview**, nor page/post upon publishing. Just a blank screen. 

Disabled all plugins and that didn't help. Changed the theme to TwentySixteen and it didn't make any difference.

This server is running Litespeed & PHP7.X. I don't know if that might have something to do with it. I did flush Litespeed cache completely and the only change I noticed was that the page changed from a white screen to a dark one. It was still blank.

If you want access I will work with you to help get this figured out. Not urgent on my end as I'm just testing it out anyway. :)

**Comment by bagrinsergiu** [comment]
Can you give me more details: 

1. Live url or screenshot
2. Simple Install or Multi Sites

Thanks for reporting.

**Comment by CJKrets** [comment]
Hi,

This is a simple install. Behaves the same on posts and pages. Divi builder works fine, but not Brizy.

https://goo.gl/ogEGCy 

Thanks,

Corey

**Comment by CJKrets** [comment]
An update to this. I installed Brizy on my other non-Litespeed server and I'm getting the same results. A blank page. Nothing shows when publishing or previewing outside of the builder. It wipes out the header as well. (See: https://goo.gl/VaRNme )

Something is really broken.

Seems to work fine inside of the builder, but never renders outside of that. 

~ Corey

**Comment by bagrinsergiu** [comment]
Hi Corey,

Can you give me WP credentials via Facebook Chat: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.

**Comment by bagrinsergiu** [comment]
@CJKrets 

Node Port (3000) is blocked on your server. We changed it to 80.  

This has been fixed and will be included in the next update, thanks for reporting.

**Comment by bagrinsergiu** [comment]
@CJKrets 

Updated.

**Comment by jtbmendoza** [comment]
Hello @bagrinsergiu  Having the same issue. I currently have 2 pages live on my WP site. 1 Home and 2 About. For some reason, About page is OK. Home appears when editing through Brizy but when previewed, only white space appears. I checked the published version and it's also just white space. Hope you can help. Thank you so much!

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
In 1.0.19 Images Resize was moved in WP from or cloud platform. Can you check image size on your pages ( IMG, and BG). I found a project with 6Mb image on BG.

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by jgbranco** [comment]
I'm having the same problem, a blank page. When I open the builder everything seems fine, I can work on it with no problem, but when I publish the page and open it on the browser its blank. How can I solve this with my server support? What do I tell them? I have the latest plugin version bothe for the free version and the pro.
