### ISSUE TITLE
Hover dropdown/submenu display behind content when using a global header template.

### ISSUE THREAD

**Issue by wtassis** [ThemeFuse/Brizy#1102]
After creating a header using template on Brizy or similar options on other themes (like custom layouts in Astra Pro) and publishing the template to a page (s) the dropdown/submenus display behind the page content when you hover the parent menu. I thought it was a theme related issue, but after trying other on other themes I got he same results. Anyway you guys can take a look at this?

Regards,
Wallace

http://prntscr.com/mgu5aw

**Comment by NataliaBB** [comment]
Hello Walace! @wtassis 
We already spoke with you regarding this issue in the chat.
As soon as I will have some news from our dev team I will get back to you asap. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
