### ISSUE TITLE
Can't close Tab

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1103]
System is WordPress 5.0.3, Brizy Version 1.0.59, Brizy Pro Version 1.0.17.,  Chrome Version 71.0.3578.98

1. Open a Brizy page and edit it 
2. Preview it
3. Click on the preview on Edit (so you got two edits open, happens)
4. Exit to WordPress 
5. You are stuck in a page that doesn't want to close because it got changes (alert from WordPress) that immediately disappears and therefor the Tab can't be closed.

**Comment by MaxZiebell** [comment]
If you think this to exotic it also occurs if I edit a page and in another tab open the page to edit the excerpt.

**Comment by NataliaBB** [comment]
Hello @MaxZiebell 

Please send me a message via our Facebook chat and mention this issue inside - #1103 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by MaxZiebell** [comment]
Isn't closing for solved? I don't have (evil) facebook.
