### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by meghanni** [ThemeFuse/Brizy#1104]
Please allow us to select 'theme default' for each element style, or override it. I am having to load my font twice, once in the theme and then again in Brizy. Plus it is a time waster having to go through and select my font, size and weight again for each element. Thank you.

**Comment by NataliaBB** [comment]
Hello @meghanni 

Thank you! I've added your request to our trello roadmap. 
The team will look over it asap. 

My best regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
