### ISSUE TITLE
Colors get back to default style every now and then

### ISSUE THREAD

**Issue by maenerai** [ThemeFuse/Brizy#1105]
Hi,

I modified a color style in the left panel to suit my needs (I took the "Yoga" style and changed all the colors).
It works fine, exept sometimes it goes back to the default color palette (the "Yoga" default).
It doesn't change everywhere on my website. Some pages or templates keep my colors, some others get back to the default.
So I regularly have to save some pages again to make them use my own color palette.
Is there a way to create a color palette from scratch ?

**Comment by NataliaBB** [comment]
Hello @maenerai 
Natalia here!
As we speak on our Facebook chat -  we work on this issue right now.
I will come back to you as soon as possible, as soon as I will have some details.

My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
