### ISSUE TITLE
Wifi glyph icon not working

### ISSUE THREAD

**Issue by nagahill** [ThemeFuse/Brizy#1106]
![screen shot 2019-02-07 at 13 34 24](https://user-images.githubusercontent.com/47411099/52395152-8d683080-2adf-11e9-9a40-24e5e1f9efda.png)

**Comment by NataliaBB** [comment]
Hello @nagahill 
Natalia here!
I've checked the wifi icons at my end and everything seems to be fine.
Please allow us to check the icons in your dashboard, send me a message via our Facebook chat and mention this issue inside -#1106 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
