### ISSUE TITLE
[Feature Request] Sparkpost Integration through their Wordpress Plugin

### ISSUE THREAD

**Issue by michacassola** [ThemeFuse/Brizy#111]
Please add Sparkpost as an integration using their Plugin.
https://www.sparkpost.com/
https://wordpress.org/plugins/sparkpost/

**Comment by bagrinsergiu** [comment]
Hi Micha,

Thank you for suggestion. Added in our to do list. 
Sergiu

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/SJcFPC1Y/35-form-integrations

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
