### ISSUE TITLE
Bug:  jQuery library not loaded for youtube video with cover image

### ISSUE THREAD

**Issue by meghanni** [ThemeFuse/Brizy#1110]
The jquery library is not loaded by Brizy when you add a youtube video with a cover image. 

preview.js?ver=1.0.84:113 Uncaught ReferenceError: jQuery is not defined
    at HTMLDivElement.<anonymous> (preview.js?ver=1.0.84:113)
    at HTMLDivElement.dispatch (preview.js?ver=1.0.84:39)
    at HTMLDivElement.v.handle (preview.js?ver=1.0.84:39)

I could make it work by activating the contact form 7 plugin which always loads jquery library even if you don't use it anywhere (very naughty!!)

**Comment by NataliaBB** [comment]
Hello @meghanni 

Usually, this error occurs when you have a cache/optimisation plugins enabled, or someone disable the loading of jquery - it may be a plugin or the theme. 
Please, try to:
1. Disable the plugins
2. Change the theme. 
If the problem still persists, please send me a short message via our facebook chat.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
