### ISSUE TITLE
Version number at end of live page urls

### ISSUE THREAD

**Issue by codeclinic** [ThemeFuse/Brizy#1111]
I've created a page with Brizy PRO, published it then set it as the site homepage/front page.

When I browse to my site, it loads up and redirects to a version of itself with a version id appended to the domain as a querystring.

For example if I visit my site at: **https://plugin-test-dev-sandbox.local/**

it appends a version number to the domain like this: **https://plugin-test-dev-sandbox.local/?v=79cba1185463** 

This is obviously ugly and bad for SEO and caching but also messes up with an API that I use on the site. How can I remove this?

P.s. My site is on localhost, so I can't let you have access unless we can arrange a time when I can open up the site to remote access for you. Alternatively, I could provide an export/backup of the site for you to clone on your local setup.

**Comment by NataliaBB** [comment]
Hello Phill @codeclinic 
Natalia here!
Could you please disable both Brizy plugins and check the page URL again? 
If the redirect still exists, then it's an installation issue. 
If not, then please send me details about how you open that page  -  from WP dashboard list pages (click on view button) or from Brizy editor build mode (preview button)? 

Thank you!
Regards, Natalia

**Comment by codeclinic** [comment]
This was caused bz a WooCommerce setting.
