### ISSUE TITLE
How to change the dropdown direction

### ISSUE THREAD

**Issue by meghanni** [ThemeFuse/Brizy#1113]
![5a0c0245-e2d4-4414-993e-94a14e2cb01b png](https://user-images.githubusercontent.com/568899/52484989-94f70a80-2baf-11e9-9e01-f58f196b342c.jpg)

I would like to change the dropdown direction. As you can see it is is on the right, how do I change it to the left? Thanks

**Comment by NataliaBB** [comment]
Hello @meghanni 
Natalia here.
No, unfortunately, we don't have this option. But I added in our improvement issue list.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
