### ISSUE TITLE
Brizy Builder Customization

### ISSUE THREAD

**Issue by Taimurian** [ThemeFuse/Brizy#1118]
Is it possible to customize/override the output of Brizy Builder and create your own blocks via the theme folder the same way we do with the Unyson Page Builder?

**Comment by NataliaBB** [comment]
Hello Taimur @Taimurian 
Natalia here.
As we spoke via our facebook chat, we do have the API module for developers in our to do list. 
https://trello.com/c/pFm3iIg8/58-developer-api 

We will take care to be released as soon as possible.
My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
