### ISSUE TITLE
Documentation for developers

### ISSUE THREAD

**Issue by pavlyukpetr** [ThemeFuse/Brizy#1119]
Hello,
do you have the documentation for developers?

**Comment by NataliaBB** [comment]
Hello Peter @pavlyukpetr 
Natalia here! 
No, we don't have documentation for developers. 

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
