### ISSUE TITLE
[Feature Request] Mautic Email Automation Integration

### ISSUE THREAD

**Issue by slomeli79** [ThemeFuse/Brizy#112]
Mautic is an underrated powerhouse in email automation. They are open source and growing quickly. Would love to see Brizy add this integration to the roadmap.

[https://www.mautic.org/](https://www.mautic.org/)

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/SJcFPC1Y/35-form-integrations

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
