### ISSUE TITLE
Site not working properly on Mac and iPad

### ISSUE THREAD

**Issue by Catkins74** [ThemeFuse/Brizy#1122]
Hi, on my site www.allaspectfitout.co.uk, Mac and iPad are showing issues.  The icons do not appear in the Services section, the dropdowns don't work on the About Us section and the testimonials do not scroll (only the 1st is visible).

What can I do to fix this?  Many thanks! 
![51731879_325677204723580_5901310722838626304_n](https://user-images.githubusercontent.com/47520840/52555158-d6bac780-2de0-11e9-97c0-b038a17b1659.jpg)
![52605535_382486425643672_6114265938792546304_n](https://user-images.githubusercontent.com/47520840/52555159-d6bac780-2de0-11e9-9ec3-da5a9e5f876d.jpg)
![51951534_588387781628343_5735972391956250624_n](https://user-images.githubusercontent.com/47520840/52555161-d6bac780-2de0-11e9-8601-efc6e863d8bb.jpg)

**Comment by NataliaBB** [comment]
Hello @Catkins74 
We are discussing this issue via our chat. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by Catkins74** [comment]
Hi, please can you reopen, as no one is discussing it in the chat, and it's not resolved.  Many thanks
