### ISSUE TITLE
Multisite issue

### ISSUE THREAD

**Issue by Ardaland** [ThemeFuse/Brizy#1123]
I am installing Brizy on WordPress Multisite Certified by Bitnami and most of items does not work. I can't even add the menu, and when trying to upload image it does not even show the upload image window only some buttons. is there any plan to make it multisite friendly?

**Comment by NataliaBB** [comment]
Hello @Ardaland 
Natalia here!
We would like to check the editor and errors from your installation. It will be possible?

Send me a message via our facebook chat to discuss these details.
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia
Thank you!
Regards,  Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by Ardaland** [comment]
Hi Natalie,
 I would like you to login to my word press and try to upload an image or
add menu to the page. Also check the whole brizy tools it seems a lot of
icons missing even though I installed the latest version.

This is multisite version so you have to go on top left to SITES and then
choose the site starting with *test1.34...*

Ip:34.73.68.181
Username:user
Password:nfz2afuxxahU

.

Thanks
Ardy
