### ISSUE TITLE
Domains with non-ASCII characters

### ISSUE THREAD

**Issue by fabiankaraben** [ThemeFuse/Brizy#1124]
I can't use a license with the domain matemáticas.xyz.

**Comment by NataliaBB** [comment]
Hello @fabiankaraben 
Natalia here, Brizy team!
Please send me your order ID in a message via our Facebook chat ?
Please, mention the number of this post - #1124

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
