### ISSUE TITLE
Messy urls in google console

### ISSUE THREAD

**Issue by PriitGit** [ThemeFuse/Brizy#1127]
Created image sitemap with Seopress and got lots of messy urls in google console. 
Example: /?brizy_media=wp-5603fb8e1a4a58c8e599d343812a0f1b&brizy_crop=iW=760&iH=1311&oX=0&oY=367&cW=760&cH=577&brizy_post=1130

**Comment by NataliaBB** [comment]
Hello @PriitGit 
Natalia here. 
Sorry for the inconvenience. We will work on this improvement asap.

My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
