### ISSUE TITLE
[Feature Request] vw, vh, em values

### ISSUE THREAD

**Issue by dnnsjsk** [ThemeFuse/Brizy#1129]
Please add these values to all marign & padding options. Especially vw is heavily used nowadays to define dynamic paddings of containers. (or at least I do ;))

**Comment by DimiBaitanciuc** [comment]
True, we had only px at first and then we've added % but we'll definitely look into adding vw, vh and em options for sure. Thanks.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
