### ISSUE TITLE
Form Interactions & Use

### ISSUE THREAD

**Issue by adegbengaagoro** [ThemeFuse/Brizy#1130]
When using the Form element in Brizy, I have noticed some issues which I believe if addressed would be beneficial to the larger community of Brizy Users, they are:

**1. There should be an option to set a custom error message for any field type specified. By default, Brizy should do some basic error checking and render the content of this custom error message if specified; at the minimum, Brizy should check that content matches field type specified.**

![brizy-form-required-fields](https://user-images.githubusercontent.com/5008453/52708795-5d130d00-2f8b-11e9-9808-9245e5cc2a82.png)

> For example, I was building a form and duplicated a field (which is the only way to add a new field to the default form) and I forgot to change the field type from email to text, I kept getting the standard error outline on the field but no indication to the reason until I checked the field setup again.

**2. It would also be nice to be able to move the fields around in terms of re-arrangement**
![brizy-field-duplicate](https://user-images.githubusercontent.com/5008453/52709181-5638ca00-2f8c-11e9-868c-b336fd8acad4.gif)

> Another example, I had built a full form and it was modified by the client and the modifications were just for the fields to be re-arranged in another order. I had to delete the whole form structure and re-build based on the new arrangement requirements from the client. This was very stressful and pain-stacking work

**3. It would also be a good thing to have the form fields clear after a successful submission and also provide a field where we can specify the success message displayed to our users. It's not every time you want to say an email was sent. Below are 2 screenshots before the form was submitted and after it was submitted**

**BEFORE SUBMISSION**
<img width="516" alt="screen shot 2019-02-13 at 12 42 23 pm" src="https://user-images.githubusercontent.com/5008453/52709400-fb53a280-2f8c-11e9-883e-1797e7ace46c.png">

**AFTER SUBMISSION**
<img width="503" alt="screen shot 2019-02-13 at 12 42 38 pm" src="https://user-images.githubusercontent.com/5008453/52709450-0a3a5500-2f8d-11e9-9205-0519908659dd.png">

**Comment by DimiBaitanciuc** [comment]
Thanks for your feedback, I've already created an issue in our internal board. Once we'll start the work on improving the form, we'll look into this as well.

**Comment by adegbengaagoro** [comment]
Thanks for the quick response on this, looking forward to this integration

**Comment by MaxZiebell** [comment]
+1 And also consider built in style options. Like underlines fields or material design like fields.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
