### ISSUE TITLE
Images not rendering on mobile version of site

### ISSUE THREAD

**Issue by AdamJackowitz** [ThemeFuse/Brizy#1131]
There are several images not rendering on the mobile version of our site. Please help!

**Comment by NataliaBB** [comment]
Hello @AdamJackowitz 
Created an issue for this right now. @maxval94  will look over it. 

My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
