### ISSUE TITLE
Page renders no pararaphs

### ISSUE THREAD

**Issue by DPOExperts** [ThemeFuse/Brizy#1133]
In the Wordpress editor, text has paragraphs. When using Brizy they disappear. This is happening on pages with any text that I am now building. The examples here relate to building a Brizy template for posts. But this problem is happening with text pasted into the Text element on web pages too. Examples shown in the images.

Attached

1. screen showing the # tag fields used for dynamic content
2. the page rendering based on using a Brizy template (no paragraphs)
3. Delete the Brizy template and show the post again (paragraphs return)
4
![screenshot 2019-02-13 at 22 01 53](https://user-images.githubusercontent.com/47613573/52747333-793e9a80-2fdb-11e9-91db-424da45d2fa8.png)

![screenshot 2019-02-13 at 22 02 07](https://user-images.githubusercontent.com/47613573/52747313-6e840580-2fdb-11e9-8730-a998cd7cdb4a.png)

![screenshot 2019-02-13 at 22 02 24](https://user-images.githubusercontent.com/47613573/52747347-7fcd1200-2fdb-11e9-9b40-68850af5ddfa.png)

**Comment by NataliaBB** [comment]
Hello @DPOExperts 
Natalia here!

The issue with paragraphs was fixed, and it will be available in the next upcoming update, which is planned for next Monday. 

My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
