### ISSUE TITLE
Form Field No Alignment Control

### ISSUE THREAD

**Issue by souljoy** [ThemeFuse/Brizy#1134]
I am a Birzy Pro user.  When using the Form Element, although there are options to align the button that comes with the form (left/center/right), there is NO option to do the same with the Form Field.  In order for the Form Field to center correctly in responsive view AND line up identically to the button below, we need to have the same alignment control as the button.  At present, the Form Field (eg email) does automatically center itself in Responsive View but it is impossible to size it the same width as the button AND keep them both center aligned no matter what size the responsive view is.  Please can you set up the three alignment options for the Form Fields.  Thank you.

**Comment by NataliaBB** [comment]
Hello @souljoy 
Natalia here!

We do have the filed allignment option in our to do list. 
We will work on this improvement asap.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
