### ISSUE TITLE
brizy make the whole website disappear!

### ISSUE THREAD

**Issue by guchik** [ThemeFuse/Brizy#1135]
brizy make the whole website disappear!
with llorix one lite theme after activating the extension everything was gone
back to step one  installing wordpress
found a trick
deledted the extension via ftp
and it went back to normal

**Comment by guchik** [comment]
As I told I installed Brizy plugin on wordpress 5.03 with the llorix one
theme.
and all in one second I was taken to the main install worpress page.
I went to the ftp directory and deleted the plugin manually and the website
went back as normal.
i installed the plugin on astra theme  and it worked perfectly

Le lun. 18 févr. 2019 à 17:30, NataliaBB <notifications@github.com> a
écrit :

**Comment by NataliaBB** [comment]
Hi @guchik 
Thanks for letting me know. I will test the Illorix one theme at my end and I will inform the team about the errors.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
