### ISSUE TITLE
[Feature Request] CSS grid

### ISSUE THREAD

**Issue by dnnsjsk** [ThemeFuse/Brizy#1139]
Please include a css grid block. Brizys UI would be perfect for creating complex layouts using it. It is the future and here to stay!
Thanks :-)

**Comment by kdub718** [comment]
I agee!  I said this few months back on facebook and didn't really get a response

**Comment by NataliaBB** [comment]
Hey @dnnsjsk @kdub718 
Natalia here!
Thanks for your request and apologizes for the late reply.
We have added this issue in the trello map. 
https://trello.com/c/1bavUYxB/206-css-grid-block

Cheers!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
