### ISSUE TITLE
Add a anchor link?

### ISSUE THREAD

**Issue by cutter2222** [ThemeFuse/Brizy#114]
CSS id to the element

**Comment by bagrinsergiu** [comment]
@cutter2222 

You mean this feature? http://joxi.ru/KAgXXdGC4gKMar

**Comment by cutter2222** [comment]
Example: https://yadi.sk/d/4mVxql_y3XaXCp

**Comment by bagrinsergiu** [comment]
Screen is broken for me: http://dl3.joxi.net/drive/2018/06/10/0028/0732/1860316/16/bbe787a804.jpg

**Comment by bagrinsergiu** [comment]
smooth transition is available by default: http://jmp.sh/dCxcQi5

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Sergiu
