### ISSUE TITLE
Images disappearing on iOS 

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1140]
I have many images on http://sculptures.diki.info

On iOS scrolling is a drag and images keep disappearing and blank spaces show up on sections I have already loaded the images at.  If you can't reproduce I can temporarily disable the "hack". Please test on mobile safari (iPad, iPhone). I could fix it with the following "hack". But brizy should fix this ASAP.

```
*:not(html) {
    -webkit-transform: translate3d(0, 0, 0);
}
```
From 
https://stackoverflow.com/questions/9807620/ipad-safari-scrolling-causes-html-elements-to-disappear-and-reappear-with-a-dela#10170170

**Comment by MaxZiebell** [comment]
There is a problem with above snippet for the edit mode so for a temporary fix I used the Code Snippet plugin with following snippet

```
add_action( 'wp_head', function () { 
	if (!is_user_logged_in()) {?>
	<style>
		*:not(html) {
    		-webkit-transform: translate3d(0, 0, 0);
		}
	</style>
<?php }} );
```

[temp-brizy-fix.code-snippets.json.zip](https://github.com/ThemeFuse/Brizy/files/2879852/temp-brizy-fix.code-snippets.json.zip)

**Comment by NataliaBB** [comment]
Hi Max @MaxZiebell 
Thanks for reporting this issue, and thanks for sharing the fix. 
I've created an issue for @bagrinsergiu and @maxval94 and they will look over this asap.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hey @MaxZiebell 
Do you have installed an image optimizer plugin in your dashboard?

Natalia

**Comment by MaxZiebell** [comment]
At the time not…

**Comment by MaxZiebell** [comment]
I must revisit the issue as it's a while back I reported it…

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
