### ISSUE TITLE
Global Block Saving Bug? Since Brizy 1.0.60 Update

### ISSUE THREAD

**Issue by souljoy** [ThemeFuse/Brizy#1144]
After updating to Brizy 1.0.60 today and using Brizy Pro 1.0.17, when I try to save a block using 'Make It Global', the block disappears and an error message is shown "An error happened while trying to display this block.  You can open an issue or remove this block" (attached photo below).  I have tried this on both a live site and on a local site with the same result.  When I use a site with Brizy 1.0.59 both live and locally, there are NO problems.  Tonight, I have even tried a fresh new local wordpress site with the new update and Brizy Pro and the same error occurs.  In all cases I am using the classic editor.  There are no other changes.  This only started after the update you released today.  

On a more positive note, the gradients and hover effects are great and work beautifully.  Really nice and simple to use with gorgeous results!  Thank you!  

I have attached a copy of the error message.  I have tried this with several default blocks including a blank block and I get the same error message.  I trust this will be an easy fix.  Thank you.
![global_block_error_message_18feb2019](https://user-images.githubusercontent.com/44711252/52991618-0ebe9d80-33d3-11e9-8f94-05d5ecf22e65.JPG)

**Comment by wtassis** [comment]
I have the same issue.

**Comment by itinmind** [comment]
Same here... :(

**Comment by turnandshoot** [comment]
Same!

**Comment by DimiBaitanciuc** [comment]
@bagrinsergiu will take a look on this. Thanks for letting us know.

**Comment by NataliaBB** [comment]
Hello Everyone!
@wtassis @souljoy @turnandshoot @itinmind 

Apologizes for the inconveniences! This bug has been fixed and it will be included in today's update.

Cheers! Natalia

**Comment by turnandshoot** [comment]
Smashed it! Thank you ✌🏽

**Comment by NataliaBB** [comment]
Later edit: New update is live.

For any additional questions, please write us.

Cheers!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
