### ISSUE TITLE
How to add more than 4 images to Brizy Slider?

### ISSUE THREAD

**Issue by svldvc** [ThemeFuse/Brizy#1146]
Just installed a theme with Brizy. The demo content had an image slider but it only had 4 circle tabs at the bottom allowing circulating only 4 images. How do I add more images to the slider? Looked everywhere and cannot find any option where to control slider options and tabs. 

thanks.

**Comment by turnandshoot** [comment]
Found the answer yesterday. Click the cog for the overall row and hit duplicate. Couldn’t figure out how to get more than 2 for a whole day 😩

**Comment by NataliaBB** [comment]
Hello @svldvc @turnandshoot 
Natalia here!

There are 2 youtube channels with different video tutorials:
https://www.youtube.com/channel/UCU-2U0NZ5vx_5jzOO0F0KgQ
https://www.youtube.com/channel/UC7tr7RBbZ0o2lmkmMZCrQVg


Regarding slider block: here are a short video tutorial: https://www.youtube.com/watch?v=CyTHBWY4Msw

My best Regards, Natalia

My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
