### ISSUE TITLE
No way to delete development or staging websites from Activated Licences in Dashboard

### ISSUE THREAD

**Issue by DenMurphy** [ThemeFuse/Brizy#1148]
During development I activated a Brizy Pro (Personal) licence in a Local website and a staging website.

I would like to remove the licence activations from the Brizy Account Dashboard, especially the staging website, as it technically does not exist anymore.

The staging website now has a different URL (changed to the live website), so the licence is unable to be activated in the WordPress backend.

**Comment by NataliaBB** [comment]
Hello Dennis @DenMurphy 
Thanks for reporting this!
I've spoken with @alexluncashu about this issue, and he will improve the licences system in Brizy account

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
