### ISSUE TITLE
Am I able to upgrade from Brizy Pro Personal to a Lifetime Licence?

### ISSUE THREAD

**Issue by DenMurphy** [ThemeFuse/Brizy#1149]
I have purchased the Brizy Pro Personal to test the Pro features, and would like to upgrade to the Lifetime licence.

Am I able to just pay the difference to upgrade, or do I have to pay the full amount on top?

How do I go about this if I can just pay the difference?

**Comment by DimiBaitanciuc** [comment]
No need to pay the full amount, let me know the email of your Brizy account and we'll send you a discount voucher to pay only the difference.

**Comment by DenMurphy** [comment]
Hi @DimiBaitanciuc, my email on Brizy is development@dennismurphy.biz

**Comment by DimiBaitanciuc** [comment]
Cool, my colleague @alexluncashu will send you an email shortly with the upgrade option. I'll close this ticket for now, we'll keep in touch over email. Feel free to open it by replying.

Cheers.
