### ISSUE TITLE
WP Theme Support

### ISSUE THREAD

**Issue by chetpat** [ThemeFuse/Brizy#115]
Which WordPress themes are supported by Free version of Brizy ? As I am trying to design pages in Renden x theme but after publishing it is not showing the designed page.........

**Comment by bagrinsergiu** [comment]
Hi @chetpat 

I think my colleagues replied to this question on Facebook Comunity: https://www.facebook.com/groups/brizy/permalink/241440383286508/

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Sergiu
