### ISSUE TITLE
Pages blank after editing them

### ISSUE THREAD

**Issue by svfreebird** [ThemeFuse/Brizy#1151]
The pages I have just finished editing are now showing up as blank pages on my site. The other pages that I have not touched are fine. What is going on??

**Comment by NataliaBB** [comment]
Hello @svfreebird 
Natalia here!
It may be a fatal error, but I need to investigate the issue from your dashboard. 
Therefore please send me a message via our Facebook chat and mention this issue inside - 1151

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
