### ISSUE TITLE
Feature request: Set img default-, min- and max size plus allow size in pixels

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#1152]
Hi there,

I have a feature request for the image module.
With Brizy we can only set the sizing in percentages, however in a lot of cases this makes the image really small or really large when viewing it on smaller screens.

Besides this I would also like to be able to set a min- and max width for the images for better display control so the sizing is more consistent. For now I use custom css to fix this per image where I need it.

Below you can see a screenshot where I have a menu cart inside the image module. However on different sizes the image is either really small or really large and the only way for me to fix this is by adding custom css by utilising a min- and max size value in pixels. So for example it would like this:

.menu-cart-image {
 width: 100%;
 min-width: 220px;
 max-width: 360px;
}

Beneath here you can see the difference in sizes of the image where the first one is good, but the second one is really small and the third one is really large:

Default size which is good
![schermafbeelding 2019-02-20 om 19 41 06](https://user-images.githubusercontent.com/6600256/53116099-1ce1fa80-3548-11e9-998c-083b4d2419c5.png)

When scaling the window down the image becomes really small. With a min-width set in pixels it can take the available space. Because when I scale the window down like 5 pixels more or so then the columns will stack. So a min-width would be great:
![schermafbeelding 2019-02-20 om 19 41 34](https://user-images.githubusercontent.com/6600256/53116200-603c6900-3548-11e9-830e-5f4dea078e21.png)

On smaller screens the image starts really big, just too big. This could be fixed by adding a max-width set in pixels:
![schermafbeelding 2019-02-20 om 19 41 42](https://user-images.githubusercontent.com/6600256/53116271-8f52da80-3548-11e9-90d3-2983cd165465.png)

This is in my opinion of the most crucial settings that are now missing for the Image module.
I hope this is not to hard to built in as it's a must have for good responsive image design.

Also it would be great if min- and max- width settings could be applied to other modules too for better sizing control.

Best regards,

Christiaan

**Comment by NataliaBB** [comment]
Hello Christiaan! @Infusednl 
Yes, we do have this option in our trello map.
I spoke with Sergiu @bagrinsergiu , will try to push up in the top to do list.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
