### ISSUE TITLE
Constant Ghost Images

### ISSUE THREAD

**Issue by cueup** [ThemeFuse/Brizy#1154]
I've got an issue where there are multiple ghost images from the demo content of the plugin that are constantly showing my my site. The site also shows the ghost images only when viewing on a mobile phone - if you tap the image it then transforms to the image I've set but goes back to the demo image on reload. 

- Tried disabling the plugin and deleting the images folder
- Deleting the images from gallery

Nothing works, anyone else having this issue? Any fix out there?

Using the latest version of the plugin Version 1.0.61
WordPress 5.1

**Comment by adegbengaagoro** [comment]
What I have noticed is that I see the demo images when I switch from desktop to mobile view and if someone isn't actively checking the responsive views, the site would basically load demo content while being viewed from a mobile device.

I also see a weirdly named image file in my media library which has repeatedly refused to be deleted.

**Comment by cueup** [comment]
Seems like a bug to me. 

Hopefully a easy fix as it misrepresents the website by loading demo images.

**Comment by NataliaBB** [comment]
Hello @cueup 
Natalia here! 
Yes, it may be a bug. 

Please, if after the latest update 1.0.64 the problem still occurs, give me a message via our facebook chat, mention also this issue 1154. 
In any case, send me a short message.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
