### ISSUE TITLE
Sections Disappear 

### ISSUE THREAD

**Issue by trancender999** [ThemeFuse/Brizy#1155]
Various sections / Blocks disappear just suddenly.. Extremely frustrating as hours of work gets destroyed. Pls, release a more stable version... Extremely amateur!

**Comment by benj69** [comment]
Hello. Same issue happening on my site all of a sudden :-( hope it gets fixed soon!

**Comment by NataliaBB** [comment]
Hello @trancender999 and @benj69 
Natalia here! 
Apologizes for the late reply!

I would like to know which blocks/sections disappeared. Saved/Global blocks? sections/global in a published page? could you give me some examples? 

Thank you!
Regards, Natalia

**Comment by benj69** [comment]
Hi Natalia, thanks for your feedback and helping to fix the bug. On my site it was some prepared saved and global blocks, which I had used for a published menu header in several pages. They were showing okay while I was developing and when I returned to continue, or use in other pages, the blocks were 'empty' and so I had to recreate them.

**Comment by NataliaBB** [comment]
Hello @benj69 
It will be possible to reproduce again this issue at your end? I would like to work a little bit in your dashboard with Brizy editor.

Thank you!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
