### ISSUE TITLE
uploading/adding image

### ISSUE THREAD

**Issue by lilsurepbc** [ThemeFuse/Brizy#1156]
When uploading a new image, it takes forever to load.  Then when I return to the page, the box is greyed out.  I hit update and it just spins.

![screen shot 2019-02-23 at 8 27 47 am](https://user-images.githubusercontent.com/45666337/53287714-aad70480-3745-11e9-855b-e81b48b69614.png)

**Comment by NataliaBB** [comment]
Hello @lilsurepbc 
Natalia here!
Could you please check if image extensions are enabled? /php-gd or php-imagick ? Could you also check the PHP environment?  upload limit? 
If it possible, send me a message via our facebook chat and I can check these options by myself.
Facebook chat:

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)


Mention the issue numer  #1156 inside. 
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
