### ISSUE TITLE
Entrance Animation causes block to disappear - Safari 9 (and older) iOS

### ISSUE THREAD

**Issue by justNiCAL** [ThemeFuse/Brizy#1157]
Browser: Safari 9 and older on mobile (iOS)

Issue: Blocks of text and images that have animation applied will not load in safari 9 on iPhones. The parts of the website that have no animation will load properly.

**Comment by NataliaBB** [comment]
Hello @justNiCAL 
Natalia here.
Please give me more details (Brizy plugin version, other plugins installed), via our facebook chat: 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Please, mention the issue number inside  #1157
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
