### ISSUE TITLE
[Feature Request] Centered content

### ISSUE THREAD

**Issue by Voronium** [ThemeFuse/Brizy#1158]
With the existing ability to set a section to be FULL WIDTH and FULL HIGHT will be amazing to have an option to make it also AUTO CENTERED. I mean, when the section is entered it automatically scroll to the center of the screen. This way the sections of the page can slide on the screen like a vertical slider.
Something similar can be seen on this page [http://theme.pixflow.net/massive-dynamic/landing/](url)

**Comment by NataliaBB** [comment]
Hello @Voronium 
Natalia here.

Thanks for your request. 
I've added in our internal GitHub list, the team will look over it.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
