### ISSUE TITLE
Include Google Tag Manager code

### ISSUE THREAD

**Issue by ebenj** [ThemeFuse/Brizy#1159]
Hi, 

Is it possible to edit Brizy template? I need to place my Google Tag Manager code but it dissapears when using Brizy template instead of the theme header so my site is not tracking anything

**Comment by andronic90** [comment]
Hi,

I think you can attach to wp_head or wp_footer actions, not recommended to edit the page template, maybe in the future will be some updates to the page template

**Comment by NataliaBB** [comment]
Hello @ebenj 
For the moment, we don't have google tag option for Brizy. It will be available with the next updates. 

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
