### ISSUE TITLE
An error happened while trying to display this block

### ISSUE THREAD

**Issue by ninamckeon** [ThemeFuse/Brizy#1160]
Hi, 

I'm currently unable to edit any of my existing blocks, and can't create new blocks for editing either (version 1.0.61)

New website was meant to go live today and was hoping someone can please assist.

thanks,

Nina

**Comment by NataliaBB** [comment]
Hey Nina!
Natalia here! 

I'm waiting for your reply via our facebook chat.
Thank you.
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
