### ISSUE TITLE
1.0.60 breaks server after page update.

### ISSUE THREAD

**Issue by MrKatz1978** [ThemeFuse/Brizy#1161]
Hi there. I have tried using brizy on 2 servers and sometimes the update page function works and other times, it breaks and then the server respond after a while

**Comment by NataliaBB** [comment]
Hello @MrKatz1978 
Natalia here!

Please send us a message via our facebook chat, the team would like to check the issue from your dashboard.

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)
Please , mention the issue number inside - #1161 

Thank you!
Regards, Natalia

**Comment by MarpoOcknew** [comment]
I have experienced the same issue, which the server responding with a 502/504 error. I managed to fix it after upping the number of concurrent connections to the max my server can handle, though it does still happen when editing a number of pages one after the other. The plugin seems to send too many requests and overloads everything.

**Comment by skynet01** [comment]
Also happens with my installation, started happening after the update.

**Comment by MaxZiebell** [comment]
I had that also while using Easy Update Manger. I got an notification that an Update ran into an Sever Error.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
