### ISSUE TITLE
Please add CMD+SHIFT+Z

### ISSUE THREAD

**Issue by pp-latortue** [ThemeFuse/Brizy#1162]
For a Redo

**Comment by NataliaBB** [comment]
Hey @pp-latortue 
Keyboard shortcuts are almost done, within the next few updates, they will be released:
https://jmp.sh/0s9xizk

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
