### ISSUE TITLE
My Darft words are hidden

### ISSUE THREAD

**Issue by willypujohidayat** [ThemeFuse/Brizy#1163]
My Draft is hidden when i try to edit in different day, when I deactivate brizzy, they appear.

**Comment by NataliaBB** [comment]
Hey @willypujohidayat 
Natalia here!
Thanks for reporting.
We are working on this issue right now, please allow us a little more time for this fix.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
