### ISSUE TITLE
An error happened while trying to display this block

### ISSUE THREAD

**Issue by jaslink** [ThemeFuse/Brizy#1165]
Where is the FB group/page/chat to report this issue?

**Comment by codeclinic** [comment]
I also keep getting blocks throw up this error. Some will sporadicly resolve themselves then glitch out again whilst others have to be deleted and manually reconstructed.

**Comment by NataliaBB** [comment]
Hi @jaslink @codeclinic 
Natalia here!
Please report the bug via our facebook chat: 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by codeclinic** [comment]
@NataliaBB What's the point of having an issues board on Github if everything just gets marked as Closed, and we get told to repost on Facebook. Are you trying to keep issues hidden??
