### ISSUE TITLE
Integrate Stencil plugin

### ISSUE THREAD

**Issue by 2Ben** [ThemeFuse/Brizy#1166]
Hello,
Stencil released a plugin that allows us to use it (for making custom images very easily) directly from WordPress. It appears, in Gutenberg, as a new Tab (after the Upload and Media Library Tabs).
So when I want to put an image in Gutenberg I can directly access Stencil, make the image I want and get it where I want. It's quite great really.
However in Brizy when I want to change an image, I get the Upload and Media Library tabs for not the Stencil one. So it's much less convenient. 
I'd love to access Stencil from Brizy, can it be done?
Thanks!

In Gutenberg
![image 2019-02-26 at 10 49 32 am](https://user-images.githubusercontent.com/876405/53635122-1f82d500-3c57-11e9-910d-8e15ae5984fd.png)

In Brizy
![image 2019-02-26 at 10 49 09 am](https://user-images.githubusercontent.com/876405/53635124-1f82d500-3c57-11e9-9a90-b03f290e7678.png)

**Comment by NataliaBB** [comment]
Hello @2Ben 
Natalia here!
Thanks for our request, I've added in our roadmap, the team will look over this plugin compatibility.

My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
