### ISSUE TITLE
Edit bar wont go away as well getting 2 !

### ISSUE THREAD

**Issue by webdesign007** [ThemeFuse/Brizy#1168]
![screen shot 2019-03-01 at 7 21 06 am](https://user-images.githubusercontent.com/29644207/53640031-00edf100-3bf9-11e9-895e-9b924d9e4d1d.png)
![screen shot 2019-03-01 at 7 23 00 am](https://user-images.githubusercontent.com/29644207/53640032-00edf100-3bf9-11e9-9491-3a721db93fd4.png)
![screen shot 2019-03-01 at 8 04 02 am](https://user-images.githubusercontent.com/29644207/53640034-00edf100-3bf9-11e9-86ef-e244b4dc8f89.png)
Whats with the edit bars on every screen ? Then getting 2 of them ?

**Comment by NataliaBB** [comment]
Hey @webdesign007 
Please, update both versions and clear cache/browser+server.

Thank you
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
