### ISSUE TITLE
Issue with Image Border-Radius

### ISSUE THREAD

**Issue by nhanle92** [ThemeFuse/Brizy#117]
I am testing Brizy with fresh installation of WordPress with latest Astra theme.

I encountered an small bug that refuse to show the border-radius of an image to the saved page. In preview mode, it works like a charm but when I save the page and went to the live version, it did not work.

In Brizy builder:
![screen shot 2018-06-10 at 3 04 10 am](https://user-images.githubusercontent.com/28459250/41195689-b1d8f356-6c5c-11e8-99b7-fd23f5934ed0.png)

In live page:
![screen shot 2018-06-10 at 3 04 17 am](https://user-images.githubusercontent.com/28459250/41195691-b7aec080-6c5c-11e8-8d1e-ec0819428077.png)

Edit: The bug can be re-produced by adding any URL to the image.

**Comment by bagrinsergiu** [comment]
Hi Nhan,

I tested this issue in 1.0.9 and it work well for me like you can see in this screen: http://dl3.joxi.net/drive/2018/06/09/0028/0732/1860316/16/56ec72a728.jpg

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by nhanle92** [comment]
I removed them and created new image and they work. I still don't know which caused the issue but thank you a lot.

**Comment by nhanle92** [comment]
I reopen the issue because adding URL (Links) to the image will make its border-radius disappear.

**Comment by bagrinsergiu** [comment]
Thank you for details. Added in our bug list.

**Comment by marcellefter** [comment]
This has been fixed and will be included in the next update.
