### ISSUE TITLE
WordPress 5.1 content created with WP editor is hidden

### ISSUE THREAD

**Issue by andronic90** [ThemeFuse/Brizy#1170]
When I create a page or post with WP default editor and then I go to edit the content is hidden, when I disable the Brizy works fine.

Video: https://www.screencast.com/t/IHbaDgrE

Please inspect the problem.

**Comment by NataliaBB** [comment]
Hi Vlad!
This Issue has been fixed in the last, Free version update 1.0.64.

Cheers!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by andronic90** [comment]
Thank you!
