### ISSUE TITLE
Duplicate colums image width stays the same

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#1171]
You can see the problem by doing these steps

1. Create a new blank block
2. Add image element in one column 
3. Click on column options and then click duplicate
![duplicate](https://user-images.githubusercontent.com/34076187/53693829-6d5e2100-3dae-11e9-863e-d2d8ca450091.JPG)

**Comment by NataliaBB** [comment]
Hey @estraatios 
Apologizes for the late reply.
May I ask you, what theme do you use? Did you set some margins on the columns?

Regards, Natalia

**Comment by NataliaBB** [comment]
Hey @estraatios 
If the problem still occurs, please send me a short message via our facebook chat.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
