### ISSUE TITLE
brizy makes whole site wonky then disappears

### ISSUE THREAD

**Issue by frankly68** [ThemeFuse/Brizy#1172]
pages become wonky then site goes poof!

**Comment by NataliaBB** [comment]
Hello @frankly68 
Natalia here!
Please give me more details via our Facebook chat and mention this issue inside - 1172

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by frankly68** [comment]
Firstly, all pages edited with Brizy would be blank. After attempting to redo pages the site wold break and I would get an "Install WordPress" dialogue. After deactivating Brizy the site came back.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
