### ISSUE TITLE
double editing bar/ slider behaving

### ISSUE THREAD

**Issue by robsonet** [ThemeFuse/Brizy#1174]
Right now I’m building (live) a t-shirt shop (  [www.actvewear.com](url) ) and having these issues on my iPhone only - Chrome and Firefox are okay:
a)	 I’m getting DOUBLE editing bar on the left side
b)	I changed those pictures of the slider but when I open it on my iPhone first it shows the original block picture but when I click on it then my pictures shows perfectly. 
Please tell me, how can I fix this?

**Comment by NataliaBB** [comment]
Hello Robson! @robsonet 
Those issues have been solved in 1.0.64 update

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
