### ISSUE TITLE
mailchimp connector for pop up

### ISSUE THREAD

**Issue by lilsurepbc** [ThemeFuse/Brizy#1176]
Hi, I am not seeing the connector any longer for the pop up.

![image](https://user-images.githubusercontent.com/45666337/53892424-e8634980-3ff1-11e9-926b-6a578600d967.png)

**Comment by NataliaBB** [comment]
Hey @lilsurepbc 
Have you tried in the button toolbar? https://jmp.sh/UiLImLt 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
