### ISSUE TITLE
Contact form send direct reply to sender

### ISSUE THREAD

**Issue by L-Lazna** [ThemeFuse/Brizy#1178]
When recieving email from contact form on my website, the sender is Wordpress. Is there any way It can be changed to sender email so I can directly reply. By now I need to copy paste the email to reply.
Thank You
Lukas

**Comment by NataliaBB** [comment]
Hi Lukas!
We do have the SMTP mail option in our to do list: 
https://trello.com/c/SJcFPC1Y/35-form-integrations 
The deadline for this feature - 2  weeks.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
