### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by cbgvh2014** [ThemeFuse/Brizy#1179]
I went to update and hit the update button but it will not update the actual page just the editor in brizy. i tried several time to update a nothing happened.

**Comment by NataliaBB** [comment]
Hi @cbgvh2014 
Natalia here!
Please send me a message via our Facebook chat and mention this issue inside - #1179

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
