### ISSUE TITLE
Advanced Settings vanished

### ISSUE THREAD

**Issue by trock536** [ThemeFuse/Brizy#118]
I was editing an image and had set an animation, and went to change it and the advanced settings no longer appear. 1.09 with Astra Pro. Removing all plugins and/or changing themes makes no difference. Advanced settings absent - but only with the one image.
![image](https://user-images.githubusercontent.com/40127646/41195951-a8e9d164-6c04-11e8-9b07-4550b384c521.png)

I have set up a couple of pages with this and a few other issues that I've run into and can give login creds. I'll detail the other issues in separate posts.

Thanks. regards, Tony

**Comment by bagrinsergiu** [comment]
Hi Tony,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by trock536** [comment]
OK, will do, thanks.

**Comment by trock536** [comment]
I tried but it keeps asking me to log in to Messenger (which I am already logged into) and then when I click on the login screen it appears for a split second and then vanishes. Keep going round and round in circles doing this. Is there any other way I can get you the creds?

**Comment by bagrinsergiu** [comment]
1 moment please

**Comment by trock536** [comment]
Figured it out - image overlap can't be between blocks, and both images must be in the same block.

**Comment by bagrinsergiu** [comment]
This has been fixed and was included 1.0.16 update

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu

**Comment by trock536** [comment]
🙂
