### ISSUE TITLE
Issue with Mobile Animation 

### ISSUE THREAD

**Issue by KMej** [ThemeFuse/Brizy#1180]
Issue with Mobile Animation Loading - from social media preview

PLEASE HELP. The animation on the site functions properly on safari. However when loaded from instagram those elements with the animation are blank. 
What can be done?

**Comment by NataliaBB** [comment]
Hello @KMej 
Please, give me a page URL to check. 
Please, also, send me a short message via our facebook chat. I would like to reproduce this issue at my end.


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia
Mention this number inside your message #1180 

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by KMej** [comment]
Why was this closed without any replies?

On Mar 12, 2019, at 9:58 AM, NataliaBB <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #1180<https://github.com/ThemeFuse/Brizy/issues/1180>.

**Comment by KMej** [comment]
Hello

I am reaching out with a request for help with a site/theme I previously had issues with.

The site is currently not showing the logo - and when I go in through the backend it does not let me edit/add it.

Please advise.

The link to the site is;
rejuvefaceandbodyspa.com/



Thanks! Kaisha
