### ISSUE TITLE
Export Leads

### ISSUE THREAD

**Issue by theraidens** [ThemeFuse/Brizy#1182]
I found amazing that you save the leads from the forms but there are a way to export them?

**Comment by NataliaBB** [comment]
Hi @theraidens 
Natalia here!
Thanks for your request.
I've added in our trello map: https://trello.com/c/IFoZWZkO/208-form-export-leads

My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
