### ISSUE TITLE
[Feature Request] Save Pages as Templates

### ISSUE THREAD

**Issue by codeclinic** [ThemeFuse/Brizy#1183]
It's great that Brizy now includes premade page templates, but we can't currently save our own page layouts for future use.

Although blocks can be saved &/or made Global itd be really useful to be able to save a full page as a template after building it. Then this could be applied to other pages as the starting basis of new pages. This would make it possible to keep consistancy between pages over things like column widths, and colours etc.

**Comment by NataliaBB** [comment]
Hey Phil @codeclinic 
Thank you for the request.
We have this option in our internal GitHub, but I've just added in our trello roadmap.
https://trello.com/c/2BFyzusO/207-save-the-entire-page

We will keep working on it.
Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
