### ISSUE TITLE
[Feature Request] Infusionsoft integration

### ISSUE THREAD

**Issue by drufus** [ThemeFuse/Brizy#1185]
Adding here so that it is not just in the FB group. 

There should be an Infusionsoft integration for forms and the popups.

**Comment by NataliaBB** [comment]
Hi @drufus 
I've added in our trello map: https://trello.com/c/SJcFPC1Y/35-form-integrations 

Thank you!
My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
