### ISSUE TITLE
Form don´t send email 

### ISSUE THREAD

**Issue by renriquegs** [ThemeFuse/Brizy#1188]
My contact form is unable to send email and redirect to the page neither.

I have wordpress 5.1 and Brizy 1.0.64.

I followed the youtube tutorials to be sure I was doing configuration properly.

The contact form doesn't´t redirects and the email never reach. I try deactivating all the other plugins and still nothing.

I installed Contact Form 7 and worked fine so I can´t figure out the problem.

The contact form is located at: https://tropicanacabo.myrmexico.com/wp/hotel-tropicana-inn-san-jose-del-cabo-on-sale/

I try the form in safari and chrome Mac and in chrome PC. In all the cases didn´t work.

**Comment by NataliaBB** [comment]
Hello Enrique! 
Please send me a message via our facebook chat, and mention this issue inside #1188


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
