### ISSUE TITLE
Mobile Menu Selections Not Linking

### ISSUE THREAD

**Issue by brandonsutton** [ThemeFuse/Brizy#1189]
I've just launched my revamped website using Brizy, but upon viewing on my iPhone X (iOS 12.1.4), the hamburger menu items do not link to the appropriate pages. The selections come up, but they are not linked. I'm running Wordpress 5.1 with The Core Child theme. Please help. http://culture-agency.com

**Comment by NataliaBB** [comment]
Hello @brandonsutton 
Natalia here!
I see the menu is coming from the theme. 
Can you please give us a message via our facebook chat?  I would like to test the menu. Please mention the issue number inside #1189


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

Thank you?

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by brandonsutton** [comment]
Thanks, Natalia. Link to the FB page?

:::::::::::::::::::::::::::::::::::::
Brandon Sutton
Culture
http://culture-agency.com<http://culture-agency.com/>
404.391.7370
