### ISSUE TITLE
Global color changes video button in edit page, but color reverts in preview and publish.

### ISSUE THREAD

**Issue by trock536** [ThemeFuse/Brizy#119]
I can change the color of a video play button via the global color settings, but as soon as I hit preview or publish, it reverts. The button is on top of a header image. If I try to change it at the button itself, the settings box covers the button and there doesn't seem to be a way to move it out of the way.

![image](https://user-images.githubusercontent.com/40127646/41196047-3f8b53b2-6c06-11e8-90b2-f84a365c10bb.png)
![image](https://user-images.githubusercontent.com/40127646/41196050-4545b9be-6c06-11e8-8f53-fedb2038013d.png)

I have set up a couple of pages with this and a few other issues that I've run into and can give login creds.

Regards, Tony

**Comment by bagrinsergiu** [comment]
Hi Tony,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by trock536** [comment]
I tried but it keeps asking me to log in to Messenger (which I am already logged into) and then when I click on the login screen it appears for a split second and then vanishes. Keeps going round and round in circles doing this. Is there any other way I can get you the creds?

**Comment by trock536** [comment]
Messenger worked with Firefox.

**Comment by trock536** [comment]
Another example where the preview doesn't match the edit page - different button font color, and different paragraph font. 1st image is the edit page.

![image](https://user-images.githubusercontent.com/40127646/41197504-ec13fe72-6c2e-11e8-9abf-185a91b1ab80.png)

![image](https://user-images.githubusercontent.com/40127646/41197507-f98c838a-6c2e-11e8-903c-123b79ddc52a.png)

**Comment by trock536** [comment]
And in this one, the preview page image is darker than the edit page one.

![image](https://user-images.githubusercontent.com/40127646/41197525-924b3fa8-6c2f-11e8-9ba1-07726f54afc2.png)

![image](https://user-images.githubusercontent.com/40127646/41197527-9cad1a98-6c2f-11e8-9752-552154712f48.png)

**Comment by trock536** [comment]
The SiteGriound color and typography issue is fixed - thanks, Sergiu! :)
