### ISSUE TITLE
Brizy and CPanel I/O Usage Limit

### ISSUE THREAD

**Issue by ahmetakkaya38** [ThemeFuse/Brizy#1190]
I used Brizy for landing page. Is there any possibility that Brizy using I/O usage excessively (I use CPanel)

**Comment by NataliaBB** [comment]
Hey @ahmetakkaya38 
Brizy Lading Page Prewiew is 100% compiled HTML, CSS and JS files available on your server
After page publish Brizy don't using I/O resources

Let me know if you have any questions.
Cheers!
