### ISSUE TITLE
navbar not found

### ISSUE THREAD

**Issue by creativemacmac** [ThemeFuse/Brizy#1192]
Hey there folks :)

I am playing around with Brizy  - the pro version - whenever I add the navbar from the left 'elements' panel it's ok it displays - but if I add a template 'header' block it can't find the navbar - the builder just says 'select a navbar, but there is nowhere to select a nav

regards
Linda

**Comment by NataliaBB** [comment]
Hello Linda! @creativemacmac 
As I reported on the facebook chat, we are working on this problem now.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
