### ISSUE TITLE
cannot add background color in icon box

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#1195]
Hi.

I would like to be able to have background and borders in the icon box element

Thanks

**Comment by NataliaBB** [comment]
Hi @estraatios 
Thanks for your request.
I've added in our internal GitHub, we will look over this option asap.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
