### ISSUE TITLE
Rows inside row inside row

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#1197]
Hi

I would like to be able to add a 3 layer row (Rows inside a row, inside a row.

Thanks

**Comment by NataliaBB** [comment]
Hello @estraatios 
Thanks for this request.
Also added in our internal improvement list.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
