### ISSUE TITLE
Popup linked in global menu doesn't appear

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1199]
A popup linked in a header set to global and inserted on a second page doesn't fire the popup? Only on the page the popup was defined originally it appears and on the other pages it can't even be assigned.

https://screen.maxziebell.de/20190315-x4ntb.mp4

**Comment by NataliaBB** [comment]
Hey @MaxZiebell 
Thanks for reporting.
We already fixed this bug. It will available within the next updates.

My  Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
