### ISSUE TITLE
Trouble when images overlap

### ISSUE THREAD

**Issue by trock536** [ThemeFuse/Brizy#120]
When I have overlapping images, sometimes I can't get at the settings for the image that is on top of another one, and sometimes if I do get access and click on the image anchor corner to resize it, what gets resized is the row padding beneath it. I also can't change the color of the grey border around the image.

I have set up a couple of pages with this and a few other issues that I've run into and can give login creds.

regards, Tony

**Comment by bagrinsergiu** [comment]
Hi Tony,

Can you give me a screenshot for this issue?

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by trock536** [comment]
Done. Messenger worked with Firefox.

**Comment by trock536** [comment]
Solved it.

**Comment by trock536** [comment]
It works when the images are in the same block, but when they are in adjacent blocks, you lose access to the settings for the overlaid block.

**Comment by maxval94** [comment]
Hi

This has been fixed and will be included in the next update (1.0.14), thanks for reporting.

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Maxim

**Comment by trock536** [comment]
Thank you, Maxim. :)

Regards,

Tony
