### ISSUE TITLE
Gallery not visible on tablet and/or mobile (it is on desktop)

### ISSUE THREAD

**Issue by bartistiek** [ThemeFuse/Brizy#1200]
The images of the gallery are not visible on tablets and mobiles. The container div is loaded including background and colours, the images are visible when using safari on a desktop in responsive mode for tablet and/or mobile view, but on the mobile itself they are not (Iphone 7). I have cleared the cache on the mobile, opened the site in a private window to make sure it is not cache related etc but no images.

**Comment by NataliaBB** [comment]
Hello @bartistiek 
Natalia here!
Please, send me your page URL and wp credentials via our facebook chat: 
Please also mention this issue number inside 1200


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
