### ISSUE TITLE
Why do updates RESET contact form integrations

### ISSUE THREAD

**Issue by TheCrucible** [ThemeFuse/Brizy#1202]
I'm NOT happy guys. https://www.screencast.com/t/tDWnuKLHOj7

Every update of your plugin resets the integrations and forms on pop ups, and contact pages. This happened last update as well. I have to go to each client site, and reconfigure and save the email send to information for every form. NOT fun.

Some have a Zapier email, some have client email, I have to reconfigured every single one!

Why?

**Comment by DimiBaitanciuc** [comment]
That shouldn't happen, we'll look into it asap. Sorry for the inconvenience. I bet is super frustrating, I  know I'd go crazy having to do it every time. 

@bagrinsergiu will look into it.

**Comment by TheCrucible** [comment]
Please check. I confirmed on two sites I updated to latest version of PRO. On both I had to reconfigure the target email on contact forms, and save again. That means clients don't get leads! Not good.

**Comment by DimiBaitanciuc** [comment]
We've looked into it and the guys discovered some issue and fixed something in the scripts. My understanding is that the issue might be server related and we still need to track this and see if it does the trick for you on our next PRO update that is coming today or tomorrow. 

I'll keep you in the loop so you can take a look once the PRO is out. Thanks for your patience.

**Comment by DimiBaitanciuc** [comment]
We've updated today the free and pro, please update to the latest version both of them and let us know if the issue still persists. 

If it does we'll need to look into your specific install and see what is causing this. Let us know.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
