### ISSUE TITLE
Sticky menu possible bug

### ISSUE THREAD

**Issue by TheCrucible** [ThemeFuse/Brizy#1203]
I'm working on a new site, latest version of Brizy Pro. When I have menu set to sticky, and scroll down, I get a new menu (I guess a sticky one?) that shows error, because no menu is selected. I just want the original menu I've created to stay sticky, not have a 2nd one. When I set menu to "fixed" it works fine again.

I used one of your pre built (dark) menu blocks when this happens. Fixed is fine, sticky is error when you scroll down on page after saving.

**Comment by NataliaBB** [comment]
Hey @TheCrucible 
I've tried to reproduce the sticky menu problem:

https://jmp.sh/wJpUB2E 

Does your error appear in the menu element of the sticky block?

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
