### ISSUE TITLE
Checkbox in form

### ISSUE THREAD

**Issue by jverspay** [ThemeFuse/Brizy#1204]
Would it be possible to have checkboxes in forms. I'd like to add one for my subscribers to explicitly confirm the use of their email-adress for contacting them on the project.

Cheers,
Johan

**Comment by TheCrucible** [comment]
I need this also. The Brizy contact form is lacking features, and still doesn't validate a phone number field, I have to set it to text to work properly?

**Comment by NataliaBB** [comment]
Hello @jverspay and @TheCrucible 
Checkbox option will be available in the next form version (app 2 weeks) 
The next update will have the number field fix.


Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by jverspay** [comment]
Dear Natalia,

 

Great! Thnx!

 

Best regards,

Johan

 

Van: NataliaBB <notifications@github.com> 
Verzonden: woensdag 20 maart 2019 15:42
Aan: ThemeFuse/Brizy <Brizy@noreply.github.com>
CC: jverspay <jverspay@telfort.nl>; Mention <mention@noreply.github.com>
Onderwerp: Re: [ThemeFuse/Brizy] Checkbox in form (#1204)

 

Hello @jverspay <https://github.com/jverspay>  and @TheCrucible <https://github.com/TheCrucible> 
Checkbox option will be available in the next form version (app 2 weeks)
The next update will have the number field fix.

Regards, Natalia

**Comment by loosemybrain** [comment]
Hey guys, any news about checkboxes, radio buttons etc.?

regards
