### ISSUE TITLE
GIF files do not work

### ISSUE THREAD

**Issue by rdpshop-info** [ThemeFuse/Brizy#1208]
Trying to add GIF animated images to a page built with Brizy. The images are not animated, only still. How do I get them to work or is Brizy not designed to run something like this.

**Comment by NataliaBB** [comment]
Hello @rdpshop-info 
Try to add GIFs via embed element. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
