### ISSUE TITLE
 When I change the row from boxed to full, it loses WYSIWYG.

### ISSUE THREAD

**Issue by trock536** [ThemeFuse/Brizy#121]
When I change a row from boxed to full, the image spacing looks very different in the editor when compared to the preview or publish mode, which makes it very hard to design the spacing of the elements on the page, no matter which Astra Pro page-width or container-width settings I use. 

![image](https://user-images.githubusercontent.com/40127646/41196138-e63315aa-6c07-11e8-9b33-e57878847ba9.png)
![image](https://user-images.githubusercontent.com/40127646/41196140-ed0ddaf4-6c07-11e8-9ff2-ef75734f41a5.png)

I have set up a couple of pages with this and a few other issues that I've run into and can give login creds.

Regards, Tony

**Comment by bagrinsergiu** [comment]
Hi

Fixed in 1.0.17 

Can you confirm if it is working with last changes?

Thanks

**Comment by trock536** [comment]
Yes, fixed - thanks!

Tony
