### ISSUE TITLE
mailchimp integration

### ISSUE THREAD

**Issue by lilsurepbc** [ThemeFuse/Brizy#1212]
hi, the mailchimp plugin got disconnected (don't know why) and now when i try to reconnect - it just spins on this screen.

![image](https://user-images.githubusercontent.com/45666337/54760499-349bb580-4bbe-11e9-8427-4ac431dc33b6.png)

**Comment by NataliaBB** [comment]
Hello @lilsurepbc 
Natalia here!
What Brizy versions do you have installed? Can you check please the console of what errors are displayed?

Thank you!

**Comment by lilsurepbc** [comment]
Hi Natalia,

Just saw a Brizy update.  Below is what I have.
Where do I see the console for errors?

[image: image.png]

Justin Lyons
Founder
224-307-5556

blazefamily.com

**Comment by NataliaBB** [comment]
Hello @lilsurepbc 
We will have a fix for the Mailchimp integration in the next update.
Sorry for the inconveniences.
My Best regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
