### ISSUE TITLE
Short Code appears in page builder but, not on live page

### ISSUE THREAD

**Issue by lilnitsch** [ThemeFuse/Brizy#1213]
Getting a "Oops! Only one WP3D Shortcode per page! The first one is above and this (additional) one was skipped!" even though there is no other WP3D Shortcode on the page. I even tried a completely blank page with the same result. http://capturenw.com

**Comment by NataliaBB** [comment]
Hello @lilnitsch 
Natalia here!
It will be possible to test the WP3D Shortcodes in your page, accessing your dashboard?
Please,  send me a message via our Facebook chat and mention this issue inside - 1213

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
