### ISSUE TITLE
An error happened while trying to display this block (Version 1.0.65)

### ISSUE THREAD

**Issue by iZEVS** [ThemeFuse/Brizy#1215]
Hello,
This bug appeared after today's update. Version 1.0.65
It appears when you click on ANY of block settings circle.
Please FIX it ASAP!
Thank you!

**Comment by iZEVS** [comment]
Brizy Pro 0.0.19 solved that problem. Thank you!

**Comment by NataliaBB** [comment]
Hey @iZEVS 
Natalia here!
Yes, the fix was in the PRO update.



I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
