### ISSUE TITLE
Upon importing XML: my saved blocks dont load and cannot edit

### ISSUE THREAD

**Issue by pmopmopmopmo** [ThemeFuse/Brizy#1216]
When I import my XML file my saved blocks just load and wont show the preview of what they are. Additionally, when I select one, and then select the edit stripe option (image attached) it removes the block and gives me an error message (see attached).

![Screen Shot 2019-03-21 at 11 34 21 AM](https://user-images.githubusercontent.com/48805865/54776416-4cc70100-4bcd-11e9-894c-6211741c78d5.png)

![Screen Shot 2019-03-21 at 11 33 38 AM](https://user-images.githubusercontent.com/48805865/54776361-315bf600-4bcd-11e9-8c55-d97184c2fc67.png)

**Comment by NataliaBB** [comment]
Hello @pmopmopmopmo 
Natalia here!
What plugin do you use to import XML file?  Do you have the same error with ALL in One Migration plugin?

Regards, Natalia

**Comment by pmopmopmopmo** [comment]
Hi there Natalia,

I use the Wordpress Importer to do so, when I export I am making sure
everything from my site is within. Additionally, I don't want to use the
ALL in One Migration plugin for WP.

Please let me know what you think.

Thanks!

**Comment by pmopmopmopmo** [comment]
Hi Natalia,

I am consistently having this issue with Brizy - do you know of any solution.

Thanks!

-Patrick

**Comment by NataliaBB** [comment]
Hello Patrick! @pmopmopmopmo 
Sorry for my late reply .
Please, let me check and fix this issue within your dashboard. I will need you wp credentials, send them please via our facebook chat:

Please also mention this issue number inside: 1216

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by pmopmopmopmo** [comment]
Thanks for your care Natalia. Unfortunately I cannot provide you the login
information - is there anyway you can simpy walk me through the steps you
would take?

**Comment by pmopmopmopmo** [comment]
Hi Natalia - I would also be happy to set up a screen share so you can walk
me through that way.

Thanks again!

**Comment by pmopmopmopmo** [comment]
Hi Natalia! Just checking in on this, please let me know how we can resolve
since this is still a re-occurring issue.

Thanks!

-Patrick

**Comment by pmopmopmopmo** [comment]
Hi Natalia,

Circling around on this matter - I still have no resolution. Please advise.

Thank you,

-Patrick

**Comment by NataliaBB** [comment]
Hello Patrick @pmopmopmopmo 
Sorry, I will need to check the files, I need to migrate your page with another plugin and upload them on my website, and check again if everything is right. 
At least, send me a back-up here: https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
