### ISSUE TITLE
[Feature Request] Mailto

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1218]
I'd love to see a mailto option for emails in the link panel with optional obfusication.

<img width="555" alt="20190320-p21s9(1)" src="https://user-images.githubusercontent.com/1752114/54783849-bf160080-4c22-11e9-8f1d-a1c48ab60039.png">

**Comment by MaxZiebell** [comment]
Could also be called `special` and offer multiple things like mailto, tel etc.

**Comment by welahavle** [comment]
Until then you can try "mailto:email@address,com". I think it works that way.

**Comment by MaxZiebell** [comment]
Yes, but that's not the "Brizy" way. Also no obfusication. But thank you!

**Comment by Voronium** [comment]
+1  for the obfuscation reason!

**Comment by NataliaBB** [comment]
Hi @MaxZiebell 
Added in our to do list: https://trello.com/c/SJcFPC1Y/35-form-integrations

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
