### ISSUE TITLE
[Feature Request] ConvertFox integration

### ISSUE THREAD

**Issue by madz00** [ThemeFuse/Brizy#122]
Would be nice if this could happen or please at least give the possibility to easy link custom html form to the Brizy form submit button (Thrive Leads has something similar maybe is worth looking at them) so we can use many ESP and CRM that don't have an specific integration in Brizy but all have html forms.
Also for the popup builder... I'm so curious to try it!

**Comment by bagrinsergiu** [comment]
Hi @madz00 

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by bagrinsergiu** [comment]
Hi again,

For ConvertFox forms  it is possible to use Ember widget: http://dl3.joxi.net/drive/2018/06/10/0028/0732/1860316/16/42ff797ae8.jpg

Brizy form + ConvertFox - added in our to do list but i don't promise we will implement it. We have ~ 20 integrations in our to do list. 

Sergiu

**Comment by madz00** [comment]
Hi Sergiu, I understand, this is why I suggested the Thrive Leads approach so we can use Brizy for styling custom html form from whatever ESP or CRM

**Comment by bagrinsergiu** [comment]
ok ok Thanks

**Comment by collizo4sky** [comment]
Collins from MailOptin here. Same way we integrate with Elementor (see https://elementor.com/email-marketing-integration/)  to provide wide range of ESP connections, we are willing to do something similar for Brizy.

We can stay away if you plan to have native integrations for all ESP.

**Comment by bagrinsergiu** [comment]
Hi Collins 

We added it in our to do list. 

Thanks.
Sergiu

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/SJcFPC1Y/35-form-integrations

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
