### ISSUE TITLE
Stuck on Mailchimp 

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1223]
Added the API key and got all the lists ... but when going to the next step after choosing the desired list the interface is stuck. Loading symbol on button. Now I get an issue error when trying to acces this section.

https://screen.maxziebell.de/20190323-55c9c.mp4

**Comment by NataliaBB** [comment]
Hi @MaxZiebell 
There is a fix about the integrations API keys. It will be available in the next update, planned this week.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by NataliaBB** [comment]
Hey @MaxZiebell 
We have the fix in the new update 1.0.66 for mailchimp. please check!

Regards, Natalia
