### ISSUE TITLE
Click on page section get error

### ISSUE THREAD

**Issue by juliedulong** [ThemeFuse/Brizy#1224]
Whenever I click on a main section to adjust it, I get the following error:

An error happened while trying to display this block
You can open an issue or remove this block

happens for newly added blocks and existing blocks. See screencast below.

[](http://somup.com/cqe0bAnOhj)

**Comment by graciashtg** [comment]
It goes blank when i open on the layout.

**Comment by NataliaBB** [comment]
Hi @graciashtg @juliedulong 
Let us know if you have any other problems, via our Facebook chat.

Thanks!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
