### ISSUE TITLE
Brizy: theme does not natively support menus

### ISSUE THREAD

**Issue by sunrisetourstravel** [ThemeFuse/Brizy#1225]
Hi Brizy,

After use your plugin awhile come out the problem is the message in wordpress menu "theme does not natively support menus" and my main page suddenly the topper got white space gap empty and it's doesn't got any error code in the php file. May i know how to solve this issue?

Awaiting your reply. Urgent

**Comment by NataliaBB** [comment]
Hello @sunrisetourstravel 
Natalia here, Brizy team
This is a WordPress issue + the theme. 
Unfortunately, I can not help you in this case. You have 2 solutions:
1. Change the theme.
2. Ask the theme author to write a PHP code for the menu. You can also write the code, but in this case, you will need to customize also the rest of the template. 

By the way, what theme do you use?
Thank you!
Regards, Natalia

**Comment by sunrisetourstravel** [comment]
Hi Natalia,

Firstly, i need to thank for Brizy offer the such of good web builder
plugin for all of the user and save a lot of time to create the nice and
premium web page layout and most of us are no complain as i guess.

But, back to the point and now my company wordpress theme is facing the
minor issue for the gap topper of menu https://www.sunrise.com.my/ after
suddently update the plugin last time ago and Twenty Nineteen theme.

Here looking for your advice is that any way or solution to solve this
issue?

Regards, Max

**Comment by sunrisetourstravel** [comment]
Hi Natalia,

Just update you and i was solve this issue already and now my theme is
getting back to normal.

Thank you and have a nice day!

**Comment by NataliaBB** [comment]
Hi @sunrisetourstravel 
Thanks for the update!


I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
