### ISSUE TITLE
Brizy Pro opt in pop up does not connect to Mailchimp

### ISSUE THREAD

**Issue by juliedulong** [ThemeFuse/Brizy#1227]
Brizy Pro will not connect the pop up to Mailchimp service. It stalls where its to connect to correct list. Screencast here: http://somup.com/cqeOIhnOtl

**Comment by NataliaBB** [comment]
Hello @juliedulong 
Natalia here!
There is a fix in the next update for the MailChimp integration. 
Sorry for the inconvenience.

My  Best Regards, Natalia

**Comment by juliedulong** [comment]
Thanks Natalia,

I eventually saw that in another thread.

Cheers!
-- 
Julie
 Dulong, Prov. RGDDigital | Print | 
E-Commerce






     
   	NataliaBB        Wednesday,
 March 27, 2019 10:48 AM    
  Hello @juliedulong
Natalia here!
There is a fix in the next update for the MailChimp integration.
Sorry for the inconvenience.
My  Best Regards, Natalia

—You
 are receiving this because you were mentioned.Reply to this email 
directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ThemeFuse/Brizy","title":"ThemeFuse/Brizy","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ThemeFuse/Brizy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NataliaBB in #1227: Hello @juliedulong \r\nNatalia here!\r\nThere is a fix in the next update for the MailChimp integration. \r\nSorry for the inconvenience.\r\n\r\nMy  Best Regards, Natalia "}],"action":{"name":"View Issue","url":"https://github.com/ThemeFuse/Brizy/issues/1227#issuecomment-477190337"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ThemeFuse/Brizy/issues/1227#issuecomment-477190337",
"url": "https://github.com/ThemeFuse/Brizy/issues/1227#issuecomment-477190337",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by NataliaBB** [comment]
ok ;) 


I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by NataliaBB** [comment]
Hey @juliedulong 
Have the fix on a new 1.0.66 update. Please check ;)

Regards, Natalia
