### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by welahavle** [ThemeFuse/Brizy#1228]
Images not loading on my wordpress site. Done everything to optimize images, re-uploaded them, nothing helped. They choose randomly when to load and when not to load. Same thing with background images as with "front" images.
In brizy editor everything looks and works perfect, no images disappearing or not loading. Only when I visit my site, or when I go to preview mode then loading problem appears.

Thank you.
Hope you can help me and hoping that fix is already on its way.

**Comment by NataliaBB** [comment]
Hello @welahavle 
Natalia here! 
Please, allow me to test the image issue within your wp dashboard.
Please send me a message via our Facebook chat and mention this issue inside -  1228 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia to test this issue in your wp dashboard. 
Please le

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
