### ISSUE TITLE
[Feature request] #PostContent Font 

### ISSUE THREAD

**Issue by welahavle** [ThemeFuse/Brizy#1229]
Please, please let us change font for the dynamic #PostContent. We can chose fonts for #PostTitle, #PostDate, #PostTime, and everything else related to dynamic posts, except the MAIN thing, content it self. This is a big thing. 

Please, make a priority to fix existing features before adding new ones, 

Thank you

**Comment by NataliaBB** [comment]
Hi @welahavle 
Natalia here!
Yes, we have an open ticket about this issue. 
We need more time to solve it.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hello!
I've added this feature request in our roadmap in order to track the working process.
https://trello.com/c/qWqXCzjz/222-edit-content-in-dynamic-content-elements

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
