### ISSUE TITLE
Page Content Disappears when adding in embed from Salsa Labs

### ISSUE THREAD

**Issue by caitmh** [ThemeFuse/Brizy#1232]
I'm trying to add a Salsa form to our page and whenever I add in the code with Brizy's embed function, the page content disappears and I'm left with only a header and footer.

**Comment by NataliaBB** [comment]
Hello @caitmh 
Natalia here! Apologizes for the late reply.
Please allow me to test in your dashboard and to try to reproduce the issue.
If it is not possible, give me a link to the plugin page, in order to install the plugin and to check at my side.

Thank you!
Natalia

**Comment by caitmh** [comment]
Thanks, Natalia. I believe you have my login info from FB messenger. Let me know if you need it again.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
