### ISSUE TITLE
Feature Image covers Breadcrumbs

### ISSUE THREAD

**Issue by Walkabout7** [ThemeFuse/Brizy#1233]
Hi Guys,

We have added Breadcrumbs to top of the page, on the right-hand side, but the feature/main image covers the breadcrumb text! ( using Oceanwp Theme )
Is there some way of being able to move feature image down ( or up ) the page as required?
Thanks

**Comment by NataliaBB** [comment]
Hi @Walkabout7 
Natalia here!
Apologizes for the late reply 
Can I have a page URL to check it?
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 
No reply.
I’m closing this issue to keep the issue database slim, Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by Walkabout7** [comment]
Hi Natalie,

Apology for my late reply had internet problems here.

I am using Oceanwp, so it was their settings that were causing the problem,
and been fixed now. ( not Brizy )

Just have to better understand the integration with Oceanwp and Brizy
better, all is a learning curve.

So thanks for your assistance.

I think Brizy is great and will keep improving, get even better in the
future.
The only fault I find with Brizy -
is the covering of what you want to edit with the dashboard that displays
all the options to do editing, that's a bit frustrating, otherwise is great.

I am sure you guys already heard of this, and I know it would be a major
fix, but am sure you guys will work it out in the future to improve this!

Anyways good job, keep it up, as you have a winner

cheers
Steve
