### ISSUE TITLE
Cropped Vimeo video background

### ISSUE THREAD

**Issue by krol1k** [ThemeFuse/Brizy#1234]
First, the cropped player is shown with a preload icon , then it stretches over the entire section. How to make invisible this process?

**Comment by NataliaBB** [comment]
Hello @krol1k 
Natalia here!
I've created an issue with this problem. We have on our list an improved module for videos, but I can not give you a deadline on this release.

Sorry for the inconveniences.
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
