### ISSUE TITLE
Click on section button gives error and suggest to enter topic

### ISSUE THREAD

**Issue by pjssms** [ThemeFuse/Brizy#1235]
https://formacaowordpress.pt/trabalhos/

I am not able to duplicate same sample pages or to change the background to white.

**Comment by gdaimansion** [comment]
Hi! I am also getting an error notification when trying to edit blocks

**Comment by NataliaBB** [comment]
Hello @pjssms @gdaimansion 
I see the colour is set from the editor: https://jmp.sh/EI0IyAo
Could you please give me some more details? how you change the background in editor mode? Give me a screenshot
You can also send the credentials I will look over it by myself
Natalia

**Comment by pjssms** [comment]
On this page

https://formacaowordpress.pt/trabalhos/

on the back office sometimes it returns this message

on editing the page and cliking on the black circle

it gives this

and the image dissapears

I have done the tf plugins update, other plugins update, disabled redis
cache and wordfence but still the error.

it is safe to send the credentials over this github ?

it is running in ubuntu with runcloud on top of it. I am updating now
server software

**Comment by NataliaBB** [comment]
Hello @pjssms 
Natalia back here! 
Apologizes for the late reply.
Please give me a message, by submitting  a ticket here: https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
