### ISSUE TITLE
Cannot Edit Brizy Pages after update

### ISSUE THREAD

**Issue by angelahlp** [ThemeFuse/Brizy#1236]
I updated the Brizy plugin yesterday AND the day before (back to back updates). after the first day update I was unable to edit pages in Brizy (just continuously shows the loading icon), the icons are no longer displaying on the site, the slider on the home page editor is no longer working, the site now longer shows the title in the page header - from "global" templates it seems ...

I need this fixed asap - please help!

**Comment by NataliaBB** [comment]
Hello @angelahlp 
Natalia here!
Please send me a message via our Facebook chat and mention this issue inside - 1236

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
