### ISSUE TITLE
Missing Block Content

### ISSUE THREAD

**Issue by souljoy** [ThemeFuse/Brizy#1238]
The following three blocks (both in Light and Dark) format only have half their content showing when they are imported into a theme.  It has been like this since Pro was released but I have only just reported it now as I would like to use these well designed blocks for some post work.  I know it is only a minor issue but it would be great to have it fixed properly as soon as you can.

With regards to the latest Brizy Pro 19 update, I would like to say a BIG "GREAT JOB" guys!!  The new PRO Templates look amazing and are beautifully designed.  The new Layouts Popup is great too!  However, I would personally prefer to be able to manually scroll over the chosen layout on the left hand side rather than have it automatically scroll up and down on its on with hover.  I find this too fast to be able to view properly.  Yes, one gets an overall view of what the layout is like but it would be nice to just do this manually.  Just a personal observation.

I would also like to say a BIG "THANK YOU" for the new larger Mobile view and the ability to edit more features in this mode instead of having to revert to Desktop to make design adjustments.  Designing first in mobile is a must now and, therefore, the ability to fully edit in Mobile view, would really be a great feature.

And, WELL DONE on the new Block Kit!!  The proposed designs look amazing!  I am really looking forward to be able to use these as soon as you can release them??

Great progress guys!!  Keep it coming!  Thank you for all your hard work.

![Block-one](https://user-images.githubusercontent.com/44711252/55284249-40af1200-5338-11e9-9226-e2e8a2f1edb4.JPG)
![Block-two](https://user-images.githubusercontent.com/44711252/55284251-47d62000-5338-11e9-8e39-cb2b39965fb8.JPG)
![Block-three](https://user-images.githubusercontent.com/44711252/55284253-4ad11080-5338-11e9-92ee-797ce9642551.JPG)

**Comment by NataliaBB** [comment]
Hello @souljoy 
Natalia here!
First of all THANK YOU for your feedback. This appreciation is extremely important for the entire team. 

Regarding the blocks issue- we already work on the fix, in the next PRO update will have the fix. 
For the rest - Can you please send me a message via our facebook chat? I would like to discuss with you.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
