### ISSUE TITLE
Search for Element

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#124]
It would be good to have a search button at the top of the elements panel to be able to search for elements to be insertrd into the  page. Even with the the current few elements, I find myself sometimes taking a bit of time to find the right one. Imagine when the elements get more crowded!

**Comment by bagrinsergiu** [comment]
Thank you for suggestion.

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/0qmsfM7q/97-search-for-element

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
