### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by cBread** [ThemeFuse/Brizy#1240]
I've add SSL Cert to my site and the Header and Footer have disappeared. 
www.100HeroesPG.com

**Comment by NataliaBB** [comment]
Hello @cBread 
I see headers are from the theme, right? anyway, could you please give me a message via our facebook chat? I will check the problem with header+footer.
Please mention the issue inside 1240
Thank you!
Cheers!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
