### ISSUE TITLE
Menues disappear, styling get wrecked

### ISSUE THREAD

**Issue by thisshitt** [ThemeFuse/Brizy#1242]
Hi there, after i made the misstake to use brezy i suffer now with the consequences. Main and Footer Menues of my website disappear and the styling of the fonts also get wrecked. All this happened after "updating" or publishing a page made with your software.  U need details? Which ones.

**Comment by NataliaBB** [comment]
Hey there @thisshitt 
Natalia here!
Yes, I need details - you created a new page with Brizy? what template did you use? that theme do you use? what plugin version do you have? 
Give me please your wp credentials and I will check the page.
Thank you!

**Comment by clifblasingame** [comment]
Did you have an answer? I am using the Core theme with Brizy and my menus are not showing. http://execrecruit.designarkansas.com

**Comment by bethedgoose** [comment]
Hello - my Brizy styling is completely ruined when I switch to the default template to try and display header and footer that comes with my theme - Customify. 
Any feedback on this? Customify is a recommended Brizy theme.

**Comment by NataliaBB** [comment]
Hello @clifblasingame @bethedgoose 
Natalia here!
Apologizes for the late reply. I've been off for 1 week and just started to check all messages in here. 
Regarding the menu, let me please test the pages at your end. Submit for us a ticket here, on our new support platform: https://support.brizy.io/hc/en-us

Waiting for you!
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
