### ISSUE TITLE
Alt tags to be insterted in Brizy

### ISSUE THREAD

**Issue by geertSchep** [ThemeFuse/Brizy#1243]
Hi,
alt tags should be possible to insert in the page builder and going back and forward to the media.
thanks.

**Comment by NataliaBB** [comment]
Hello @geertSchep 
Natalia here!

Apologizes for the late reply. May I have the page URL to test on tablet/mobile mode?

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hello @geertSchep 
We added in the latest updates this option. Can you check?

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
