### ISSUE TITLE
Full width blocks in tablet and mobile mode become BOXED [Version 1.0.67]

### ISSUE THREAD

**Issue by iZEVS** [ThemeFuse/Brizy#1245]
Full width blocks in tablet and mobile mode become BOXED [Version 1.0.67]
How to change it in the tablet and the mobile modes?
For example: when you add full width revolution slider and make that block full width also, it becomes boxed in mobile and tablet versions of the website.
This appeared after the 1.0.67 update.

**Comment by iZEVS** [comment]
update 1.0.68 and 1.0.69 didn't fix it

**Comment by NataliaBB** [comment]
Hello @iZEVS 
Natalia here!

Apologizes for the late reply. May I have the page URL to test on tablet/mobile mode?

Thank you!
Regards, Natalia

**Comment by iZEVS** [comment]
Helo!
I like Brizy more than any other analog.
https://ultrafastsystems.com/products/ <https://ultrafastsystems.com/products/>
Please pay attention to the revolution sliders in tablet and mobile modes. They were fullwidth before 1.0.67…… update.


I've also found some problems with jQuery after that update
https://ultrafastsystems.com/time-resolved-spectroscopy-questions-answers-knowledge-base/ <https://ultrafastsystems.com/time-resolved-spectroscopy-questions-answers-knowledge-base/>
No live search any more. 


Many thanks in advance! Regards guys! Your product is awesome! Just fix the bugs.

**Comment by NataliaBB** [comment]
Hey @iZEVS 
Thanks for your quick reply. 
Yes, I see the page is boxed. 
Can I have your wp creds to run some tests?
You can give them within a support ticket: https://support.brizy.io/hc/en-us 
My best Regards, Natalia

**Comment by iZEVS** [comment]
Natalia, do you speak Russian by chance? :)
Unfortunately I can’t provide you the access. Sorry.
But if you need any other info from me I can give you that.

Thank you!
Stanislav

**Comment by NataliaBB** [comment]
Здравствуйте Станислав!
Да, я говорю на русском языке :) 
У меня есть вопросы по поводу "some problems with jQuery after that update"
Сможете отправить более подробнее здесь https://support.brizy.io/hc/en-us? 

Спасибо!
С уважением, Наталья

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
