### ISSUE TITLE
Changing the Filter "Order" of the WordPress Posts widget does not work

### ISSUE THREAD

**Issue by DenMurphy** [ThemeFuse/Brizy#1246]
Changing the Filter "Order" of the WordPress Posts widget does not work. The order remains Oldest to Newest always.

![image](https://user-images.githubusercontent.com/6964524/55526671-465e7c00-56d9-11e9-946c-cc0482faf108.png)

I am using Brizy v1.068, Brizy Pro v0.0.19, and the Astra Pro v1.8.0 Theme.

I have tested using a list of 6 Blog Posts with Date, ID, Title, Date, and Random selections with no change in results.

**Comment by NataliaBB** [comment]
Hello Dennis! @DenMurphy 

This bug was already fixed and it will be included in the next release
Apologizes for the inconvenience. 

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
