### ISSUE TITLE
Losing Focus

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1247]
When editing since the latest update (the one with the keyboard shortcuts) I am losing focus on textfields while typing and navigating in textfields (arrows).

Using latest Chrome on Mac OS 10.14

**Comment by NataliaBB** [comment]
Hi @MaxZiebell 

Do you still have this problem after the last updates?

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
