### ISSUE TITLE
Sorting and filtering for posts seem not to work with the latest update 1.0.68

### ISSUE THREAD

**Issue by pilpfiction** [ThemeFuse/Brizy#1248]
With the latest update it seems that the option filtering and sorting for posts do not work correctly anymore. While defining to show my latest ppost, instead the first post I create on my wordpress instance is shown.

**Comment by NataliaBB** [comment]
Hello @pilpfiction 
Natalia here!
Posts order issue was fixed. It will be included in the next release (hopefully this week)

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
