### ISSUE TITLE
Menus Disappear-Brizy

### ISSUE THREAD

**Issue by clifblasingame** [ThemeFuse/Brizy#1249]
Menus disappeared with Core and Brizy.  Please help.  http://execrecruit.designarkansas.com

**Comment by clifblasingame** [comment]
Header and footer are gone.  Brizy!?!

**Comment by NataliaBB** [comment]
Hello @clifblasingame!
Apologies for the late reply
I see your homepage has the menu and footer. Can you give me please a short update?

Regards, Natalia

**Comment by calliepegues** [comment]
Hello, I am having this same issue when I use the Brizy page builder with the Core theme.

https://www.stamom.com

**Comment by NataliaBB** [comment]
Hi @clifblasingame 
If you still have this problem, please send me a support ticket here: https://support.brizy.io/hc/en-us
Thank you! 
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by calliepegues** [comment]
THIS WAS REMEDIED BY CHANGING THE PAGE TEMPLATE TO 'DEFAULT' ISTEAD F 'BRIZY'
