### ISSUE TITLE
DOM tree is too deep

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#125]
Would be nice if you could filter empty DOM before output.
It's unnecessary deep and too many empty DOM.

**Comment by bagrinsergiu** [comment]
We have this issue in our to do list. Thanks for reporting

Sergiu

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/MwMANRIk/90-dom-tree-is-too-deep

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
