### ISSUE TITLE
Cannot edit blocks on Blog posts

### ISSUE THREAD

**Issue by RecInnovation** [ThemeFuse/Brizy#1251]
I am having an issue when I am editing a blog post with Brizy. I am able to add new blocks but when I click the edit button to change the background image of the block, I receive an error message : An error happened while trying to display this block.

This happens with different blocks and on both new posts, as well as existing posts.
<img width="1440" alt="Screen Shot 2019-04-04 at 5 37 15 PM" src="https://user-images.githubusercontent.com/49293973/55595338-97359b00-5700-11e9-9584-6fb5668015d1.png">

**Comment by NataliaBB** [comment]
Hello @RecInnovation 
Natalia here!
May I know what Brizy plugin version do you have installed? 

Can you give me more details by submitting a ticket here? https://support.brizy.io/hc/en-us 
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi @RecInnovation 
This issue has been fixed in the 1.0.69 version. If you have any other bugs to report, please feel free to write here: https://support.brizy.io/hc/en-us



I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
