### ISSUE TITLE
saved pro popup block - can't edit button / doesn't work

### ISSUE THREAD

**Issue by juliedulong** [ThemeFuse/Brizy#1252]
I created a block for my opt-in and lead magnet and saved it to my library.

I tried to insert it into a post and can't click on the popup to make any changes... I saved it to the post and tried it from a new browser and the original connection to Mailchimp on the saved block doesn't work.

https://screencast-o-matic.com/watch/cqfh2hZiON

Please advise.

**Comment by NataliaBB** [comment]
Hello Julie!
Natalia here!
This issue has been fixed in version 1.0.77 Free plugin. The new update will be released this week (now you can install only Beta version and test).
Subscribe here to receive beta versions for Brizy plugins: https://www.brizy.io/beta-testing/
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
