### ISSUE TITLE
Spacing issues for GiveWP when upgrading to 1.0.68 and Pro ..19

### ISSUE THREAD

**Issue by mindburn** [ThemeFuse/Brizy#1253]
Upgrading to brizy 1.0.68 has now broken our GiveWP form, the spacing is off and is not usable.

**Comment by mindburn** [comment]
i was able to fix it with css

.brz .brz-rich-text{white-space: normal;}

**Comment by NataliaBB** [comment]
Hi @mindburn 
Natalia here!

Thanks for letting us know and sorry for the inconvenience.  I will create an issue for the team in order to prevent the styles before releases.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
