### ISSUE TITLE
[Enhancement] Offset for Post

### ISSUE THREAD

**Issue by pilpfiction** [ThemeFuse/Brizy#1256]
It would be nice to be able to define an offset (number) which defines the post number to start to display in a post block.

For example I intend to have the first post displayed highlighted and the next eg 5 posts in a different, more compact way, below on the same page. For the second post block I would need to set the offset to 2, so the block does not display the first post again.

**Comment by MaxZiebell** [comment]
+1

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
