### ISSUE TITLE
HTML/Paypal

### ISSUE THREAD

**Issue by cricsos** [ThemeFuse/Brizy#1258]
When I embed code from Paypal for a button/link, some of the code is displayed on the page.

**Comment by NataliaBB** [comment]
Hello @cricsos 
Natalia here!
I've tested the PayPal embed code and I did not have this kind of problem. Please let me test in your page as well. Send me the wp credentials by submitting a ticket here: 
Please submit a ticket https://support.brizy.io/hc/en-us

Thank you!
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
