### ISSUE TITLE
There is an error with this block

### ISSUE THREAD

**Issue by LS25** [ThemeFuse/Brizy#1259]
I am building a website for my client and when I am trying to edit the cover block at the top of my homepage, I am getting an error saying there is a problem with the block and I should open an issue or delete the block. 

The problem is, if I delete the block and re-add it, the issue occurs again. 

The error occurs when I click the option to open up the edit menu (see screencast below):

[https://ls25websolutions.d.pr/JUBivy]

Please advise urgently as I need to finish this website for my client. 

Matt

**Comment by MaxZiebell** [comment]
I had a similar error … please look at the console. Often the error is described there and copy & paste it to this error report to help the Brizy team.

**Comment by NataliaBB** [comment]
Hello @LS25 
Natalia here!

We fixed this error in the 1.0.69 Free Version.  Please check if you have the latest updates for both plugins. 
If the error still occurs, please submit a ticket right here: https://support.brizy.io/hc/en-us 

Thank you!
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
