### ISSUE TITLE
Feature Request: Filterable Post Archives, Grids, Portfolios, etc

### ISSUE THREAD

**Issue by RocketGS** [ThemeFuse/Brizy#126]
Being able to filter say blog posts by Tags or Categories.

As example, https://essential-addons.com/elementor/filterable-gallery

Of course with more content control and expansion of what can be included as Brizy does.

**Comment by bagrinsergiu** [comment]
Hi @rockalife 

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by madz00** [comment]
I'm also very interested in this feature!

**Comment by maflman** [comment]
Would be really nice to have filterable image gallery.

**Comment by NataliaBB** [comment]
Brizy Roadmap Link: https://trello.com/c/4Sjk1vF8/49-portfolio

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
