### ISSUE TITLE
Astra* duplication

### ISSUE THREAD

**Issue by iZEVS** [ThemeFuse/Brizy#1260]
Brizy works perfect with **Astra**, one of the most popular Free themes on the market. It’s stylish & easily customizable.

Duplication. Please replace the "Astra" with appropriate names [here](https://brizy.io/themes-list/) (except 1st example)

**Comment by NataliaBB** [comment]
Hey @iZEVS 
Done!
https://www.brizy.io/theme-partners/
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
