### ISSUE TITLE
Very slow on Safari

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1261]
This is a followup to the site I have built being unusable. All Images keep reloading and are not properly visible on Safari. It takes ages to load the page there and on iOS it's utterly broken. Chrome displays the page properly.

https://sculptures.diki.info

**Comment by MaxZiebell** [comment]
Update: Seams related to the Twenty Nineteen Theme! I installed Generate Press (Free) and now the page works better. This seams to be a serious issue then because most people will have that theme activated after a fresh install of WordPress!

**Comment by NataliaBB** [comment]
Hello @MaxZiebell 

The team already start to work on the improvement module for the performance of the builder. In a couple of updates, we will start to release ths new module. 


Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
