### ISSUE TITLE
[Feature Request] Lazy Loading

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1263]
I built a image heavy page ... so I really would appreciate native Lazy Loading support.
I will try to use "Lazy Load" for now based on https://github.com/verlok/lazyload

**Comment by JayOkey** [comment]
Yes lazy loading would be great especially as it will be supported natively Chrome https://addyosmani.com/blog/lazy-loading

**Comment by MaxZiebell** [comment]
For the time being I am using this and it works with Brizy. No fancy animations though.
https://wordpress.org/plugins/rocket-lazy-load/

**Comment by NataliaBB** [comment]
Hi @MaxZiebell 
Added in our internal roadmap and Trello roadmap: https://trello.com/c/5f5EwsJR/223-lazy-load-integration
Thank for the request!

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
