### ISSUE TITLE
Smooth scrolling to Section Anchor from regular menu

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1265]
I am having issues when assigning a anchor manually and referencing it from a main menu (built in WordPress menus). There I use a custom link pointing to the #anchor

Works but without the nice smooth scrolling I usually get when using sections in the Brizy links.

**Comment by pilpfiction** [comment]
I am having same issue and I am looking for a way to also have the smooth scrooling from a menu to an anchor on the same page!

**Comment by NataliaBB** [comment]
Hello @MaxZiebell , @pilpfiction 

Added this request in our trello map: https://trello.com/c/DopW13Sn/214-smooth-scrolling-on-anchors 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
