### ISSUE TITLE
[Feature Request] Text Gradients

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1266]
Native support for Gradients on Text using this trick in Brizy
https://cssgradient.io/blog/css-gradient-text/

**Comment by NataliaBB** [comment]
Hi @MaxZiebell 
Added: https://trello.com/c/fUbKxFaJ/225-text-gradient

Thanks a lot!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
