### ISSUE TITLE
Preview of saved blocks will not load upon import

### ISSUE THREAD

**Issue by pmopmopmopmo** [ThemeFuse/Brizy#1270]
Hello - I am searching for resolution to this matter as I still have none. My saved blocks will not load upon import of XML into wordpress. I made the import with Brizy and the theme is Haven. Please reference my last request for resolution at ticket #1216.

Thank you!

---------------------------------------------------------------------------

Hello Patrick! @pmopmopmopmo 
Sorry for my late reply .
Please, let me check and fix this issue within your dashboard. I will need you wp credentials, send them please via our facebook chat:

Please also mention this issue number inside: 1216

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

_Originally posted by @NataliaBB in https://github.com/ThemeFuse/Brizy/issues/1216#issuecomment-477219075_

**Comment by pmopmopmopmo** [comment]
Anyone else having this issue?

**Comment by NataliaBB** [comment]
Hello @pmopmopmopmo 
Let me check what is the problem with the blocks. Send me the wp credentials here: https://support.brizy.io/hc/en-us 
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by pmopmopmopmo** [comment]
Sorry Natalia, I cannot provide those credentials - Can you please explain
what you would be looking into? I have attached my XML file so you may try
to import yourself. I am using the Haven theme and the latest version of
the theme as well as Brizy is activated.

Thanks for your help!
