### ISSUE TITLE
Colour for Bullets

### ISSUE THREAD

**Issue by Froogleme** [ThemeFuse/Brizy#1272]
Hi - love the software

Would like to be able to make bullets/numbers the same colour as text

**Comment by Voronium** [comment]
+1

**Comment by NataliaBB** [comment]
Hi @Froogleme @Voronium 
Thanks for your love :)
Also, Thanks for your suggestion
Added this request in our trello map: https://trello.com/c/IAVYGYsC/215-edit-option-for-bullet-numers

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
