### ISSUE TITLE
Ajout de texte

### ISSUE THREAD

**Issue by MLWetzler** [ThemeFuse/Brizy#1274]
A chaque fois que je mets du texte dans les zones prévues pour, page contact du themereel story, le texte n'est pas pris en compte???? Quand je fais mis à jour, le texte est tout simplement effacé
![Capture_brizy](https://user-images.githubusercontent.com/49520585/55953631-e9c10b00-5c5c-11e9-8dc6-6e5a655f43d9.JPG)

**Comment by NataliaBB** [comment]
Hello @MLWetzler 
Natalia here!
Most probably, it can be a theme error. Please submit a ticket for me and write the wp credentials to test the page: 
https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
