### ISSUE TITLE
Content disappear in slides / carousel after load 

### ISSUE THREAD

**Issue by uritron** [ThemeFuse/Brizy#1276]
The content load and you can see it for half a second, but than it disappear.
on the website one can see the carousel controls, but not the content (same for slider).

Screenshot from site: http://winnerscodecoach.com/
![image](https://user-images.githubusercontent.com/49524428/55960815-336a1f80-5c76-11e9-95a3-1c04c28e2aee.png)

Screenshot from backend:
![image](https://user-images.githubusercontent.com/49524428/55961036-b12e2b00-5c76-11e9-90cf-f80605ee6059.png)

**Comment by NataliaBB** [comment]
Hello @uritron 
I see on the page both sliders blocks work well in preview mode. 
Can you confirm this now?

Thank you!
Regards, Natalia

**Comment by uritron** [comment]
Yes, 

I have changed site language from Heboew to English and the slider works fine.

 

--- Uri.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
