### ISSUE TITLE
White Hover Problem

### ISSUE THREAD

**Issue by AznDrizzy** [ThemeFuse/Brizy#1278]
So, my problem is simple, when i create a template and use a cover, when i hover the background, it's flashing white two times and becoming normal. How to fix the flashing thing ?

**Comment by AznDrizzy** [comment]
I found out what's the problem, it's the hover effect on the cover, so i would like to know if it's possible to disable it.

**Comment by NataliaBB** [comment]
Hello @AznDrizzy 

Did you try to set to 0% the hover effect: https://jmp.sh/yBCxPB5 

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
