### ISSUE TITLE
 I can not write a big Z anymore

### ISSUE THREAD

**Issue by MarcBEEFGE** [ThemeFuse/Brizy#1279]
Can you please solve this problem? 

It does not work on any of my browsers (Safari, Chrome, Firebird). I believe since version 0.0.19?!?

Thank you

**Comment by NataliaBB** [comment]
Hello @MarcBEEFGE 
The bug is solved + prepared to be released. 
The new version is coming this week. 

Thank you!
My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
