### ISSUE TITLE
Animations break

### ISSUE THREAD

**Issue by cowdar** [ThemeFuse/Brizy#128]
If Add an animation to a photo or other. you can no longer get back to the animation settings it just closes the advances settings 
[Vid.zip](https://github.com/ThemeFuse/Brizy/files/2089729/Vid.zip)

**Comment by bagrinsergiu** [comment]
This has been fixed and was included 1.0.15 update

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu
