### ISSUE TITLE
Mobile only view

### ISSUE THREAD

**Issue by manfye** [ThemeFuse/Brizy#1280]
Is there any function to make a certain block, mobile only? instead of currently desktop only

**Comment by Ravisi** [comment]
Hi @manfye, you can go to the Block Settings/More Settings/Advanced and change Show on Desktop to "OFF" if you want also hide in Tablet mode you can go to Tablet Design click on the Block and hide it with the Eye Icon. And then you will have the Block shown only on Mobile Version.

**Comment by manfye** [comment]
thank you very much!

**Comment by Ravisi** [comment]
your welcome!

**Comment by NataliaBB** [comment]
Thanks @Ravisi for the reply!



I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
