### ISSUE TITLE
?how to embed the gif

### ISSUE THREAD

**Issue by motokimotoki** [ThemeFuse/Brizy#1281]

**Comment by iZEVS** [comment]
Use embed block and paste there something like this:

<img src="https://yourdomain.com/wp-content/uploads/2019/04/pic.gif" alt="" height="auto" width="auto">

**Comment by NataliaBB** [comment]
Hi @motokimotoki 
Add embed element and insert the code inside the box: https://jmp.sh/bfowpzJ

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
