### ISSUE TITLE
video not showing in page

### ISSUE THREAD

**Issue by roshanveni** [ThemeFuse/Brizy#1283]
I am new user for brizy i ready my page I add my youtube URL like in my page in brizy editor video showing but in my website video not showing 
![Untitled](https://user-images.githubusercontent.com/49720401/56288672-dde1b700-613c-11e9-9c7d-146fe1fa71a8.jpg)
![Untitled1](https://user-images.githubusercontent.com/49720401/56288673-dde1b700-613c-11e9-85e6-905ca5fad8de.jpg)

**Comment by NataliaBB** [comment]
Hello @roshanveni 
Please send me the wp credentials by submitting a ticket here: https://support.brizy.io/hc/en-us 

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by LuNiPriSe** [comment]
We have a siilar problem with YouTube Videos not showing in Sliders:
https://neu.hub.zdf-digital.com/
