### ISSUE TITLE
[Feature Request] Back to page

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#1287]
It would be nice to have a back to page option.
https://screen.maxziebell.de/20190418-mvg7e.jpg

The "Brizy-Way" could be that the editor rembers where you started editing from and when you start from a page in the front end (while being logged in) you see "Back to page" and if you started editing from WordPress it would say "Back to WordPress" go back to the backend Post or Page index (depending on where you started).

This works very great with the new Cloud "Back to Brizy" and would be consistent

**Comment by NataliaBB** [comment]
Hi @MaxZiebell 

Added: https://trello.com/c/AkU6MU6v/226-back-to-page-option 
Thanks! 
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
