### ISSUE TITLE
Dividers Broken after 1.0.70 Update

### ISSUE THREAD

**Issue by tylerwinter** [ThemeFuse/Brizy#1288]
The dividers option no longer appears under the style menu under a block after last update.

**Comment by MaxZiebell** [comment]
+1 … the colors in my case where all black. Even though in the settings the color was still set. Only after typing in the color value again it restored it in the preview and then I needed to save the page again. Weird was also that the color picker didn't work in this mode when the color is black.

**Comment by NataliaBB** [comment]
Hi @tylerwinter 
Divider issue has been fixed in the 1.0.74 version. 
Sorry for the inconveniences. 

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
