### ISSUE TITLE
Can´t update

### ISSUE THREAD

**Issue by sergiomoar** [ThemeFuse/Brizy#1289]
Hello, i just update to version 1.0.70 and now if i click on update i can´t and don´t save changes.

**Comment by pmopmopmopmo** [comment]
Same here - I am unable to update with the update button. I am on version .24

**Comment by sergiomoar** [comment]
I just update to 1.0.72 but same issue. A can´t save in update button

**Comment by alexluncashu** [comment]
We working on that. Trying to find what's wrong on some servers. On our test, it works https://jumpshare.com/v/ISmdclG9wp0RK9Twau2y

**Comment by SundialWeb** [comment]
Even we can't update a page by clicking the "Update" button! We are trying to use Saved blocks in new pages.

**Comment by NataliaBB** [comment]
Hello everyone! @sergiomoar @pmopmopmopmo @SundialWeb 
We fixed this issue in the 1.0.73 version. 
Sorry for the inconveniences.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
