### ISSUE TITLE
Add the ability to label saved and global blocks

### ISSUE THREAD

**Issue by andrew-lof** [ThemeFuse/Brizy#129]
It be great if you could name the Block when you saved or made it it global. Then you could search by keyword for it after when adding a new block. 

Also, if the thumbnail could be a screenshot of how it looks on a page instead of a thumbnail of the premade block it was based off of.

**Comment by bagrinsergiu** [comment]
Hi Andrew,

Live thumbnail block preview is planned in 2-4 weeks. 

Can you give me more details why you need keywords for Saved/ Global blocks? From our experience (Themefuse) users add maxim 10-15 blocks in Save Section

Sergiu

**Comment by andrew-lof** [comment]
That is great about the thumbnail preview.

Being able to label a block would let other editors know what section that block is meant to be used for and to quickly search for a block. This should also help reduce multiple users creating very similar blocks and bloating the block library. 

Will the ability to save custom elements like a stylized button to reuse in multiple sections also come in the near future?

Thanks

**Comment by bagrinsergiu** [comment]
Q: Will the ability to save custom elements like a stylized button to reuse in multiple sections also come in the near future?

A: Yes, It is in our to do list but i'm not sure how important it is for Agecies and their clients, it is planned very similar to Sketch Symbols but more powerful (https://sketchapp.com/docs/symbols/). In sketch it is possible to change only content ( text, image ) ( no styles, sizes, align).  . 

Regarding Saved Blocks. I promise to think about keywords. I will investigate how blocks are used. 

Thank you too   
Sergiu

**Comment by quantumleap33** [comment]
Saving elements functionality would be great! Also agree with block saved thumbnail, needs to represent the current block and not the original. Ability to search with keywords would further enhance the functionality! It wuld also be good to be able to ahve a title for the block.

**Comment by PeterArt** [comment]
Just a wild thought - when viewing the library of blocks or elements, at the end of the list could be the list of saved local and or shared blocks/elements (in pro version) if you adopt a shared philosophy. Where I think pro users would see what other creative users are doing, it might reduce the pressure on the Dev team to increase blocks and elements.

**Comment by quantumleap33** [comment]
Sounds like a good idea as long as reducing the pressure on the devs, doesn't mean increasing the server resources on our sites!

**Comment by vagrantjo** [comment]
Looks like this problem still hasn't been resolved. At the very least, we should have the ability to name our blocks. Right now, it just lists blocks with the name "Started From Scratch" with the default image preview. Thereby making it impossible to know which block is which, we have to click each one and figure out which one it is. Having the option to name a block "menu" or "footer" would be extremely useful.

**Comment by AntonKing60** [comment]
Agreed. The ability to re-position the blocks is rendered pointless if all added blocks are blank with the words 'Started from Scratch' on them. Once you have a few blocks on a page, it's impossible to judge which one you are moving. The blocks need to have at least an image of the content, as per the stock blocks, or the ability to name them.

**Comment by AntonKing60** [comment]
Also, as mentioned above, I have saved 3 blocks but, when viewing the saved blocks there is no indication as to what is what. They all just say 'Started From Scratch' on them. We must be able to name them and/or have a visual reference as to what the block is.

**Comment by bagrinsergiu** [comment]
Hi all, 

Live thumbs for Saved and Global blocks module is under review. Sorry for the delay.

Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/Bey1hFce/111-blocks-thumb-generation

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
