### ISSUE TITLE
Brizy Templates Don't show up on assigned pages

### ISSUE THREAD

**Issue by garyld1962** [ThemeFuse/Brizy#1290]
I created a template with a header and footer and assigned it to the "Home" page, but It does not show up on the page. Am I missing a step?

Gary

**Comment by NataliaBB** [comment]
Hello Gary! @garyld1962 

If you create a template and assigned to the Home Page, then you don't need to open the "Home" page with Brizy.  
Send me a screenshot of the page in the preview mode.
If you need more details, please write me a ticket here: https://support.brizy.io/hc/en-us

Best Regards, Natalia

**Comment by garyld1962** [comment]
Maybe I don't understand, I want to have a "Product page" template that is different from all other pages. I created a "product page" template in the Brizy menu and I set the rules. I cannot get this template to show up based on the rules or any other way

**Comment by NataliaBB** [comment]
Hi Gary! @garyld1962 
So you may have a condition rule bug. Please, remove your condition rule from the Brizy (product page) template, and then refresh your permalinks. 
Send me a short update if you managed.

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
