### ISSUE TITLE
when I make changes using the Brizy editor it does not save using publish or update

### ISSUE THREAD

**Issue by daputtputt** [ThemeFuse/Brizy#1292]
when I make changes using the Brizy editor and update it does not save the changes on my astra word press theme, how do i save the changes ?I can see the saved edits in the  templates section of the brizy pro but I cannot seem to make them change on my WP theme?

**Comment by Salloom88** [comment]
I have the same problem

**Comment by SundialWeb** [comment]
Exact same issue here!

**Comment by NataliaBB** [comment]
Hello @daputtputt, @Salloom88 @SundialWeb 
Please submit a ticket here: https://support.brizy.io/hc/en-us 

Astra made some changes in the code, and we need to check what happened after this update.

Thank you!
Regards, Natalia

**Comment by marianglobalplus** [comment]
i cannot either update my changes in my webiste sirtracking.com. This problems exists since last week. You know when it is going to be solved? Thank you.

**Comment by McScience** [comment]
I have the same problem

**Comment by NataliaBB** [comment]
Hello @marianglobalplus @McScience 
We fixed this issue in the version 1.0.76. Please update the plugin.
If the problem still occurs, send me the wp credentials here - 
https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
