### ISSUE TITLE
Brizy icon library not showing icons

### ISSUE THREAD

**Issue by lmyers1307** [ThemeFuse/Brizy#1293]
Whenever I try to add a icon and click the star to access the icon library all I see is blank boxes. It also won’t show in edit mode. I have the brizy pro version. It’s halting my project because I can’t add social media icons or any.

**Comment by NataliaBB** [comment]
Hi @lmyers1307 
Please submit a ticket here: https://support.brizy.io/hc/en-us . Please write the wp credentials to check the code.
Thank you!
Regards, Natalia

**Comment by lmyers1307** [comment]
Ive submitted multiple tickest and got no response.

**Comment by NataliaBB** [comment]
Hi @lmyers1307 
I've sent a reply to you regarding this problem, asked for wp credentials. My reply - 13.05.2019, in the same day when you submit the ticket. 
Ticket number 353
Please check!

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
