### ISSUE TITLE
[Feature Request] FaceBook Groups

### ISSUE THREAD

**Issue by DenMurphy** [ThemeFuse/Brizy#1295]
Can you add to the Facebook block "FaceBook Groups". I would like to embed an open FaceBook Group to a Brizy built page.

**Comment by NataliaBB** [comment]
Hi @DenMurphy 
Thanks for your request. I've added in our roadmap facebook group element. 

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
