### ISSUE TITLE
Block Crashing

### ISSUE THREAD

**Issue by tadisa** [ThemeFuse/Brizy#1296]
Hello,
I updated to the latest update and started having block crashing problems.
When I added new block to start designing, The block crashes when I click to process it.
Kindly see images below of before and after.

![New Block Added](https://user-images.githubusercontent.com/20805136/56653729-39a0c880-6686-11e9-94f0-12dd605af8c9.png)

![New Block Crashed As I Want To Process It](https://user-images.githubusercontent.com/20805136/56653747-41f90380-6686-11e9-8808-80636642c435.png)

Quick fix will be greatly appreciated.

Thank you.
Cheers.

**Comment by NataliaBB** [comment]
Hello @tadisa! 

What version do you have installed? 
Free version 1.0.74 // PRO version 0.025

Regards, Natalia

**Comment by tadisa** [comment]
Hi,
Thanks for getting back on this.

I have Pro version 1.0.17 and Free version 1.0.74 installed.

Thanks.
Cheers.

**Comment by carlton327** [comment]
I am having the same issue! My Pro and Free versions are the same as well.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
