### ISSUE TITLE
Menu items not clickable

### ISSUE THREAD

**Issue by pilpfiction** [ThemeFuse/Brizy#1297]
Clicking on a mobile device menu element defined and displayed as hamburger menu has no effect. An new page or an anchor on the same page are not loaded or scrolled to.

**Comment by NataliaBB** [comment]
Hey @pilpfiction 
A page link, please?

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
