### ISSUE TITLE
Brizy Not Loading 

### ISSUE THREAD

**Issue by morganfarley11** [ThemeFuse/Brizy#1298]
I have just finished my website nd used brizy through wordpress. I updated it yesterday, not it will not load at all just has the spinning lines for hours.. What should I do ?

**Comment by NataliaBB** [comment]
Hello @morganfarley11 

Please submit a ticket for me here: https://support.brizy.io/hc/en-us

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
