### ISSUE TITLE
Bugs & Usabilities List

### ISSUE THREAD

**Issue by hlaporthein** [ThemeFuse/Brizy#13]
The things I found for now

- [x] - Paste plain text on selected text doesn't work
- [x] - Command + A shortcuts makes selected to other area not only target block ( especially, you could see when we are editing something with popup)
- [x] - Color picker small square predefine color can't make the element to change color.
- [x] - Removing the whole predefined text make the predefine style remove
- [ ] - Link can't edit well
- [x] - Duplicate pricing show in editing mode. And then after updated, Duplicate pricing table doesn't show.

**Comment by bagrinsergiu** [comment]
Thanks for letting us know, we are looking into it.

**Comment by bagrinsergiu** [comment]
1. It seems to work well: http://jmp.sh/zm4YTdK Can you give me more details?

**Comment by hlaporthein** [comment]
Hello @bagrinsergiu , I am tested on mac+chrome.  Could I test it on another day and I would reply back to you with screencast if I find it. Thanks for your amazing works.

**Comment by hlaporthein** [comment]
Hi @bagrinsergiu , 1,2,3 and 6 are working now. I have tested on mac+chrome+wordpress. Sorry for bothering you. Have a great day. Happy Code!

**Comment by bagrinsergiu** [comment]
@hlaporthein 

5. We have a pull request for this issue (~ 1-2 weeks).

Thanks

**Comment by hlaporthein** [comment]
Thanks @bagrinsergiu , I would test it again and planning to use in customer websites. waiting for pro version, too. Cheer!

**Comment by quantumleap33** [comment]
I believe in the future it would be better to list each separate bug in its own thread instead of a big list. Makes it more managable.
