### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by Fumbic** [ThemeFuse/Brizy#1301]
Do not display pictures on the page!

I turned off all third-party plug-ins, changed themes, changed versions of PHP - nothing helps!

Please, help!

An example of a page where images are not displayed:
https://olgazolotova.com/pages/hoty-site-26190

**Comment by NataliaBB** [comment]
Hello @Fumbic !
Didn't find anything under this url. If you still have this problem, please check if you have the php image-gd option enabled. If this will not solve the problem, please  submit a ticket here: https://support.brizy.io/hc/en-us
Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
