### ISSUE TITLE
When using Advance Custom Fields preview is broken

### ISSUE THREAD

**Issue by garyld1962** [ThemeFuse/Brizy#1302]
ACF fields only show up when you click "view" in the "All Pages" screen. they don't show on "Preview" in the WP screen or the Brizy builder screen.

**Comment by NataliaBB** [comment]
Hello @garyld1962 
please, send me a short update if you still have this problem after 0.0.27 and 1.0.82 Brizy versions.

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
