### ISSUE TITLE
No Shadow button

### ISSUE THREAD

**Issue by thebeazer** [ThemeFuse/Brizy#1303]
I went to use the Shadow feature on a button, but it isn't in the menu as an option. In Brizy's video tutorial the Shadow button appears below the margin sliders.

I inserted several new elements and they all don't have the option.

Any one know what is going on?

**Comment by HEYiKEN** [comment]
+1

**Comment by NataliaBB** [comment]
Hello @thebeazer , @HEYiKEN 
Shadow option is in the button toolbar: https://jmp.sh/s5eAhbL Can you check? Can you please send me a screenshot? 

Thank you!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
