### ISSUE TITLE
[Feature Request] Code Element

### ISSUE THREAD

**Issue by ergongervalla** [ThemeFuse/Brizy#1305]
Add a code element to the toolbar. This would let us add custom code inside Brizy template areas.

**Comment by JayOkey** [comment]
By code element, I assume you mean for html & css this would be really handy in some cases.

**Comment by NataliaBB** [comment]
Hello @ergongervalla 
Do you mean for the entire template? not like for each element in the page, which is now available in Advanced tab? https://jumpshare.com/v/t7FuQQOv0f0iLjmB2CSw 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
