### ISSUE TITLE
Video in pop ups

### ISSUE THREAD

**Issue by RichardWall601** [ThemeFuse/Brizy#1307]
I have a group of images for the purpose of making a video gallery, I´m using pop ups to display the videos but when I click on the images only the first video of the gallery loads no matter what images I click to open the video.
When I change the orden or the images now the first video on the gallery is the only one loading.
I tried other elements and the only one with this behavior is the video element.

**Comment by NataliaBB** [comment]
Hi @RichardWall601 
We fixed pop-up element bugs in the 0.0.26 PRO version (video+pop-ups on global blocks)
As a PRO member, you should receive a 0.0.26 beta version. Please check, update and let me know if you still have this problem.
Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
