### ISSUE TITLE
Brizy Does Not Load

### ISSUE THREAD

**Issue by jdokoli** [ThemeFuse/Brizy#1308]
I am in the midst of using your software to build a project for a client. before I could upgrade my account today brizy has been unavailable and refuses to load I have remained in the attached screen page for hours even after repeated refreshes, deactivations, and complete computer restarts.

<img width="2553" alt="Screenshot 2019-04-29 at 17 17 34" src="https://user-images.githubusercontent.com/50113762/56910942-a7445e80-6aa3-11e9-8883-1ac5caf4d8ac.png">

**Comment by NataliaBB** [comment]
Hello @jdokoli 
The upcoming 1.0.75 version will have the fix for this issue.

Please for any bugs report, submit for us a ticket here: https://support.brizy.io/hc/en-us 
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
