### ISSUE TITLE
When you publish an article in a rubric, its text replaces the text of other articles.

### ISSUE THREAD

**Issue by Maxim850** [ThemeFuse/Brizy#131]
When you publish an article in a rubric, its text replaces the text of other articles.
https://youtu.be/iq1JEC_A4Rg
All articles are replaced with the newly created one. The headings remain from the old, but the body of the article itself is one for everyone.

**Comment by bagrinsergiu** [comment]
Hi @Maxim850 

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by Maxim850** [comment]
I tried to create a record in the standard way. Everything went right. It's really in the plugin.

**Comment by bagrinsergiu** [comment]
Hi Tony

This has been fixed and was added in (1.0.13)  version, thanks for reporting.

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Sergiu
