### ISSUE TITLE
Contact form not sending

### ISSUE THREAD

**Issue by rovillesarate** [ThemeFuse/Brizy#1310]
Hi! The contact form wont send the form. iregardless if i integrate it using wordpress or not. I am using the latest version but still getting this issue.

You can check it here: www.autoserved.com/shop-owners

**Comment by NataliaBB** [comment]
Hello Roville!  @rovillesarate 
I see you have a contact form shortcode inserted in your page. 
Regarding the problem with Brizy contact form - can I run some tests on a new page?
Can you send me the wp credentials here on zendesk: https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
