### ISSUE TITLE
No Previews for Global/Saved blocks

### ISSUE THREAD

**Issue by metalmatze74** [ThemeFuse/Brizy#1312]
![image](https://user-images.githubusercontent.com/43218450/57037055-63458b00-6c56-11e9-9b60-74decffb27c9.png)
For all new blocks I save, I only get the circle...
I have the last version of brizy and brizy pro.

**Comment by NataliaBB** [comment]
Hello @metalmatze74 
It is possible to check these blocks from your dashboard?

Can you please submit a ticket here: https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia

**Comment by metalmatze74** [comment]
Hi Natalia,
yes I can use or delete them, but no previews either in the View where I can reorder the Blocks or the Dashboard will appear.
I have done a Migration (creating a staging system) with Updraft to a new url for the whole site. This is a one to one copy. In the new location the previews in the reorder Blocks view and for new blocks are shown.

**Comment by heybenbro** [comment]
Same problem here, previews don't load... and all global blocks disappeared:
![Saved Blocks](https://user-images.githubusercontent.com/50721535/57892005-b264f180-77fa-11e9-8796-82d46bb50937.PNG)
![Global Blocks](https://user-images.githubusercontent.com/50721535/57892065-e3ddbd00-77fa-11e9-9bc3-efa02937b7a0.PNG)

**Comment by NataliaBB** [comment]
Hi @metalmatze74 @heybenbro 

Can you send me a backup to check at my end If I can open those blocks?

Regards, Natalia

**Comment by metalmatze74** [comment]
Hi Natalia,

 

after a migration to another domain and back to the original system the preview in the Drag to reorder view is working again. If I save a new block the preview works, but the old blocks dont show a preview. The attached xml file contains the old saved blocks. I have export and import them without success to get the previews….

 

Regards

Matthias

 

Von: NataliaBB <notifications@github.com> 
Gesendet: Donnerstag, 23. Mai 2019 17:11
An: ThemeFuse/Brizy <Brizy@noreply.github.com>
Cc: metalmatze74 <matthias.hahn@web.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ThemeFuse/Brizy] No Previews for Global/Saved blocks (#1312)

 

Hi @metalmatze74 <https://github.com/metalmatze74>  @heybenbro <https://github.com/heybenbro> 

Can you send me a backup to check at my end If I can open those blocks?

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
