### ISSUE TITLE
Click on block settings and get this message "An error happened while trying to display this block You can open an issue or remove this block" Tried on several blocks and receive same message.

### ISSUE THREAD

**Issue by Matthewhoelker** [ThemeFuse/Brizy#1313]

**Comment by wendyhendry** [comment]
Me too!  Has this been addressed?
![Screen Shot 2019-05-09 at 12 02 25 PM](https://user-images.githubusercontent.com/50461504/57476396-b79ecb00-7253-11e9-9f76-b042eccf35da.png)

**Comment by NataliaBB** [comment]
Hello @Matthewhoelker @Idontwannasignup1111 @wendyhendry 

This bug was fixed in our previous versions. What Brizy version do you have installed now?

Regards, Natalia

**Comment by Idontwannasignup1111** [comment]
@wendyhendry Manually updating my Brizy Pro plugin fixed the issue, check if yours is the current version!

**Comment by wendyhendry** [comment]
Hi. Thanks for your reply. I’ve updated and it’s still doing the same thing.  I really need to get this page up and going. Are there any options?  I’m attaching a screenshot so you can make sure I have the latest version.  Thanks!

**Comment by NataliaBB** [comment]
@wendyhendry 
It's strange. please, let me run some tests in your dashboard,  please send me the wp credentials via zendesk: https://support.brizy.io/hc/en-us 

Thanks!

**Comment by wendyhendry** [comment]
Hi.  Have you figured it out?  I’m really frustrated.  I have a training on Saturday, and I can’t send people to my website because I can’t update this damn page.  I need this fixed right now.

**Comment by omark118** [comment]
I do have the same issue. I tried to update manually still getting the same message. Any updates?

**Comment by wendyhendry** [comment]
I haven’t heard anything.  I”m super frustrated though.  I think it’s time to leave a bad review and go back to using word press.

**Comment by NataliaBB** [comment]
Hello @wendyhendry 
Please, make sure you have installed the latest versions:
FREE 1.0.76
PRO 0.0.25
If you will still have this problem, send me your WordPress credentials here:  https://support.brizy.io/hc/en-us

Thank you!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by wendyhendry** [comment]
Hi.  I'm sorry I haven't gotten back to you. I've been super busy.  Hold off closing it.  I'll get in right now and see where it's at.  Can you give me 30 min?

**Comment by wendyhendry** [comment]
I'm attaching a screenshot of my plugins.  My brizy pro is not current, but it is not giving me a way to update it.  I am sending you my wordpress credentials to https://support.brizy.io/hc/en-us

![Screen Shot 2019-05-23 at 9 32 04 AM](https://user-images.githubusercontent.com/50461504/58265986-05c8c980-7d3e-11e9-9d11-0ed40f583628.png)

**Comment by wendyhendry** [comment]
Hi Natalia. I’ve sent a couple of emails in regards to this issue and have not received a reply. My block editor is still not working. I would like to receive a refund on the Brizy Pro. Please let me know what I need to do.
On May 23, 2019, at 9:10 AM, NataliaBB <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi!

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
