### ISSUE TITLE
[Feature Request] Button hover icon

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#1316]
Hi.

I would like to have the icon be displayed only when I hover. Also, I would like to have other effects when I hover buttons or other elements like shrink, pulse, jump etc.

Thanks

**Comment by NataliaBB** [comment]
Hi @estraatios 
Added in our roadmap: https://trello.com/c/kUCJaTQU/218-button-hover-icon

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
