### ISSUE TITLE
OceanWP compatibility

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#1317]
Hi.

I tried to create a custom footer with OceanWP theme. Inside My Library in Theme Panel I created a new template and designed it with brizy (picture 1). When I saved it and check it from the front end everything looked OK but when I set my template as a footer I got something like in the picture 2. 
I installed then Elementor and did a new footer with that. It works no problem.

Brizy has some issues with that
I tried this
![brizy2](https://user-images.githubusercontent.com/34076187/57185035-59798d00-6ecd-11e9-998b-a17b79b3a035.JPG)

and got this
![brizy1](https://user-images.githubusercontent.com/34076187/57185034-58e0f680-6ecd-11e9-8829-f6196cda7a38.JPG)

**Comment by NataliaBB** [comment]
Hello Karavarakis!
As I wrote in my message on zendesk, we have an open ticket with Ocean WP team about this issue. 
As soon as I will have a reply from them, I will come back to you with a notification.
Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
#
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
