### ISSUE TITLE
brizy page won't open for editing

### ISSUE THREAD

**Issue by lilsurepbc** [ThemeFuse/Brizy#1318]
Hi, i can't edit my page.  It just spins.

![image](https://user-images.githubusercontent.com/45666337/57185159-003d3980-6e8c-11e9-966d-2f5d003fc4bd.png)

**Comment by ccan007** [comment]
I have the same issue, did Brizy help?

**Comment by NataliaBB** [comment]
Hello @ccan007 @lilsurepbc 
We fixed this problem in the 1.0.75 Brizy Free Version.
Can you please update the plugin and let me know if the editor is loading?

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
