### ISSUE TITLE
Can't save Brizy Sides in my project

### ISSUE THREAD

**Issue by MarcBEEFGE** [ThemeFuse/Brizy#1319]
Hi,
If I want to save a page in my BRIZY project it takes up to two minutes and then after pressing BACK TO WORDPRESS the message appears that the page was not saved by the browser. Can you help me please?
Thank you
Marc
https://www.niendorf-gewerbeimmobilien.de

**Comment by NataliaBB** [comment]
Hello @MarcBEEFGE 
We fixed this problem in the last 1.0.75 Free version, could you please update the plugin and let me know  if the changes are saved?

Thank you!
Regards, Natalia

**Comment by miunana160** [comment]
Hi I have the same issue, I tried to edit wit BRIZY and publish, but it take time and never progress, and didn't saved at all. Thanks!
Nana

**Comment by miunana160** [comment]
Hi never mind! I bought pro and updated the apple os to the latest one, it worked! 
Nana

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
