### ISSUE TITLE
Text Transformations

### ISSUE THREAD

**Issue by madz00** [ThemeFuse/Brizy#132]
Hi, would be possible to add in the typography tab basic text transformations like uppercase, lowercase, capitalize...? Would be useful specially in regards to future dynamic content and global typography across the entire website.

**Comment by bagrinsergiu** [comment]
Hi @madz00 

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by forcedlogic** [comment]
100% need this. Uppercase, Lowercase, Capitalize, underline and strike through have a common use. The ability to do these are necessary.
![font features](https://user-images.githubusercontent.com/28716228/45050295-8461c780-b046-11e8-9e66-a7bf137207e5.PNG)

**Comment by anthonypero** [comment]
I agreed. I purchased the Pro version, and love some of it, but even the free version is useless on a client site without basic formatting tools.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/n0JsfHzM/148-text-transformations

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
