### ISSUE TITLE
No Audio element in Brizy Editor

### ISSUE THREAD

**Issue by samburdy** [ThemeFuse/Brizy#1320]
I'm not able to add audio file or playlist element using the brizy editor. Whereas Elementor has this feature. However Elementor has some pros and cons of its own. I like the way Brizy works but without audio it would be difficult. Only SoundCloud is allowed and i don't want to use it at this moment.

**Comment by NataliaBB** [comment]
Hello @samburdy 
Thanks for your suggestion. I've added in our internal GitHub roadmap. 
We will look into it. 

Regards,Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
