### ISSUE TITLE
Popup close button gone

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#1321]
Hi.

I am using OceanWP theme and created a website with a vertical menu.
When I create the popups I want I cannot close them because the close button is not visible probably under the menu. It should be movable so I could choose its location.

Please fix it. 
You can see it in this URL bu pressing Login or Register buttons in the hero block.
https://milleruniversity.org
![brizy](https://user-images.githubusercontent.com/34076187/57217943-ae67f100-6ffc-11e9-908b-ae13680e69a8.JPG)
Thank you

**Comment by NataliaBB** [comment]
Hello @estraatios 
We are waiting for an update from the Ocean WP regarding this issue. 
Will come back to you within the open ticket via Zendesk when the problem will be fixed.

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
