### ISSUE TITLE
MAILCHIMP AND BRUZY NOT WORKING

### ISSUE THREAD

**Issue by chiaraBCE** [ThemeFuse/Brizy#1324]
HI!
IF DE INTEGRATION IT'S OK WITH BRIZY PRO AND MAILCHIMP 
WHY THE FORM IS NOT WORKING??????

**Comment by NataliaBB** [comment]
Hello @chiaraBCE !

Please, submit a ticket here: https://support.brizy.io/hc/en-us
Please, send in your message the page URL and the wp credentials.

Waiting.
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
