### ISSUE TITLE
Column background hover image with link does not swap image

### ISSUE THREAD

**Issue by mcarv2018** [ThemeFuse/Brizy#1325]
When using two images for a column background, the hover image swap no longer works when you add a link to the image. The initial image remains and the link works, but the hover image does not render.

**Comment by NataliaBB** [comment]
Hello @mcarv2018 
Thanks for reporting this issue.
I was able to reproduce the same problem in my page, just created an issue for the team in order to check and solve this issue.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
