### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by spostau** [ThemeFuse/Brizy#1328]
Can't upload images.
I inserted the image box, but can't choose images.
I click on the cloud with arrow symbol, but nothing happens.
Please look into it urgently. It's a blocker.

<img width="268" alt="Screen Shot 2019-05-09 at 10 34 40 am" src="https://user-images.githubusercontent.com/50429385/57417021-283eeb00-7246-11e9-97e9-25cdfe4a6240.png">

I'm on the latest version of Brizy/Pro.

**Comment by MaxZiebell** [comment]
I had some major problems with image loading and redraws out of the box using Brizy with the default WordPress 2019 theme. Maybe change the Theme to the free version of GeneratePress or OceanWP. Not sure if it helps in this case.

**Comment by NataliaBB** [comment]
Hello @spostau 
What theme do you use? plugins?

Can you please submit a ticket for me on this problem: https://support.brizy.io/hc/en-us
thank you! 
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
