### ISSUE TITLE
Mobile version button

### ISSUE THREAD

**Issue by alexgr1985** [ThemeFuse/Brizy#1329]
hello, I have some issues with mobile phone version. Buttons doesn't appear and the text is not justify like i choose. It's ok when I design it but it doen't appear when I check with my iphone. Could you help me?

**Comment by alexgr1985** [comment]
When I create an anchor to a global element of the page, it does'nt work

**Comment by NataliaBB** [comment]
Hi Alex @alexgr1985 
Send me a ticket here: https://support.brizy.io/hc/en-us I will look over these problems.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by consultorml** [comment]
I have the same issue. When I use #anchor-id on menu item, the hamburguer menu don't do nothing. In classic menu works well. Link: [https://consultor.ml](https://consultor.ml)
