### ISSUE TITLE
Editor load time after 1.0.11 push

### ISSUE THREAD

**Issue by tylerwinter** [ThemeFuse/Brizy#133]
editor load time increased from 3-4 seconds to over 10 seconds after updating.
Not sure if it is conflicts with older elements (page was started to be built on 1.0.9). 
The page I'm working on only has a couple section background images and few feature images. What you would call an "average" SaaS site.
Actual page load time is unaltered.

**Comment by bagrinsergiu** [comment]
Hi 

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by bagrinsergiu** [comment]
Hi, 

Can you try to use it in incognito mode or in a different browser (Firefox or Chrome). 

Adblock Chrome extension increase load time x3. We plan to add an notice for this case.

Thanks for reporting
Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue due to no reply. Feel free to re-open if I’ve misunderstood you.

Thanks for reporting.
Sergiu
