### ISSUE TITLE
Unable to paste (control+v) text in button

### ISSUE THREAD

**Issue by ONEKENO** [ThemeFuse/Brizy#1332]
MacOS 10.13.6 - Safari & Chrome Version 74.0.3729.131
WordPress 5.0.4 
Brizy 1.0.74

1. Create a page with Brizy
2. Create a button 
3. Copy text from another app 
4. Click on the Brizy button text then paste(control+v) the text
5. The text is not pasted

I'm able to paste(control+v) the text to Text element else but not in the Button element.
I've tried right click the paste is deactivated.

However, I've figured out how to paste by another way by going to Chrome>Edit>Paste

**Comment by NataliaBB** [comment]
Hello!
Natalia here!
If you still have this issue, please submit a ticket here: https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia
