### ISSUE TITLE
Brizy Menu Links

### ISSUE THREAD

**Issue by sjdunaway** [ThemeFuse/Brizy#1334]
The menu links are not working on my homepage--51franklin.com. Please advise!
<img width="1091" alt="Screen Shot 2019-05-13 at 2 19 40 PM" src="https://user-images.githubusercontent.com/50594349/57644535-509e5080-758a-11e9-8de2-82f93ecf5af0.png">

**Comment by NataliaBB** [comment]
Hello @sjdunaway 

I've tried to reproduce the same menu on my page: https://jumpshare.com/v/bBvFuhx4UGovnYIqNCAu
everything seems to work fine. Can I check within your dashboard?

Regards, Natalia

**Comment by sjdunaway** [comment]
That you be great, thank you! 

The login is: /wp-admin
developer
51F2019!

--
Sarah Jane Dunaway
sarahjaneandco.com

Sent from my iPhone

On May 14, 2019, at 08:29, NataliaBB <notifications@github.com> wrote:

Hello @sjdunaway

I've tried to reproduce the same menu on my page: https://jumpshare.com/v/bBvFuhx4UGovnYIqNCAu
everything seems to work fine. Can I check within your dashboard?

Regards, Natalia

**Comment by sjdunaway** [comment]
Also I should add it’s just the menu placement on the homepage, below the slider. On the internal pages the menu works. 

--
Sarah Jane Dunaway
sarahjaneandco.com

Sent from my iPhone

On May 14, 2019, at 08:29, NataliaBB <notifications@github.com> wrote:

Hello @sjdunaway

I've tried to reproduce the same menu on my page: https://jumpshare.com/v/bBvFuhx4UGovnYIqNCAu
everything seems to work fine. Can I check within your dashboard?

Regards, Natalia

**Comment by NataliaBB** [comment]
Hey @sjdunaway 
There is a spacer above the menu - https://jumpshare.com/v/aSrRHbSzVoIvim2hVe3A  If you set z-index on the menu a little bit higher, the problem will disappear. Now everything works.

Regards, Natalia

**Comment by sjdunaway** [comment]
Thank you so much!

 
Sarah Jane & Co. Sarah Jane Dunaway	
m: 443-995-2540 <tel:443-995-2540>	
w: http://sarahjaneandco.com <http://sarahjaneandco.com/> e: hello@sarahjaneandco.com <mailto:hello@sarahjaneandco.com>	
 
 <http://www.facebook.com/sarahjaneandco>  <http://www.linkedin.com/in/sjdunaway>  <http://www.instagram.com/sarahjaneco>

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
