### ISSUE TITLE
center menus on mobiles

### ISSUE THREAD

**Issue by marampb78** [ThemeFuse/Brizy#1338]
I added a menu in wordpress and i want to include it on a given page build with brizy. I would like that the menu is displayed in toggled mode for the mobile version. I would like this is displayed in the centered mode, in such way it better fit the representation on an phone.
it is impossible to add a menu centered in the current implementation. 
would it be possible to add this possibility. 
there could be a way i'm tweaking the css around, however the structure i see it is created with the menus is done with li tags, and there is no class or id present with, so adding specific css becomes a little more complex. 

thanks a lot for your support
regards,
Bogdan

**Comment by NataliaBB** [comment]
Hello Bodan!

Please specify  - do you want to centre the menu items? https://jmp.sh/XblNshH
If yes, click on the menu list and open the toolbar, you will find the centre align in there.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
