### ISSUE TITLE
Brizy Update Page not working

### ISSUE THREAD

**Issue by ppate67** [ThemeFuse/Brizy#1343]
Brizy stopped working all of a sudden and brought down all other pages. Edit with brizy is working fine but when i try to save my work using the update button, it's not saving it and loops continuously.

**Comment by tylerspragg** [comment]
Unable to make updates as well (update button loops continuously).

**Comment by pmopmopmopmo** [comment]
Same - update button not working.

**Comment by progenthemes** [comment]
Same thing here. Update button just keeps spinning. Just started all of a sudden about 15 mins ago.

**Comment by manfye** [comment]
is brizy site down?

**Comment by ezeenet** [comment]
same Brizy update button not working

**Comment by estraatios** [comment]
same here

**Comment by jeff-caston** [comment]
Same issues here. Update button just spins and does not actually update anything

**Comment by NataliaBB** [comment]
Hello everyone!

We had a server and wp issues last week, lasted 2 hours. Hopefully, everything is solved.
But, if someone still has this problem, instal the 1.0.77 Free beta version or submit a ticket here: https://support.brizy.io/hc/en-us 

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
