### ISSUE TITLE
Updated WordPress and Brizy, page now forced into theme settings

### ISSUE THREAD

**Issue by cesteptcbguy** [ThemeFuse/Brizy#1345]
I am working on a site for a client. Never used Brizy before. I updated Wordpress from 4.9 to 5.2. Now the page looks as it should in the Brizy editor, but shows up forced into the Twenty Seventeen theme. Is there a switch I am missing?

**Comment by cesteptcbguy** [comment]
After restoring a backup, site is up again. However, when I update Brizy to latest version, that's when it breaks on me.

Currently restoring backup again.

**Comment by NataliaBB** [comment]
Hello @cesteptcbguy 

Can I test this problem within your dashboard? Can you submit a ticket here: https://support.brizy.io/hc/en-us

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
