### ISSUE TITLE
Not integrating with site

### ISSUE THREAD

**Issue by lolaso81** [ThemeFuse/Brizy#1346]
When creating a page, everything works the way it should but once the page is done and ready to view the layout breaks and doesn't look like what you designed. Also, it takes a long time to load. Any thoughts? Thanks

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
