### ISSUE TITLE
An error happened while trying to display this block You canopen an issue or remove this block

### ISSUE THREAD

**Issue by sheriff2019** [ThemeFuse/Brizy#1347]
Serious attention....

I can't work with majority of my Brizy pages website since few days back. The block settings doesn't open and even all the pages doesn't open with Brizy except the main page.

Any help please???? It is critical as my client is on my neck.

Below is the error

An error happened while trying to display this block
You canopen an issueorremove this block

**Comment by thailander27** [comment]
I'm having the same issue. 

When I click on the block settings button, the block displays the error and I am unable to continue working. This is only happening on one of the sites that I'm working on currently, however. 

This leads me to believe that it could be an issue with other plugins. I will test them and I will submit a list of what I'm running, but in the meantime I'm looking to get past this quickly. 

Thanks!


<img width="1490" alt="Screenshot of Google Chrome (2019-5-20, 9-42-34 AM)" src="https://user-images.githubusercontent.com/50561536/57991790-9f486f00-7ae3-11e9-9d17-40748192bc21.png">

**Comment by NataliaBB** [comment]
Hello @sheriff2019 . @thailander27 
Make sure you installed the latest Brizy versions:
Free - 1.0.76
PRO - 0.0.25

Please update and let me know if you still have this problem.
Thank you
Regards, Natali

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by thailander27** [comment]
@NataliaBB Sorry for the delay. After updating to 1.0.79 (Free) and 1.0.17 (Pro), I am continuing to have this issue. Please advise.
