### ISSUE TITLE
Unyson conflict with Brizy

### ISSUE THREAD

**Issue by MKACK5** [ThemeFuse/Brizy#1350]
I have The Core Multipurpose theme and the Unyson version is overriding my Brizy version (Mac 10.14), but I want the Brizy version to post. If I turn off Unyson, I lose the contact form I set up on the Contact Us page which I do not want. How can I have the Brizy version show in preview mode, not Unyson? I am beginning to think I should start over and I do not want to. Please help.
 
<img width="852" alt="Brizy" src="https://user-images.githubusercontent.com/50778111/57973012-178e2380-7970-11e9-9951-f0ad29c0654f.png">
<img width="878" alt="Unyson" src="https://user-images.githubusercontent.com/50778111/57973013-1bba4100-7970-11e9-952b-cb1eba6c4a28.png">

**Comment by NataliaBB** [comment]
Hey @MKACK5 
Nope, unfortunately Brizy will not work on Unsyon page....

Natalia

**Comment by MKACK5** [comment]
Natalia,

I wonder why it doesn't work because from what I've read ThemeFuse is now
working to a great extent with Brizy. > see attachment that is taken from
your HOME screen.
I would love a more helpful answer on how to solve this problem. I was
working with "Alex" and sent a few screen shots to explain what is
happening.

Can you please provide an explanation on how to solve it without having to
rebuild the page?

Thank you!

Marianne

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia

**Comment by MKACK5** [comment]
Natalia,

 Can you please reopen my case #1350? I never received a reply from my May
23 email.

Best,

Marianne
