### ISSUE TITLE
Role Manager/Post Type Activation

### ISSUE THREAD

**Issue by thailander27** [ThemeFuse/Brizy#1352]
When I attempt to activate a new post type and press "save changes" I am redirect to the "Optimize Images" tab. My New post type is not activated. Major Problem.

**Comment by NataliaBB** [comment]
Hello @thailander27 
We have the fix in the free version - 1.0.77 (not in the beta). The new release is planned for these days.
Thank you!
Regards, Natalia

**Comment by thailander27** [comment]
This aoppears to have been fixed!
