### ISSUE TITLE
Brizy / Brizy Pro not able to edit Mailster Campains

### ISSUE THREAD

**Issue by josephmurphy88** [ThemeFuse/Brizy#1359]
I was excited to see the Campaign checkbox with Brizy, and thought I would be able to edit Mailster Campaigns, but alas I just get the animated Brizy circles but it never does flip over into edit mode. I hope that wasn't too cryptic a description of my issue. Thanks, cheers.

**Comment by josephmurphy88** [comment]
Could this issue be related to "#1355 Brizy edit not loading, keep spinning in the page"? When I try to edit a Mailster campaign using Brizy, in both FireFox and Safari, Brizy edit doesn't load, but rather just displaying the spinning animation.

**Comment by NataliaBB** [comment]
Hey @josephmurphy88 
Can you please update the Free version to 1.0.77 and check if the editor will work? Log in to your account and check if you have the beta version. If not - subscribe here - https://www.brizy.io/beta-testing/ and we will send you the new release.
Thanks!
Regards, Natalia

**Comment by josephmurphy88** [comment]
Hello Natalia, I forgot to include that I am using Brizy Version 1.0.77-beta with Brizy Pro Version 0.0.26-beta and I am still getting the same unexpected result. I'm still not able to edit Mailster campaigns. And as far as I know I am using the latest and greatest of WordPress 5.2.1, Mailster 2.4 etc.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
