### ISSUE TITLE
Any plans to link Brizy with Google Analytics

### ISSUE THREAD

**Issue by Vivaleviv** [ThemeFuse/Brizy#136]

**Comment by bagrinsergiu** [comment]
Hi @Vivaleviv 

Can you give more details why you need GA integration in Brizy? It is possible to use a WP plugin.

Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
