### ISSUE TITLE
Brizy Pro 0.0.26-beta requires Brizy to be 1.0.77 or newer

### ISSUE THREAD

**Issue by jlconsult** [ThemeFuse/Brizy#1360]
Brizy Pro 0.0.26-beta requires Brizy to be 1.0.77 or newer.
I do not see or get the 1.077 update

**Comment by jlconsult** [comment]
I am not able to activate Brizy for Woocommerce products in the settings page

![afbeelding](https://user-images.githubusercontent.com/39246570/58174757-eaf34800-7c9e-11e9-9c30-1eb46400e35d.png)

**Comment by NataliaBB** [comment]
Fixed in the new 1.0.77 release.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
