### ISSUE TITLE
Mautic Integration

### ISSUE THREAD

**Issue by JamesBarrettDM** [ThemeFuse/Brizy#1365]
Please add mautic integration to the roadmap 🙏🏼

**Comment by NataliaBB** [comment]
Hello @JamesBarrettDM 
Thanks!

Added! https://trello.com/c/SJcFPC1Y/35-form-integrations

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
