### ISSUE TITLE
[Question] CSS style sheet

### ISSUE THREAD

**Issue by miunana160** [ThemeFuse/Brizy#1367]
Hi Is the any way to connect css style sheet from wordpress theme folder? I mean if can I use style sheet for every pages not custom css at each page?

**Comment by miunana160** [comment]
And also is there any way to custom font color with css?

Thanks!

**Comment by NataliaBB** [comment]
Hey @miunana160 
Nope, it will not be possible to connect css style sheed from your theme. We have custom css for each shortcode https://jumpshare.com/v/t7FuQQOv0f0iLjmB2CSw 

Also, you can add custom css for font colour, from Advanced tab of the element.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
