### ISSUE TITLE
Some Photos are appearing incorrectly on mobile

### ISSUE THREAD

**Issue by samhyde1** [ThemeFuse/Brizy#1368]
Really unfortunate bug here.  The Mobile brizy preview shows 2 of my images perfectly.  Yet, the actual Mobile view makes the images 1px in height, and the same width.  

Exhibit A is how the Editor shows it (correctly)
Exhibit B is how it actually looks on my iPhone XS (obviously wrong)

Exhibit A
![Screen Shot 2019-05-26 at 6 59 47 PM](https://user-images.githubusercontent.com/51062734/58388148-d2f62e00-7fe8-11e9-96a4-c5701eb85b76.png)

Exhibit B
![image1](https://user-images.githubusercontent.com/51062734/58388154-de495980-7fe8-11e9-95e7-d29ae2af0f61.png)

**Comment by NataliaBB** [comment]
Hello @samhyde1 
Natalia here!
I assume you added a background image to a section. In this case, add a spacer in the section and resize this spacer in the mobile version: 
add the spacer element: https://jmp.sh/zOJAtlA
resize on mobile version: https://jmp.sh/W11n7lD

Cheers!
Natalia

**Comment by samhyde1** [comment]
Thanks!  Appreciate it


*Sam Hyde*
Follow me on Instagram @samhyde1 <https://www.instagram.com/samhyde1/?hl=en>

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
