### ISSUE TITLE
Icons not showing up on site

### ISSUE THREAD

**Issue by leoniebarrow** [ThemeFuse/Brizy#1373]
I've added icons to my site. They are showing up in the Brizy editor but they are invisible on the site itself.

My (temporary) site:
http://237.2ca.myftpupload.com/

**Comment by samhyde1** [comment]
I've got the same problem on multiple pages.  Not sure how to +1 your comment lol so I'm just commenting

**Comment by NataliaBB** [comment]
Hello @leoniebarrow @samhyde1 
Try to Remove the svg file type from your your cdn settings.
![JE8J08WPmpqM9x0iBQT-XKUP_5-neU2ElC_4mt6LbCiltZfzdhgkwNeDxiEGYBjSNsH4PNB_c3zjwLURoPL9iTJprjKJn4snkOQIlHyX-Do](https://user-images.githubusercontent.com/36154919/58876050-acfe1700-86d5-11e9-92f2-35fe7a8c9e45.png)

Natalia

**Comment by samhyde1** [comment]
Would the CDN settings be on the backend of my hosting (GoDaddy) or on the
backend of WooCommerce/Wordpress?


*Sam Hyde*
Follow me on Instagram @samhyde1 <https://www.instagram.com/samhyde1/?hl=en>

**Comment by NataliaBB** [comment]
Hey @samhyde1 - GoDaddy

**Comment by samhyde1** [comment]
Didn't work, nor did downloading the plugin Enhanced Media Library and then
'Allowing .svg File Types'

Any other ideas?  Our site doesn't even have a firewall so it's not the CDN
settings.  They actually aren't accessible on GoDaddy, we had to call and
confirm.


*Sam Hyde*
Follow me on Instagram @samhyde1 <https://www.instagram.com/samhyde1/?hl=en>

**Comment by leoniebarrow** [comment]
I'm in the same boat and have tried the same things as Sam. My icons still aren't showing up.

**Comment by NataliaBB** [comment]
Hey @samhyde1 
I've sent a message via zendesk, can you update me please regarding the problem with icons?

@leoniebarrow  , please send me also a ticket and I will check the issue.

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
