### ISSUE TITLE
#PostContent Font Not Applying

### ISSUE THREAD

**Issue by bwagner78** [ThemeFuse/Brizy#1375]
Ever since the latest Brizy update, my fonts in my blog post template are defaulting to the browser default.

Prior to this, I was able to apply a font to the #postcontent and it would update the site. As of now - no changes. Is this a known issue? Am I missing something?

**Comment by NataliaBB** [comment]
Hello @bwagner78 
Natalia here!
Which version do you use right now? Can we test with the next Brizy update?

Natalia

**Comment by bwagner78** [comment]
I believe I am current.

Brizy: v. 1.0.81
Pro: v. 0.0.27

Is that correct?


---
Brett Wagner
brettwagner.net





On Jun 4, 2019, at 4:37 AM, NataliaBB <notifications@github.com> wrote:

Hello @bwagner78 <https://github.com/bwagner78>
Natalia here!
Which version do you use right now? Can we test with the next Brizy update?

Natalia

**Comment by NataliaBB** [comment]
Hey @bwagner78 
Yes, both versions are the latest. 
Can you please send me your wp credentials via a ticket? https://support.brizy.io/hc/en-us 
I will revert to the previous plugin version and test the #postcontent  fonts 

Thanks!
Regards, Natalia

**Comment by bwagner78** [comment]
Done.

Thank you.

---
Brett Wagner
brettwagner.net





On Jun 5, 2019, at 1:15 AM, NataliaBB <notifications@github.com> wrote:

Hey @bwagner78 <https://github.com/bwagner78>
Yes, both versions are the latest.
Can you please send me your wp credentials via a ticket? https://support.brizy.io/hc/en-us <https://support.brizy.io/hc/en-us>
I will revert to the previous plugin version and test the #postcontent fonts

Thanks!
Regards, Natalia

**Comment by jlconsult** [comment]
I have the same issue
 Brizy: v. 1.0.81 Pro: v. 0.0.27
Kind regards, 
John

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia

**Comment by bwagner78** [comment]
Is it resolved?
