### ISSUE TITLE
Unyson page builder conflict w/ Brizy

### ISSUE THREAD

**Issue by jm915998** [ThemeFuse/Brizy#1376]
I initially built a few pages with Unyson's page builder.  Then I discovered Brizy and really liked it.  I have since created a new version of the original pages that I built.  Unfortunately, my site is still showing the original Unyson built pages.  Is there a way to force the Brizy built page to show?

**Comment by NataliaBB** [comment]
Hello @jm915998 
Disable unyson on all pages, including the Brizy pages. 
https://jumpshare.com/v/HFvDL96p3Ky1FuPU1gcG
Next - Edit with Brizy button and save the changes with Update button.


Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
