### ISSUE TITLE
Radial Color Gradient Glitch

### ISSUE THREAD

**Issue by grabassenstein** [ThemeFuse/Brizy#1378]
Attempting to select the Radial Color Gradient for the background of a column element errors the entire block out, returning: "An error happened while trying to display this block
You can open an issue or remove this block"

![Radial-Gradient-Error](https://user-images.githubusercontent.com/26425684/58896813-68b24d00-86bc-11e9-9d86-ed47b1c4ec79.gif)

**Comment by NataliaBB** [comment]
Hey @grabassenstein 
Please, make sure you have the latest Brizy versions:
FREE 1.0.81
PRO 0.0.27

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
