### ISSUE TITLE
Issue whenever I click the black white setting button for block

### ISSUE THREAD

**Issue by MVicente90** [ThemeFuse/Brizy#1380]
whenever I click the black white settings block this pops up
![Screen Shot 2019-04-19 at 12 11 01 PM](https://user-images.githubusercontent.com/51390996/58925325-b5257900-870c-11e9-9dd3-c791da40da6a.png)

Thank you

**Comment by NataliaBB** [comment]
Hello @MVicente90 
Please, update the Brizy plugins to the latest versions 
FREE version 1.0.81
PRO version 0.0.27

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
