### ISSUE TITLE
[Feature Request] Support Local Hosted Video on Video Element

### ISSUE THREAD

**Issue by taoguangc** [ThemeFuse/Brizy#1384]
I noticed that the video element is only YouTube and Vimeo, and there is no local video. Local video is needed in many cases.

**Comment by NataliaBB** [comment]
Hello Philip @taoguangc 
Yes, we have this feature added in our trello map https://trello.com/c/roS1N0WS/32-video-from-wp-library planned for the new future.

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
