### ISSUE TITLE
[Feature Request] Video hosted locally

### ISSUE THREAD

**Issue by PG248** [ThemeFuse/Brizy#1386]
Now that YouTube removed the option to competely hide info overlays on embedded videos, the only way to present an totally unbranded video is via hosting the video alongside the wordpress site.

Elementor has the option to do this. Would be nice, if you could add this option to Brizy as well.

I'd also suggest to make the apect ratio of the video fully customizable (i.e. more than just predefined ratios like 16:9, 4:3, 1:1) via the UI without having to add custom CSS.

**Comment by NataliaBB** [comment]
Hello @PG248 
Both requests added in the trello map:

https://trello.com/c/zsaQGUgz/230-youtube-info-bar
https://trello.com/c/CaPz1haW/231-video-ratio

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
