### ISSUE TITLE
Cannot correct text

### ISSUE THREAD

**Issue by savadzehverovic** [ThemeFuse/Brizy#1387]
Hello,

I have given Brizy a try today and downloaded it to work on my friend's website.

However, everything was going smoothly until I wanted to edit text. I am simply not able to select any text and correct it, thus not able to build any page. 

Can anyone explain what might be happening?

Thank you for your assistance

**Comment by NataliaBB** [comment]
Hey @savadzehverovic 
Please disable all plugins and switch to another, default theme. Let me know which plugin caused this problem.

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
