### ISSUE TITLE
Brizy Contact Form

### ISSUE THREAD

**Issue by TyanaKorol** [ThemeFuse/Brizy#1388]
Hi, the Brizy contact form doesn't work

Can u help please?

**Comment by NataliaBB** [comment]
Hello @TyanaKorol 
What exactly doesn't work? a page url, please?

Thanks!
Natalia

**Comment by TyanaKorol** [comment]
@NataliaBB https://codesushi.co/contact/ "your email doesn't send"

**Comment by NataliaBB** [comment]
@TyanaKorol please, install the contact form 7 plugin and try on a new form on a new page. Send me a short update if it's worked. 

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
