### ISSUE TITLE
Dragging an empty column in an empty space leads to a blank screen

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#139]
I have tried in both Firefox and Chrome with the same result. Whenever an empty column is dragged to an empty area in another column or section, the page gets blank and you have to hit back, go to the WordPress editor and hit "Edit with Brizy" again! Sometimes it happens even in areas with other content but for sure in empty areas. That happens when editing in Brizy template mode. When having the default template mode the page just exists outside the editor and you have to hit back to go back to the editor. I have tried it with a couple of standard themes too(GeneratePress, Twenty Seventeen). Here is a screenshot of what is going on:
https://ibb.co/gj0XNy

**Comment by JMeisterDesign** [comment]
I too experienced this yesterday. It was very frustrating.

**Comment by bagrinsergiu** [comment]
This has been fixed and was included 1.0.14 update

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu

**Comment by quantumleap33** [comment]
Yeah, seems to be working fine now, thanks!
