### ISSUE TITLE
Pro menu isn't working

### ISSUE THREAD

**Issue by robsonet** [ThemeFuse/Brizy#1390]
My theme is Astra and I'm trying to build my menu using the pro block, I did create two pages menu Home / About but every time I try to import the Brizy header menu it keeps asking me to choose a menu! What am I doing wrong? is it a BUG?
Thanks
![screenshot-about easil com-2019 06 12-11-42-08](https://user-images.githubusercontent.com/45770313/59374640-4ce12380-8d1a-11e9-8842-7d46d6948419.png)

**Comment by robsonet** [comment]
I'm sorry, wrong Image. Here's the right one
![screenshot-masternance com-2019 06 12-13-34-47](https://user-images.githubusercontent.com/45770313/59374720-7a2dd180-8d1a-11e9-9a75-44cd07613052.png)

**Comment by NataliaBB** [comment]
Hello Rob!
Select the menu from the right corner of the menu section: https://jumpshare.com/v/39Wm22J02q3SXCrqyPrg

Regards, Natalia

**Comment by robsonet** [comment]
Thank you Natalia as always! 
Robson

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
