### ISSUE TITLE
Brizy icons returning 404

### ISSUE THREAD

**Issue by John-Henrique** [ThemeFuse/Brizy#1391]
I use Brizy free in 3 sites, but I try use in a new site and isn't working as expected... Eg. When access "testimonial", I get several 404 errors like this. Icons isn't displayed in edit mode or view.
![brizy-error](https://user-images.githubusercontent.com/332925/59442343-6e9ce200-8dd0-11e9-80c8-35cb65f1c023.png)

URL get from console errors https://static.brizy.io//1.0.101/template/img-block-thumbs/Dimi004Light.jpg
Returning

```
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
/1.0.101/template/img-block-thumbs/Dimi004Light.jpg
</Key>
<RequestId>775380B53955B99A</RequestId>
<HostId>
CtaXoZbM7oSZk+pvg/GSaxJOZ4Rhodgl/10XgqF1NCR0/RYVqhsdeZnYDk4lFu1AReX+9nZGhr4=
</HostId>
</Error>
```

Brizy: 1.0.81
WordPress: 5.2.1
PHP: 5.6.38
cURL: 7.19.7 NSS/3.27.1
Lim memory: 256MB

What is happening?

**Comment by John-Henrique** [comment]
@NataliaBB can you help me? 
I note this at first line 
`
Error: Icon not valid <!doctype html>
`

**Comment by NataliaBB** [comment]
Issue fixed via zendesk ticket system.



I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
