### ISSUE TITLE
"View Page" is all white

### ISSUE THREAD

**Issue by Tuckerhouse616** [ThemeFuse/Brizy#1392]
"View Page" is all white on my Home Page. I can edit it in "Edit with Brizy." What's the solution?

**Comment by NataliaBB** [comment]
Hello @Tuckerhouse616 

A white page usually is a fatal error, but we need to inspect it from your dashboard. 
Please, submit for me a ticket here: https://support.brizy.io/hc/en-us
Write your wp credentials and I will test the page.

Thank you!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
