### ISSUE TITLE
Menu not connecting to the page

### ISSUE THREAD

**Issue by Tuckerhouse616** [ThemeFuse/Brizy#1393]
Menu is not connecting to the page. Is there something I'm missing?

**Comment by NataliaBB** [comment]
Hey @Tuckerhouse616 
Please, give us some details? what exactly is the problem? a screenshot? error message maybe?

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
