### ISSUE TITLE
Images not loading in Brizy

### ISSUE THREAD

**Issue by melissa-lopez17** [ThemeFuse/Brizy#1394]
Trying to edit images in the Brizy editor but they appear as broken links. Any ideas why?

Thanks!

![image](https://user-images.githubusercontent.com/50712677/59541717-784d4500-8eb7-11e9-8e80-04389a451268.png)

**Comment by jeff-caston** [comment]
I am having the same issue on my site. Can't see any images when I am editing any of my pages

**Comment by tylerspragg** [comment]
This happening for me too on multiple sites with Brizy. 

No photos on any site are displaying. When can this be resolved?

![Screen Shot 2019-06-14 at 4 29 34 PM](https://user-images.githubusercontent.com/50711976/59543730-9cae1f00-8ec1-11e9-9443-88d2edcce282.png)

**Comment by xninedesign** [comment]
Hey.

Are you migrate your sites or change any path in hosting panel for used site domain?

Today i just rename folder name of my wordpress installation and all images dissappear.
When I rename it back images appeared again.

It seems Brizy script use a absolute path from your hosting to display images not relative one. So when You rename a main folder main or you change licalization of your site on server, or when you migrate the site to another hosting, images must dissappear. I think Brizy developers choose wrong idea for generate images.

**Comment by NataliaBB** [comment]
Hello @melissa-lopez17 @tylerspragg 

The image is not displayed because the php-gd or php-imagick is not enabled. Ask you hosting provider to enable them, or you can do this through your Cpanel dashboard.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
