### ISSUE TITLE
Block Settings Give error

### ISSUE THREAD

**Issue by dwsworks** [ThemeFuse/Brizy#1395]
Whenever i try to open the block settings the following error is displayed...

An error happened while trying to display this block
You can open an issue or remove this block

**Comment by NataliaBB** [comment]
Hello @dwsworks !

Please, make sure you have the lastest brizy updates:
Free - 1.0.82
PRO - 0.0.27
This issue has been fixed in the 0.0.17 PRO version. 
Regards, Natalia

**Comment by aliasak** [comment]
On website brizy.io only 1.0.81 for download. 
Block get error again.

**Comment by NataliaBB** [comment]
Hello @aliasak 
If the issue still is displayed on your page, please write me a ticket and send me please the wp credentials to check the editor - https://support.brizy.io/hc/en-us 

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
