### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by emmajuenke** [ThemeFuse/Brizy#1396]
Hi, 

I can't seem to get the emails from the contact form in the template haven with Brizy sent to our email.  http://www.villafleurdelyszanzibar.com/?page_id=579

We are using the latest version of contact 7. unsure about where to put the shortcode? It doesn't seem to work.. 

Please help with this asap as it is a major issue for us.

**Comment by NataliaBB** [comment]
Hello @emmajuenke 
1. Regarding the Brizy contact form error - please check at your server provider if you have the php mail function enabled. 
2. Regarding the contact form 7 plugin. You need to add a shortcode element in the Brizy page https://jmp.sh/HZe9pqV and paste the contact form 7 shortcode https://jmp.sh/IsyyoOp . If it will not work please contact your server provider.

Thanks!
Regards, Natalia

**Comment by emmajuenke** [comment]
Thanks, it worked.
Emma

Den mån 17 juni 2019 kl 19:11 skrev NataliaBB <notifications@github.com>:

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
