### ISSUE TITLE
how to replace background image for colums

### ISSUE THREAD

**Issue by makutamatey** [ThemeFuse/Brizy#1397]
Please I am creating a  new page with the Brizy template below, I cannot replace the images with my own. Kindly show me how to go about it. Thank you.
<img width="721" alt="team" src="https://user-images.githubusercontent.com/44055180/59621213-54d80380-911e-11e9-8cf3-648262c2bacd.PNG">

**Comment by NataliaBB** [comment]
Hello @makutamatey 
Natalia here!
You just need to open the section toolbar, in the right corner - https://jmp.sh/nSCIiFn 
Video on how to work with the image here: https://www.youtube.com/watch?v=BIBJhBcf12w 

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
