### ISSUE TITLE
I am not able to load popup in my site nor create

### ISSUE THREAD

**Issue by Nupur10sec** [ThemeFuse/Brizy#1398]
Hi Team,

I am not able to load popup in my site nor create popup from Button, CAn you help me to fix this asap.

**Comment by NataliaBB** [comment]
Hello @Nupur10sec 
Natalia here!
Can you give me some additional information? What exactly is the problem? the pop-up is not displayed in the preview? https://jmp.sh/Zh77mAp 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
