### ISSUE TITLE
All gone!

### ISSUE THREAD

**Issue by miunana160** [ThemeFuse/Brizy#1399]
Hi I created template yesterday, saved several times, but it's all gone. How can I fix this? Thanks!

**Comment by John-Henrique** [comment]
If you is using Brizy (free), visit the page, click "Edit", after "Edit with Brizy". If nothing error (in your site) on last save, this will show you your content.

**Comment by NataliaBB** [comment]
Hello @miunana160 
Can you send me a screenshot of the editor page and preview page? 
However, if the preview page is white (blank) page, then this is a fatal error and needs to be check with the code. 

Please,  send me a ticket here: https://support.brizy.io/hc/en-us with the wp credentials and I will check asap.


Regards. Natalia

**Comment by miunana160** [comment]
Hi Thank you for following up!

But I recreated anyway, I think it was because I edited with the page
opened, I should've logged in again first.

Thanks,

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
