### ISSUE TITLE
Parallax on mobile

### ISSUE THREAD

**Issue by dani1003** [ThemeFuse/Brizy#14]
Perhaps you can add parallax for mobile devices.

**Comment by bagrinsergiu** [comment]
@dani1003 

Thanks for letting us know, we are looking into it.

**Comment by thewebstylist** [comment]
Pls PLS Yes ThemeFu$e #MOBILEPARALLAX never more Priceless!! Dam Squarespace even has this in one click, and am doing all I can to get any and all off of Wix and Squarespace (they have such large advertising budgets being big paid for global platforms, all template based, but mobile parallax image styling adds an immediately priceless on scroll style) 🙏🏻💥🙌🏻

**Comment by bagrinsergiu** [comment]
Hi @dani1003 @thewebstylist 

On mobile devices CSS background-attachment Property is not working well: http://dl4.joxi.net/drive/2018/06/10/0028/0732/1860316/16/98468a25cf.jpg

it is possible to add with jQuery but this is not so easy. 

Thanks for letting us know, we are looking into it in future

Sergiu

**Comment by thewebstylist** [comment]
Just so you know, I have put mobile parallax as a #1 site design style and flavor for 4 years, 2 years in WordPress builds and I have never had a single complaint about site view style or load issues. Here are just a view examples to checkout, and pls let me know if any issues viewing on your own mobile phone view:
https://bebnzo.com/
https://officialjoannacassidy.com/
https://demos.thewebstylist.com/actor-model
https://elementorpagebuilder.demo.site/
https://TheWebStylist.com
http://TheWebStylist.LA (built on Adobe Muse 4 yrs ago and with insane multi layered butter smooth mobile parallax!)

I can send dozens more of my client designs if you'd like, but just hoping these serve as great examples of how many other theme developers have had no prob with allowing for smooth mobile parallax theme styling

BIG UPS and hope possible soon w Brizy pls! #winWIN Priceless mobile World View style!!

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/41IuL7HY/129-parallax-on-mobile

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu

**Comment by thewebstylist** [comment]
Wow, I see 7 months later and no one ever replied on Trello to your post Sergiu... I can't believe this isn't a priority fix #mobilefirst2019 or is there no fix...?
I can't use Brizy if this is the case (mobile parallax has been my favorite site style element for years) if it isn't smooth. I just upgraded to Pro and forgot about this issue until tried to use here 
https://cl.ly/d2adc3d571ac 🙏🏻📱⚡️
