### ISSUE TITLE
Pricing Table element

### ISSUE THREAD

**Issue by srikat** [ThemeFuse/Brizy#140]
May I suggest a pricing table element be added?

It should ideally have the standard parts like header, pricing, features, footer and ribbon.

**Comment by JMeisterDesign** [comment]
There's quite a few pricing blocks already in the plugin, or are you talking about something different?

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me a pricing element example?
Why you need it as an element?

As @JMeisterDesign said "There's quite a few pricing blocks already in the plugin".

Thanks
Sergiu

**Comment by srikat** [comment]
oh yes, forgot about pre-existing blocks. Thank you.

Two additional options would be cool:

1. Being able to assign an icon for each line of text. Ex.: https://d.pr/i/BjOJuC

2. Being able to set up a `?` at the left or right of the text to show more info in a tooltip on hover.

**Comment by bagrinsergiu** [comment]
Hi @srikat 

Q: Being able to assign an icon for each line of text. Ex.: https://d.pr/i/BjOJuC
A: We have Icon Box element for this case: http://dl4.joxi.net/drive/2018/06/13/0028/0732/1860316/16/59328bcd37.jpg

Q: Being able to set up a ? at the left or right of the text to show more info in a tooltip on hover.
A: You mean tooltip for each option? http://dl3.joxi.net/drive/2018/06/13/0028/0732/1860316/16/7760cc6a31.jpg If yes it is in our to do list. 

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Please add new issues for every new problem/ bug/ feature.

Sergiu

**Comment by srikat** [comment]
>We have Icon Box element for this case

https://www.facebook.com/groups/brizy/permalink/243407969756416/

>You mean tooltip for each option? If yes it is in our to do list.

Great.

**Comment by bagrinsergiu** [comment]
Try with Margin right margin left: http://dl4.joxi.net/drive/2018/06/13/0028/0732/1860316/16/b02f97999c.jpg

**Comment by KyleAtDND** [comment]
When I did the pricing table, I needed to add more rows, so I duplicated the content of one row, but I found myself having to tweak the vertical margins of some of the cells after I did that. Is that a known problem? Would you like to see an example of that?

**Comment by bagrinsergiu** [comment]
Hi @KyleAtDND 

Thanks for reporting. Please add a new issue with more details. 

Thanks 
Sergiu

**Comment by KyleAtDND** [comment]
You should be able to see here: http://cloud.designanddevelop.io/2e1360a3cd94

In this video, when I created the Pricing block with a bare-bones OceanWP template, it started off with some of the rows misaligned. But the bigger problem is that if I copy all the elements in a row (as the video shows), the new row isn't lined up correctly. It is usually off by 1-2px at some point everytime I try to copy a row.

**Comment by KyleAtDND** [comment]
@bagrinsergiu, sorry I just noticed that you said to add a new issue. I went ahead and did that even though you already re-opened this, so you can close this and go to that: https://github.com/ThemeFuse/Brizy/issues/981
