### ISSUE TITLE
Blank page in edit mode

### ISSUE THREAD

**Issue by snstar2006** [ThemeFuse/Brizy#1400]
Theme: Haven by ThemeFuse
Hosting InMotion Hosting

Site: https://www.cassiahillbelize.com/

![image](https://user-images.githubusercontent.com/2364410/59877954-64e12480-9364-11e9-95ca-eae7aec6f1e0.png)

When I tried to edit a page, the page seems blank as if nothing was there. When the page is loaded in default Wordpress editor, there are code inside the editor. I didn't click update or save anything after I notice this. At first I thought it was because I recently upgraded the WP core to 5, but after downgrading it back to 4.9.10, the same issue is still there. What can I do to fix this issue? I found many similar posts but none have any solution posted. 

Thanks

**Comment by NataliaBB** [comment]
Hello Ian @snstar2006 
Natalia here!

Please, install the demos of this theme. All demos are Brizy converted:
https://jmp.sh/DhEZVX3

https://jmp.sh/QeThX4Q 

Regards, Natalia

**Comment by snstar2006** [comment]
@NataliaBB I have solve the issue on FB chat with the Theme Fuse team. The issue was not with the Brizy editor.
