### ISSUE TITLE
just purchased cannot log in

### ISSUE THREAD

**Issue by jeff21up** [ThemeFuse/Brizy#1418]
Just purchased the brizy pro yearly and cannot log in? Waiting to be approved, i purchased several hours ago, sent email but no reply as yet?
Shouldn't a purchase give you immediate access?
Please advise
Jeff
![brizy](https://user-images.githubusercontent.com/37186670/60705349-d392b600-9efe-11e9-99ed-fbb0569430d6.PNG)

**Comment by John-Henrique** [comment]
After purchase you will receive emails with information and link to active your account. Verify your spam box...

**Comment by jeff21up** [comment]
Yes got the emails no password or log in details were asked for on purchase

**Comment by John-Henrique** [comment]
Looking for this email "Brizy: Registration"

**Comment by jeff21up** [comment]
Hi John
This is the email i received

![brizy2](https://user-images.githubusercontent.com/37186670/60708420-f7a5c580-9f05-11e9-839b-9738eaf6866c.PNG)

As you can see there is no password and it never asked for one, ive clicked the lost password reset link, done that and still no log in
confused.com

**Comment by John-Henrique** [comment]
This email isn't what I saw... In my case, I receive password automatically into email titled as "Brizy: Registration"

**Comment by jeff21up** [comment]
nope not got that one and its not in spam or junk or deleted?

**Comment by NataliaBB** [comment]
Hello @jeff21up 
Did you manage to log in and download the PRO file? If not, please send me your order confirmation I will check if the registration mail has been sent to you.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
