### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by lgiltor** [ThemeFuse/Brizy#1419]
Hi, My icons are missing in desktop, tablet or phones view.

**Comment by NataliaBB** [comment]
Hello @lgiltor 
Natalia here!

I will need to check what error is displayed in the console. Please, send me your page url. 
Or, it is possible send me a ticket with wp credentials https://support.brizy.io/hc/en-us to check the editor.

Thank you!
Regards, Natalia

**Comment by heybenbro** [comment]
I'm having the same issue in the brizy editor. Icons not showing up:
![image](https://user-images.githubusercontent.com/50721535/63292621-5095a700-c283-11e9-84ad-becf8fb832e7.png)

**Comment by heybenbro** [comment]
I'm having the same issue. Icons not showing up in editor or on published site:
![image](https://user-images.githubusercontent.com/50721535/63292967-22649700-c284-11e9-8368-02fdb5e10672.png)

**Comment by NataliaBB** [comment]
Hi! 
This is a DNS setting error. 
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia

**Comment by winnieza** [comment]
Was this issue resolved? I am facing the same issue.
