### ISSUE TITLE
HTML Element

### ISSUE THREAD

**Issue by srikat** [ThemeFuse/Brizy#142]
It will be very useful if Brizy has a HTML element where we can place custom HTML code and have it rendered.

**Comment by ash-f** [comment]
How about using embed element? it does render html.

**Comment by bagrinsergiu** [comment]
Hi @srikat 

Please check this element: http://dl3.joxi.net/drive/2018/06/13/0028/0732/1860316/16/3355d609e7.jpg

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Thanks
Sergiu
