### ISSUE TITLE
Project Block doesn't save

### ISSUE THREAD

**Issue by grickmarshall** [ThemeFuse/Brizy#1420]
Unable to save project block. See below. Other blocks save just fine.
![image](https://user-images.githubusercontent.com/52606105/60758812-60597480-9fd0-11e9-9e82-d3eb375fd569.png)

**Comment by NataliaBB** [comment]
Hello @grickmarshall 
Natalia here!
My tests: 
Editor mode: https://jmp.sh/xXaLE1s 
Preview mode: https://jmp.sh/LoaCl78

Please, disable all plugins and check again, including Brizy plugins.  Clear the cache and the browser cache.
If the problem still occurs, please send me the wp credentials I will check the environment.
Link: https://support.brizy.io/hc/en-us

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
