### ISSUE TITLE
Can't find heart icon to save block

### ISSUE THREAD

**Issue by Catkins74** [ThemeFuse/Brizy#1423]
I want to save a block, but I can't see the heart icon to save it.  Where that used to be, I just have the + new column icon.  How do I save a block / section now?
Thanks

**Comment by NataliaBB** [comment]
Hello @Catkins74 
Natalia here!

The save option is in the block settings. See video: https://jmp.sh/rMl77vg

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
