### ISSUE TITLE
[Question] font color and size change

### ISSUE THREAD

**Issue by miunana160** [ThemeFuse/Brizy#1424]
Hi Is there any way to change the font color and size in the sentence? 

For example, 

This is good for the summer

and Can I change the color & size only "summer" part ?

Thank you,

**Comment by SandraPrunici** [comment]
Hello!

Yes, it is possible. For this, you have to add the word you want to style in the span tag and add a class name to it. https://jmp.sh/Eh1PTYX  Then go to the Text settings -> More settings -> Advanced and go to Custom CSS field. Here you will find the "element" after it, place the name of the class you attribute to the span (for example it should look in such a way element .custom { }). Inside, place the styles you want. After the text-size attribute add "!important".
https://jmp.sh/34HMO2H (it have to look in such a way)

**Comment by miunana160** [comment]
Thanks! That helps a lot!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
