### ISSUE TITLE
Export custom blocks (global) ??

### ISSUE THREAD

**Issue by Amiga4ever** [ThemeFuse/Brizy#1425]
I'm realy concerm why there is no functionality to export/import custom (global) blocks.
I want to use custom blocks in many sites but it's just impossible. Every time I need to create it from scratch. It's make this framework useless for me which is really sad :( I really like it. Are you planning to add this feature?

**Comment by NataliaBB** [comment]
Hello @Amiga4ever 
Yes, the import/export feature is in progress. Will try to finish as soon as possible this module.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
