### ISSUE TITLE
can't view brizy block menu

### ISSUE THREAD

**Issue by arsalan-iqbal** [ThemeFuse/Brizy#1427]
I can't veiw block settings in brizy. why ?

**Comment by NataliaBB** [comment]
Hey @arsalan-iqbal 
You don't see this toolbar? https://jmp.sh/us1BUjB
Send me please a screenshot. 
Natalia

**Comment by arsalan-iqbal** [comment]
Hi,

KIndly find the attached file.

Thanks
![Brizy Issue 2](https://user-images.githubusercontent.com/51250581/61485529-cffd3580-a9ba-11e9-8f5b-ec48b88bf029.jpg)
![Brizy Issue](https://user-images.githubusercontent.com/51250581/61485530-d095cc00-a9ba-11e9-819c-a49afb32625d.jpg)

**Comment by NataliaBB** [comment]
Hello @arsalan-iqbal 
Thanks for the screenshot!

In this case, I will invite you to submit a ticket for me here: https://support.brizy.io/hc/en-us. Please send me your URL link and username and password. 
We will fix this asap.

Thank you! 
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
