### ISSUE TITLE
Unable to edit a block

### ISSUE THREAD

**Issue by igniparra** [ThemeFuse/Brizy#1428]
Every time I try to edit a block, I get the "An error happened while trying to display this block
You can open an issue or remove this block" error message.

**Comment by NataliaBB** [comment]
Hello @igniparra 

If you have the latest Brizy plugin versions and still have this error, please send me your wp credentials to fix this issue.
Link here: https://support.brizy.io/hc/en-us

Thanks
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
