### ISSUE TITLE
Using my Brizy page

### ISSUE THREAD

**Issue by GraceNyameyeNtreh** [ThemeFuse/Brizy#1429]
Hi there I just created a landing page via Brizy however when I went to use it inside my WordPress site it wasn't there, I couldn't add it to the rest of my pages. Could you please help me out with this

**Comment by NataliaBB** [comment]
Hello @GraceNyameyeNtreh 
Natalia here!
 
I'm assuming you created the landing page with Brizy cloud, yes? How did you connect the page with your WordPress site? 

Thanks!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
