### ISSUE TITLE
Parallax not working and gaps between sections in Safari

### ISSUE THREAD

**Issue by srikat** [ThemeFuse/Brizy#143]
URL: https://parallax-pro-brizy.wpdemos.net/

There are 3 sections on the above page with animated parallax background.

The first one is a full height one and only the top half appears with the bottom half totally white.

Parallax effect is not working for the other two sections.

There is a gap or white space appearing between the last sections.

These issues are not present in Chrome.

**Comment by srikat** [comment]
Possibly similar: https://github.com/ThemeFuse/Brizy/issues/85

**Comment by srikat** [comment]
Apparently, render issues are present in Edge as well.

A friend shared this screenshot in MS Edge: https://cl.ly/2J3c3m2w1l21

**Comment by bagrinsergiu** [comment]
Hi 

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by blitzgeek** [comment]
It works with the "Safari Technology Preview"([Download](https://developer.apple.com/safari/download/)), so maybe it's just a matter of time in this case.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
