### ISSUE TITLE
brizy stay spining

### ISSUE THREAD

**Issue by jairherre** [ThemeFuse/Brizy#1431]
I cant edit my brizy today all day stay spining 
![brizy](https://user-images.githubusercontent.com/51828179/61333079-7a266300-a7eb-11e9-97b4-4c02fd9a88d5.PNG)

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
