### ISSUE TITLE
Feature Request: Set Background color in Text - Highlighted words

### ISSUE THREAD

**Issue by DavidLean** [ThemeFuse/Brizy#1434]
**_1. Word(s) Highlighting._** 
Today the Brizy Text element allows you to select some words within a paragraph & make them bold, italic &/or set their text color. It would be nice if the text element also permitted the setting of the Background color. 
eg: This gives the look that someone has used a yellow highligher on some of the words in the text. 

**_2. Paragraph Highlighting._** 
Would also be handy if it was possible to set the background color on a Text element. 
Today I need to create a column, then put the text into it. etc. 
Compare to Gutenberg Blocks where I can have many paragraphs of text & quickly set the background of just one of them. 
This is handy when one part of your text is a "Caution: don't forget to do this" instruction. Could also be used for a quote, testimonial or notice without a ton of formatting.

**Comment by NataliaBB** [comment]
Hey @DavidLean 
Thanks for your suggestions.
I've added both requests to our trello map : https://trello.com/b/3OtE8BCR/brizy-public-roadmap

The team will look into it.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
