### ISSUE TITLE
Parallax speed

### ISSUE THREAD

**Issue by srikat** [ThemeFuse/Brizy#144]
Feature request: Add an option to control the speed of the parallax scrolling.

**Comment by bagrinsergiu** [comment]
Hi

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/xqSzdKgQ/179-block-parallax-speed

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
