### ISSUE TITLE
Video issue

### ISSUE THREAD

**Issue by GraceNyameyeNtreh** [ThemeFuse/Brizy#1441]
Hi there I am trying to upload a video to my page via Brizy however I can't see the button which actually allows me to upload the video to my page. The video container is ready to go, I now just want to upload my contact via my embedding code

**Comment by NataliaBB** [comment]
Hello @GraceNyameyeNtreh!

Video Issue: You need to add the video URL: https://jmp.sh/qZxTQ0k 

upload my contact via my embedding code - you can upload a contact form shortcode via embed element/shortcode element: https://jmp.sh/zGNMrjz

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
