### ISSUE TITLE
Feature Request: Accordion - Option to add "Expand / Collapse" Indicator

### ISSUE THREAD

**Issue by DavidLean** [ThemeFuse/Brizy#1445]
Please consider adding the ability to display an indicator on each tab that indicates to the user the accordion can be expanded or collapsed. 

This could be the words **[ Expand ]** or **[ Collapse ]**  
Or maybe a choice of a few characters / icons; eg: **^**, **...** , **+/-**  or an Up/Down arrow character.

**Comment by NataliaBB** [comment]
Hello David @DavidLean 
Thanks for your suggestion.
Added in our trello map: https://trello.com/c/81MK3z23/233-accordion-expand-collapse-indicator

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
