### ISSUE TITLE
Bullet Points Color

### ISSUE THREAD

**Issue by Benjo412** [ThemeFuse/Brizy#1450]
Hello,

The Bullet Points seem to only appear in black, and are not able to change color with the text color that is chosen.

Thanks.

**Comment by NataliaBB** [comment]
Hello @Benjo412 
If you mean the bullet points of the Slider, then you can change from the colour tab: https://jmp.sh/KTVRdK1
If you mean the bullet points of the lists, then you can change only through css custom code. 
We have an improvement ticket for the bullet points list. We will try to add this improvement as soon as possible.

Thank you!
Natalie

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
