### ISSUE TITLE
Microsoft Edge - page content not correctly displayed

### ISSUE THREAD

**Issue by carlognegna** [ThemeFuse/Brizy#1451]
Opening the website in Edge browser all content are collapsed on right side. Once scrolled on bottom page content are displayed correctly. 
![Screenshot Brizy](https://user-images.githubusercontent.com/25816142/62063928-1f99f780-b22c-11e9-8e33-e22aa9110333.PNG)

**Comment by NataliaBB** [comment]
Hello @carlognegna 
What theme do you use?
Try to change the theme to a default one.
I run on Astra: https://jumpshare.com/v/UJnItkX4VsoPscmAL2gB 

Regards, Natalia
