### ISSUE TITLE
Brizy errors

### ISSUE THREAD

**Issue by Tendai05** [ThemeFuse/Brizy#1452]
on localhost i have built a webpage using Brizy and now when I go to edit any content I get stuck with the brizy page loading and it won’t load (wheel just keeps spinning). I have tried with other browsers/pc’s and have the same issue. I am using Version 1.0.8.1  on WordPress version

**Comment by NataliaBB** [comment]
Hello @Tendai05 
Please, give us some details: 
You are trying to open a created page? or a new page?
What was the last action made on that page?
TrY TO deactivate all plugins and check again the editor. Open the console and check which errors are displayed. 
Thanks!
P.S I've sent a reply via zendesk but I didn't get any news from you.

Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
