### ISSUE TITLE
Elements image(s) don't show with mobile

### ISSUE THREAD

**Issue by siimonz** [ThemeFuse/Brizy#146]
It works well on big-screen, but on responsive images just show up as a line for an element.

**On small sreen:**
<img width="372" alt="screen shot 2018-06-12 at 10 59 09 pm" src="https://user-images.githubusercontent.com/40224470/41329603-40eac78e-6e94-11e8-8777-24dc48defbea.png">

**Big screen:**
<img width="1214" alt="screen shot 2018-06-12 at 10 59 00 pm" src="https://user-images.githubusercontent.com/40224470/41329604-40f916ea-6e94-11e8-873d-8bca7f57e0fa.png">

URL: https://bit.ly/2JumTLw

**Comment by bagrinsergiu** [comment]
Hi 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
Hi Siimon,

Just add an space element inside.
http://dl3.joxi.net/drive/2018/06/14/0028/0732/1860316/16/c3aa2232e1.jpg

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by siimonz** [comment]
Hey,
Not sure what you mean by that. The page is at: https://onlinehustle.co/testas/ <https://onlinehustle.co/testas/> and it’s the default block. I’m giving this plugin on more shot, if it doesn’t work, I’m switching.

How can I do that?
S

**Comment by bagrinsergiu** [comment]
Hi Siimon,

1. Add brizy block
2. Add space element in empty columns
3. Switch to mobile 
4. Resize space eleemnts
5. Done

Video: http://jmp.sh/1ecnw8F

Sergiu
