### ISSUE TITLE
Image upload interface error

### ISSUE THREAD

**Issue by nounoub** [ThemeFuse/Brizy#1466]
![problem](https://user-images.githubusercontent.com/53820153/62534865-4ec2f100-b84a-11e9-9c62-9a8921a91074.PNG)

I can't upload any images...
I've tried to get rid of all the other plugins thinking something was interfering.... but no change
I'm quite frustrated //

**Comment by NataliaBB** [comment]
Hello @nounoub 
Do you have the latest Brizy plugin versions? 
Try to clear your cache, change the theme. 
I'm assuming the css is not loading in your page. 
If you still have this problem, send me your wp credentials and I will check what is the problem
https://support.brizy.io/hc/en-us

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
