### ISSUE TITLE
An Error Happened When Trying to Display This Block

### ISSUE THREAD

**Issue by astreyamz** [ThemeFuse/Brizy#1467]
![Screen Shot 2019-08-06 at 11 24 09 AM](https://user-images.githubusercontent.com/53831387/62557539-d6a1fe80-b83c-11e9-8e16-1306cfb77d88.png)

I'm trying to fix some links on my website but keep getting this error. HELP!

**Comment by NataliaBB** [comment]
Hello @astreyamz 
Please send us your wp credentials into a support ticket, here: https://support.brizy.io/hc/en-us 

Thanks!
Natalia

**Comment by astreyamz** [comment]
Does this require brizy pro?

**Comment by mfawadkhan91** [comment]
Hello!
Same issue with me.
Kindly guide me "how to resolve this bug?"
Thanks

**Comment by NataliaBB** [comment]
Hello!
@astreyamz - No, you don't need to have PRO. 
@mfawadkhan91  - for the global blocks we already fixed, it will be included in the second update (not this beta-version), for some users, this issue disappeared after log out and cleaned the cache. 
Anyhow - if it possible give us access in your dashboard and we will check.

Regards, Natalia

**Comment by nagahill** [comment]
Hello,I have the same issue. Don't know what to do.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
For any bug reports, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
