### ISSUE TITLE
No iFrame Editing

### ISSUE THREAD

**Issue by Tymustafa** [ThemeFuse/Brizy#147]
Hey guys:) Loving Brizy Pro so far! Had a question that is a little weird. Asked on the home page and they said I should ask here.

So I am developing a marketing planning app that let's you create a plan for funnels, social, keywords and other marketing. Inside each page you can view and edit the pages. I have been able to get all builders including Divi, Beaver Builder, Click Funnels, Live Composer and more to work in an iframe when in edit mode but not Brizy:(

Any way to know if that is for security purposes or if there is a plan to add this functionality soon?

I am wanting to use Brizy in our Facebook Live broadcasts so that is why I am curious.

Here is a short Video so you can see what I am talking about in detail.
https://cl.ly/3b1s201F2C3o

**Comment by bagrinsergiu** [comment]
Hi 

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by rockalife** [comment]
Hi @Tymustafa 

We inspected this issue and it should be fixed in the next release. Closing this for now, but feel free to reopen if you'll find any problems after the update.
