### ISSUE TITLE
Repeatedly lost formatting and long load times

### ISSUE THREAD

**Issue by calliepegues** [ThemeFuse/Brizy#1471]
After a day or two my Brizy-edited pages loose their formatting and it takes forever to load the page. If I go in to each page a click update they start working again for a short time.

What are known plugin conflicts?
How can I continue to use this plugin and be totally sure my pages will stay intact and load quickly?

Also, when I update it now, the width gets condensed.??

Thanks!
Callie

https://satmom.com

**Comment by calliepegues** [comment]
Hello? Anyone have an idea? I've got to iron this out asap or quit using the Brizy plugin.

Thanks!

**Comment by NataliaBB** [comment]
Hello Callie @calliepegues 
I see you have "Failed to load resource: the server responded with a status of 404 ()" coming from the theme. Apparently, the css code is not loading in your page. 
Please, send me a ticket here and I can look on your dashboard and check. 
Link here: https://support.brizy.io/hc/en-us 
Thanks
Natalia

**Comment by calliepegues** [comment]
Thank you Natalia, I submitted a request with the same info posted here. Is there any additional info you need from me?

Thanks!
Callie

**Comment by calliepegues** [comment]
Nevermind, I received the email with the additional info!

**Comment by calliepegues** [comment]
Hi Natalia, I replied to your email with additional information but haven't
heard back.

Currently all my brizy pages are taking forever to load including my home
page (satmom.com), and pages are still losing their formatting (
https://satmom.com/en/6-week-moon-center-course/).

Also, switching to 'default layout' in order for my navigation to show up
reduces my layout to 2/3 of the screen instead of the full width.

Please contact me as soon as you can!

Thank you,
Callie


*Jag Jiwan Kaur     |     SATMOM.COM <http://SATMOM.COM>     |
857-212-9685*

**Comment by NataliaBB** [comment]
Hello Callie!
Apologizes for the late reply. Yes, we received your message, the team have this ticket in their dashboard, I've just updated it with an email. Let's continue to discuss via the ticket.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by calliepegues** [comment]
Please don't close this ticket. It seems after 3 weeks of waiting I'm
finally getting a response. I am gathering info for you now and would like
to continue using Brizy.

Thanks

*Jag Jiwan Kaur     |     SATMOM.COM <http://SATMOM.COM>     |
857-212-9685*

**Comment by calliepegues** [comment]
Why is this ticket closed?!

I am still having the same problem that my site won't load and the page formatting completely goes away at seemingly random intervals, even when no work is being done on my site.

My home page has formatting: https://satmom.com
but this other page has already lost the design:
https://satmom.com/en/womens-moon-centers/

**Comment by calliepegues** [comment]
Per my email to you last friday Set. 13:

I'm back to the original issue where the page formatting is getting lost and it's bumping my whole website offline. This is a total deal breaker for me but I'd like to continue with Brizy and not lose all the time and money I've invested so far.

https://satmom.com/en/womens-moon-centers/

I don't believe the login/out plugin was the only issue as this started long before I began using that plugin. Believe this has to to do with the Restricted Content Pro plugin. 

Please re-elevate this issue and let me know what solutions arise asap.
