### ISSUE TITLE
[Feature Request] Show icon name

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#1473]
Hi.

When I try to change the icon, I get a collection of about 4000 icons. 
There is a search bar to find an icon but there is no way to find the name of the icon you like when you browsing. 
So if I am searching for an icon and I see 2 more that I like there is no way to get their names for fast search. I will have to go again and search for them one by one.
Please add the icon name under it or when you hover or something.

Thank you

**Comment by NataliaBB** [comment]
Hello @estraatios 
Thanks for your suggestion.

I added this request in our internal GitHub #6147. The team will look over it.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
