### ISSUE TITLE
Posts are Forced to be Published

### ISSUE THREAD

**Issue by domesticworkersaid** [ThemeFuse/Brizy#1474]
Driving me crazy that I can't keep a post "Private" when saving it in Brizy, or as a Draft. Seems like that'd be pretty simple to implement. Is that coming soon?

**Comment by NataliaBB** [comment]
Hey @domesticworkersaid!

Why don't use Draft option when you save the page? https://jmp.sh/i9jkYKt  You also can switch to draft option while you have the Publish page https://jmp.sh/1XBKM6m 
In a couple of updates, we will have also the Draft/Publish options in the editor. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia

**Comment by domesticworkersaid** [comment]
Problem is that if I set it to Private, Draft, etc, whenever I make an update in Brizy, it automatically publishes it. So in order to keep it a draft, I would have to set it as a draft, update it in Brizy, then go back and save it as a draft. But then there's a moment where my website will show the new article. Plus that discourages me from saving often (because of the extra steps), which makes it more likely I'll lose my work.
