### ISSUE TITLE
"Edit with Brizy" button is still shown in Editor user even though Role Manager marked as "No Access"

### ISSUE THREAD

**Issue by HEYiKEN** [ThemeFuse/Brizy#1475]
PHP 7.2.9
MySQL 5.7.23
WordPress 5.2.2
Theme: OceanWP v1.6.10
Brizy 1.0.81

Steps:
1. Created an Editor user
2. Go to Backend Brizy>Role Manager>Role Manager
3. Make every Role to be "No Access"
4. Log in with Editor user
5. Go to Posts>Add Post

"Edit with Brizy" button is still shown in Editor user even though Role Manager marked as "No Access"

This has been reproducible since Brizy 1.0.80 but Brizy 1.0.79 is working fine.

**Comment by NataliaBB** [comment]
Hello! @HEYiKEN 
Can not reproduce the issue: 
My tests: 
**Natalia no editor** is set as a subscriber - https://jmp.sh/YEFy2DI 
 no access for "Natalia no editor" https://jmp.sh/BKIr2XI , 
when I log in as Natalia no editor - I can not create anything - https://jmp.sh/D6EjNHn  

Can you disable all plugins and try again?

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
For any bug reports, please submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
