### ISSUE TITLE
My page and media will not update.

### ISSUE THREAD

**Issue by Sbanke18** [ThemeFuse/Brizy#1476]
I'm on Brizy Pro, and the page I'm working on will not update with new media that I post. It's as if the update never takes effect and is critical to the project that I'm working on.

**Comment by NataliaBB** [comment]
Hello @Sbanke18 
Try to:  deactivate all plugins, increase your PHP memory limit, check and delete all revisions. 
If it will not work, please, send me a ticket here with your wp credentials. I will look over this problem asap. 
Link here https://support.brizy.io/hc/en-us 
Thanks!

Natalia

**Comment by Sbanke18** [comment]
Hi Natalia,

Thank you for the help – I’ve fixed the issue and the plugin is working correctly.

Best,

[cid:image001.jpg@01D557F5.56E96CC0]<http://www.sbacil.org/>
Steve Banke Jr.
Chief Operating Officer
The Small Business Advocacy Council

Phone 312-548-8608
Web www.sbacil.org  Email steve@sbacil.org
120 W Madison St. Suite 520, Chicago, IL 60603

[Title: LinkedIn - Description: image of LinkedIn icon]<https://www.linkedin.com/in/steven-banke-jr/>

**Comment by mprocto** [comment]
what was the fix? i'm having the same issue.

**Comment by Sbanke18** [comment]
I disabled all of my plugins and reactivated them. Everything worked seamlessly afterwards.

**Comment by DeReya** [comment]
Nothing worked for me! I tried everything: I cleared cache, php memory limit is set to 512, I deactivated all plugins, made a WPsweep ...
Nothing helps this time.
I NEED TO MAKE URGENT UPDATES TO MY SITE!
Can someone from Brizy team please help and/or clarify?

**Comment by NataliaBB** [comment]
Hello @Sbanke18 - Thanks for the update.
@DeReya - if you still the issue after deactivating all plugins, cleared the cache (including the server cache) and increased the php memory, then please send me your wp credentials here https://support.brizy.io/hc/en-us and I will look asap.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
