### ISSUE TITLE
Where is drop shadow in version 1.0.81

### ISSUE THREAD

**Issue by drace3000** [ThemeFuse/Brizy#1478]
I have looked and could not find where drop shadow settings are located.  When on a button I select Color. There is a Shadow option but it doesn't show drop shadow setting. Then I selected Settings and there are no drop shadow options either.  I see it on youtube presenations in Settings with earlier versions.  Please advise. Thank you

**Comment by NataliaBB** [comment]
Hello @drace3000 
We moved the shadow option in the image/section toolbar, under "color" option.
For images: https://jmp.sh/KeC9Om6
For sections: https://jmp.sh/1opcyNS 
For buttons: https://jmp.sh/CqkcGgI 

Let me know if you have any questions.
Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
For any bug reports, please submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
