### ISSUE TITLE
Edit page from the front end causes style resets.

### ISSUE THREAD

**Issue by JMeisterDesign** [ThemeFuse/Brizy#148]
Any time I hit the "Edit Page in Brizy" link in the wordpress admin bar on the front end of WP all of my colors reset back to Brizy default. I have to go into the admin backend > pages  and edit the pages through there to maintain my color styles.

**Comment by bagrinsergiu** [comment]
Hi 

This is a critical issue. Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
Hi @JMeisterDesign 

Can you help e with this issue? I need more details. 

This is a critical issue. Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by JMeisterDesign** [comment]
It hasn’t been an issue as consistent as it used to be but it will happen sometimes with no rhyme or reason. I haven’t been able to pinpoint a way to reliably reproduce it.

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thanks for suggestion
Sergiu
