### ISSUE TITLE
Vertical alignment on Block setting

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#149]
Would be useful when the block is full height.

**Comment by bagrinsergiu** [comment]
Hi 

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/ZDftaxwz/146-block-vertical-alignment

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
