### ISSUE TITLE
Not able to set up facebook page once integrated with Brizy

### ISSUE THREAD

**Issue by aimepingi** [ThemeFuse/Brizy#1499]
When I add facebook page, i see only white blank and not editable space. Now way to add my own facebook page .

**Comment by NataliaBB** [comment]
Hello @aimepingi 
Natalia here!
Thanks for reporting this problem. I could reproduce it and already forwarded to the team in order to fix this issue. I will come with a notification when I will have the fix.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
