### ISSUE TITLE
missing

### ISSUE THREAD

**Issue by dani1003** [ThemeFuse/Brizy#15]
missing:

1. animation options
2. html possibilities, like in text
3. shadow options

**Comment by bagrinsergiu** [comment]
@dani1003 

1. animation options - max 14 days
2.  Sorry, I’m not sure I understand what you mean
3. shadow options - 30 - 40 days

Thank you for the report.

**Comment by bagrinsergiu** [comment]
@dani1003 

Animation was added. Shadow options are on the way.

**Comment by bagrinsergiu** [comment]
Shadow is planned in (1.0.19) on Monday

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you suggestion.
Sergiu
