### ISSUE TITLE
Parallax effect on elements

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#150]
Would be nice if I can use on other than background image.
Themify Builder has this.
https://themify.me/demo/themes/builder-layouts/built-in-layout/parallax-gradient-design

**Comment by bagrinsergiu** [comment]
Hi 

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/hFGfpXsJ/171-parallax-effect-on-elements

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
