### ISSUE TITLE
Repeat lost formatting and site not loading

### ISSUE THREAD

**Issue by calliepegues** [ThemeFuse/Brizy#1500]
I'm reposting this because the problem was NOT resolved but my ticket closed.

Per my email response to this issue (previous ticket) last Friday Sept. 13:

I'm back to the original issue where the page formatting is getting lost and it's bumping my whole website offline. This is a total deal breaker for me but I'd like to continue with Brizy and not lose all the time and money I've invested so far.

https://satmom.com/en/womens-moon-centers/

I don't believe the login/out plugin was the only issue as this started long before I began using that plugin. Believe this has to to do with the Restricted Content Pro plugin. 

Please re-elevate this issue and let me know what solutions arise asap.

**Comment by NataliaBB** [comment]
I'm sorry you had these issues on the page,
This error is displayed in the editor mode: Error 406 https://jmp.sh/MVBAndK 
This error is displayed in the preview mode: https://jmp.sh/eFoHKNq 

This means that Apache has a mod_security tool that tries to block SQL injections by url. This rule is also blocking some real urls. More information you can find here https://www.inmotionhosting.com/support/website/error-numbers/406-error 

Therefore, you will need to contact your hosting support team and ask them to check the problem . Send them those screenshots above and ask them to search for mod_security tools and check if it's blocking some URLs



Please, let me know if you managed to check with your hosting provider this issue, let me know when they will have a reply.

By the way, last Friday, when I changed the template for you, the editor worked very well and the formatting has not been lost. Now, starting from Monday, the editor didn't work anymore. May I know what was your last actions last week-end?

Thank you!

P.S This ticket is not closed, it will be closed ONLY after the fix. 

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
