### ISSUE TITLE
I am unable to save changes on any page other than the home page

### ISSUE THREAD

**Issue by BrandonAwrey** [ThemeFuse/Brizy#1501]
Hi I am wondering why any changes I make to any page other then the home page will not save.

**Comment by NataliaBB** [comment]
Hello @BrandonAwrey 
Please, submit a ticket here: https://support.brizy.io/hc/en-us, send me your wordpress credentials and I will look over this problem asap.
Thank you! 
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
