### ISSUE TITLE
Cant save changes.

### ISSUE THREAD

**Issue by defectroyal** [ThemeFuse/Brizy#1502]
No changes will save. brizy has created a new page by itself (brizy #10) And there are no changes from the last 3 hours if i reopen it. The page i started/wanted to editi was totally blank. Cant save the blocks and then use in other pages.  lost a whole days work..............................

**Comment by NataliaBB** [comment]
Hello @defectroyal 
Natalia here!
Please, for this kind of error and bugs, submit a ticket here: https://support.brizy.io/hc/en-us
Send me your wp credentials and I will test the editor error asap.
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by defectroyal** [comment]
Thank you for answering Natalia but i had to redo the whole page before you could get back to me. I think the problem was me editing in a older tab after i upgraded Brizy.  

Is there a way to get pro support outside of facebook?
