### ISSUE TITLE
Error after update.

### ISSUE THREAD

**Issue by McScience** [ThemeFuse/Brizy#1507]
After updating 'Brizy' and 'Brizy Pro', the page created with 'Brizy' does not appear and the 'Astra' theme in use appears.

www.mcscience.com

**Comment by NataliaBB** [comment]
Hello Jaewook @McScience 
Let me know if you have the same issue after the latest Brizy updates.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
