### ISSUE TITLE
Can't view Blocks

### ISSUE THREAD

**Issue by elizacrawford1** [ThemeFuse/Brizy#1508]
I can't view the blocks - they all show up as loading wheels.  
![Snag_24301529](https://user-images.githubusercontent.com/55547634/65254067-b2873d80-dac9-11e9-85c3-228017ab0fca.png)

**Comment by NataliaBB** [comment]
Hello Eliza!
Are the block displayed in the page? The block list is displayed? saved/global blocks? 

Can you please send me your credentials to test this issue in your dashboard? Link here: https://support.brizy.io/hc/en-us.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
