### ISSUE TITLE
An error happened while trying to display this block You canopen an issueorremove this block

### ISSUE THREAD

**Issue by McScience** [ThemeFuse/Brizy#1509]
An error happened while trying to display this block
You canopen an issueorremove this block

why?

**Comment by NataliaBB** [comment]
Hello!
The issue is fixed in the latest updates.

Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
