### ISSUE TITLE
fullPage/pagePiling effect

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#151]
Would be nice to have effects like those popular js library.
Themify Builder has this.
https://themify.me/blog/new-parallax-section-scrolling-feature-ultra-fullpane

**Comment by bagrinsergiu** [comment]
Hi 

We tested this feature for sliders in the past. We need to solve 2-3 bugs and this feature will be added in production. 

Thank you for suggestion 
Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/BarncDd9/14-slider-more-animation-effects

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
