### ISSUE TITLE
[Bug] After importing saved blocks, the saved blocks tab shows blank page

### ISSUE THREAD

**Issue by loryel** [ThemeFuse/Brizy#1512]
Tools >> Export >> Saved blocks

and then

Tools >> Import >> WordPress

Now totally I can't access the Saved blocks tab any more now.

**Comment by NataliaBB** [comment]
Hey Lee!
The issue is fixed within zendesk platform. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
