### ISSUE TITLE
[bug] not working  Shortpixel API Key

### ISSUE THREAD

**Issue by loryel** [ThemeFuse/Brizy#1515]
Brizy >> Optimize Images >> Settings >> Shortpixel API Key

It's now working

**Comment by NataliaBB** [comment]
Hello Lee! @loryel 
The API Key issue is fixed in the 1.0.87 Brizy version.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
