### ISSUE TITLE
Brizy PHP error on pages, Cannot access editor - BROKEN SITES

### ISSUE THREAD

**Issue by melissa-lopez17** [ThemeFuse/Brizy#1516]
On many sites, the briny builder will not load. I cannot edit pages. When I look at the pages on the front-end of the site, they are all broken.We have had our developers look at it and they said it is a Brizy issue with php.

Attached are screenshots and the php error logs.

Also, we have already tested for a theme or plugin conflict. We have also started on a completely fresh Wordpress Install, and imported the pages from a site, and it still will not work. Running latest versions.

This is a HUGE issue for us, as we have many customers with Live sites that look like the screenshots attached.

Site example with issue: https://www.riverparkinn.com/

JavaScript error preventing Brizy from loading:

editor.js?ver=106:1 editor bootstrap error Error: Project data should exist
at d (editor.js?ver=106:1)
at editor.vendor.js?ver=106:71
at editor.vendor.js?ver=106:71
at MutationObserver.s (editor.vendor.js?ver=106:112)

**Comment by samanthawatersody** [comment]
This is a HUGE issue and we need a solution!

**Comment by KTd3n** [comment]
Same problem over here.

**Comment by pablobae** [comment]
And here..

**Comment by NataliaBB** [comment]
Hello! @melissa-lopez17 @samanthawatersody @KTd3n @pablobae 
The issue needs to be fixed locally.  Therefore, please send us your credentials via a zendesk ticket: https://support.brizy.io/hc/en-us.
Thank you!

Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia

**Comment by juanjosezg** [comment]
This issue remains when you try to replace or upload an image. any solution?
