### ISSUE TITLE
Bugs after updating to brizy.1.0.86 / brizy-pro-0.0.28

### ISSUE THREAD

**Issue by spostau** [ThemeFuse/Brizy#1517]
I am experiencing several bugs after updating to:
brizy.1.0.86
brizy-pro-0.0.28

- Site scroll up and down is very laggy, on mobile view.

- Mobile view is stretched to full width, even when "boxed" is chosen.

- Some elements not displayed in mobile view when it's disabled in desktop view, even though mobile view is enabled.  It only gets displayed in mobile view when i also enable in desktop view. 

All above were fine before updating from previous version.

Issues still persist after updating to 1.0.87.

**Comment by NataliaBB** [comment]
Hello @spostau 
The issue "Site scroll up and down is very laggy, on mobile view." is still open in the dev's dashboard.
The rest of the issues are fixed. But, if you still have those problems, please write me here: Shttps://support.brizy.io/hc/en-us.
Thank you!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
