### ISSUE TITLE
Can't restore from backup after updating to brizy.1.0.86/brizy-pro-0.0.28

### ISSUE THREAD

**Issue by spostau** [ThemeFuse/Brizy#1518]
After updating to brizy.1.0.86 / brizy-pro-0.0.28 and finding issues, i decided to revert my site to previous version , so restored from most recent backup.

However, after restoring, the site gets errors and is totally not accessible. Even wpadmin can't be accessed. 
Restoration has been done many times before with older versions, and it has always been fine.

Below is error. (note, i have replaced my home directory with ****)

Error Details
=============
An error of type E_ERROR was caused in line 23 of the file ****/public_html/wp-content/plugins/brizy/admin/migrations/globals-to-data-migration.php. Error message: Uncaught Error: Call to undefined method Brizy_Admin_Migrations_GlobalsToDataMigration::getProjectPost() in ****/public_html/wp-content/plugins/brizy/admin/migrations/globals-to-data-migration.php:23
Stack trace:
#0 ****/public_html/wp-content/plugins/brizy/admin/migrations.php(149): Brizy_Admin_Migrations_GlobalsToDataMigration->execute()
#1 ****/public_html/wp-content/plugins/brizy/admin/migrations.php(39): Brizy_Admin_Migrations->upgradeTo('1.0.81')
#2 ****/public_html/wp-content/plugins/brizy/editor.php(56): Brizy_Admin_Migrations->runMigrations('1.0.81')
#3 ****/public_html/wp-includes/class-wp-hook.php(286): Brizy_Editor->runMigrations('')
#4 ****/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 ****/public_html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#6 ****/public_html/wp-settings.php(525): do_action('init')
#7 ****/public_html/wp-config.php(98): require_once('/h

**Comment by spostau** [comment]
Site can only be accessed again when i re-installed brizy.1.0.86 / brizy-pro-0.0.28. 
So i'm pretty much stuck in that version

**Comment by NataliaBB** [comment]
Hello @spostau 
If you will have this error in the future updates, please write us on zendesk: https://support.brizy.io/hc/en-us. 
We don't recommend to upgrade to the previous versions. Further, if you will have issues witht he new version,  please write us.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
