### ISSUE TITLE
Brizy -  Can't edit/save changes

### ISSUE THREAD

**Issue by SCREDI22** [ThemeFuse/Brizy#1521]
When I create new content or a page, and click update content, just stuck in loop.

All Css settings have disappeared, I can't even see the "edit with brizy" button at the top of the page.

**Comment by John-Henrique** [comment]
Same with me, with PRO active or not

Brizy: 1.0.90
WordPress: 5.2.3
PHP: 7.2

**Comment by jlydia** [comment]
Same problem here, major customer's website is useless with high-profile donors unable to use the site. All I see are the menu items displayed down the left side of the screen.

Brizy: 1.0.90
Brizy Pro: 0.0.28
PHP: 7.2

I created a ticket earlier today, but have heard nothing as of yet.

**Comment by John-Henrique** [comment]
Testing with downgrade until 1.0.71
Brizy: 1.0.71
PHP: 7.0 and 7.1

@NataliaBB can you help us?

**Comment by hitorclick** [comment]
I have a client that is pissed and experiencing the same issue for several months. Going to be dropping Brizy pretty soon if no resolution.

**Comment by NataliaBB** [comment]
Hello Everyone @hitorclick @John-Henrique @jlydia @SCREDI22 
This issue has been fixed. 
For any technical bugs please write on our zendesk platform: https://support.brizy.io/hc/en-us 
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
