### ISSUE TITLE
Updated this morning, Brizy edit fields are blank

### ISSUE THREAD

**Issue by RickHH2** [ThemeFuse/Brizy#1522]
The block edit buttons (page and block) only show the duplicate field, all others are blacked out.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
