### ISSUE TITLE
Update to Global Items Not Cascading Across Applicable Pages  

### ISSUE THREAD

**Issue by goshenweb** [ThemeFuse/Brizy#1523]
I followed the advice to make my header block global first and then added it on all my pages however when I modified the header, the modifications did NOT cascade to all my applicable pages. The only way is to manually apply the changes on all applicable pages which appears to defeat the purpose of saving a section as Global.

thanks

**Comment by NataliaBB** [comment]
Hello @goshenweb 
What Brizy plugin version do you have installed?
Can I test this issue in your dashboard? Can you please send me credentials via zendesk platform: https://support.brizy.io/hc/en-us

Thanks!
Natalia

**Comment by goshenweb** [comment]
Apologies for not responding earlier. This issue appears to be resolved after I moved from localhost to prod server. Not sure why it was problematic on localhost. Many thanks
