### ISSUE TITLE
Brizy not loading after update 1.0.94 

### ISSUE THREAD

**Issue by MattMajch** [ThemeFuse/Brizy#1526]
On my Wordpress website I have only installed Brizy and Brizy Pro. 
I have updated both of plugins and now I can not edit my pages. 
When I click "Edit with Brizy" there is only loading animation on dark blue screen. 

I am using newest version of WordPress 5.2.3 and Brizy Pro (0.0.30).
There is no other plugins installed. 

Thats the big issue for me, please help if you can.

Greetings,
Matt

**Comment by KennethKr** [comment]
I have the same issue over here. Got stuck after upgrade.

**Comment by Martin-1970** [comment]
same issue...

**Comment by dorianalucia** [comment]
I'm having the same issue. I want to edit my pages, but Brizy is not loading

**Comment by MattMajch** [comment]
I've updated to newest version (1.0.95) and it still not working ...
I've uninstall and install free plugin again... still not working.

**Comment by KennethKr** [comment]
I updated to the latest Brizy 1.0.96. Now it's working again. Brezi pages is horribly slow, tho.

**Comment by Martin-1970** [comment]
Now 1.0.97 is published - no change....

**Comment by Martin-1970** [comment]
what is the best alternative for brizy??

**Comment by NataliaBB** [comment]
Hello everyone @Martin-1970 @KennethKr @MattMajch 
For any technical issue, please write us a ticket here: https://support.brizy.io/hc/en-us.
Unfortunatly I can not help you here since I don't know what errors are displayed in the console. 

Waiting for you on zendesk.
Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
