### ISSUE TITLE
Brizy not loading pages to edit. 1.0.95 Version

### ISSUE THREAD

**Issue by dorianalucia** [ThemeFuse/Brizy#1527]
I can't load my pages to edit. I open to edit on Brizy, but it stays at a loading page and doesn't show anything more.

What to do? I want to edit stuff for my pages. I use Brizy in 3 websites.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
