### ISSUE TITLE
Brizy issue Version 1.0.96

### ISSUE THREAD

**Issue by drkangl90** [ThemeFuse/Brizy#1528]
I go to load Brizy on my website and after initially trying to load I get the following error
"Sorry, Brizy could not load
Your theme must use the the_content filter in order for Brizy to work"

Everything is updated but having issues :-/

**Comment by NataliaBB** [comment]
Hello Mary @drkangl90 
You need to change the template. Try to use the Brizy template, or if it possible switch to another theme. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
