### ISSUE TITLE
Brizy not loading after update 1.0.97

### ISSUE THREAD

**Issue by Martin-1970** [ThemeFuse/Brizy#1529]
I have installed Brizy 1.0.97
- no preview when working with the page builder
- white screen at the front-end

What can I do?

**Comment by NataliaBB** [comment]
Hello Martin! @Martin-1970 
White screen in the front-end can be reproduced as a Fata error. 
-curl error.
-https error
-500 internal error
-migration error.

Please, if it possible, submit a ticket here - https://support.brizy.io/hc/en-us, include your wp credentials and I will check what is the problem.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
