### ISSUE TITLE
Ability to Add Blog post grids

### ISSUE THREAD

**Issue by gaurabdas** [ThemeFuse/Brizy#153]
Can you add a feature to list the blog posts grid wise or list wise or in any other style

https://prnt.sc/jszrqa

**Comment by bagrinsergiu** [comment]
Hi @gaurabdas 

Yes it is in our to do list. 

Thank you for suggestion.
Sergiu

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/rGs87TDQ/48-posts

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
