### ISSUE TITLE
Request: Change Brizy Templates

### ISSUE THREAD

**Issue by peterpinkster** [ThemeFuse/Brizy#1532]
I am almost having Brizy for a year!!!
I was directly in love with it. I  love the Interface, the easy to use Interface. Simply beautiful!!

After 4 months I got stuck alot. I had to buy Themes instead of making them. I couldn't figure out how I needed to use the Templates.   So I bought Oxygen and made all my websites since that day with Oxygen.

Oxygen doesn't have the nice interface. so I want to ask the Brizy Team.

**Please Change Templates Function**

In O I can create a Template with my header and footer and see directly the result when I open a page to edit.  Single posts are so easy. Please check Oxygen and copy it!!

**Another wanted feature**

In Oxygen I can write CSS, HTML, Javascript and even PHP directly in a page! So there are no limits.

Again... please add those features so that I finally can use Brizy after a year of waiting for an improvement!  **It will make Brizy the best**

**Comment by NataliaBB** [comment]
Hi Peter!
Natalia here!

Please Change Templates Function - in the next 2-3 updates;

CSS, HTML, Javascript and even PHP directly in a page - for each element we have custom css option - https://jmp.sh/K7T3VhC , HTML/JS code can be added within the embed element. 

PHP code can be added within these  plugins:
https://wordpress.org/plugins/php-everywhere/
https://wordpress.org/plugins/insert-php-code-snippet/

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
