### ISSUE TITLE
Cannot edit a button with link

### ISSUE THREAD

**Issue by sarneeh** [ThemeFuse/Brizy#1534]
When you assign a URL to a button, it is impossible to edit it later on. Click in the editor will redirect to the linked page.

**Comment by NataliaBB** [comment]
Hi!
Natalia here!
Unfortunately, I could not reproduce your problem, video: https://jumpshare.com/v/gvYIb6uacuY2hBMPfIhw 
If you still have this issue, please submit a ticket here: https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia
