### ISSUE TITLE
Brizy pages are unworkable!! slow!! in Safari on iPad / iPhone / Mac

### ISSUE THREAD

**Issue by ReneOverkleeft** [ThemeFuse/Brizy#1535]
Pages made with brizy can not be displayed in Safari.
On a iPad Safari will crash on brizy page.
On iPhone and Mac it takes 10 - 20 seconds just for a page-up or page-down.
No problems with other browsers. Everybody with Apple devices can not use my website.
See for example my website rsoverkleeft.nl

Please solve immediately, because we can not deploy any website now.

**Comment by yudikondo** [comment]
Hi, we have the same problem here!
See this client website: https://www.venoclin.com.br

**Comment by bagrinsergiu** [comment]
Hi 

This issue was solved 4-5 updates ego. Sorry for the inconvenience.  Filters on Safari are working very bad. We spend 4-5 days to find this issues.

Regards 
Sergiu
