### ISSUE TITLE
Ability to add Tables with sort and other features 

### ISSUE THREAD

**Issue by gaurabdas** [ThemeFuse/Brizy#154]
Hi , would be great if you can consider augmenting the elements with a table element.Presently we need to do it with external plugins like Tablepress

**Comment by bagrinsergiu** [comment]
Hi @gaurabdas

Duplicate issue: https://github.com/ThemeFuse/Brizy/issues/127

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you suggestion.
Sergiu
