### ISSUE TITLE
shape divider with various designs( zig zag,cloud,etc)

### ISSUE THREAD

**Issue by gaurabdas** [ThemeFuse/Brizy#155]
Hi , like that of in other builders , would be great if you can consider having a shape dividor with various designs by which each section can be demarcated by designs.
https://docs.elementor.com/article/207-shape-divider

**Comment by bagrinsergiu** [comment]
Hi @gaurabdas 

Duplicate issue: https://github.com/ThemeFuse/Brizy/issues/28

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you suggestion.
Sergiu
