### ISSUE TITLE
An error happened while trying to display this block

### ISSUE THREAD

**Issue by codeclinic** [ThemeFuse/Brizy#1555]
On numerous sites  I am seemingly randomly hit with an issue whereby clicking to edit a block/row jut results in the content disappearing and being replaced with this message:

`An error happened while trying to display this block
You canopen an issueorremove this block`

Console shows:
`TypeError: "a is not a function"`

**Comment by NataliaBB** [comment]
Hello!
Natalia here!
If you still have this issue with our latest plugin versions (Free 1.0.114/PRO 0.0.35) please submit a ticket here: https://support.brizy.io/hc/en-us;

Thank you!
Regards, Natalia
