### ISSUE TITLE
Settings overlay window covers working area

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#156]
Sometimes when an element is at the top of the page, any related element settings can appear on top of the actual element making difficult to preview and work with. It would be nice for the builder to be able to track where the element is, compared to the browser window and shift the window accordingly. Here is an example of the problem I am talking about:
https://youtu.be/tRIKQnwI00A?t=542

**Comment by NataliaBB** [comment]
Hello!
This issue has been fixed. It will be included in the next Brizy version. 1.1.115/0.0.35.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
