### ISSUE TITLE
[BUG] Posts pagination can't be styled

### ISSUE THREAD

**Issue by MarpoOcknew** [ThemeFuse/Brizy#1569]
Using the latest versions, v1.0.105 and v0.0.31, setting the colour of the pagination links on dynamic posts on pages and the archive block when working on templates doesn't apply.

**Comment by bagrinsergiu** [comment]
Hi 

You are right. This option is planned in update. Sorry for the inconvience.

Regards
Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
