### ISSUE TITLE
Brizy template - Print text without tag <p>

### ISSUE THREAD

**Issue by John-Henrique** [ThemeFuse/Brizy#1572]
Using templates get note HTML printed become without tag P for paragraphs, this cause some problems related to design. In my case, paragraphs can`t be customized. 

![brizy-post-content-error](https://user-images.githubusercontent.com/332925/70275052-1e557a00-178c-11ea-8e5c-afda5138c941.jpg)

How fix this?  @NataliaBB

**Comment by bagrinsergiu** [comment]
Hi John, 

This issue was solved ~ 2-3 updates ego. It is needed to replace #the_title with new elements from right sidebar: https://jmp.sh/ou6oQAp

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu

**Comment by John-Henrique** [comment]
I update my install and try, I can`t see this new elements. Any suggestion?
