### ISSUE TITLE
Element Posts - How define offset?

### ISSUE THREAD

**Issue by John-Henrique** [ThemeFuse/Brizy#1574]
I have one page where put 10 posts, then I put 2 elements posts, the first display only one last post and the second, display other 9 last posts, at this point it`s ok, but, see the image above, 2 posts is equals, because the first element post is displaying last post and the second element post too.

The solution here is have a offset parameter like code above image. 

Any suggestion to solve this?

![brizy-post-offset](https://user-images.githubusercontent.com/332925/70292366-d733ad00-17bc-11ea-9795-795eac219ee1.jpg)

```
$args = array(
 'post_type' => 'post',
 'tax_query' => array(
  array(
   'taxonomy' => 'categories',
   'field'    => 'slug',
   'terms'    => 'news',
  ),
 ),
 'posts_per_page' => '9',
  'offset' => 1, // excludes the first post in the query
);

```

@NataliaBB

**Comment by bagrinsergiu** [comment]
Hi John

Sorry for the inconvenience. We plan to extent Post element in 2-3 updates. 

I added this improvement in our roadmap. 

Regards 
Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu

**Comment by John-Henrique** [comment]
@NataliaBB  @bagrinsergiu  this item was improvement? I test with last version free and PRO, can`t see changes.
