### ISSUE TITLE
[Feature Request]  Sync saved Blocks and Layouts between Cloud and WP

### ISSUE THREAD

**Issue by Kyruil** [ThemeFuse/Brizy#1577]
One of the features I was hoping to find was the ablity to create a template layout and use it between different WP installs.

There is an article posted about 8 months about talking about but there is no update that I could find.

Thanks, Jodi

**Comment by bagrinsergiu** [comment]
Hi Jodi,

This feature is planned in ~ 4-5 weeks. It is needed a lot of tests in order to launch it. 

Thanks for suggestion
Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
