### ISSUE TITLE
Ideas and wish…

### ISSUE THREAD

**Issue by Philippe-Bertrand** [ThemeFuse/Brizy#158]
I'm newbie to Brizy (I think as many of us in here) and newbie to GitHub…
This morning, we exchanged on the Brizy facebook Group about the ability to add ID to section (we yet can add class), and to other stuff (it's an idea and a wish)…
I added maybe,
paged blocks for blog/posts,
infinite loading…
maybe the ability to choose from categories (one by name… more with IDs - The order of the post… the feature state of a post…
But… it's just ideas and wishes…
(Sorry for my english)

**Comment by bagrinsergiu** [comment]
Hi @Philippe-Bertrand 

Each block include ID by default like you can see in this screen: http://dl4.joxi.net/drive/2018/06/15/0028/0732/1860316/16/9c064d5262.jpg

We plan to add ID Editor interface in the same way as classes ( but is is not so easy - every time we change a anchor link we need to rebuild all pages - and this mechanism is not available in our system right now)

Thank you
Sergiu

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/wfxFxpXF/75-custom-id-to-an-element

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
