### ISSUE TITLE
Feature Request: Editor navigation in Textfield

### ISSUE THREAD

**Issue by worldoptimizer** [ThemeFuse/Brizy#1588]
Please add `⌘ + →` and `⌘ + ←` to navigate inside a text field while writing. It should jump to the end of the line or block and vice verse.

PS: Is there any chance you can remove the Brizy Community from Facebook and make it a Discourse forum https://discourse.org/. First this would be so much more accessible to people like me that don't use Facebook (privately) and not in the claws of evil Data-Mongers ;-) and it is really popular and made for this! I love writing and using it.

**Comment by bagrinsergiu** [comment]
Thanks for suggestion. 

I added this suggestion in our public roadmap: https://trello.com/c/k8y9U7Pc/249-editor-navigation-in-textfield

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu

**Comment by bagrinsergiu** [comment]
PS: Is there any chance you can remove the Brizy Community from Facebook and make it a Discourse forum https://discourse.org/. First this would be so much more accessible to people like me that don't use Facebook (privately) and not in the claws of evil Data-Mongers ;-) and it is really popular and made for this! I love writing and using it.

---

We added a community on our site: https://support.brizy.io/hc/en-us/community/topics

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
