### ISSUE TITLE
Brizy is just loaing o a black page I cant edit.

### ISSUE THREAD

**Issue by sumbooke2** [ThemeFuse/Brizy#1595]
The same issue everyone has been having I tried it severally to no avail.
It just keep loading and I have deativated almost all my plugins but it still wom't load.

Please help @NataliaBB 

Thank you

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message to Support and mention this issue inside: https://support.brizy.io/hc/en-us

Thank you!
Regards, Sergiu
