### ISSUE TITLE
[Feature Request] Unfold text

### ISSUE THREAD

**Issue by bariiis** [ThemeFuse/Brizy#1597]
https://shop.namogo.com/elementor-extras/widgets/unfold/

Please add unfold text element

**Comment by bagrinsergiu** [comment]
Thanks for suggestion. 

I added this suggestion in our public roadmap: https://trello.com/c/YBFLpvG7/248-unfold-text

We don't have an eta for this feature.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
