### ISSUE TITLE
Feature Request: Make current page active in the menu

### ISSUE THREAD

**Issue by melissa-lopez17** [ThemeFuse/Brizy#1606]
I would like to request that the menu changes color when a page is active. For example, if on the Homepage the color is different than the rest of the menu items. Thanks!

**Comment by bagrinsergiu** [comment]
Thanks for your sugegstion. 

Duplicate of # https://github.com/ThemeFuse/Brizy/issues/1611

Thank you!
Best Regards, Sergiu
