### ISSUE TITLE
[Feature Request] json Lottie animations

### ISSUE THREAD

**Issue by gigit95** [ThemeFuse/Brizy#1607]
Would be cool to have an ability to manipulate the .json files from AfterEffects Bodymovin plugin.
Importing Lottie animations, adding triggers (onload, onscroll, playing forward/backward, mouseover/out, etc).
I think we need a "Lottie element".

**Comment by bagrinsergiu** [comment]
Thanks for your suggestion

I added this suggestion in our public roadmap: https://trello.com/c/B1K9GPIV/247-feature-request-json-lottie-animations 

We don't have an eta for this feature. Please vote on Trello for it. 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
