### ISSUE TITLE
[Feature Request] User.com integration

### ISSUE THREAD

**Issue by peter-enestrom** [ThemeFuse/Brizy#1609]
I'd love for you to integrate with the CRM, user.com, so that we can send data from forms etc more easily.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/2hDp955E/246-usercom-integration. we don't have an eta for this integration. 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
