### ISSUE TITLE
Brizy couldn't save my changes

### ISSUE THREAD

**Issue by adigaproductions** [ThemeFuse/Brizy#1613]
Hello Good day!

I am having some issues with the brizy theme I am using, I made some changes and saved, but when I went to preview I discover that it has not updated only to be showing me the previous one. Anyone to help?

**Comment by bagrinsergiu** [comment]
Hello, I would love to help you with this issue. You just need to write a ticket for support. Thanks!

**Comment by adigaproductions** [comment]
Ok I will do that.

**Comment by adigaproductions** [comment]
Please how do I find the ticket?
