### ISSUE TITLE
Allow inputs direct changes

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Brizy#162]
This is very cumbersome, if I want to go from font size 14 to 38 I am forced to click the little arrow 24 times. This is unexpected from a frontent builder. It should be as fast as possible

![download](https://user-images.githubusercontent.com/2340172/41361348-24035442-6f2f-11e8-9d7c-4d97f46f2312.png)

**Comment by bagrinsergiu** [comment]
Hi 

A Pull Request with Rich Text Improvements is in our Review List.

Thank you for suggestion. 
Sergiu

**Comment by bagrinsergiu** [comment]
Hi,

We solved this issue and is planned for next update 1.0.45. Thanks for reporting. 


I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
