### ISSUE TITLE
Parallax Zoom

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#164]
When I use the parallax feature on some image, the image gets zoomed a lot. How can this be fixed?

**Comment by bagrinsergiu** [comment]
Hi 

Examples 1:

Screen Size: 1300x900
Block Size: 1300x600
Image: 1300x600
Parallax: none = 1300x600

It is working fine. It is 100% fro your container width and height

Examples 2:

Screen Size: 1300x900
Block Size: 1300x600
Image: 1300x600
Parallax: fixed -> 
-- Height = Scren Size = 900 
-- Width = 900/600*1300 = 1950

In this case image BG is changing position. If you want to see image on 100% screen size image and your image height is too small you will see this efect. 

Thanks 
Sergiu
