### ISSUE TITLE
Tree navigation panel

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#166]
Block ordering panel is useful but when Brizy gets full control for layered elements using z-index, Something like DOM/Elements tree navigation will be needed.

Like this
https://www.wpbeaverworld.com/smart-settings-ui/

**Comment by bagrinsergiu** [comment]
Hi

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by jamaalhassan** [comment]
### **Tree navigation panel will help us to select when this happen.**
![navigation](https://user-images.githubusercontent.com/43518055/45930020-9d78dc80-bf51-11e8-9296-ebce4f34e250.gif)

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/jX6vJ8dv/136-tree-structure-overview

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
