### ISSUE TITLE
Selecting Post Types "Products" Makes Product Page's Short Description Disappear

### ISSUE THREAD

**Issue by bytesource** [ThemeFuse/Brizy#168]
Hi, 

I have WooCommerce installed and wanted to test out how Brizy works on a single product page. But after selecting the Post Type "Products" in the Brizy settings, I noticed that on a single product's page the text box for the short description did not show up. Also, trying to add a comment threw an error:

![brizy - post type products selected - product short description not showing](https://user-images.githubusercontent.com/610307/41399178-33ae46fa-6fec-11e8-8d4b-53a509a83f81.png)

Unchecking "Products" in Brizy's settings made everything return to normal.

I'm using the OceanWP theme on my test site.

Cheers, 

Stefan

**Comment by bagrinsergiu** [comment]
Hi Stefan,

This has been fixed and was included in 1.0.15 update

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu
