### ISSUE TITLE
Ability to add Tables

### ISSUE THREAD

**Issue by gaurabdas** [ThemeFuse/Brizy#169]
Hi 
is there any possibility to add tables as an element in Brizy

https://thrivethemes.com/tkb_item/how-to-use-the-table-element/

https://uaelementor.com/widgets/table/

**Comment by bagrinsergiu** [comment]
Hi @gaurabdas

Duplicate issue: #127

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you suggestion.
Sergiu
