### ISSUE TITLE
Add the ability to add ID in advance settings

### ISSUE THREAD

**Issue by andrew-lof** [ThemeFuse/Brizy#172]
Hi, it be great to be able to add an ID in the advance setting panel the same way a class can be added. This is needed to target specific sections with custom JS. Would help with selecting  elements with jQuery as well. 

Another example is that we want to add a web personalization tool from Marketo and it needs unique IDS to be able to swap out dynamic content. 

I see that it has also been requested by Philippe in a batch request: https://github.com/ThemeFuse/Brizy/issues/158

Thanks

**Comment by cowdar** [comment]
+1 for me

**Comment by bagrinsergiu** [comment]
Hi all,

Each block include ID by default like you can see in this screen: http://dl4.joxi.net/drive/2018/06/15/0028/0732/1860316/16/9c064d5262.jpg

We plan to add ID Editor interface in the same way as classes ( but is is not so easy - every time we change a anchor link we need to rebuild all pages - and this mechanism is not available in our system right now)

Thank you 
Sergiu

**Comment by andrew-lof** [comment]
Sounds good, I can use the generated IDs for now for sections.

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/wfxFxpXF/75-custom-id-to-an-element

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
