### ISSUE TITLE
Issue with Translate Page, all my work is gone

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#174]
I was building my page for 1-2 days... I installed one of the themefus themes and it came with some sort of a translate page plugin. I was using the theme template, even translated the page in another language. Then I decided to switch to the brizy template to see if it will work with the translator, but all sorts of broken texts appeared and then all my work vanished.

**Comment by bagrinsergiu** [comment]
Hi

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by logaritym** [comment]
Hi. Unfortunately some bug prevents us from recovering my page. Your team member on the Facebook page already tried:/

**Comment by NataliaBB** [comment]
Hi Arthur! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
