### ISSUE TITLE
Inline button in forms

### ISSUE THREAD

**Issue by madz00** [ThemeFuse/Brizy#176]
Hi,
I was trying to style a simple lead magnet with an email field and a submit button next to it and found that is not possible actually.
Please can you add the possibility in the form widget to have the submit button inline next to a field?

**Comment by NataliaBB** [comment]
Hi @madz00!
Thanks for your suggestion.
We added this feature in our to do list.

Natalia

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/zOIzZUHS/69-inline-button-in-forms

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
