### ISSUE TITLE
Integration with reCAPTCHA and honeypot

### ISSUE THREAD

**Issue by github52341123** [ThemeFuse/Brizy#177]
Would like to add reCAPTCHA or honeypot in Brizy forms to secure from spam?

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/SJcFPC1Y/35-form-integrations

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
