### ISSUE TITLE
Shape Dividers 

### ISSUE THREAD

**Issue by cowdar** [ThemeFuse/Brizy#178]
Please Please add Shape Dividers 
Most of the other big builders have them and they are great at making your website look more unique

https://www.youtube.com/watch?v=d11trd0klQE

**Comment by IamJAX** [comment]
+1

**Comment by bagrinsergiu** [comment]
Duplicate: https://github.com/ThemeFuse/Brizy/issues/28

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you suggestion.
Sergiu
