### ISSUE TITLE
cannot re-edit page

### ISSUE THREAD

**Issue by peterhermans** [ThemeFuse/Brizy#18]
When I try to re-edit a page in Brizy, I get a 404 in reponse.
WP 4.9.5; Cryout Nirvana Theme

**Comment by bagrinsergiu** [comment]
@peterhermans 

Hi,

Can you give me WP credentials via Facebook Chat: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

or email: bagrin.sergiu@gmail.com

Thank you.

**Comment by peterhermans** [comment]
done

2018-05-12 10:46 GMT+02:00 bagrinsergiu <notifications@github.com>:

**Comment by bagrinsergiu** [comment]
Thanks

**Comment by bagrinsergiu** [comment]
@peterhermans 

After login on wp-admin i see homepage: http://dl4.joxi.net/drive/2018/05/12/0019/0888/1307512/12/97fafd4d9b.jpg

How i can access Wp Dashboard?

**Comment by peterhermans** [comment]
o.k. try again

Verzonden vanuit Mail voor Windows 10

Van: bagrinsergiu
Verzonden: zaterdag 12 mei 2018 12:29
Aan: ThemeFuse/Brizy
CC: peterhermans; Mention
Onderwerp: Re: [ThemeFuse/Brizy] cannot re-edit page (#18)

@peterhermans
After login on wp-admin i see homepage: http://dl4.joxi.net/drive/2018/05/12/0019/0888/1307512/12/97fafd4d9b.jpg
How i can access Wp Dashboard?

**Comment by bagrinsergiu** [comment]
@peterhermans 

Is a permalink problem. I added it to to do list. 

Thanks for reporting.

**Comment by bagrinsergiu** [comment]
@peterhermans 

Can you give e access again? 

Thanks 
Sergiu

**Comment by peterhermans** [comment]
donr

Op ma 14 mei 2018 09:15 schreef bagrinsergiu <notifications@github.com>:

**Comment by bagrinsergiu** [comment]
@peterhermans 

Thank you

**Comment by bagrinsergiu** [comment]
@peterhermans 

We had a problem with compilation. Can you confirm if it is working with last changes?

Thank you 
Sergiu

**Comment by peterhermans** [comment]
It works! Good job!

Op ma 14 mei 2018 10:35 schreef bagrinsergiu <notifications@github.com>:

**Comment by bagrinsergiu** [comment]
Thank you.

**Comment by bagrinsergiu** [comment]
@peterhermans

Can you give e access again?

Thanks
Sergiu

**Comment by peterhermans** [comment]
Hi Sergiu
I upgraded to 1.02 and everything seems to work fine now.
Cheers, Peter

Op ma 14 mei 2018 om 11:34 schreef bagrinsergiu <notifications@github.com>:

**Comment by bagrinsergiu** [comment]
Thank you Peter 

Have a nice day!

**Comment by peterhermans** [comment]
Hi Sergiu,
I noticed you will be bringing out a pro version of Brizy for $199.
That's too expensive for an amateur like me.
Can you tell me if the basic version stays as it is now?
Peter

Op wo 16 mei 2018 om 08:10 schreef bagrinsergiu <notifications@github.com>:

**Comment by DimiBaitanciuc** [comment]
@peterhermans The basic Free version will not only stay as it is now, we'll enhance it even further. This week will add save sections plus global sections in the free version and more will come soon.

This lifetime license is aimed more at freelancers/agencies but once we launch the Pro we will have more accessible licenses available that will cost as much as a regular WordPress theme costs: $49. 

Hope this helps.
