### ISSUE TITLE
Remove Google fonts

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#180]
It would be great to be able to remove any extra Google fonts added or from the ones that exist by default. When you try out different fonts, you end up with a big list that you later might not want to appear and clutter the interface.

**Comment by NataliaBB** [comment]
Hi!

Delete option for Google fonts is in our to do list, but it will be available later on. 

Natalia

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/FOwutnNj/84-remove-google-fonts-added

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by aaronkinsey** [comment]
Has this feature been added? @NataliaBB @bagrinsergiu

**Comment by bagrinsergiu** [comment]
@aaronkinsey - We move all features from Github to Brizy feature request list on Trello.
