### ISSUE TITLE
Undo/Redo history

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#181]
The undo/redo functionality is great but it would be very useful to also have a historical list where the use can recall and go straight to that function without multiple undos/redos.

**Comment by bagrinsergiu** [comment]
Hi,

Thanks for letting us know, we are looking into it.

Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/T8r5y4iM/172-undo-redo-history

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
