### ISSUE TITLE
Unable to edit homepage

### ISSUE THREAD

**Issue by LS25** [ThemeFuse/Brizy#183]
Hi, 

When I click Edit with Brizy on my homepage (https://www.ls25webhosting.co.uk), it is not showing me the body of my site, only the header and footer of my theme (see attached).

![home 4](https://user-images.githubusercontent.com/39123588/41476008-255db5dc-70b8-11e8-826f-43934850f9db.png)

Can you help me urgently please?

Thanks

Matt

**Comment by bagrinsergiu** [comment]
This has been fixed and was included 1.0.15 update

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu

**Comment by ramyas12** [comment]
my site not showing me the bod
![My site](https://user-images.githubusercontent.com/53647524/62410484-d2d76780-b603-11e9-8412-457d88739cbb.png)
y of my site, only the header and footer of my theme (see attached).
