### ISSUE TITLE
More color palletes

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#184]
It would be great if there were more than 8 colors in a global pallete(16 maybe?) and also if multiple pelletes could be saved and recalled for later use.

**Comment by IamJAX** [comment]
Import/export cookies would be nice option

**Comment by NataliaBB** [comment]
Hi!
New color pallet will look like here: 

![33670694-512acf06-daae-11e7-80fd-aa74bbeabfa5](https://user-images.githubusercontent.com/36154919/41601068-24edab2c-73e0-11e8-809b-20af11bc62d6.jpg)
![33670705-56713450-daae-11e7-8f22-4c5bbc1a090d](https://user-images.githubusercontent.com/36154919/41601084-2e2c14da-73e0-11e8-8918-bb957aa036d1.jpg)
![33670716-5e6e933c-daae-11e7-82ca-cc5f3bff2609](https://user-images.githubusercontent.com/36154919/41601106-35332250-73e0-11e8-922f-45c5c8274e4a.jpg)
![33670899-d2479c04-daae-11e7-8620-4bcb83cd4558](https://user-images.githubusercontent.com/36154919/41601112-3a648fd4-73e0-11e8-9dad-1cfe8250c81c.png)

Natalia

**Comment by quantumleap33** [comment]
That looks groovy, thanks!

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/eKZUFTer/88-more-color-palletes

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
