### ISSUE TITLE
Columns in forms

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#186]
Would be nice to have ability to have columns in forms.
Not just making form elements inline side by side but making containers for elements.

**Comment by bagrinsergiu** [comment]
Hi 

Can you give me more details/ examples/ screenshots? 

Thanks for suggestion 
Sergiu

**Comment by ash-f** [comment]
Like this.
name & email is in left column / message & button in right column
https://cl.ly/1M131s33180N

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/zOIzZUHS/69-inline-button-in-forms

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
