### ISSUE TITLE
Brizy "hijacking" excerpts in templates

### ISSUE THREAD

**Issue by greenisland-tim** [ThemeFuse/Brizy#187]
I have a page template that includes Related Posts at the bottom, and those include excerpts from the posts. I only use Brizy to fill the contents of the page. 

Within the Brizy editor, the excerpts are showing correctly (first screenshot). However, on the live site, the excerpt is pulled from the content of the Brizy page (second screenshot). You can see all three posts have the same excerpt, which is actually the content written into the Brizy page. Everything else on the related posts works correctly, and I believe the loop is correctly coded. 

If I add a manual excerpt, it works correctly. It's only when I let WordPress generate it's own excerpt that it pulls from the Brizy content.

![35195808_10216788848177084_1894913977285083136_n](https://user-images.githubusercontent.com/40306711/41491837-0cfac788-70c1-11e8-9d07-6021009e9bd0.png)
![35199103_10216788848297087_2612997294739423232_n](https://user-images.githubusercontent.com/40306711/41491838-0d0cceec-70c1-11e8-877b-bdd9517a4c37.png)

**Comment by madz00** [comment]
Hi, which plugin are you using for the related posts? Looks like WP Show Posts right?
