### ISSUE TITLE
contact form connecting issue

### ISSUE THREAD

**Issue by focalflicks** [ThemeFuse/Brizy#188]
I used these plugin to make my contact page but don't know how to connect contact form to my mail id. Please help

**Comment by bagrinsergiu** [comment]
Hi @focalflicks 

1. Update plugins to version 1.0.14
2. Click on integration icon: http://dl4.joxi.net/drive/2018/06/16/0028/0732/1860316/16/2d8443f088.jpg
3. http://dl3.joxi.net/drive/2018/06/16/0028/0732/1860316/16/d76074ba68.jpg
4. http://dl4.joxi.net/drive/2018/06/16/0028/0732/1860316/16/160c217ab2.jpg
5. http://dl3.joxi.net/drive/2018/06/16/0028/0732/1860316/16/6cd3f01842.jpg
6. Done

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you suggestion.
Sergiu

**Comment by geekysachintech** [comment]
Hey, i have follow the above steps but it still not working.
It showing message not sent

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
