### ISSUE TITLE
Feature Request: Add HTML Export Functionality To Finished Plugin As Seen In Demo

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#19]
It would be great if you could re-add the HTML export functionality since you already have it done anyway. Maybe in the pro version?

This would be a great way to be able to build websites and upload them to hosting accounts that aren't as powerful for people who don't plan on using most of WP functionality anyway. Plus, it could be easily recreated in WP later, if need be.

**Comment by bagrinsergiu** [comment]
@CJKrets 

I don't have an answer for this feature request right now. 
I added it to Feature Request List. 

Thanks

**Comment by bagrinsergiu** [comment]
I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Sergiu
