### ISSUE TITLE
 Border Effects

### ISSUE THREAD

**Issue by cowdar** [ThemeFuse/Brizy#190]
You delete my last  request  I’m guessing because I had a link to Elementor border styles as I could not see anyone else asking for this. So I will request this  enhancement  Again please add SVG  border styles/shape dividers 
Like they have in Elementor, Divi,  Ultimate beaver. 
They are great and add a lot to sites.

**Comment by NataliaBB** [comment]
Hi!

Thanks for letting us know, we are looking into it.

Natalia

**Comment by IamJAX** [comment]
Hey Cowdar,
This was already requested weeks ago. You last request got closed because it's a duplicate of the old request.

https://github.com/ThemeFuse/Brizy/issues/28

**Comment by cowdar** [comment]
Ok that’s good
I search and could not find  any reference to it.
Thanks
