### ISSUE TITLE
[Feature Request] Gradient Overlays like in Thrive Arcitect

### ISSUE THREAD

**Issue by michacassola** [ThemeFuse/Brizy#192]
Please add Gradient Overlays like in Thrive Arcitect.
https://www.youtube.com/watch?v=-2rHuNLlAcY

**Comment by bagrinsergiu** [comment]
Hi Micha,

Thanks for letting us know, we are looking into it. 

Sergiu

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/Ls3RZZa2/61-element-gradient

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
