### ISSUE TITLE
Implement column margin/padding functionality similar to section padding

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#196]
Wouldn't it be great to have the same functionality we do with the sections padding handling applied to the column paddings/margins as well? It would make Brizy even more of a truly "visual" editor and save a few clicks and trips to the advanced settings!

**Comment by bagrinsergiu** [comment]
Thanks for letting us know, we are looking into it. 

Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/shLcEGDg/151-column-row-margins-with-dnd

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
