### ISSUE TITLE
Pinterest Style Gallery & Posts(Feature request)

### ISSUE THREAD

**Issue by madbradjohnson** [ThemeFuse/Brizy#198]
Hi

It would be really awesome to have a pinterest style gallery option (Displayed in a masonry layout). (With the ability to add the title of the image and have the caption displayed.)

Hopefully this would be embeddable in a page and post with a load more/ auto loading function.

Filtering the gallery would be great.

**Comment by NataliaBB** [comment]
@madbradjohnson 

Hi Brad!
We have these features in our to do list, but they will come a little bit later. 

Natalia

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/rGs87TDQ/48-posts https://trello.com/c/WFFxNCB5/50-gallery

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
