### ISSUE TITLE
Brizy db logs break WP Migrate DB Pro import

### ISSUE THREAD

**Issue by kellymears** [ThemeFuse/Brizy#199]
I've already addressed this issue for myself by using wp-cli to do the import, so I don't need any help/support. I wanted to flag it for the Brizy devs. 

Running WP in network configuration WP Migrate DB Pro halts with an AJAX error when importing the brizy logs MySQL table. Notably, wp-cli doesn't have a problem with the table when using the check command. Excluding the table from the db import process also works, as does removing the entries from the table before running the import. Still, a potential incompatibility that may be more widespread than my personal experience.

**Comment by bagrinsergiu** [comment]
Hi Kelly

Thanks for letting us know, we are looking into it.

Sergiu

**Comment by bagrinsergiu** [comment]
This has been fixed and was included 1.0.16 update

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu
