### ISSUE TITLE
FONTS

### ISSUE THREAD

**Issue by joelmwasserman** [ThemeFuse/Brizy#2]
also can I use my own fonts...install them etc

**Comment by DimiBaitanciuc** [comment]
Right now you can use only Google Fonts but we plan to add the ability to add custom fonts in the future. 

They (Google Fonts) have a huge font collection. If you dont have to use a certain corporate font I think you can find a good replacement in their library. 

Anyway, thanks for dropping by.

**Comment by madz00** [comment]
More important would be the possibility to inherit default fonts from the theme so we can add them from the theme and have a consistent design between the theme and the page builder

**Comment by bagrinsergiu** [comment]
HI @madz00 

I'm not sure this is possible ( in each theme implementation is different and i'm not sure themes will be needed in near future like you know it today ). But you can use our global fonts and colors in order to sync Theme options with Brizy Options. 

http://dl4.joxi.net/drive/2018/06/10/0028/0732/1860316/16/2871c3f93d.jpg

Sergiu

**Comment by madz00** [comment]
Hi Sergiu, you are right, maybe it is something that we can avoid in future, but for now we need an easy option for using custom fonts in Brizy (not hosted somewhere) and simply inherit the system font family from the theme can be an easy temporary workaround. Elementor does it and it worked flawlessy before they released their custom fonts manager.

**Comment by bagrinsergiu** [comment]
Thank you for suggestion. I added in our list

**Comment by madz00** [comment]
Great! Also I noticed that there is no possibility to delete a font family from the global typography panel after it has been added, so after trying 10 or 20 different google fonts before finding the one the list becomes huge. Would it be possible to give us an option to delete them when are no more useful?

**Comment by JayOkey** [comment]
Just like to add my 2 cents. I would really like it if Breeze was able to inherit fonts from the theme in a similar fashion to Elementor and Beaver builder. While the plan might be to use Brizy as a theme builder for the majority of sites I build with Elementor or Beaver Builder I happy with letting the theme control most of the default settings. 

In the suggestion above regarding syncing fonts with the theme using the Global font settings wouldn't that cause you to load the fonts twice and slow the site down?

**Comment by NataliaBB** [comment]
Brizy Roadmap Link: https://trello.com/c/JKK5n0wa/82-custom-fonts

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
