### ISSUE TITLE
Clone option for elements (feature request)

### ISSUE THREAD

**Issue by gigit95** [ThemeFuse/Brizy#200]
Would be great to have an ability to "clone" an element. Let's say I clone an icon-box and if I change the bg-color, text-color, borders ... of the "parent" all clones change according to this element. And if I want I could "unClone" one of them to be able modify it differently.

**Comment by quantumleap33** [comment]
Like how it works with Global Sections but for Elements. That would be awesome! +1

**Comment by gigit95** [comment]
Yes. For example, we could have a checkbox  for "custom class". 

![myclass](https://user-images.githubusercontent.com/11440530/41612791-38bcbb02-73f4-11e8-95b5-4742d498ca81.jpg)

**Comment by NataliaBB** [comment]
Hi @gigit95 , @quantumleap33 

We are working on this feature now - these will be Symbols. But, it will not be available soon. 

Natalia

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/WMnOq9UR/173-symbols

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
