### ISSUE TITLE
Won't save and duplicate left toolbar problem

### ISSUE THREAD

**Issue by TheCrucible** [ThemeFuse/Brizy#201]
See here https://www.screencast.com/t/kiBGNpYcg

**Comment by bagrinsergiu** [comment]
Hi @TheCrucible 

Thanks for reporting. 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
