### ISSUE TITLE
Integration with TCS3 problem

### ISSUE THREAD

**Issue by tony47** [ThemeFuse/Brizy#203]
Hello, we are running a large site and we use TCS3 so that attachments are uploaded to our S3 space at Amazon AWS.

After selecting an image in Brizy editor, we get the following Warning, and image is not being shown:`

```
/var/log/apache2/error.log.1:[Mon Jun 18 19:56:07.517874 2018] [:error] [pid 28836] [client 127.0.0.1:39790] PHP Warning:  file_get_contents(/var/www/site/wp-content/uploads/2017/08/20170821114048-08134702.jpg): failed to open stream: No such file or directory in /var/www/site/wp-content/plugins/brizy/editor/user.php on line 397, referer: https://site/brizy-362991/?brizy-edit-iframe
```

This is happening because we are no storing files in the filesystem, but in  Amazon AWS.

Would it be possible to use Wordpress attachment functions instead of PHP filesystem API calls?

Thanks.

**Comment by bagrinsergiu** [comment]
Hi Toni

We need more time for this issue. We plan 2 updates for images in 2-3 weeks. After we can verify why it is not working.

Sergiu

**Comment by NataliaBB** [comment]
Hello!
Natalia here!
If you still have this issue, please submit a ticket here: https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia
