### ISSUE TITLE
Static Righthand Settings Dialog Box

### ISSUE THREAD

**Issue by cowronboom** [ThemeFuse/Brizy#205]
Please allow us to move the righthand settings dialog box where the padding and margin attributes are located. It hides things and makes it to where we cannot get to things or see them.

**Comment by NataliaBB** [comment]
Hi @cowronboom! 

Thanks for your suggestion. We are looking into it.

Natalia

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/azyn1ewb/144-right-panel

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
