### ISSUE TITLE
Easier in-site linking and unlinking

### ISSUE THREAD

**Issue by zartgesotten** [ThemeFuse/Brizy#206]
It would be a great improvement if the internal linking would work like it does in WordPress or other builders. You type in three letters and it gives you a list of compatible pages inside your own WordPress site. Also I am having problems unsetting a link, once it's set. Just removing the link URL is not working. Link is still there.

**Comment by NataliaBB** [comment]
Hi @zartgesotten 

Thanks for your suggestion on internal links. We are looking into it.

Regarding your technical issue, could you please give me a screenshot or your WP credentials? 
Please, send us a short message on our chat, via https://brizy.io/ 

![chat](https://user-images.githubusercontent.com/36154919/41662155-22dab59a-74a9-11e8-9444-cde3087cd18b.png)

Thank you!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
