### ISSUE TITLE
Custom Typography styles and Global blocks not working after migrating website

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#207]
Hi,

When moving a website from my localhost to a live domain/server there are a few things that go wrong:

1. The custom typography styles I created are gone.
2. The exisiting typography styles are reset.
3. Global blocks are broken, I see a message to submit an issue and an option to delete the block.

I migrated the website using the 'All In One WP Migration' plugin by Servmask:
https://nl.wordpress.org/plugins/all-in-one-wp-migration/

Best regards,

Christiaan

**Comment by bagrinsergiu** [comment]
Hi Christiaan,

Thanks for reporting. I will be back with a reply.

Sergiu

**Comment by mhun** [comment]
Hi,
Same bug here did you find a solution or a fix pls?

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by NataliaBB** [comment]
Hi @mhun 

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
