### ISSUE TITLE
Question: custom CSS

### ISSUE THREAD

**Issue by jrc2** [ThemeFuse/Brizy#21]
A couple questions, can I add custom CSS (or at least a custom class) to an element, and can I have custom responsive breakpoints?

**Comment by jrc2** [comment]
@bagrinsergiu 
Another feature suggestion: Let designers lock in the design so clients can edit content, but not mess up the design.

Another question: I see how to hide something on desktop, but how would I hide something on mobile?

**Comment by bagrinsergiu** [comment]
@jrc2 

Thank you for details. I need more time to think about this. 
I will reply here after investigation.

Sergiu

**Comment by jrc2** [comment]
@bagrinsergiu 

Sergiu,

Thanks! Is all CSS inline instead of a separate CSS file? Isn't that bad for caching/site speed?

I like how this page builder works though! The code is a lot cleaner than .... another free page builder I've used before.

**Comment by bagrinsergiu** [comment]
@jrc2 

We have a long list of optimisations. CSS inline, Editor Speed, Image Quality (Retina, Mobile, Tablet, Desktop), BG Images (sizes + retina), we have a lot of unused <Div> in preview, Global Styling Speed, ....

Last week we finished with image and BG optimisations.  
We plan to improve all Preview parts like (Images, CSS, HTML, JS) as soon as possible.

Sergiu 
Thanks for reporting.

**Comment by curiousprojects** [comment]
I would love to see a custom CSS option starting with site-wide then per page. Thx.

**Comment by tinsterman** [comment]
I see you can add a CSS class to an element. Could we add a custom ID?

**Comment by bagrinsergiu** [comment]
Brizy Roadmap 

1. Custom CSS: Link: https://trello.com/c/AFOkANLg/74-custom-css
2.  can I have custom responsive breakpoints: https://trello.com/c/SgjBI1az/44-responsive-breakpoint
3. Let designers lock in the design so clients can edit content, but not mess up the design. - https://trello.com/c/FYiOSfGA/36-role-manager
4. Custom ID: https://trello.com/c/wfxFxpXF/75-custom-id-to-an-element

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by dwsworks** [comment]
> @bagrinsergiu
> Another feature suggestion: Let designers lock in the design so clients can edit content, but not mess up the design.
> 
> Another question: I see how to hide something on desktop, but how would I hide something on mobile?

Yes a must...
