### ISSUE TITLE
Embed widget height issues

### ISSUE THREAD

**Issue by JMeisterDesign** [ThemeFuse/Brizy#211]
I have a gallery that I embedded with the embed element a few versions back that works perfectly. The embedded content dictates the height of the element because it's dynamic.

Fast-forward to today where I am building a separate gallery in an identical fashion, even using the same gallery plugin. NOW the embed element wants a height value set up front, which is not feasible with dynamic content such as a user generated gallery. 

Since the addition of a height slider in the embed widget, dynamic content is overflowing its container and has to be manually adjusted any time content is added. This is not ideal, as clients add content all the time to galleries and I don't expect them to go in and do the math to figure out the container height to fit their new changes.

![screen shot 2018-06-20 at 2 52 06 pm](https://user-images.githubusercontent.com/22325617/41682898-b699380c-749e-11e8-91cd-7d1a66fa1c7a.png)

![screen shot 2018-06-20 at 2 52 22 pm](https://user-images.githubusercontent.com/22325617/41682902-b7f7c4de-749e-11e8-830d-d81606c2ae1a.png)

**Comment by bagrinsergiu** [comment]
Hi,

I need to investigate this on my side. 
Thanks for reporting.

Sergiu

**Comment by Loumeer** [comment]
I would like to add that I am running into a similar issue with some shortcode I am using.

**Comment by Sclafsac** [comment]
I'm having the same issue. I created a page last May without issues (it still works as expected) but now, with version 1.0.19, I must set an height for my code embed, so the layout of the page won't change accortingly with the embed's real size

**Comment by bagrinsergiu** [comment]
Hi all,

This bug was fixed in version 1.0.21.
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thanks for suggestion
Sergiu
