### ISSUE TITLE
Using tabs - Android

### ISSUE THREAD

**Issue by Jonboix** [ThemeFuse/Brizy#214]
I have a block with two tabs. This works fine on my desktop and in editing preview mode for mobile.

When I access that link on my Android I see two tabs. The view opens to second tab with first showing behind it.

If I click on tab one, tab two is no longer visible.

http://jonbo.com/home-page/about-me/#eAto8hn7ms

**Comment by marcellefter** [comment]
Hi Jon,

Can you give me a screenshot for this issue?
I've been testing on Android and didn't notice your issue - https://prntscr.com/jxx8c6.

Thank you.
Marcel

**Comment by Jonboix** [comment]
Actually, I just realized that the other tabs drop to the bottom of the open tab. It wasn't disappearing.

I did just discover another issue. When I click on the third tab "Music Professional" it jumps out of the tabs.

Thank you so much for your response and help.

Jonbo

[Image]


[Image]



to another block.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Jonboix** [comment]
Thank you. Issue resolved.
The other tabs had moved to the bottom of the screen.
