### ISSUE TITLE
Brizy Contactform only working when logged in

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#218]
Hi there,

I was testing the Brizy contactform on a development site of mine, however I noticed it only works when I am logged in. When I am not logged in I see an error message underneath the contactform: "Message not sent". I already tried the following:

- Create a new page with a contactform from the Brizy library and connect it to the Wordpress mailer, but that didn't work either.

- I also tried two SMTP plugins and tried to send a test message from the plugin settings: WP Mail SMTP by WPForms (https://wordpress.org/plugins/wp-mail-smtp/) and Easy WP SMTP (https://wordpress.org/plugins/easy-wp-smtp/). These two send a test message perfectly fine but unfortunately don't work with Brizy but at least I know my server can send emails right.

Unless I am missing something it seems to be a bug with Brizy. Please let me know what I can do to help fix this.

Best regards,

Christiaan

**Comment by bagrinsergiu** [comment]
Hi Christiaan,

This has been fixed and was included 1.0.16 update

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu

**Comment by Infusednl** [comment]
Glad I could help in making Brizy better. Thanks again for the great support!

Christiaan

**Comment by bagrinsergiu** [comment]
Thank you!
