### ISSUE TITLE
Images Linked To Brizy

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#22]
There are still links to Brizy within the current version of the **plugin** that are pulling pictures from your servers.

These are the ones I had show up on the first page I built. 

https://app.brizy.io/storage/media/iW=5000&iH=any/3715ae7da78bcde1fe3d0fe9f129cfd86edb0d76.jpeg
https://app.brizy.io/storage/media/iW=5000&iH=any/7c627a8c2eece4831ff43399b8edad32eab7e561.jpeg
https://app.brizy.io/storage/media/iW=5000&iH=any/dd81059582abb5710fa8ca1da32a825a4f4bc587.jpeg

Don't know if this is intentional, or an oversight. Thought I would mention it anyway.

~ Corey

**Comment by bagrinsergiu** [comment]
@CJKrets 

Hi Corey,

We use our server as CDN. Brizy Plugin + Blocks today is > 100 MB. In future we plan to add more blocks + themes, from this point of view plugin can be 200, 300, 500 Mb. 

Every time a new block is added we use Remote CDN for images and cache it in WP. Preview use 100% local files all time. 

Sergiu

**Comment by CJKrets** [comment]
Hi,

Totally understand why the external links are used for page building, but these links show up after publishing as well. I copied those from Pingdom.

Would be nice if there were some way to import them into the media library. (Feature request?) That way they can be properly optimized, and do not rely on your external servers after the image has been chosen as a final version. That's assuming you are allowing folks the right to use these images(?)

Thanks, Sergiu.

Corey

**Comment by bagrinsergiu** [comment]
@CJKrets 

Hi Corey,

Can we discuss about this ~ in 10 days? In 1 week we plan a big update for images (retiina, screens sizes optimizations) BG ( screen sizes optimization), image resize library, image in editor and preview, wp media library, image alt + title

Thank you
Sergiu

**Comment by bagrinsergiu** [comment]
In 1.0.19 version images resize was moved 100% to WP. Only CDN and page compiler is on our servers but we plan to move it to WP in 2-4 months.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
