### ISSUE TITLE
Plugin Update Error - V1.0.15

### ISSUE THREAD

**Issue by mc-flurry** [ThemeFuse/Brizy#220]
Hi.  Ive updated the plugin to latest version but its changed colours on the site and also left a lot of the content blocks unusable.  I get the following error when trying to edit the page 

https://i.imgur.com/K1EMM1H.png

I ideally dont want to just remove the block so if an issue with updating and we cant resolve, would i need to downgrade so i can get the content.

**Comment by bagrinsergiu** [comment]
Hi 

Can you give me Project Link?

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
We had an issue with Globals between 1.0.14 and 1.0.15

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sorry for the inconvenience
Sergiu
