### ISSUE TITLE
Feature Request: A Lighter UI Option

### ISSUE THREAD

**Issue by iFillip** [ThemeFuse/Brizy#222]
**The 'black' UI in Brizy makes it really difficult to see the white wording.** 

It would be nice to have a lighter interface. I've used Elementor, now I'm a BRIZY fan,  and their UI was perfect. Please download the FREE version of Elementor on a test site and see how their UI color is light and very easy on the eyes. It would be great to have an "option" for a lighter UI.

I realize a lot of good folks like the dark UI, Apple included (see Mohave). Apple at least kept the "option" for folks who prefer a lighter UI.

 Love what you're doing. Please give this feature request some serious consideration and move it to the top. Cheers.

![1-brizy-dark-ui](https://user-images.githubusercontent.com/38173727/41789622-f200e208-768a-11e8-95bd-c7d42dbcd683.png)
![2-brizy-black-ui-gear](https://user-images.githubusercontent.com/38173727/41789623-f22d5a04-768a-11e8-9b19-4ed577408a0c.png)
![3-brizy-dark-ui-option-pop-up](https://user-images.githubusercontent.com/38173727/41789624-f253740a-768a-11e8-8a06-d4987414ff91.png)

**Comment by DimiBaitanciuc** [comment]
Hey, thanks for the suggestion, we'll look into it. 
I like the idea of having multiple color styles for the UI, so everyone can choose their preferred one.

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/z82ffIM5/89-a-lighter-ui-option

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
