### ISSUE TITLE
[Feature Request] Community Created Blocks

### ISSUE THREAD

**Issue by MilenFrom** [ThemeFuse/Brizy#223]
In other words to allow users to create their own blocks and to be able to publish it to public repository which will be accessible for all (pro)  #users.
Like... App Store for Brizy

**Comment by DimiBaitanciuc** [comment]
Love.the idea. We'll look into it.

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/MaJjIRBW/98-community-created-blocks

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
