### ISSUE TITLE
Wordpress Menu doesn't work inside of a row element

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#224]
The Wordpress menu works file if added to one of the preset blocks, but if you add a  "Row" element and then add it to one of the columns, it does not link and the drop down menu does not work.

**Comment by bagrinsergiu** [comment]
Hi, 

WP Menu element is link/ dropdown menu is working only in preview mode. 

https://jmp.sh/2oaLCwG

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by vitog** [comment]
@bagrinsergiu How can I get the menu to show the drop downs i've created in wordpress.

**Comment by NataliaBB** [comment]
Hi @vitog 
Create the drop down menu in WP: https://jumpshare.com/v/6M0ZVPdq79MypvWKvKpH
Then add as an element : https://jumpshare.com/v/1qGRuRBCApb1yz2O1buR

Best Regards, Natalia

**Comment by vitog** [comment]
Hi Natalia,

When I set up the menu, it wont allow me to click and open in a new menu.

Do the Drop Downs need to pages versus custom links?

**Comment by NataliaBB** [comment]
Hey @vitog !
The drop-down menu also must be set in the wp dashboard:
https://jumpshare.com/v/OiXnKsz17KpJZi0Je8vI 

But, if you want to add custom links, you need to add the links from your Theme settings, like in this video:
https://jumpshare.com/v/7wkV8UeyDWV2xAewCj85

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
