### ISSUE TITLE
Error with the blocks

### ISSUE THREAD

**Issue by kritsky** [ThemeFuse/Brizy#225]
Got this errors when trying to add the block
![sceen](https://user-images.githubusercontent.com/2165973/41810640-b883d4f6-770a-11e8-8008-7cca1849c944.jpg)

**Comment by bagrinsergiu** [comment]
Hi Michael

Can you give me Project Link?

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
Fixed in 1.0.19 

In case it is not working please switch to Astra theme and check again

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thanks for reporting
Sergiu
