### ISSUE TITLE
html importer/converter

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#226]
Brizy needs html importer/converter from raw html code or Classic editor content to Text element(Quill object)

**Comment by bagrinsergiu** [comment]
Hi 

Thanks for reporting. Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/99GrSFob/131-html-importer-converter

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
