### ISSUE TITLE
Latest update craches Apache on local install

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#227]
I am on a local installation on Windows 7 running the Laragon local environment. After updating to 1.0.15, I can edit a page with Brizy but when it's time to preview or view the page, my Apache keeps crashing. The enviroment runs the Apache 2.4.27 win64-VC14 build but swatching to 2.4.29 win64 VC15 . PHP version is 7.1.14. t happens in both Firefox and Chrome. Is that something that you could reproduce?

**Comment by bagrinsergiu** [comment]
Hi 

 It might be worth to have a look in the console and see if there are any errors or Apache error log file?

**Comment by bagrinsergiu** [comment]
Can you give me Teamviewer access? Thanks

**Comment by bagrinsergiu** [comment]
Laragon Wamp ? http://dl4.joxi.net/drive/2018/06/24/0028/0732/1860316/16/6979770f19.jpg

**Comment by bagrinsergiu** [comment]
I installed Laragon and tested a page with 7 blocls http://dl3.joxi.net/drive/2018/06/24/0028/0732/1860316/16/069e6de873.jpg

I can't reproduce this issue.

**Comment by quantumleap33** [comment]
Thanks for trying it man. In my case any pages that had been created with the previous Brizy version, had that issue. But new created pages work fine. I hope that was something on my end. Thanks again for the quick reply!
