### ISSUE TITLE
Copy Style

### ISSUE THREAD

**Issue by madz00** [ThemeFuse/Brizy#228]
Hi there, would be possible to plan a right click copy style feature like the one Elementor is building? I see this a perfect companion for the global styles feature that is limited to few elements, right now only fonts and colors. For example can be used for button, sections, rows or columns...

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/lztAHGLE/28-element-styles-copy-paste

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
