### ISSUE TITLE
Feature Request: Reverting Brizy Back to Previous Version.

### ISSUE THREAD

**Issue by timolukayode** [ThemeFuse/Brizy#23]
Can you add the ability to revert Brizy Plugin back to a previous stable version in case there is a bug in the new update?

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/3ITkQo8Y/86-reverting-brizy-back-to-previous-version

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
