### ISSUE TITLE
Please give us the tools to do more

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Brizy#230]
We are doing as much as we can to give you 500% support but I must admit that we are limited. 
I am trying to create several creatus.io pages but there are so many limits that do not let us do so. 
I hate to admit but must say that it took us only an hour to replicate a page with the big E builder and their export import feature is flawless. I can pack the pages now and give them to our customers as drop in replacement for the pages built with Unsyon page builder. Tomorrow we will release 1.0.2 with full support for Brizy but us giving you more than that is currently not possible. And we want to duplicate all pages we have for Brizy.

Please give us; 
docs
API
export/import
full page elements styling control

We want to do everything that is in our power to push towards Brizy , but we need tools to do so. 
If I am not able to figure out how to control sections and columns, number of columns, section width , section content width in few second than this is cumbersome. 

It might seem easy to do something from your custom templates but starting from scratch and just setting up the layout makes us run in circles. 
Just me asking for docs should say enough. I never used E before but I figured it out within seconds. 

One thing that is loosing me is More Settings, please add in title what the more settings is for. 

Try with adding row and column , and than click on the arrows, it might seem easy for you since you made it but I am lost. I dont know what I am adjusting , row or column. I choose full width and columns stretch , full width should be for the row and there should also be boxed/full for the row content. 

Than adding row from the left menu on blank page does not do anything , I can drag drop move , nothing happens. 

Here , http://take.ms/17tpd

I mean.. , well. Help me help you. Is all I can say now.

**Comment by bagrinsergiu** [comment]
Hi 

--- 

I am trying to create several creatus.io pages but there are so many limits that do not let us do so.
I hate to admit but must say that it took us only an hour to replicate a page with the big E builder and their export import feature is flawless. I can pack the pages now and give them to our customers as drop in replacement for the pages built with Unsyon page builder. Tomorrow we will release 1.0.2 with full support for Brizy but us giving you more than that is currently not possible. And we want to duplicate all pages we have for Brizy.

From this part i understand that you need import export feature for pages. Ok ok

---

Please give us;
docs
API
export/import

We plan to add developer API after Pro launch 

---

Can you give more details about this

1. If I am not able to figure out how to control sections and columns, 
2. number of columns 
3. section width
4. section content width in few second than this is cumbersome.

---

One thing that is loosing me is More Settings, please add in title what the more settings is for.

More settings will be changed in the future. We have a new design concept for this module.

---

Than adding row from the left menu on blank page does not do anything , I can drag drop move , nothing happens.

ADD A NEW BLOCK // Press the button to add blocks - Brizy structure is different than other builder.

Section -> Row -> Column -> Element

In future we plan to add at last 5 types of Sections:

1. Header: Ex: http://test-de12d4.bitblox.site:9000/editor/brizy
2. Footer
3. Popup
4. Banner
5. Default blocks 

When the user adds a new row, what type of block will be added (Header, Footer, Banner) ?

**Comment by DimiBaitanciuc** [comment]
@danyj we launched 3 weeks ago and Elementor and the rest launched 2 years ago man? give us a couple of months. I've looked over all your demos and you can do a bunch of them with Brizy right now with minor compromises. The same way we are doing with all ThemeFuse themes right now. 

If you want them to be 1 on 1 then you'll have to wait a couple of months and then you'll be able to do them 1 on 1.

**Comment by danyj** [comment]
@DimiBaitanciuc dont get defensive. You 177 issues asking for things, this one is not different.  If we dont give you heads up who will? Take it as a issue , not a complaint against you.
