### ISSUE TITLE
Export/Import and templates

### ISSUE THREAD

**Issue by danyj** [ThemeFuse/Brizy#233]
@bagrinsergiu 

Please see if you can add export/import feature for pages. 

The thing I would love to see is the abbility to add my own tab for templates and their previews. 
For example I make 50 pages in Brizy for theme Creatus  and add the tab name Creatus here 

![add_ab](https://user-images.githubusercontent.com/2340172/41823587-69b24972-7802-11e8-81a8-06b6f80e8b21.png)

**Comment by NataliaBB** [comment]
Hi @danyj 

Thank you for this suggestion, we are looking into it.

Regards, Natalia

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/xYQB0C04/77-export-import-for-demos

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by jdcalled** [comment]
The possibility of export and import is very useful to duplicate sites, for example, when somebody is going to build the same website but in other languages.

**Comment by MaxZiebell** [comment]
+1 import export of pages / designs
+1 copy & paste (preferably even across domains, but then without style as new site has its own style, but should work as style is in CSS and copy content is only structure)
