### ISSUE TITLE
Please add "no-follow" along with the "open in new tab" for URL links

### ISSUE THREAD

**Issue by iFillip** [ThemeFuse/Brizy#235]
When creating a link, it would be nice to have the option to "check" a "no-follow" box. Right now, there's only an "open in new tab" box.

**Comment by bagrinsergiu** [comment]
Hi

Added in 1.0.20. Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
