### ISSUE TITLE
Export block and pages

### ISSUE THREAD

**Issue by cajsah** [ThemeFuse/Brizy#236]
I would be good if you could add a function for export a saved block/page/template as js. files, like you can in Elementor.

**Comment by NataliaBB** [comment]
Hi @cajsah 
Thanks for your suggestion, it is already added to our list. 

Natalia

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/xYQB0C04/77-export-import-for-demos

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
