### ISSUE TITLE
Issue - Editing page and resizing column

### ISSUE THREAD

**Issue by kwmdesign** [ThemeFuse/Brizy#237]
A recent issue with editing a page via Brizy. I go to adjust the column width, and it exits the builder without clicking anything. Also caused the column to run underneath automatically.

<img width="172" alt="screen shot 2018-06-25 at 11 36 47 pm" src="https://user-images.githubusercontent.com/29698768/41853260-b9479e14-78d0-11e8-9a1e-dedafaaee2fe.png">
<img width="689" alt="screen shot 2018-06-25 at 11 36 53 pm" src="https://user-images.githubusercontent.com/29698768/41853262-b9871f80-78d0-11e8-8179-6ce1b5a8a730.png">

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
I tested it with Brizy Template and Default WP Theme

Astra theme add a lot of empty links after each div.

https://jumpshare.com/v/eVd6u8X5ToRaqhm3yX1i

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
