### ISSUE TITLE
Buddypress/Bbpress Integration 

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#239]
Do you think this would be possible? It will be a killer feature, but not sure how hard it will be.

**Comment by NataliaBB** [comment]
Hi @logaritym 

Thanks for your suggestion, we will add it to our Integration list.

Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
