### ISSUE TITLE
Possibility to add widgets to blocks

### ISSUE THREAD

**Issue by jlconsult** [ThemeFuse/Brizy#24]
Possibility to add widgets to blocks, now I only can add a sidebar

**Comment by bagrinsergiu** [comment]
@jlconsult 

Hi,

We plan to add it soon. It is in our To Do List.

Thanks for reporting.
Sergiu

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/guXtVHgE/68-wp-widget

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
