### ISSUE TITLE
Does not edit but creates a new page.

### ISSUE THREAD

**Issue by Maxim850** [ThemeFuse/Brizy#241]
After I changed the title, the editor stopped seeing the contents of the page.
https://youtu.be/Oqfumqb2ymw
The problem with displaying the title in the browser tab is also relevant. Instead of the title, the address is still displayed.

**Comment by Maxim850** [comment]
After updating the plugin to version 1.0.17, when trying to open the main ladder, the editor again suggested creating a new page. When the editor was closed, a white blank screen began to appear on the page.

**Comment by Maxim850** [comment]
If you need more information, I'm ready to provide.

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by Maxim850** [comment]
I hope I did everything right. The message sent.

**Comment by Maxim850** [comment]
He sent the updated data.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
