### ISSUE TITLE
Button corner in mobile view

### ISSUE THREAD

**Issue by nhanledev** [ThemeFuse/Brizy#242]
Hello.

The button corner in mobile view does not inherit the option that was set on desktop. I tried to change the corner to zero to make the square button BUT in mobile view it was reset to the default round corner.

**Comment by marcellefter** [comment]
Hi @nhanledev !

We're working on this issue and will be fixed in the next updates. I’m closing this issue to keep the issue database slim. Feel free to re-open if you need more details.

Thank you for understanding!
Marcel
