### ISSUE TITLE
Right-click functionality

### ISSUE THREAD

**Issue by sunnyt7** [ThemeFuse/Brizy#247]
I just tried out the new Elementor 2.1 beta, and the right click functionality is really nice to use. Makes it easier to edit/delete sections, and then being able to copy both style and full on widgets or sections is super handy as well.

Having used it for even only a few minutes, it's hard to imagine going back to not having it. Would definitely recommend as a need-to-have as opposed to a nice-to-have!

![image](https://user-images.githubusercontent.com/5510344/41951500-297f6e0a-7999-11e8-83cd-5827a6138db6.png)

**Comment by nhanle92** [comment]
I remember that they have discussed about the right click functionality because there are people who work on touchscreen like the iPad will not be able to reach the right-click menu. But I hope they soon will have this feature too!

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/lztAHGLE/28-element-styles-copy-paste

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
