### ISSUE TITLE
Media queries for mobile and tablets

### ISSUE THREAD

**Issue by jlconsult** [ThemeFuse/Brizy#25]
Please add the posibilty to change the layout (with media queries)at several breakpoints

**Comment by bagrinsergiu** [comment]
@jlconsult 

Thanks for letting us know, we are looking into it.

**Comment by bagrinsergiu** [comment]
Duplicate: https://github.com/ThemeFuse/Brizy/issues/21

**Comment by bagrinsergiu** [comment]
Hi @jlconsult 

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Thanks for reporting
Sergiu
