### ISSUE TITLE
Too much space at top.

### ISSUE THREAD

**Issue by Jonboix** [ThemeFuse/Brizy#251]
I used the pre-built slider block in the headr section. No matter how hard I try I cannot move my visuals any closer to the top. There is a large blank area.
The opening frame looks fine; but, the other blocks are low on desktop and mobile.

http://jonbo.com/home-page/about-me/

**Comment by bagrinsergiu** [comment]
Hi 

Use advanced settings for this case: http://dl3.joxi.net/drive/2018/07/03/0028/0732/1860316/16/888fc9484c.jpg

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by Jonboix** [comment]
Thank you.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
