### ISSUE TITLE
How to add many languages in Brizy?

### ISSUE THREAD

**Issue by arlindabd** [ThemeFuse/Brizy#252]
Hello my name is arlind, i need some help from you guys.I dont know how i can add many languages for my website in brizy(wordpress).Please help me.

**Comment by bagrinsergiu** [comment]
Hi Arlind

It is possible via a WP plugin Polilang or WPML. 

Polilang: https://wordpress.org/plugins/polylang/
WPML: https://wpml.org/purchase/?dr=email

Thank you!
Best Regards, Sergiu
