### ISSUE TITLE
Feature Request:  Upload custom icons into Brizy

### ISSUE THREAD

**Issue by kb08807** [ThemeFuse/Brizy#253]
I have a large set of custom icons in vector svg and eps format.  I'd like to be able to upload those svg files (or whatever other vector format is needed to make this feature work) into Brizy, and then be able to choose an icon from within that custom set in the same way you can choose "Transportation" or "Sports" icons within Brizy.  I have purchased the Pro version and would love for you to add this feature.  Thanks :-)

**Comment by bagrinsergiu** [comment]
Duplicate: https://github.com/ThemeFuse/Brizy/issues/35

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
