### ISSUE TITLE
Huge log files - How to deactivate

### ISSUE THREAD

**Issue by PeterHasitschka** [ThemeFuse/Brizy#254]
Since there is only a facebook (!!!) chat for communication on your homepage and (as most others in business) I don't own a facebook account in my company, I'll try it here.. 

My customer's database became extremely huge and had about 800M in the end.
This was caused by a table by your extension: wp_brizy_logs. It is constantly filled with json-data every few seconds!!! Thus it had about 550M until I truncated it.

![bildschirmfoto 2018-06-28 um 10 19 10](https://user-images.githubusercontent.com/7084114/42022157-c4b7be94-7abc-11e8-9267-b9a141ab04ef.png)

In your changelog I found the possibility to deactivate logging.
![bildschirmfoto 2018-06-28 um 10 20 16](https://user-images.githubusercontent.com/7084114/42022189-e8b6d3c0-7abc-11e8-9ac7-71db94573cf9.png)

Thus, I just updated to 1.0.18 using the wordpress backend. However there is no possibility to deactivate logging in the settings. Could you describe how to apply this setting, and why the database is permanently filled?
![bildschirmfoto 2018-06-28 um 10 21 26](https://user-images.githubusercontent.com/7084114/42022404-9018689a-7abd-11e8-8ac5-2e971a0ca8c7.png)

Thanks for your answer in advance!

**Comment by bagrinsergiu** [comment]
Hi Peter,

Deactivate/ Activate Brizy Plugin is the solution :) 

Can you confirm if it is working for you?

Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
