### ISSUE TITLE
Author Box

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#259]
Hi. It would be great if you have an author box. Sometimes we post material on the blog which must be credited to someone else, so it will be handy if there is an element in which we can add a picture and description of the actual author. Maybe we can save the author box and then choose it on another page from a dropdown or something.

**Comment by bagrinsergiu** [comment]
Hi, 

In last update ( 0.0.12 ) was added Author Box blocks for blog pages: 

1. https://jmp.sh/FxsfQsL
2. https://jmp.sh/c0OGFc3
3. https://jmp.sh/Ce47Fs6
4. https://jmp.sh/hq1vfa9

Thanks for suggestion
Sergiu
