### ISSUE TITLE
wordpress menu behaviour at mobile and tablets

### ISSUE THREAD

**Issue by jlconsult** [ThemeFuse/Brizy#26]
Wordpress menu behaviour for mobile and tablets.
At this moment the menu only shrinks, there no setting at breakpoints for the 'hamburger' menu icon and how this hamburger menu can be styled

**Comment by bagrinsergiu** [comment]
HI 

hamburger menu added in 1.0.20 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
