### ISSUE TITLE
Change image on hover

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#261]
I am not sure this will be easy to do, but it will be nice if you at least allow us to add some effects on hover (blurry, BW, etc).

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/fKZYNQOD/153-image-hover

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
