### ISSUE TITLE
White page in preview

### ISSUE THREAD

**Issue by orfeo1963** [ThemeFuse/Brizy#262]
Hi, I recently installed brizy plugin for wordpress.
I have no problem creating a page with the brizy editor, but when I press the preview button I'm presented with a blank page.
You can kindly help me.
Congratulations on the plugin ... beautiful

**Comment by laJim** [comment]
I have the same problem. However, this occurs only on my local server (tested both Desktopserver and Local by Flywheel). It works flawlessly on a live server.

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by Mariano215** [comment]
I'm having the same issue.  Visible in edit mode.  Blank in preview or server.  

I noticed it happens when I added a Wordpress short code section.

**Comment by mktunited** [comment]
I have the same issue here.
It happens at my flywheel test site with 
WP 4.9.7
Brizy  1.0.19 
I have no other plug ins only Brizy.

I literally install wp, brizy and modified sample page and saw preview. Then I go the white screen,
the brizy contents show in the brizy preview screen either wp template or brizy template. but actual page doesn't show anything.

**Comment by bagrinsergiu** [comment]
Hi

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
