### ISSUE TITLE
Doesn't Update/Save | Unable to upload images.

### ISSUE THREAD

**Issue by blueGecko921** [ThemeFuse/Brizy#263]
### **Doesn't Update/Save:**
I started to edit my home page with Brizy and finished, so I clicked the button labeled "Update" just to go to my site and see nothing changed. I have installed all the recommended plugins, pressed update on the WordPress end, and even changed my theme 3 different times just to find that nothing worked. I was wondering if anyone could help me? Thank you.
![capture1](https://user-images.githubusercontent.com/30154540/42130456-b29dc39a-7cb3-11e8-8a47-e0e7e0af025e.PNG)
The image above is what my site looks like.

### **Unable to upload images:**
I wanted to change my background image and clicked the button labeled "Background" then I went to upload the background of my choice just for it to freeze up on the loading screen for 10 minutes doing nothing.
![capture2](https://user-images.githubusercontent.com/30154540/42130461-e96fc74c-7cb3-11e8-878b-6ea239dfc3d2.PNG)
The image above is all that happens when I try to upload an image.

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
