### ISSUE TITLE
Images can not be loaded

### ISSUE THREAD

**Issue by i6tet** [ThemeFuse/Brizy#265]
hi
I can not upload my images from the media library.
After selecting the image, only the preloader of the download is visible .. And nothing more happens, the image is not added.
What could be the problem?
**UPD**
This is somehow connected with hosting.
On another hosting, everything works.

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
