### ISSUE TITLE
Add links to div-containers

### ISSUE THREAD

**Issue by marcosoldati** [ThemeFuse/Brizy#267]
I've create a container with some title, some image and some text. 
Now I want to create a link from the container box to some external web page. According to the support chat this is not possible. 
Of course I can create a link for each element in the box, but the white spaces between the elements are not clickable like this.

**Comment by bagrinsergiu** [comment]
Hi,

Thanks for your suggestion, we are looking into it.

Regards, Natalia

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/Ri0mrQ7s/152-column-add-links-to-div-containers

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
