### ISSUE TITLE
Icons and images not displayed on page.

### ISSUE THREAD

**Issue by jasper1986** [ThemeFuse/Brizy#268]
When I place images or icons on pages, they will not be displayed when I view the page.
Even the images and icons in the default template block don't work.
When I browse to the image url from the page source, I can view the images.
Strange thing, the background images do work also when changed to a custom image.

I've disabled all other plugins except Brizy and reinstalled Brizy but this didn't help.
All templates have the same issue.
Anyone knows how to fix this or what could be the problem?

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by jasper1986** [comment]
I don't use Facebook.
Other ways to communicate?

**Comment by bagrinsergiu** [comment]
Email: sergey.roxigo@gmail.com

**Comment by IamJAX** [comment]
Is this the issue with none SSL links added for images? I had similar issue and then noticed that image urls were http:// and so when viewing page over https://, these are not loaded since they were not secure content.

**Comment by bagrinsergiu** [comment]
Hi @IamJAX 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by jasper1986** [comment]
I've checked and my images urls are http://
How did you fix the issue?

**Comment by IamJAX** [comment]
I fixed it within minutes of noticing it.
