### ISSUE TITLE
Brizy Editor Not Working

### ISSUE THREAD

**Issue by huffakk** [ThemeFuse/Brizy#269]
Whenever I try to edit on a wordpress page and click on the "edit with brizy editor" it won't show up anything and I can't edit anything. What's the issue?

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by huffakk** [comment]
Will do! I just sent a chat over with my login regarding the issue! Thanks!

**Comment by markvguchte** [comment]
I'm having the same issue with my page (www.fixmob.co/education).  It's completely blank after to going to "back to wordpress editor" and then going back to editing with Brizy - none of the content pulls over to Brizy.   Please help

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
