### ISSUE TITLE
clickable images

### ISSUE THREAD

**Issue by krnkrn** [ThemeFuse/Brizy#273]
I love Brizy, thank you! I do have one question, I have images on my website, can I make them clickable? So they can open if people want to watch them enlarged?

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/jcGZmLYB/3-image-lightbox

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
