### ISSUE TITLE
Brizy stoped working

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#274]
In a new site with less than 10 plugins just stopped working. I press the edit with Brizy button and I get a blank white page with nothing to do.

Disabled all plugins and set theme to twenty seventeen but nothing. 
If you want to check the problem see the https://1pc.gr/wp-admin

User: demo
Pass: demo

**Comment by bagrinsergiu** [comment]
Hi 

Video Demo Link: https://jmp.sh/aW4gVMK

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by estraatios** [comment]
I know hot to operate the brizy builder. The thing is that it does not work. Please login with the info I gave you to see by yourself

**Comment by bagrinsergiu** [comment]
Can you give me more details? What is not working? In my video it works perfect on Edit mode + Prevew mode

**Comment by estraatios** [comment]
Sorry. Did not realize it was mine installation.

Now it is working. Did you do anything?
Close the issue. Thank you

**Comment by bagrinsergiu** [comment]
Nope. Nothing. Very strange.
