### ISSUE TITLE
Conflict with slider revolution plugin

### ISSUE THREAD

**Issue by desiment08** [ThemeFuse/Brizy#275]
When I'm trying to include slider revolution in brizy page, getting an error:

"Revolution Slider Error: You have some jquery.js library include that comes after the revolution files js include.
This includes make eliminates the revolution slider libraries, and make it not work.

To fix it you can:
1. In the Slider Settings -> Troubleshooting set option: Put JS Includes To Body option to true.
2. Find the double jquery.js include and remove it."

How can I solve this?
![untitled](https://user-images.githubusercontent.com/40837139/42289875-ba9495ae-7fdf-11e8-8e3a-29159037777b.png)

**Comment by desiment08** [comment]
Hello, any update?

**Comment by NataliaBB** [comment]
Revolution slider issue fixed.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
