### ISSUE TITLE
Spinning wheel when trying to edit a page

### ISSUE THREAD

**Issue by sapierce4** [ThemeFuse/Brizy#276]
When I open a page for editing and click "edit with Brizy", all I see is a spinning red, white, and blue wheel. The page never loads.
<img width="1259" alt="screen shot 2018-07-04 at 2 23 50 pm" src="https://user-images.githubusercontent.com/40837946/42290965-8ab53774-7f96-11e8-88e4-ffaa263d8d97.png">

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
Can you check if Autoptimize plugin is active? Disable and try again.

Thanks

**Comment by sapierce4** [comment]
Autoptimize only shows a white screen and Brizy never loads. I sent you login information via Facebook chat.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
