### ISSUE TITLE
Will there be functions in Brizy Pro  to make Quiz and Survey?

### ISSUE THREAD

**Issue by alex21x21** [ThemeFuse/Brizy#277]
Will there be functions in Brizy Pro  to make Quiz and Survey?

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://github.com/ThemeFuse/Brizy/issues/277

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
