### ISSUE TITLE
FacetWP, Pods Integration

### ISSUE THREAD

**Issue by davidmabelle** [ThemeFuse/Brizy#278]
Hoping to be able to do faceted search easily on Custom Post Types.

**Comment by bagrinsergiu** [comment]
Hi 

Added to Brizy Roadmap: https://trello.com/c/P0YwAYWJ/24-dynamic-content-pods

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
