### ISSUE TITLE
Theme doesn't load

### ISSUE THREAD

**Issue by mamichnya** [ThemeFuse/Brizy#279]
So, working in WP, I was able to install and edit pages with the page editor, but the Brizy template does not load, and the Brizy page editor does not show the default template. So, it looks like the Brizy template, but when I view the website, only the default template loads - and none of the pages I created w/the Brizy page editor. Further, when I tried to upload the Brizy theme template, I get this error:

Installing Theme from uploaded file: brizy.zip
Unpacking the package…
Installing the theme…
The package could not be installed. The theme is missing the style.css stylesheet.
Theme installation failed.

So, right now, I'd say Brizy fails.

**Comment by bagrinsergiu** [comment]
Hi,

Brizy is a WP Plugin not a Theme. Can you try again via Upload Plugin section?

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
