### ISSUE TITLE
Feature Request: Background Editing

### ISSUE THREAD

**Issue by dnnsjsk** [ThemeFuse/Brizy#28]
The shape dividers in Elementor are a great design tools. (see here: https://docs.elementor.com/article/207-shape-divider)

However, one is limited to given shapes. It would be awesome if Brizy had the option to add anchor points to a section backgrounds and modify it like in modern vector graphics applications. (curve etc.)

The possibilities would be endless.

**Comment by ash-f** [comment]
Nice. Shape divider is must have function for modern for page builders!

**Comment by DimiBaitanciuc** [comment]
It is and we'll do it. Since we just launched we have other top priorities right now, but shape dividers will be there in the coming months, no worries about it.

**Comment by ash-f** [comment]
Please make it shape background effect like BeaverBuilder 2.2.
It's not just a divider but background effect that can be laid  under page elements.
Even combination with gradient and using custom shape is possible.
https://www.youtube.com/watch?v=8UBIiydoc0U

**Comment by DimiBaitanciuc** [comment]
Excellent suggestions. We'll take a look and when we'll start working on the dividers we'll consider every possibility.

**Comment by EngageNow** [comment]
Since we look at other pagebuilders here, let me throw in an example on how ThriveThemes does this since the latest update: https://thrivethemes.com/fancy-dividers/ The great thing here is that its pretty simple and intuitive to match the colors of the dividers with the colors of the background sections they divide... Sweet! Please add something similar, "but the Brizy way" 😄

**Comment by DimiBaitanciuc** [comment]
Thanks for the link. We'll look it over.

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/fjQTSEGZ/16-block-shape-divider

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
