### ISSUE TITLE
Conflict with Microthemer Plugin

### ISSUE THREAD

**Issue by sebastianwebb** [ThemeFuse/Brizy#280]
Hi guys, 

I'm the author of Microthemer. A customer just reported a compatibility issue with Brizy. On further inspection, it looks like Brizy might be removing a jQuery extension I added using the following syntax, which I believe is standard: 

`$.fn.extend({add_overlay: function(options){...}});`

On pages where Brizy _hasn't_ been used, I can see my _add_overlay_ function on the main jQuery object. But on pages where Brizy has been used, it is absent. I will try to troubleshoot this properly tomorrow, to see if a fix can be implemented at the Microthemer end only. But thought it worth mentioning to you guys as this issue might affect a number of other plugins that extend jQuery. And so you could potentially resolve multiple issues by addressing this.

All the best,
Sebastian

**Comment by bagrinsergiu** [comment]
Hi Sebastian

Thanks for reporting.  I will be back with a reply.

Sergiu

**Comment by sebastianwebb** [comment]
I managed to implement a workaround by using jQuery() instead of $(). I'm not sure exactly what the interaction was here, I guess Brizy is affecting the $ reference somehow. But only partially, because $.fn.extend syntax can still be used to add the plugin. It just needs to be called with jQuery('body').add_overlay(). 

The issue was only happening when trying to edit a Brizy generated page when Brizy was NOT active. When Brizy was active inside Microthemer, things worked as usual. 

Just in case this info helps.

Cheers,
Sebastian

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
