### ISSUE TITLE
Theme Design suggestions

### ISSUE THREAD

**Issue by abbsinternationalservices** [ThemeFuse/Brizy#283]
I would like to mark my suggestion on the theme design.

I purchased Brizy pro, I don't know more about your theme designs but so far your block designs are awesome.
If you add a menu design like ( https://www.jellyfish.co.uk/ ) this one would be great. Also if you can play around with different menu styling options then it will be fantastic. So far I loved Brizy.

One more suggestion. If you can provide different image/video over lay styles like (http://www.haymarket.com/) ( https://www.jellyfish.co.uk/ ). I mean dot styles which applied over the video.

I hope Brizy is going to be the next generation WordPress page builder.
All the best

**Comment by bagrinsergiu** [comment]
Hi,

If you add a menu design like ( https://www.jellyfish.co.uk/ ) this one would be great. Also if you can play around with different menu styling options then it will be fantastic. So far I loved Brizy.

We plan this feature in pro version: https://trello.com/c/KiRpXuPM/46-element-menu-pro

---

One more suggestion. If you can provide different image/video over lay styles like (http://www.haymarket.com/) ( https://www.jellyfish.co.uk/ ). I mean dot styles which applied over the video.

https://trello.com/c/SKFm8nMx/9-video-element

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
