### ISSUE TITLE
Static homepage without standard wordpress header and footer?

### ISSUE THREAD

**Issue by ChrisK772000** [ThemeFuse/Brizy#284]
I just made an homepage with brizy, but when i set it as a static homepage it shows the standard header and footer of wordpress? how can i fix this.

**Comment by bagrinsergiu** [comment]
Hi @ChrisK772000 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Web Page: https://brizy.io

Thank you.
Sergiu

**Comment by ChrisK772000** [comment]
I already did, but no answer on the site!

**Comment by ChrisK772000** [comment]
@bagrinsergiu can u help me?

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
