### ISSUE TITLE
Custom Media Breakpoints

### ISSUE THREAD

**Issue by Raavail** [ThemeFuse/Brizy#286]
I was thinking about what could be a really look feature to incorporate into the builder.

And the ability to define custom breakpoints, for tablet and mobile will be extremely cool.

I was recently working on a site, and the break points defined by the theme and page builder were different.  So my header would snap into the mobile view a little sooner then the rest of the content on my page. 

This can be worked around of-course, but that got be thinking how this could be a really nice sort of advanced feature, it can maybe have settings global settings under the brizy tab in the WP admin area, and from here one could be able to set these values, which can then apply everywhere the builder works, even with dynamic content and headers and footers in the future.

**Comment by Raavail** [comment]
just found out that the new elementor release has added this feature. So its definitely doable and would a great addition to brizy as-well.

**Comment by black-eye** [comment]
+1

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/SgjBI1az/44-responsive-breakpoint

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
