### ISSUE TITLE
Design inspiration

### ISSUE THREAD

**Issue by sunnyt7** [ThemeFuse/Brizy#288]
I know this is a 'way down the road kind of thing', but thought I would bring up an example of who is handling pre-made layouts for their page builder very well.

Divi has some amazingly modern layouts: https://www.elegantthemes.com/layouts/

And they don't just take an existing layout and make slight layout/color adjustments. Each layout is really thorough, and serves different use-cases. They actually also serve as a learning tool, as they incorporate some neat styling tricks.

They then document some of these tricks on their blog. For example: https://www.elegantthemes.com/blog/divi-resources/how-to-design-abstract-lines-to-frame-your-content-in-divi

What's amazing, is that they've built a team of designers to be able to release 2 of these layouts per week: https://www.elegantthemes.com/blog/theme-releases/design-initiative-2-0

So yeah, just thought I'd share this as an example of what I feel a competitor is doing right. They're making a web designer's life a heck of a lot easier by releasing these amazing pre-made layouts, but then also making them a better designer along the way. To me, that is a huge value prop.

**Comment by bagrinsergiu** [comment]
Hi @sunnyt7 

We added 50+ pages and 80+ blocks in pro version in (0.0.11, 0.0.12) Also we plan to add 150+ new pages and a new kit soon. 

0.0.11: https://brizy.io/blog/brizy-pro-predesigned-pages-and-styles/
0.0.12: https://brizy.io/blog/premium-popups-and-blog-blocks/

I like the idea to document  some of these tricks.

I added this suggestion in our public roadmap: https://trello.com/c/aMrGFT2M/154-design-inspiration

Thanks for suggestions.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
