### ISSUE TITLE
Not Receiving Email From Form

### ISSUE THREAD

**Issue by Supo65** [ThemeFuse/Brizy#289]
Hi, is anyone else having this issue. Have my form connected ok and the form gives me a message sent successfully but I never receive the email. Not sure where to check next. Never had much success with receiving the WP mail. Thanks.

**Comment by bagrinsergiu** [comment]
Hi

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Web Page: https://brizy.io

Thank you.
Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
