### ISSUE TITLE
Schema.org support

### ISSUE THREAD

**Issue by tinsterman** [ThemeFuse/Brizy#290]
Can you please add schema.org to your code.

**Comment by quantumleap33** [comment]
+1 for that. 

Schema markup is code (semantic vocabulary) that you put on your website to help the search engines return more informative results for users. I believe it's necessary for Brizy to be injecting schema markup code to the various elements to help with the SEO aspect of things!

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/jJV7jDoZ/156-schemaorg-support

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
