### ISSUE TITLE
AMP support

### ISSUE THREAD

**Issue by tinsterman** [ThemeFuse/Brizy#292]
Any plans for developing an AMP version?

**Comment by NataliaBB** [comment]
Hi @tinsterman!

Thanks for your suggestion. It is in our to do list already ;) 

Regards, Natalia

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/7l0jkbTW/59-amp

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
