### ISSUE TITLE
Need "Default" Color Reset Button for Color Palette

### ISSUE THREAD

**Issue by iFillip** [ThemeFuse/Brizy#294]
Please provide a "default" button that will "reset" the color palette to its original colors. As it is now, once I change the colors there's no going back. Even hitting the little "revision" button does nothing. 
You folks are doing great. Thank you for your time and continued development.

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/ucZLm2Nm/87-reset-button-for-color-palette

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
