### ISSUE TITLE
Provide a Way to Import / Export Color Palettes

### ISSUE THREAD

**Issue by iFillip** [ThemeFuse/Brizy#295]
Would be nice to have an option to save/import/export color palette. Each site uses different colours. So Brizy default colours aren't always relevant for the majority of the sites.

**Comment by NataliaBB** [comment]
Hi @iFillip 
New Palette colour is added to our new features list. Here are some images of how it will look like: 
![33670705-56713450-daae-11e7-8f22-4c5bbc1a090d](https://user-images.githubusercontent.com/36154919/42369190-e0dabaee-8111-11e8-93b7-9a899e88f4b2.jpg)
![33670716-5e6e933c-daae-11e7-82ca-cc5f3bff2609](https://user-images.githubusercontent.com/36154919/42369213-f5c634c4-8111-11e8-8368-1ca9ce419f84.jpg)
![33670899-d2479c04-daae-11e7-8620-4bcb83cd4558](https://user-images.githubusercontent.com/36154919/42369247-13ca1dc8-8112-11e8-8f3d-72cf9e85392d.png)

Natalia

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/tcpr0V6i/79-styles-import-export

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
