### ISSUE TITLE
If you add SAVE TO HTML to the Pro Edition I have about a dozen buyers

### ISSUE THREAD

**Issue by jbsurveyer** [ThemeFuse/Brizy#297]
I just went to a javaScript Meetup in Toronto and among 30++ attendees there was great interest in creating SPAs with Brizy and more ample Code widget. The key reuirement: Ability to Save to HTML

**Comment by alisarfraz** [comment]
This is a brilliant suggestion. I am in for this too.

**Comment by davidmabelle** [comment]
Would love to use Brizy as an app builder.

**Comment by JayOkey** [comment]
I've already purchased the Pro version but I love this idea.

**Comment by DimiBaitanciuc** [comment]
Thanks, we'll look into it.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/P7fCwP1T/157-save-to-html

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
