### ISSUE TITLE
Editing any page with Brizy  not working

### ISSUE THREAD

**Issue by aemediainc** [ThemeFuse/Brizy#30]
The demo looked great so I thought I'd give it a try – says it works with all themes – but installing it and trying it in a blank/new WP site I can't get it to work, at all.

This is a brand new install, with no other plugins installed, and I've tried it with TwentySixteen and TwentySeventeen themes.

Working basic page https://terracorp.ca/ingersollgolf/test2/

After clicking "Edit with Brizy" https://terracorp.ca/ingersollgolf/sample-page/ it basically 404s and I can't get that page to do anything other than deleting it.

**Comment by bagrinsergiu** [comment]
@aemediainc 

Thanks for letting us know, we are looking into it.

**Comment by bagrinsergiu** [comment]
@aemediainc 

Can you give me WP credentials via Facebook Chat: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

or email: bagrin.sergiu@gmail.com

Thank you.
Sergiu
