### ISSUE TITLE
icons and photos not showing

### ISSUE THREAD

**Issue by owenmarcus** [ThemeFuse/Brizy#300]
We got your Pro version, but I didn’t want to wait, so I created a landing page using your free version. Wow, I am impressed. You have what I’ve been looking for. The ease of use then the results are impressive.
I have one problem, my icons and embedded pictures are not showing. They do on all my other pages.
Here’s the page: https://owenmarcus.com/emotional-leadership-coaching/

Can you help?
Thanks. Owen

**Comment by Rafei3** [comment]
Have same problems :( ?

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
