### ISSUE TITLE
Image size increasing when used.

### ISSUE THREAD

**Issue by shenickisland** [ThemeFuse/Brizy#301]
When images are used the size increases radically. For example, a 136kb image used a background image becomes a 399kb image in Brizy. The dimensions of the file stay the same so I can only assume the images are being recompressed badly.

This also happens with normal images blocks.

**Comment by shenickisland** [comment]
Thanks @bagrinsergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
