### ISSUE TITLE
Ability to add own chosen / selected icons

### ISSUE THREAD

**Issue by aamirtajalli** [ThemeFuse/Brizy#303]
Response of Dimitrie

Dimitrie Baitanciuc 

We have that on our list, of course, you'll be able to add your own icons in the future. It just we are focusing on other things right now and this feature doesn't have a high priority, but we'll get there.

Just a reminder for to do list.

**Comment by NataliaBB** [comment]
Hi @aamirtajalli 

Yes, this feature is still on our to do list :)

Natalia

**Comment by bagrinsergiu** [comment]
Added to our roadmap: https://trello.com/c/wrfhV9sj/7-image-svg-support

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
