### ISSUE TITLE
Just a question 

### ISSUE THREAD

**Issue by purewaterman** [ThemeFuse/Brizy#305]
Hello all, 

I have a client that wants a horizontal scrolling feature for the whole website implemented. Their visitors are mostly tablet users. I want to to make each page a slider but would to have a navigation that can move the slider forward or backwards as atop navigation. This works on Smart Slider 3 quite well with the ID's of each slider linked to a navigation button. Can this work with the slider function of Brizy?

**Comment by bagrinsergiu** [comment]
Hi 

We plan to add this feature in future. Right now it is not possible. 

Thanks for suggestion 
Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/c160BFmi/155-horizontal-scrolling-feature

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
