### ISSUE TITLE
Link Editor Jumps to Edit Text

### ISSUE THREAD

**Issue by willhousecreative** [ThemeFuse/Brizy#306]
Loving Brizy so far and eagerly awaiting the pro version.

I have noticed, when adding a link to text, that the link field jumps me out into the text itself (see screen grab).

![tel-links](https://user-images.githubusercontent.com/19369150/42467818-de9ad11c-8367-11e8-94e1-24d3a5005080.gif)

The issue seems to go away if I click in the URL field wait a second and then click again to get back into the URL field. After a second, that first click in the link field wants jump the cursor into the main text field. If I'm not careful it replaces what's in the text field.

**Comment by IamJAX** [comment]
I have also noticed this issue

**Comment by NataliaBB** [comment]
Hi @willhousecreative, @IamJAX,

Thanks for reporting this bug. We'll look into it asap.

Thank you
Natalia

**Comment by akwright** [comment]
Confirmed the bug is still occurring.

**Comment by bagrinsergiu** [comment]
Hi all,

Fixed (1.0.4): Cursor jumping when editing RichText url

Thanks for reporting 
Sergiu
