### ISSUE TITLE
Error when installing Brizy

### ISSUE THREAD

**Issue by Norwegianwoman** [ThemeFuse/Brizy#307]
Hi,

Try to install Brizy to Wordpress, but get error, missing the file `style.css.

How do I fix this ?

Thanks

Tone

**Comment by IamJAX** [comment]
Brizy is a wordpress plugin.  Based on the error you mentioned, it looks like you tried installing brizy as theme. Please try installing Brizy as plugin.

**Comment by NataliaBB** [comment]
Hi @Norwegianwoman! 

To install Brizy to WP, please follow these simple steps from our Youtube tutorial: https://www.youtube.com/watch?v=ohbiLLhrmSw 

Thanks, @IamJAX for the prompt reply. 

Natalia

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
