### ISSUE TITLE
image upload error

### ISSUE THREAD

**Issue by fatbuddha1** [ThemeFuse/Brizy#309]
Hey I'm having an issue with the brizy builder in wordpress. When I try to change or upload an image to a section there's no option to select an image in the media library, when I click on an image it just opens the file browser window. I've uninstalled it and tried everything to fix it. Anyone else having this issue?

See screenshot:
http://somup.com/cFiQ32VszB

**Comment by bagrinsergiu** [comment]
A different plugin bocked WP Library.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
