### ISSUE TITLE
It doesn't seem to work with Astra Theme transparent headers. Any ideas?

### ISSUE THREAD

**Issue by jfwag** [ThemeFuse/Brizy#31]
I cannot seem to change the color to transparent. any ideas? Also need to move photo up into header area.

**Comment by bagrinsergiu** [comment]
@jfwag 

Hi,

It is working fine like you can see in this screen: dl4.joxi.net/drive/2018/05/21/0028/0732/1860316/16/8dc7fecb06.jpg

Steps: 
1. Template: Change to Default Template: http://dl3.joxi.net/drive/2018/05/21/0028/0732/1860316/16/bd97028f61.jpg
2. No Sidebar: http://dl3.joxi.net/drive/2018/05/21/0028/0732/1860316/16/5ec9c65122.jpg
3. Layout: http://dl3.joxi.net/drive/2018/05/21/0028/0732/1860316/16/f8d8e5af4e.jpg
4. Enable Transparent Header: http://dl3.joxi.net/drive/2018/05/21/0028/0732/1860316/16/8a58746098.jpg

Thanks for reporting. However I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.
Sergiu
