### ISSUE TITLE
Slider Section in Safari Produces Extra Gap

### ISSUE THREAD

**Issue by willhousecreative** [ThemeFuse/Brizy#310]
Please see the screenshot: 
![slider-height-safari](https://user-images.githubusercontent.com/19369150/42480127-bb5831b2-8390-11e8-8f72-b5a6f0d9440e.jpg)

On Chrome the slider section looks great. But once I load it up in Safari there is a gap between the image and the dots. 

I was able to cut some of the space down by adjusting the padding in the settings of the section (see screenshot below) but there still is a sizable bottom gap. 

![slider-height-safari-after-adjusting-padding](https://user-images.githubusercontent.com/19369150/42480407-174dd26e-8392-11e8-96cb-fea9c58c2318.jpg)

**Comment by marcellefter** [comment]
Hi @willhousecreative !

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg
Link: https://brizy.io/

Or you can update the plugin to version 1.0.19 and check it again.

Thank you.
Marcel

**Comment by marcellefter** [comment]
Hi @willhousecreative !

This has been fixed and will be included in the next update. I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Marcel
