### ISSUE TITLE
Countdown Element Display Vertically in Preview/Live

### ISSUE THREAD

**Issue by pellissierjp** [ThemeFuse/Brizy#311]
When setting up the countdown element it displays perfectly in the page builder view, but when going into preview/live mode, the days, hours, minutes, seconds are all stacked vertically under each other.

![countdown element](https://user-images.githubusercontent.com/40877277/42488962-9fb01862-8408-11e8-906e-92c26d3eca15.PNG)

**Comment by NataliaBB** [comment]
Hi @pellissierjp!
Thanks for reporting this bug. Our team will look over this issue asap.

Regards, Natalia

**Comment by marcellefter** [comment]
Hi @pellissierjp 

This bug was fixed in version 1.0.19.
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thanks for suggestion
Marcel
