### ISSUE TITLE
Not able to set brizy page as homepage

### ISSUE THREAD

**Issue by geekysachintech** [ThemeFuse/Brizy#314]
Hey, I am not able to st brizy as homepage.

**Comment by NataliaBB** [comment]
Hi @geekysachintech 
Could you send us, please a message on our website chat? https://brizy.io/
![chat1](https://user-images.githubusercontent.com/36154919/42556375-0f78f268-84f4-11e8-89cb-8296fe369178.png) 
Thank you!
Natalia

**Comment by bagrinsergiu** [comment]
Hi

Sergiu from Brizy here.

1. Switch to Astra theme
2. Under Settings > Reading > A static page > Homepage select your page

https://jmp.sh/lY9yyHZ

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
