### ISSUE TITLE
Possibility to send our custom content blocks to become part of Brizy's Library

### ISSUE THREAD

**Issue by elisandroborges** [ThemeFuse/Brizy#32]
Hi, there! It would be awesome if we had the choice on Brizy's website to be able to send our own custom content blocks so you (Brizy Developer) can add the best content blocks created by the users into Brizy's Content Library. Also, the choice to export/import layouts, sections, custom modules. 

I loved Brizy! It is an amazing page builder and will be even greater!

Thank you!

**Comment by DimiBaitanciuc** [comment]
Hey, this is a very interesting idea. We had something similar in mind later down the line. We'll discuss it with @bagrinsergiu our developer team leader and see what can be done about it.

**Comment by elisandroborges** [comment]
Great! Thank you, Dimi!

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/MaJjIRBW/98-community-created-blocks

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
