### ISSUE TITLE
Color Palette

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#320]
Please, add more colors to the color palette, explain which color to which element is associated, and then let us rearrange the colors. Also, let us save color palettes.

**Comment by bagrinsergiu** [comment]
Thanks for suggestion. 

Duplicate: https://github.com/ThemeFuse/Brizy/issues/184
Duplicate: https://github.com/ThemeFuse/Brizy/issues/295

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by logaritym** [comment]
It is pretty much the same thing, but some people have been assigning saved colors for elements which were not the elements linked to these colors. For example, I have been assigning the second and third squares to text elements. Later on I realized that by default, you are assigning the 5th (or 6th?) square to text elements. So I am actually building upon these suggestions and asking to let us choose which element gets which color by default.

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/eKZUFTer/88-more-color-palletes

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
