### ISSUE TITLE
An error happened while trying to display this block

### ISSUE THREAD

**Issue by yossa2045** [ThemeFuse/Brizy#321]
#Help me please an error to edit my website.
"An error happened while trying to display this block
You canopen an issueorremove this block."
![error](https://user-images.githubusercontent.com/41146257/42623273-a423f824-85ec-11e8-9d89-db076e126835.JPG)

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by ouadielim** [comment]
I have the exact same issue. I'm on Localhost with a custom "underscores_" theme.
When switching to Twenty-seventeen or another WP theme, the plugin starts working.

Is there a setting that needs to be set to start using the plugin on a blank theme?

**Comment by leifstenfeldt** [comment]
Same for me. Not even a blank block is working :-(

**Comment by ouadielim** [comment]
Make sure jQuery is loaded in the head section of your theme

**Comment by Supo65** [comment]
I tried your update and that didn't work. This totally sucks if a new wordpress install has to be made for it to work again.

**Comment by Supo65** [comment]
@ouadielim I'm not sure what jQuery script should be in the header can you elaborate further. Thanks.

**Comment by bagrinsergiu** [comment]
Hi @Supo65 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
The same issue can be 10-20 different bugs ( different themes, plugin, servers, php versions ). I'm here to solve this issue

Thanks
Sergiu

**Comment by bagrinsergiu** [comment]
Hi @erikallkelly ,

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
