### ISSUE TITLE
Keep it simple

### ISSUE THREAD

**Issue by ianstudio** [ThemeFuse/Brizy#323]
**Keep the builder simple.** Elementor is great for example but already way too complex for "average/lambda" users, you "could/should/may want to" fill the gap and be a sort of WIX-killer !! And thus something I can sell to clients who "want to manage their own site".. They all say that and never do ultimately.. Most people are much less geeky than they think they are, they can barely remember their Gmail password ;0)

**Comment by bagrinsergiu** [comment]
Hi 

ok ok Can i close this issue?

**Comment by ianstudio** [comment]
Sure as long as you keep it in mind :0)

**Comment by bagrinsergiu** [comment]
ok ok :)
