### ISSUE TITLE
My form is not working 

### ISSUE THREAD

**Issue by purewaterman** [ThemeFuse/Brizy#324]
Hi 
I added a form to a customers website. All went well 
only the form does not work. I connected the button 
to wordpress and the correct email address. 

When trying to submit the form, it say form not submitted

![screen shot 2018-07-12 at 15 29 33](https://user-images.githubusercontent.com/20480917/42639821-d79f6782-85e8-11e8-863c-4e03d9e4844e.png)

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
