### ISSUE TITLE
Is there a demo of the pro version?

### ISSUE THREAD

**Issue by bentalgad** [ThemeFuse/Brizy#327]
Sorry i am asking it here but you can't be contact without a facebook account and i really don't want to open one.

Is there a brizy pro demo? (or we suppose to pay 270$ without seeing the app before? :)

**Comment by cliffordp** [comment]
Pro is expected to be available/released in September, so it doesn't quite exist yet... but their site states a refund for lifetime Pro is available for up to 30 days after its release. So low risk in that sense.
