### ISSUE TITLE
"Back to WordPress Editor" will lose everything.

### ISSUE THREAD

**Issue by Emilybkk** [ThemeFuse/Brizy#329]
I head someone said this is know issue and is fixing but I not sure about that so I create issue here.

After finished design page and all update then we click **Back to WordPress** we will see the window below. Then If we click the **Back to WordPress Editor** we will lose everything when return to Brizy again. 

[https://youtu.be/zAOHeHeowgI](url)

![back-to-wp-editor](https://user-images.githubusercontent.com/13035541/42677950-8f25c860-86a7-11e8-91e2-9eba350f919d.png)

**Comment by DimiBaitanciuc** [comment]
Hi, yes we are looking into this. Thanks for letting us know.

**Comment by Emilybkk** [comment]
Good to know that. Can't wait for next updates!
