### ISSUE TITLE
adding video from library

### ISSUE THREAD

**Issue by vlapre** [ThemeFuse/Brizy#33]
...adding video from the library is not an option or will be?

**Comment by bagrinsergiu** [comment]
Hi, 

Right now we don't have it in our to doing list. Can you give me more details why you need to ocal not on Youtube for ex? 

Thanks
Sergiu

**Comment by vlapre** [comment]
background on homepage

**Comment by bagrinsergiu** [comment]
@vlapre 

Thank you for details. I added it to our to do list. I don't have a deadline for this future.

Sergiu

**Comment by NataliaBB** [comment]
Mutat in WP Library din Propuneri GitHub

**Comment by NataliaBB** [comment]
Mutat in WP Library din Propuneri GitHub

**Comment by PeterArt** [comment]
from a comment I put in Trello:
A cool use would be a short loop video that could be used as an animated header background or slider image. That would simple style to some web pages in my view.

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/roS1N0WS/32-video-from-wp-library

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by PG248** [comment]
It is more than just for video backgrounds.

YouTube restricted the way you can control overlays in the video:
- If you disable video controls you get a "Play on YouTube" overlay you cannot hide.
- There is always a badge of the YouTube user account and video title you cannot hide.

In addition some clients have a policy not to host their video content on YouTube for copyright reasons.

Thus for commercial usage Brezy needs an option to play video locally from the Wordpress media library or from other sources than YouTube or Vimeo.
