### ISSUE TITLE
Bouncing Animation Broken (BUG)

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#333]
The bouncing animation is broken. I have 6 elements in 1 row which I wanted to bounce, but they do not perform properly. Bounce twice, some of them bounce higher... very weird.

**Comment by logaritym** [comment]
Also for some images no matter how many times I adjust the bounce parameters, they always get reset to the default 1sec.

**Comment by logaritym** [comment]
Guys, there is no bug, sorry. I have become confused with the bouncing of the image and the bouncing of its container.

**Comment by logaritym** [comment]
I take it back. It is a bug, Brizy does not remember when I change the settings.

**Comment by andronic90** [comment]
Hi,
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
