### ISSUE TITLE
Request featured: Form field reorder

### ISSUE THREAD

**Issue by Emilybkk** [ThemeFuse/Brizy#336]
Would be truly intuitive if we able to reorder fields by drag and drop too.

**Comment by NataliaBB** [comment]
Hey @Emilybkk 
Thanks for your suggestion. We will look into it.

Best Regards, Natalia

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/9HrtnkFu/130-dnd-for-tabs-accordions-form-fileds

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
