### ISSUE TITLE
Copy and paste styles

### ISSUE THREAD

**Issue by cmbc58** [ThemeFuse/Brizy#338]
These have been massive improvements to Divi and Elementor. Without these features Brizy will always lag behind those two well established page builders. If Brizy can keep up with and even over-take what those two have been doing recently, then it will rule the WordPress world!! Still very hopeful for the Autumn Pro version. A road map of what is in the pipeline would ease frustration and keep our spirits up!

**Comment by NataliaBB** [comment]
Ben,
A roadmap will come very soon, we hope the next few days. Please follow our FB community and our blog, we will share the link there. 
Link to the community: https://www.facebook.com/groups/brizy/
Link to our blog: https://brizy.io/blog/ 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hey @cmbc58! 
Here we are: https://trello.com/b/3OtE8BCR/brizy-public-roadmap 

I meant a few hours  :) 
Regards, Natalia

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/lztAHGLE/28-element-styles-copy-paste

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
