### ISSUE TITLE
Save custom element

### ISSUE THREAD

**Issue by cmbc58** [ThemeFuse/Brizy#339]
Feature request: It would be brilliant if you could save an 'element' as well as a 'block'. The you could build up your site with your own custom made elements and blocks.

It would also be much better if you could edit the names of the 'saved/favorited' blocks and elements. (I think you are working on making the thumbnails actually look like the blocks they are thumbnails of. (Without this building up a block or element library of ones own is going to very difficult to manage - if not impossible.)

Keep up the good work!!

**Comment by NataliaBB** [comment]
Hey Ben!
Yes, the save element option is in our to do list, and we will work on it after Pro launch.

Thanks for your interest in our builder ;)
Regards, Natalia

**Comment by bagrinsergiu** [comment]
Hi @John-Henrique 

I'm not sure but i suppose it will be free.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/WMnOq9UR/173-symbols

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
