### ISSUE TITLE
Visibility on Mobile/Desktop

### ISSUE THREAD

**Issue by bergomel** [ThemeFuse/Brizy#34]
I created two separate blocks for the header, but I can't these blocks from mobile/desktop view. I set:

- On the _mobile_ block (on Desktop view): Setting > More Setting > Advanced > Show on Desktop > Off
- On the _desktop_ block (on Mobile view): Enable on Mobile > Off

Both of them still show up on both views

**Comment by bagrinsergiu** [comment]
@bergomel 

Sorry for this issue. It will be fixed in 4-5 days. 

Thanks for reporting.

Sergiu

**Comment by marcellefter** [comment]
This has been fixed and will be included in the next update
