### ISSUE TITLE
Elements overlap in tablet mode or when window is shrinked

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#340]
When I shrink the window width-wise, some elements do not adjust properly and end up on top of each other (buttons for example).

**Comment by NataliaBB** [comment]
Hey @logaritym 
Please, send us a screenshot on our website chat, Link: https://brizy.io/ 
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
