### ISSUE TITLE
Hover Over Effects

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#341]
It will be great if you can add some hover over effects for text and image elements. Maybe filters, saturation, brightness, etc...

**Comment by NataliaBB** [comment]
Hi @logaritym 
These features will come in soon, within the next few updates.

Regards, Natalia

**Comment by jamaalhassan** [comment]
### **i hope we get something like this even better one  i know already been asked.**
![ezgif com-resize](https://user-images.githubusercontent.com/43518055/45929475-43284d80-bf4a-11e8-867d-abb52e80af66.gif)

**Comment by bagrinsergiu** [comment]
Hi all

@logaritym - Thanks for suggestion. Filters was added in 0.0.7 Pro version: https://brizy.io/blog/brizy-pro-block-shape-dividers/

@jamaalhassan 

I added this suggestion in our public roadmap: https://trello.com/c/hQS1eVSl/162-section-row-column-hover-styles-link-properties

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
