### ISSUE TITLE
Nothing showing up on my page

### ISSUE THREAD

**Issue by Supo65** [ThemeFuse/Brizy#345]
Not sure whats going on with my page. When I try to edit my page now everything is gone. When I click preview though it shows ok.

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by Supo65** [comment]
You should have my login info, I gave it to you before. It looks like others are having this same issue.

**Comment by Supo65** [comment]
Brizy is completely not working I can't even create a new page without the error showing up. Getting totally frustrated and not happy with this plugin.

**Comment by bagrinsergiu** [comment]
@Supo65 - Can you disable all plugins and switch to default theme. I'm 100% it will work with this environment. 

Sorry but i don't know your facebook ID, github username does not help me too much.

Thanks

**Comment by Supo65** [comment]
Hello,

Yes, that seemed to have it working now where I can edit but are you saying I have to use the default theme and no plugins with it. If that’s the case this still sucks and I may need to try another builder.

I have a theme that I like and Brizy seems to have a problem with the plugins used. Nice plugin but shouldn’t be this difficult getting it to work especially since it was working fine before.

Don

**Comment by bagrinsergiu** [comment]
Hi Don,


I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
