### ISSUE TITLE
Homepage not loading after update

### ISSUE THREAD

**Issue by bossertandre** [ThemeFuse/Brizy#347]
My Homepage is not loading on 2 websites after update.

**Comment by bossertandre** [comment]
Somehow your newly added shadow feature is breaking elements done on a previous version of Brizy

**Comment by bossertandre** [comment]
Something is now returning a 500 error in page

Please fix ASAP

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
In 1.0.19 Images Resize was moved in WP from or cloud platform. Can you check image size on your pages ( IMG, and BG). I found a project with 6Mb image on BG.

**Comment by bagrinsergiu** [comment]
Hi 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
