### ISSUE TITLE
Reset button

### ISSUE THREAD

**Issue by cmbc58** [ThemeFuse/Brizy#349]
It would be excellent to have a 'reset button' on, for example, the 'More Settings' section. I know this can be achieved to some extent by exiting and using the 'Undo' button - but it would be really handy to have a reset option anywhere where the settings can be changed - so that you can QUICKLY go back to the default settings.

**Comment by NataliaBB** [comment]
Hi Ben!
Thanks for your suggestion! We added to our to do list.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
