### ISSUE TITLE
Support to SVG

### ISSUE THREAD

**Issue by bergomel** [ThemeFuse/Brizy#35]
I'd like to suggest you to support SVG, for both img and background-image.

**Comment by bagrinsergiu** [comment]
@bergomel 

Hi, 

I added it to our to do list. We don't have a deadline for this feature. Thanks for help.

Sergiu

**Comment by anandau** [comment]
+1 for SVG support. 
I think it should not wait for the release of PRO

**Comment by quantumleap33** [comment]
+1 for SVG support, must have feature nowadays!

**Comment by black-eye** [comment]
+1

**Comment by bagrinsergiu** [comment]
Added to our roadmap: https://trello.com/c/wrfhV9sj/7-image-svg-support

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by aalainn** [comment]
It's a musthave!
