### ISSUE TITLE
Not working with Microthemer

### ISSUE THREAD

**Issue by cowdar** [ThemeFuse/Brizy#350]
With the update it still is not working with Microthemer
https://themeover.com
I believe he has been in contact.
please can you work together to resolve this.

**Comment by NataliaBB** [comment]
Hey @cowdar!
Could you please send us a message via our website chat?
Link https://brizy.io/ 
Thank you! 
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
