### ISSUE TITLE
Photos not loading after recent uptade

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#352]
I just noticed that the photos are not loading after the last update, and I'm getting cannot find resources errors even though the images are in the media library and nothing has changed on the site.
Site: https://curiousprojects.com/
Brizy Version 1.0.19

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
In 1.0.19 Images Resize was moved in WP from or cloud platform. Can you check image size on your pages ( IMG, and BG). I found a project with 6Mb image on BG.

**Comment by curiousprojects** [comment]
The largest file size in the media library is:
File name: Webkits-Layout-1024x946.png
File type: image/png
Uploaded on: June 27, 2018
File size: 617 KB
Dimensions: 1024 × 946

Bill Franklin
Curious Projects Inc.
bill@curiousprojects.com

www.curiousprojects.com
613-967-2191

**Comment by bagrinsergiu** [comment]
Solved. Just saved page again.
