### ISSUE TITLE
Will you do  multi step forms in Brizy?

### ISSUE THREAD

**Issue by alex21x21** [ThemeFuse/Brizy#353]
Will you do a multi steps forms in Brizy?

**Comment by bagrinsergiu** [comment]
Hi

Maybe, but i'm not 100% sure right now. 

Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/SJcFPC1Y/35-form-integrations

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
