### ISSUE TITLE
[Feature Request] User-defined CSS/media breakpoints to allow content-based layout

### ISSUE THREAD

**Issue by drank** [ThemeFuse/Brizy#354]
This is a follow-up to a [discussion in the Facebook group](https://www.facebook.com/groups/brizy/permalink/270398873723992/?comment_id=270502443713635&reply_comment_id=275857116511501&comment_tracking=%7B%22tn%22%3A%22R%22%7D) and also an extension to the [Custom Media Breakpoints](https://github.com/ThemeFuse/Brizy/issues/286) request.

**Some short introduction**
When we are designing our layouts (whether it is mobile-first or desktop-first) we are always facing the challenge of how to configure our CSS (or media) breakpoints. We have no choice but to submit to what the page-builder provides and usually this is a set (2-3, Oxygen has 5) of pre-defined breakpoint values that are based on some common device sizes. This is good (simplicity) when you are a beginner but bad for our content - because we are constraining the responsive-ness of our content to a set of fixed sizes.

**There is a better way to approach though.**
I will not go into details, there are smarter people than me that already did this, so here are some articles:
- [Stop using device breakpoints](https://medium.com/simple-human/stop-using-device-breakpoints-b11a87e2625c)
- [Media Query-less Design, Content-based Breakpoints & Tweakpoints](http://dmolsen.com/2013/03/05/media-query-less-design-content-based-breakpoints-tweakpoints/)
- https://responsivedesign.is/strategy/page-layout/defining-breakpoints/

There is even more info on the topic if you search about content based layout or content based breakpoints.

**To the point**
One of the prerequisites in order to be able to do content based layout-ing with Brizy is to be able to define our breakpoints dynamically, while we are laying out our content. This means that **we need the ability to add/edit user-defined breakpoints lifting the current limit of 2**.
I stress on the ADD part because builders (guEss who I am rEfErring to) usually tend to only add the ability to edit the existing 2-3 ones and that will NOT unlock the power :).

In order to achieve the content based layout nirvana, we also need to have a good way to edit the CSS for separate elements (I don't see this in Brizy now) - this will allow for adding sub-container-specific breakpoints (tweakpoints in the 2nd article) but I am saying this only for the complete picture - let's focus this request on the main breakpoints for now.

**To the Brizy devs**: please take into consideration the competitive edge of implementing this feature. No page builder (AFAIK) has this implemented so far and IMHO whoever first does it will do a real breaktrough in how page builders are used for designing websites.

PS: Here is another article that presents a reason to have more than 2-3 breakpoints - [The 100% correct way to do CSS breakpoints](https://medium.freecodecamp.org/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862) - it is not about content based layout but nevertheless gives another reasoning for having multiple user-defined breakpoints.

**Comment by black-eye** [comment]
+1

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/SgjBI1az/44-responsive-breakpoint

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by drank** [comment]
@bagrinsergiu 

Thanks for putting this request to the roadmap!

I would just feedback that the image in the trello board is misleading a little bit - initially I thought (only looking at the image) that you are just meaning to allow editing only the 2 built-in breakpoints (Desktop and Mobile).

Anyway, as long as you implement what is in the text, everything is fine ;)
