### ISSUE TITLE
An error happened while trying to display this block You canopen an issueorremove this block

### ISSUE THREAD

**Issue by djwhalley** [ThemeFuse/Brizy#355]
Trying to add a block and getting this message with Brizy? 

An error happened while trying to display this block
You canopen an issueorremove this block

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by l2lwebdesigns** [comment]
Hi there, can you assist me on the same issue? I was troubleshooting and came around the same issue.

**Comment by bagrinsergiu** [comment]
Hi @l2lwebdesigns 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by vramanbala** [comment]
I am having this issue, I just downloaded this plugin.

**Comment by NataliaBB** [comment]
Hi @vramanbala!

Natalia here, Brizy team
It can be a server issue or a plugin conflict. 
Please send me a message via our Facebook chat and mention this issue inside, I would like to check this and fix it.

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
