### ISSUE TITLE
I think Brizy keeps reuploading my images

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#356]
I noticed that a lot of my images reappear in my media as copies. Is it possible that Brizy is the problem?

**Comment by logaritym** [comment]
It is definitely Brizy. Every time I add a saved block with an image inside, the image gets reuploaded in my library.

**Comment by NataliaBB** [comment]
Hey @logaritym 
Is it possible to send me a message via our website chat?
Thanks!

Natalia

**Comment by bagrinsergiu** [comment]
Hi

Sorry for the delay. This issue was solved in 1.0.40.

Thanks for reporting
Sergiu
