### ISSUE TITLE
JQMIGRATE: Migrate is installed, version 1.4.1

### ISSUE THREAD

**Issue by havequestions** [ThemeFuse/Brizy#358]
Hi, 
Just trying out an issue, but noticed multiple errors.
Can you please advise on multiple errors my https://truebrandstudio.com/services/ page generates
Thank you.
Lana

```
JQMIGRATE: Migrate is installed, version 1.4.1
89Error in event handler for (unknown): TypeError: Cannot read property 'step' of undefined
    at Function.mapStateToPros [as mapToProps] (<URL>)
    at r (<URL>)
    at p (<URL>)
    at a (<URL>)
    at <URL>
    at Object.run (<URL>)
    at p.onStateChange (<URL>)
    at <URL>
    at Store.replaceState (<URL>)
```

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by havequestions** [comment]
Hi, Sergiu
I created and a new page and so far it didn't give me any issues (errors). So, for now, I would say let's just not worry about it.
Thanks,
Lana

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
