### ISSUE TITLE
Feature Request: hooks

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#36]
Please add action/filter hooks.

i.e.
*content filter for all elements to replace/modify the output.
*query filter for loop elements to  replace/modify the query.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/pFm3iIg8/58-developer-api

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
