### ISSUE TITLE
Migrate not possible?

### ISSUE THREAD

**Issue by lindebjerg** [ThemeFuse/Brizy#360]
I have tried, more than one time, to migrate a small site with BackupBuddy. 
But it is not possible?
I get this Error all over the site: Warning: array_merge(): Argument #2 is not an array in /wp-content/plugins/brizy/editor/api/project.php on line 11

Please make it possible to migrate a site without Errors!

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
Hi

Fixed in 1.0.21. Can you confirm if it is working with last changes?

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thanks for reporting 
Sergiu
