### ISSUE TITLE
Suggestion : Image element should prompt to upload after drag to block.

### ISSUE THREAD

**Issue by Emilybkk** [ThemeFuse/Brizy#361]
When we drag the Image Element and drop it in block we have to click that element and then click again on the Image icon to able to upload image. I think these steps can cut down. When drop the Image Element in block it should immediately prompt to upload image. 

What do you guys think?

**Comment by NataliaBB** [comment]
Hi @Emilybkk!
Thanks for your suggestion, we will look into it. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
