### ISSUE TITLE
Brizy blank page after upload to server

### ISSUE THREAD

**Issue by CodeWavePro** [ThemeFuse/Brizy#364]
Hello.
I saved all my sections, uploaded site to my hosting. Then I had a page with broken elements like them had no styles, images and etc. When I checked my home page made with Brizy and click edit with Brizy I found a blank page.
This is not the first time I have this problem. One time it was OK, other times all was like this. I don't understand, what I must do to upload my local working site to my hosting. I can't understand what is wrong with me or with this editor.
P.S.: all background images have icon of broken, are not showed while editing, but all is fine checking web-page (checked on 2 websites)...

**Comment by Critick-rbs** [comment]
![error](https://user-images.githubusercontent.com/24782391/42962402-3694111e-8b9a-11e8-8aa1-015a320e2372.png)

**Comment by NataliaBB** [comment]
Hi Andrei @CodeWavePro 
Natalia here, Brizy team
Sorry for my late reply.
This is a Siteground issue and it can be fixed at your side.
If we did not discuss via our Facebook chat, please send me a short message and mention this issue inside #364

Thank you
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
