### ISSUE TITLE
Be Able to Add a Border Around the Icon Box

### ISSUE THREAD

**Issue by iFillip** [ThemeFuse/Brizy#366]
It would be nice if you kind folks would provide a way of adding a border around the Icon Box. Please include options for:
1. Border line: For example: solid, groove, dot, etc.
2. Border thickness
3. Changing the radius, making the square corners more rounded
4. Selecting Border colors. 
Thank you.

**Comment by NataliaBB** [comment]
Hi @iFillip 
Thanks for suggestions. 
All these items are in our to do list already.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
