### ISSUE TITLE
TypeError: (e.wp || e.parent.wp).media is not a function - WP Multisite, theme: Enfold

### ISSUE THREAD

**Issue by MilenFrom** [ThemeFuse/Brizy#367]
Hi Brizy team,

I am trying to use the builder in one of my projects.

However, each time I add a block this error pops up the console in the dev tools and I can't preview the blocks which makes the usage of the builder impossible.

![image](https://user-images.githubusercontent.com/14107346/43029253-83229a34-8c8d-11e8-8756-a8625ac8b6b7.png)

**Comment by NataliaBB** [comment]
HI @MilenFrom! 
Thanks for reporting this. Could you please send us a message via our chat? 
https://jumpshare.com/v/Gbd5r0022uaLGX5KQVlx 

Thank you!
Regards, Natalia

**Comment by MilenFrom** [comment]
Hi @NataliaBB,

Sure, I'll send you message through your chat on the website.
Should I continue to conversation here afterwards or we'll discuss this in the chat?

Regads,
Milen

**Comment by bagrinsergiu** [comment]
Hi

In last update 1.0.20 we added a fix for this issue. Can you confirm if it is working with last changes?

Thanks for reporting
Sergiu

**Comment by MilenFrom** [comment]
It's working with this fix.

Thank you!
