### ISSUE TITLE
full height option

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#37]
I see custom height option for sections but need "full height" option that most page builders have.

**Comment by DimiBaitanciuc** [comment]
Are we talking about this? http://joxi.ru/eAO608EUxpPJY2

**Comment by ash-f** [comment]
Thanks! I didn't noticed it somehow.

**Comment by DimiBaitanciuc** [comment]
No worries, I'll just close this one ... one enhancement is done, a ton to go ... :P :)))))))))
