### ISSUE TITLE
Brizy Page Builder. No HTML (H1,H2,H3,etc) tag using Heading Styles, just visual no good for SEO

### ISSUE THREAD

**Issue by Ravisi** [ThemeFuse/Brizy#370]
Hi, i was testing your page builder in wordpress, i just want to share with you that your page builder is not SEO friendly, and its very important for the users, the aplication is not taging correctly the HTML of the Headings (H1,H2,H3,etc..) a webpage without this can´t be well positioned by Google, if you don´t tell Google for wich Keywords you want to rank for.

**Comment by bagrinsergiu** [comment]
Hi Raul
Sergiu from Brizy here
It is possible to set HTML tags for Texts like you can see in this video

https://jumpshare.com/v/9vRwzW7rM3cB73ia1BVl

https://jumpshare.com/v/QX4EbnAOhzbZ9lhMIioc

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
