### ISSUE TITLE
Feature Request: Download Button Option

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#372]
In the Buttons settings, a new option that allows you to access the media library to select or upload a PDF (or any document).

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/lA4gJ3bA/53-download-button-option

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
