### ISSUE TITLE
[Feature Request] Gradient Support

### ISSUE THREAD

**Issue by sunnyt7** [ThemeFuse/Brizy#375]
Since I didn't see this on the roadmap, I thought I'd create it here just in case.

It is pretty essential for us to be able to use gradients anywhere that you're able to set a colour - especially row backgrounds, row overlays, and buttons. Bonus if you're able to use a gradient on text, icons, and image overlays.

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/Ls3RZZa2/61-element-gradient

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by sunnyt7** [comment]
Just wanted to add one thing here. I lot of modern gradients include 3 colours. It would nice to be able to make 3-colour gradients as opposed to just the two.
