### ISSUE TITLE
The content won't update

### ISSUE THREAD

**Issue by profatech** [ThemeFuse/Brizy#377]
After new update, when i create new content or a page, and click update content, just stuck in loop

![tempsnip](https://user-images.githubusercontent.com/17934057/43090301-4b55c394-8ea7-11e8-87b4-eeb294f95a1a.png)

**Comment by frodoux** [comment]
Same problem here! Very annoying. Glad to see I'm not the only one having this issue.

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by frodoux** [comment]
Brizy Version 1.0.20 did not fix the problem, we cannot create nor edit pages.

**Comment by ltphen** [comment]
Hello Me too i have the same problem . i can't save my page ... 

Please can they fix the bug . it's very urgent

**Comment by profatech** [comment]
Hi Itphen,They working on it.

**Comment by ltphen** [comment]
Ok thanks ! Waiting for the update 💯

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by profatech** [comment]
Hi Sergiu, it's working now 👍

**Comment by bagrinsergiu** [comment]
Hi @ltphen, @frodoux

In last update 1.0.20 we added a fix for this issue. Can you confirm if it is working with last changes?

Thanks for reporting
Sergiu

**Comment by ltphen** [comment]
Yeah Everyhing is right now .. wanna notice that in your wordpress configuration you have to allow the brizy site to be called from your own websites . if not you will always receive a 500 error while trying to save ressources that will send data from brizy to your wordpress page !

**Comment by frodoux** [comment]
It is working now, thanks for the quick fix. By the way, amazing customer service.

**Comment by PD06818** [comment]
I am having the same issue and running 1.0.20

**Comment by bagrinsergiu** [comment]
Hi @PD06818 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you.
Sergiu

**Comment by Gregoire34** [comment]
Hello @bagrinsergiu 

I have the same problem on my website. I can't update the pages with brizy (infinite looping....) :
![brizy pb](https://user-images.githubusercontent.com/44607164/47716238-611c5880-dc42-11e8-8cc4-f6daf95dab97.png)

- I have this version of brizy : Version 1.0.29
=> When I update to last version (1.0.41), I have error 500 problems.

Can you help me quick please. ??!!
I realy need tu update the content of my website !!

I am not on facebook, so how can I send you my WP credentials ?

Thx for your answer.

**Comment by PD06818** [comment]
Hi,

I just ended up going with a different website tool. This stuff doesn't work well. I was able to get it out of the loop by tricking it. Go back to the WP default editor, publish the updates after and then you may be able to get back into brizy to edit again and make changes. Brizy is just crappy in general - which is why i went with something else. Make sure you have up to the minute backups for each change you make with it! I've lost a lot of work by not having them.

**Comment by Freerideandy** [comment]
I have the same problem. I spent quiet a while now editing in brizy and really liked it to be honest until I found out it doesnt save the changes at all and is stuck in this loop when hitting the update button. 
I just wanted to redesign my personal website and i think it was the most inappropriate time i could have ever chosen with this Gutenberg Update... I hope I didn't spent the money for nothing for my new template that i wanted to edit with brizy. 
Can someone help me please...
I run Version 1.0.52 of brizy just updated wordpress to 5.0.1. and purchased the Envo Multipurpose Pro Theme...

**Comment by Freerideandy** [comment]
no one can help?

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
