### ISSUE TITLE
Give the option to toggle text hyphenation

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#378]
I noticed that text get's hyphenated automatically. It would be good to add an option in the Typography settings to activate/deactivate hyphanation. I believe, it should be deactivated by default. Currently, I would have to go add CSS to disable globally:

`.brz .brz-rich-text {
  -webkit-hyphens: none;
  -moz-hyphens: none;
  -ms-hyphens: none;
  hyphens: none;
}`

**Comment by chrisagon** [comment]
Hello,
I do not agree ! In french, the hyphenation must be activated by default. Actually on our page the hyphenation is desactivated and it is UGLY !!!

**Comment by bagrinsergiu** [comment]
Hi 

This has been fixed and will be included in the next update. (1.0.21) in ~ 20 hours

 I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Sergiu
