### ISSUE TITLE
Sticky Header disappeared on the HOME PAGE but appears on all other new pages. HELP

### ISSUE THREAD

**Issue by SGS17** [ThemeFuse/Brizy#380]

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
