### ISSUE TITLE
No images, bad align

### ISSUE THREAD

**Issue by CodeWavePro** [ThemeFuse/Brizy#383]
1. All images are showing broken img icon in img setting popup when editing. And I can see only white screen.
![err3](https://user-images.githubusercontent.com/24782391/43125513-f532794e-8f32-11e8-8ecd-ba3e39a9a4aa.png)

2. Main section main text align is center on edit page, but it goes left on preview. Section width is set to fixed, but on preview text goes in an emphasis to the left side of the screen.
![err1](https://user-images.githubusercontent.com/24782391/43125523-fb9ecae4-8f32-11e8-9628-ab78b89f9516.png)
![err2](https://user-images.githubusercontent.com/24782391/43125525-fbc69de4-8f32-11e8-8d77-a97b9ddde043.png)

And one more question. Please, can you tell me, seriously, will you ever fix bugs with page sections dissapearing after upload from local server, or I'm just losing days and weeks of my time, working with your builder and waiting for support answers and problems solving?

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me mode details. How can i reproduce this issue. 

Migration in 1.0.19 is tested with 

1. Duplicator 
2. All in one Migration  

Thanks

**Comment by Critick-rbs** [comment]
Align problem was solved by re-installing Brizy. Problem with broken images and white screens while editing is the same.

I'm uploading my websites by ftp, importing DB in phpMyAdmin. So, I must uploading my website to web only by this plugins? I can not upload it the normal way by importing db & files? Sorry, but I don't think that it's the best solution...

**Comment by Critick-rbs** [comment]
Just after the update, some styles have stopped working! On the editing page, they remain the same, and on the preview differ even after re-saving! Are you f*****g kidding me?!!?!? 

BG images shifted upwards, when parallax animation is set. Parallax disappeared:
![err1](https://user-images.githubusercontent.com/24782391/43149099-5a946f36-8f6f-11e8-8bc1-981d43f44ab2.png)
![err3](https://user-images.githubusercontent.com/24782391/43149101-5abfaaa2-8f6f-11e8-83a2-b0d89391dcc7.png)

Buttons changed their colors. I change colors, delete the button and do a new one - bad styles remain on the preview.:
![err2](https://user-images.githubusercontent.com/24782391/43149167-7a6ef966-8f6f-11e8-8adf-96f1de2b4965.png)

Icons changed their colors and size. I change colors, delete the icon (or even section) and do a new one - bad styles remain on the preview:
![err4](https://user-images.githubusercontent.com/24782391/43149184-882d5fd4-8f6f-11e8-8ace-1eec36f3bda1.png)

So, you know who you are. Goodbye!

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
