### ISSUE TITLE
Brizy PHP 7.2 Compatibility Warnings

### ISSUE THREAD

**Issue by andrew-lof** [ThemeFuse/Brizy#385]
I used a PHP 7 Compatibility Plugin to run an audit on my new site using Brizy. It passed for PHP both  versions 7.0 and 7.1 but for PHP 7.2. it had no errors but it did have a few warnings.

Plugin:
https://wordpress.org/plugins/php-compatibility-checker/

My audit results are below: 

FILE: /nas/content/live/corporateweb/wp-content/plugins/brizy/vendor/twig/twig/lib/Twig/Compiler.php
----------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------------------------------------
 218 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
----------------------------------------------------------------------------------------------------

FILE: /nas/content/live/corporateweb/wp-content/plugins/brizy/vendor/twig/twig/lib/Twig/Lexer.php
-------------------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
-------------------------------------------------------------------------------------------------
 87 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
 91 | WARNING | INI directive 'mbstring.func_overload' is deprecated since PHP 7.2
-------------------------------------------------------------------------------------------------

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
