### ISSUE TITLE
brizy won't run with expires headers active

### ISSUE THREAD

**Issue by bruisend** [ThemeFuse/Brizy#386]
i've found an issue that caused brizy not to load. i when i use Browser caching in htaccess brizy does not load. when without brizy works fine. seems brizy is behaving like a browser (editable) and finds conflict with the htaccess expire times. 
i use Webarx for site protection and had the code pasted in the .htaccess area in webarx plugin settings

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
