### ISSUE TITLE
Brizy ignores global SSL Settings

### ISSUE THREAD

**Issue by chr1s1** [ThemeFuse/Brizy#391]
Hi, 

this could be setting issue on my site, but I wanted to write it down here to see if others have the same issue. 

I am using Lets encrypt and enforce SSL in the host config of my bitnami instance. On my "regular" wordpress pages, if I enter the url without https (http / www) I will get redirected to the SSL version (https://www.) for the pages I created with brizy this is completely ignored. I can access the page using anything. This leads to duplicate content in google. :( 

Any idea how I can solve this?

Best
Chris

**Comment by chr1s1** [comment]
Contacted you.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
