### ISSUE TITLE
Feature Request - CPT w/ Custom Fields Support

### ISSUE THREAD

**Issue by lwoods** [ThemeFuse/Brizy#392]
I purchased the lifetime Pro version and HOPE that it supports CPT's with custom fields---in Singles and Archives.  This is what is lacking in other page builders. And you don't have to support all of the CPT plugins. Pick one. I would recommend a simple CPT builder and ACF (not affiliated), but you could choose Pods (too complex), etc. This will make Brizy the first choice of developers.

**Comment by bagrinsergiu** [comment]
Thanks for suggestions.

Brizy Roadmap Links: 

1/ WP - https://trello.com/c/YPEX4YQW/20-dynamic-content-wordpress
2/ ACF - https://trello.com/c/4VaFYhaN/22-dynamic-content-acf
3/ Woo - https://trello.com/c/kjqKYGtd/21-dynamic-content-woocommerce
4/ Toolset - https://trello.com/c/znNBME0W/23-dynamic-content-toolset
5/ Pods - https://trello.com/c/P0YwAYWJ/24-dynamic-content-pods

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
