### ISSUE TITLE
Exporting Page/Post with blocks/style/layout

### ISSUE THREAD

**Issue by peleroberts** [ThemeFuse/Brizy#393]
Ability to export (download) page or post style, blocks setup to another page on the same site or another site which has brizy installed.  Though free and pro options must be respected in the sense that you can export pro options to a pro enabled brizy only.

**Comment by bagrinsergiu** [comment]
Brizy Roadmap 

Import/ Export for:

1. Page/Post: https://trello.com/c/xYQB0C04/77-export-import-for-demos
2. Style - https://trello.com/c/tcpr0V6i/79-styles-import-export

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by peleroberts** [comment]
Nope that's perfectly fine. In fact that is my fault for not spotting that on the roadmap.  Keep up the good work. 

Thanks
