### ISSUE TITLE
[Feature Request] Custom CSS

### ISSUE THREAD

**Issue by sunnyt7** [ThemeFuse/Brizy#398]
As I believe the 'Custom Styles' card is something different, please let us be able to set custom CSS for the page. Use this all the time.

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/AFOkANLg/74-custom-css

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
