### ISSUE TITLE
email

### ISSUE THREAD

**Issue by joelmwasserman** [ThemeFuse/Brizy#4]
for some reason the form is not working...do i need to set something up?

https://www.dropbox.com/s/wj12748ovm46fyx/Screenshot%202018-04-30%2023.23.19.png?dl=0

**Comment by DimiBaitanciuc** [comment]
Thanks for letting us know, we are looking into it.

**Comment by bagrinsergiu** [comment]
Hi 

This has been fixed and will be included in the next update (1.0.12), thanks for reporting.

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Sergiu

**Comment by ASAPHAANING** [comment]
Same issue here. using 1.0.15
