### ISSUE TITLE
No Facebook account

### ISSUE THREAD

**Issue by rayedo** [ThemeFuse/Brizy#405]
Pardon me if this has been address, but I've chosen for obvious reason to delete my Facebook account and will not be signing up for another. I've paid for a Pro account, but now find out that the only way to contact any of these people is thru FB Messenger. Seems really lame. They either need to get another way for people to contact them or make that clear before people sign up.

ray

**Comment by badcat** [comment]
Agreed - perhaps something like Slack or Discord could work?

**Comment by rayedo** [comment]
I think the overall preference, at this point, would be Telegram. They would just need to set up a corp account and post news etc. Don't understand why this hasn't happened. Anyone with any respect about their security or privacy has dumped FB. It's a messaging system for grandmothers, not serious companies. They're showing their age here. This is a five minute fix. I'll be asking for a refund if something doesn't happen quickly.

**Comment by NataliaBB** [comment]
Hey @rayedo and @badcat 

FB Messenger is a temporary solution.  

I added this suggestion in our public roadmap: https://trello.com/c/tSBPpXQq/81-customer-service-channels 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you! 
Best Regards, Natalia
