### ISSUE TITLE
IDEA: Tweet This Quote Box

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#41]
An element to add quotes with a tweet button would be really cool. There are some example that can be found if you search for TweetDis. (I didn't want to link to them in your GIT)

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/vY7dMSc5/96-others

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
