### ISSUE TITLE
Element Customization Settings Hides the Element.

### ISSUE THREAD

**Issue by sshobhi776** [ThemeFuse/Brizy#410]
Hi,

I was customizing a button and giving some padding for space from the right side but when the Customization settings open, I can't see the element because the "Setting box" hides the button and I can't see what I am doing (Means how much padding is sufficient). I have to go back check it.

![element hiding issues](https://user-images.githubusercontent.com/41860320/43365702-51e90b02-934e-11e8-95e7-5024fbc80a34.png)

The same issue is for the left side section, If I dragging an element in the left section then element box hides the space where I decided to drag the element and I have to drag it any other place and then have to move the element at the right place. 
![element issues](https://user-images.githubusercontent.com/41860320/43365710-89420892-934e-11e8-8efe-406f89fbe186.png)

Here If you can consider moving the Setting box anywhere on the page or put all the Element customization box or "New Element Box" anywhere bottom of the page then it would be very easy to navigate and access all the settings and new elements without overlapping the existing section or elements.

Thank you!

**Comment by Bert0440** [comment]
Just wanted to add that I noticed the same thing while using the text editor.  It covers the element you want to change.  Not sure what would be the solution,    Heres a pic just for reference.

![brizy1](https://user-images.githubusercontent.com/41208967/43436078-dda2f42a-9450-11e8-85f2-86c4e4b64679.PNG)

Trying to edit the headling, or any element get covered

![brizy2](https://user-images.githubusercontent.com/41208967/43436111-0c96dcce-9451-11e8-99d9-2126db348f7c.PNG)

Everything is looking really great so far, but obviously this needs a tweaking..  
keep up the incredible work!

**Comment by Bert0440** [comment]
Just want to add that on some other pics and elements  the text editor appears above the element being edited.  (which is perfect)

I knew that it seemed funny that it was covering the element, because i don't remember Brizy doing that before..  maybe its just a temporary bug , so yea I guess it most likely a glitch rather than a design flaw.

**Comment by sshobhi776** [comment]
Hi again,

You can check "Beaver Builder" for reference to find out the solution.

They have an option to Minimize and Move the Element and Customization Box.

Thank you.

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/kwt8FbIK/95-settings-hides-the-element

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
