### ISSUE TITLE
Error Form

### ISSUE THREAD

**Issue by panalc** [ThemeFuse/Brizy#411]
Please take a test on this form and see how the error is.

the form created on the site does not send the data to my configured email on the site.
https://fabriciopaniago.com.br/consultoria

**Comment by bagrinsergiu** [comment]
Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you.
Sergiu
