### ISSUE TITLE
[Feature Request] Column Reordering

### ISSUE THREAD

**Issue by JayOkey** [ThemeFuse/Brizy#414]
I would love to be able to reorder columns on for different screen sizes. A familiar pattern in web design is to have alternating rows, having an image in the first column then text in the second column then on the next row having text in the first column and an image in the second column. The pattern works well on a desktop but we need the ability to switch the ordering on mobile otherwise there's no break in the text.

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/b/3OtE8BCR/brizy-public-roadmap

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
