### ISSUE TITLE
Thrive Theme Builder example video

### ISSUE THREAD

**Issue by sunnyt7** [ThemeFuse/Brizy#415]
Hey guys,

Just thought I'd share this preview video of how the alpha version of the Thrive Theme Builder works:

https://drive.google.com/file/d/1nVIGCMc5j45FeeGYU2ID4ZGOBRU25SgQ/view

Love that it allows you to control all components of an archive page.

**Comment by bagrinsergiu** [comment]
Hi 

Thanks for suggestion. We plan to add the same feature soon.

1. Templates is 90% done
2. Blog posts, portfolio, ... + Dynamic Content is 20% done.

Thanks again 
Sergiu
