### ISSUE TITLE
broken word with new lines - makes texts useless!

### ISSUE THREAD

**Issue by RazielKanos** [ThemeFuse/Brizy#416]
When a text comes to the end of the line, the last word doesn't get moved to the next line, it just gets cut. For example, in my case it was "aktuell" and I had "akt" on the end of the upper line, and the lower started with "uell".

I "might" be able to live with that on a private website, but this is an absolute no-go for a business website. Lasts words that don't fit in the line, have to be moved to the next line. As far as I know, it's a  simple CSS issue, but I wasn't able to locate the correct file in the brizy folder

**Comment by maxval94** [comment]
Hi @RazielKanos

This bug was fixed in version 1.0.21.
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thanks for suggestion
Maxim

**Comment by bagrinsergiu** [comment]
In case it is not working for you can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu
