### ISSUE TITLE
An error happened while trying to display this block

### ISSUE THREAD

**Issue by curixLV** [ThemeFuse/Brizy#418]
Hi!

I was making global multiple blocks at once from the same page, and then pressed button to save the changes. It took long to load, so I navigated away from the Brizy editor for the page. When trying to edit this page now, it shows an error on each of these blocks.

The page displays correctly, but I'm not able to edit these blocks though.

Regards.

**Comment by bagrinsergiu** [comment]
Also i recommend to check Settings -> General -> WP URLs

Can you try with http and https in wp urls: https://jmp.sh/vs6d4ot

Sergiu

**Comment by jorgefigueg** [comment]
Same error, with http and with https. I already tried the above in configuration and it's the same, in backend it doesn't show the blocks but in frontend it does.

![image](https://user-images.githubusercontent.com/28811499/43962592-239a6926-9c86-11e8-81c1-1d1f82235ced.png)

**Comment by NataliaBB** [comment]
Hi!
This issue has been fixed within our last updates.
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by heybenbro** [comment]
@NataliaBB, this just started happening in the editor. Plugin up to date. WP up to date:
![image](https://user-images.githubusercontent.com/50721535/58052546-5e1b8380-7b12-11e9-9bcb-bb1d107cd35c.png)

**Comment by akwright** [comment]
This is also happening for me after the latest update. Everything up to date.

**Comment by theopaul** [comment]
Just happen with me also
