### ISSUE TITLE
Mixed Content: Failing to load images over SSL

### ISSUE THREAD

**Issue by PolkGeo** [ThemeFuse/Brizy#419]
I've created two sites using Brizy and noticed a strange bug (possibly). It seems intermittently Brizy fails to recognize the SSL I'm using. For these sites, we use a "free SSL" through our host (https://www.inmotionhosting.com/). Basically it's a 30% chance that when the site loads, images will be broken with the following error: 

_Mixed Content: The page at 'https://mysite.com/' was loaded over HTTPS, but requested an insecure image 'http://mysite.com/?brizy_media=wp-19af1137b59f80b5497fec20b07e032c&brizy_crop=iW%3D787%26iH%3D590%26oX%3D0%26oY%3D0%26cW%3D787%26cH%3D590&brizy_post=136'. This request has been blocked; the content must be served over HTTPS._

What seems to fix it (temporarily) is opening the page in Brizy editor and just hitting save.

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
Also i recommend to check Settings -> General -> WP URLs

Can you try with http and https in wp urls: https://jmp.sh/vs6d4ot

Sergiu

**Comment by andrew-lof** [comment]
I noticed i have the same mixed content issue too for inline images:

https://evoqinternational.com/

<img width="1409" alt="screen shot 2018-08-26 at 2 41 44 pm" src="https://user-images.githubusercontent.com/7736282/44631728-38c06700-a93e-11e8-8fea-58a7d8c90849.png">

**Comment by albertodominguezs** [comment]
I was the one reporting the issue. And it still persists. 
I create a couple Global Sections (header and footer) with the brand image. The images disappeared and an error was reported by browsers "Connection is not Secure. Parts of this page are not secure". 

It only happens with Global elements. Images work for a few weeks and then starts loading images from HTTP not HTTPS. Not sure if it is a Caching system or a problem. It does not happen with any other image on the site.

**Comment by NataliaBB** [comment]
Hi!
This issue has been fixed within our last updates.


I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
