### ISSUE TITLE
IDEA: RSS Feed Widget

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#42]
So, this already exists and can be added via a widget. That said, you folks have the design chops that even the gods must admire. Having an RSS feed widget on a landing page adds a cool ability, and you can do this better. I'm sure of that much.

https://wordpress.org/plugins/rss-feed-widget/

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/guXtVHgE/68-wp-widget

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
