### ISSUE TITLE
"Edit page with Brizy" loads a broken layout

### ISSUE THREAD

**Issue by willhousecreative** [ThemeFuse/Brizy#420]
Hi All,

I was all exited to use Brizy today. Just updated to 1.0.21. Went to "edit a page with Brizy" and the page loaded a broken layout (see gif). 
![broken-layout](https://user-images.githubusercontent.com/19369150/43494292-f5e610ee-94e6-11e8-885e-afdb5dd40fc5.gif)

Not sure what's going on but I checked all the pages on this site. The front end looks great. But the Brizy editor is producing a broken page. 

Thanks for your time on this.

-Richard

**Comment by bagrinsergiu** [comment]
Hi Richard,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu
