### ISSUE TITLE
Select List Needs Label Option

### ISSUE THREAD

**Issue by willhousecreative** [ThemeFuse/Brizy#421]
Hi All,

Loving Brizy! Thank you for all your hard work!

I was setting up a form and wanted to incorporate a select list. When I did so the label that describes the select list becomes a selectable option (see gif)

![form-select-menu](https://user-images.githubusercontent.com/19369150/43494530-2355886a-94e8-11e8-9f92-f37195868c44.gif)

There should be a way to introduce a select list with an instructional label.

Many thanks for your time with this.

-Richard

**Comment by bagrinsergiu** [comment]
Hi Richard

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu
