### ISSUE TITLE
White bar on the left

### ISSUE THREAD

**Issue by Studio110** [ThemeFuse/Brizy#422]
I have a white bar that is not allowing my page to be full screen.
http://www.studio110photography.com

**Comment by bagrinsergiu** [comment]
In theme vivagh, file https://studio110photography.com/wp-content/themes/vivagh/css/layout.css?ver=1.2 was added padding left 100px left

<code>
.left-header.left-header-boxed {
    padding-left: 100px;
}
</code>

https://jmp.sh/bVSv32z

It is possible to overwrite it with custom CSS or delete it from main file.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
