### ISSUE TITLE
Pages not loading Brizy content after transfer

### ISSUE THREAD

**Issue by aronjeney** [ThemeFuse/Brizy#423]
Only one page loads after I transferred my site - [http://6ps.0fd.myftpupload.com/about-us/](http://6ps.0fd.myftpupload.com/about-us/)

The other pages do not load the Brizy content. The code is available in the classic editor, but it doesn't load when editing with Brizy or when I view the page.

Any help would be appreciated, thanks!

**Comment by NataliaBB** [comment]
Added to To do list

**Comment by bagrinsergiu** [comment]
Waiting for details...
