### ISSUE TITLE
[FEATURE REQUEST-IMPROVEMENT] Bullet list with Sub-lists

### ISSUE THREAD

**Issue by iFillip** [ThemeFuse/Brizy#424]
Please provide a better way to make a bullet list. 
* As it is, every major 'bullet heading starts with "1" followed by a bullet in the same margin. 
* It would be nice to have option to have bullets without numbers or with numbers.
    * Please add the ability to create sub-lists
        * And more sublists like this.
See attached sreenshot of problems with "Bullet lists" in the Brizy Text Editor
![brizy bullet editor](https://user-images.githubusercontent.com/38173727/43503205-3f3ac016-9599-11e8-9c32-c59f0330e65a.png)

**Comment by bagrinsergiu** [comment]
![txnftnyqwnlvzopld5bu_1vqwwngcebjn5lzts9c3rgsooxj1remzkn-ebmn8szglo-4uqqb52s05h3t827jun0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/5760683/43507902-08d85f28-9577-11e8-9dd3-02d017c588a2.png)

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/bJSe5uDQ/101-bullet-list-with-sub-lists

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
