### ISSUE TITLE
Saving/ Not Publishing

### ISSUE THREAD

**Issue by odai86** [ThemeFuse/Brizy#425]
hi 
when i try to new thing or update any thing its saving but Not Publishing
i use last update

**Comment by odai86** [comment]
i try to create new page not working at all !!!

**Comment by odai86** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
this is the problem how to fix it

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
Also i recommend to check Settings -> General -> WP URLs

Can you try with http and https in wp urls: https://jmp.sh/vs6d4ot

Sergiu

**Comment by pianometal** [comment]
I'm having the same trouble. My site will not update and I'm stuck in an endless loading period for publishing.

**Comment by odai86** [comment]
it was java script file blocked by server just call your server and ask them to allow this file to load from server

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
