### ISSUE TITLE
Editor not loading after last update (wp multisite)

### ISSUE THREAD

**Issue by webforsoho1** [ThemeFuse/Brizy#427]
![screen shot 2018-08-02 at 11 22 45 am](https://user-images.githubusercontent.com/35761025/43560948-5711bace-9647-11e8-957a-94309a7310b4.png)

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
Also i recommend to check Settings -> General -> WP URLs

Can you try with http and https in wp urls: https://jmp.sh/vs6d4ot

Sergiu

**Comment by innovedia** [comment]
same issue but not on a multi-site. I created an entire site then updated the plugin and now Brizy won't load the pages to change anything.

**Comment by bagrinsergiu** [comment]
Hi @innovedia, @curiousprojects

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by Sportpilot919** [comment]
I am experiencing the same issue with the Brizy editor not loading. It get stuck no matter if I'd editing an existing blog or starting a new one.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
