### ISSUE TITLE
Slider dots

### ISSUE THREAD

**Issue by peleroberts** [ThemeFuse/Brizy#429]
Option to change colour of dots per slide.

Example -

When the slider option is enable with more than one slide

On one slide which has a dark background use white dots and on a slide that has a light background use dark dots.

Thanks

**Comment by bagrinsergiu** [comment]
Hi @peleroberts 

Thanks for suggestion. Added to our huge to do list :)

Sergiu

**Comment by peleroberts** [comment]
No worries, keep up the good work.

P.S. Brought Pro 👍
