### ISSUE TITLE
IDEA: Video Frames

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#43]
One of the things that I miss within themes is the easy ability to make videos look nicer. There are sites like Vidello that offer it, and a plugin that resides outside of the repo that does as well. The latter is very buggy.

My clients LOVE having customized video frames. I truly believe that adding something like this could take Brizy to a whole new level. One that no theme I'm aware of has taken advantage of yet.

I have a copy of the plugin I mentioned in case you want to see some examples. Many are not very good, but others are quite nice. It would be a great selling point if this were added as a block, IMHO.

**Comment by bagrinsergiu** [comment]
Added to our roadmap: https://trello.com/c/GqNG2wgk/10-video-frames

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
