### ISSUE TITLE
Feature Request: Draggable form fields

### ISSUE THREAD

**Issue by toton333** [ThemeFuse/Brizy#430]
I wanted  to create Name, Email, Subject fields in left column and Message and Send button filling up the right side column, but currently it is not possible . If we try to use 50% width to fields the positioning of fields goes out of sync, and we can't really move Send button to anywhere , except left, middle, right alignment . So are repositioning and customizing fields  technically viable in upcoming updates

**Comment by bagrinsergiu** [comment]
HI @toton333 

Can you give me a screenshot with details? 

Thanks 
Sergiu

**Comment by toton333** [comment]
Sure, Here is the desired style i want to achieve
![form](https://user-images.githubusercontent.com/7140284/43673314-747b3e12-97de-11e8-9630-43c4c6c4882e.png)

**Comment by NataliaBB** [comment]
Will be available in the contact form V2

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
