### ISSUE TITLE
Hyphenation still doesn't work correctly on page made with Brizy

### ISSUE THREAD

**Issue by chrisagon** [ThemeFuse/Brizy#431]
#Hello,
I still have the issue. I have updated brizy => 1.0.22.
I have reopen the page and updated it but the hyphnenation still doesn't work.

**Comment by bagrinsergiu** [comment]
Hi @chrisagon 

1.0.22 was a hotfix for 1.0.21. hyphnenation issue is planned in 1.0.23 on Monday

Thanks for reporting.
Sergiu
