### ISSUE TITLE
Brizy unnaccessible when Gutenberg plugin is active

### ISSUE THREAD

**Issue by John-Henrique** [ThemeFuse/Brizy#432]
Trying use gutenberg I see wich brizy is unnaccessible because gutenberg remove button "Edit with Brizy". I don't know if this happen only using gutenberg plugin or will be default view in WordPress 5 (new editor gutenberg definitive).

**Comment by bagrinsergiu** [comment]
Hi @John-Henrique 

We plan to add  fix in 2-3 updates for this issue.  Thanks for reporting. 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
