### ISSUE TITLE
{question} We have a documentation to extend features?

### ISSUE THREAD

**Issue by John-Henrique** [ThemeFuse/Brizy#433]
I want extend brizy with new features, so, where I can find documentation to extend?

**Comment by bagrinsergiu** [comment]
Hi @John-Henrique 

Developer api is planned after Pro launch.

We have an Brizy Roadmap Card regarding Developer API : https://trello.com/c/pFm3iIg8/58-developer-api

Thanks for suggestion 
Sergiu
