### ISSUE TITLE
[ Feature Request ] : Content Toggle, Tooltip

### ISSUE THREAD

**Issue by vishalchavda24** [ThemeFuse/Brizy#434]
Hello,

I found Brizy is amazing page builder. This extra feature will help us to create more awesome pages and designs.

Cheers

**Comment by bagrinsergiu** [comment]
Hi @vishalchavda24 

Please, send us a screenshot with details 

Thank you!
Regards, Sergiu

**Comment by vishalchavda24** [comment]
Hi @bagrinsergiu 

Price list is best example for content toggle.

Content toggle examples: 
http://prntscr.com/kfstof

Essential add-on for Elementor given the best add-ons for Elementor which I like the most and very useful.
Below is the reference links
https://essential-addons.com/elementor/content-toggle/
https://essential-addons.com/elementor/tooltip/

Cheers

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/vY7dMSc5/96-others

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
