### ISSUE TITLE
Editor doesn't load after site migration to a new domain

### ISSUE THREAD

**Issue by leowys** [ThemeFuse/Brizy#435]
Hi! I've just moved a site from a staging development to a lilve site with different domain and the brizy editor doesn't load! Please help!! #

**Comment by leowys** [comment]
The migration was made with backbuddy...

**Comment by John-Henrique** [comment]
If you is using Google Chrome try this, Press F12 to open console, look for any message error.

Probably some error message like 404 will be displayed

Reason probably, in your WordPress options, data of brizy yet have URL from old domain, in this case, you can try uninstall and install again.

**Comment by bagrinsergiu** [comment]
Hi,

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by leowys** [comment]
Hi! I'm stuck right now with other Brizy problem. Will create a topic for the new problem and then go back here. Thanks!
