### ISSUE TITLE
Can not access block settings

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#436]
Before, if I put my cursor near the boundaries of a block, it was highlighted and I could access the settings for the block. Now, this does not work most of the time.

**Comment by bagrinsergiu** [comment]
Hi @logaritym 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu
