### ISSUE TITLE
(conditional) column order 

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#44]
Would be nice if there was (conditional) column order  setting.

i.e.
*sometimes need to reverse column order on mobile.
*change column order without changing html markup for better seo.

**Comment by DimiBaitanciuc** [comment]
I like this, we've actually discussed it a while back. Thanks for the suggestion.

**Comment by Emilybkk** [comment]
Reverse column order is a must. You don't need to discuss. It have to put there. We all see the design trend that use image/content + content/image and this have to be reversed on mobile. Put it as soon as possible!

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/bgztVGqd/142-column-order

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
