### ISSUE TITLE
Number field in form doesn't work

### ISSUE THREAD

**Issue by leowys** [ThemeFuse/Brizy#440]
Hello again!
I'm having troubles with the "Number" field in the form. When selected this type of field in the website doesnt work, even typing only numbers the field doesn't validate a s a valid data entered. I've switched to text field for a temporary solution and works.
Any idea?
Thanks!

**Comment by NataliaBB** [comment]
Hi @leowys! 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Web Page: https://brizy.io

Thanks!
Natalia
