### ISSUE TITLE
Mobile Images cropping

### ISSUE THREAD

**Issue by launchlabspdx** [ThemeFuse/Brizy#441]
See mobile view attachements. Website is launchlabspdx.com mobile version crops the images.. Any way to fix this? 
![38635925_262328101246379_2823705869135380480_n](https://user-images.githubusercontent.com/42187655/43798318-127ec2ac-9a3f-11e8-893c-36fd959760dd.jpg)
![38860558_448402352350021_1009111800374886400_n](https://user-images.githubusercontent.com/42187655/43798321-142f876c-9a3f-11e8-887f-f7731528507b.jpg)

**Comment by bagrinsergiu** [comment]
Solved: https://www.facebook.com/groups/brizy/permalink/296824654414747/
