### ISSUE TITLE
BUG Blank image upload dialogue 

### ISSUE THREAD

**Issue by tomekmarchi** [ThemeFuse/Brizy#444]
The upload dialogue is transparent and inoperable. The issue seems to stem from of a lack of a CSS style sheet that should of been loaded but was not.
<img width="1333" alt="brizy" src="https://user-images.githubusercontent.com/7284608/43883391-f5b1188a-9b80-11e8-8522-68921299dc37.png">

**Comment by bagrinsergiu** [comment]
Hi @tomekmarchi 

Can you check with default theme and disable all plugins. Also Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Link: https://brizy.io/

Thank you.
Sergiu

**Comment by tomekmarchi** [comment]
Did all of that. Only way I could fix is was by manually adding this to main.php 
wp_enqueue_style( 'hotfix-marchi', "/wp-admin/load-styles.php?c=1&amp;dir=ltr&amp;load%5B%5D=media-views,revisi&amp;load%5B%5D=media&amp;", array(), BRIZY_EDITOR_VERSION );

**Comment by tomekmarchi** [comment]
In the case this was a theme related issue - it would be wise to ensure that the theme doesn't have to go out of it's way to support the editor especially on such a small issue as this. The small issue being all that was required was a specific style sheet. Instead it's best to ensure the editor works as best as possible out of the box.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
