### ISSUE TITLE
Bug: text link color not changeable , feature request: hover color option for text link

### ISSUE THREAD

**Issue by toton333** [ThemeFuse/Brizy#447]
I made a word as a link in a text element, after the word became a link i'm unable to change its text color and there is no option to change the hover color.

**Comment by cmbc58** [comment]
I had the same problem. Surprised this has not been picked up before. Or perhaps it has?!

**Comment by NataliaBB** [comment]
Hi @toton333 and Ben @cmbc58 

We added this options into our roadmap: https://trello.com/c/abkAqzvg/102-text-link-color-hover-color 

At the moment, you can set the code for the needed colour. Here is a short video: 
https://jumpshare.com/v/3cXDG3Je5aiY7CJKGzUS

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Best Regards, Natalia
