### ISSUE TITLE
Does Developer Api included when pro version release?

### ISSUE THREAD

**Issue by hlaporthein** [ThemeFuse/Brizy#450]
I saw [developer api](https://trello.com/c/pFm3iIg8/58-developer-api) is included in Brizy roadmap & found many upvotes. Would it be included in pro version release. Now, I would like to change my premium themes to frontend builders. If brizy would take more time for that, I have to buy another frontend builder.

**Comment by NataliaBB** [comment]
Hi @hlaporthein! 

Yes, Developer API will be included in the ProVersion.
One Note - this module will be developed after Pro launch.

Best Regards, Natalia
