### ISSUE TITLE
brizy latest version can not connect to its icon library

### ISSUE THREAD

**Issue by esrafidan** [ThemeFuse/Brizy#453]
Hi team!

I use the latest version of Brizy to developping. Brizy work properly except icon library. I could not the find the reason . Please could you help me asap.

Yo may find the screenshots as attachments.

Thanks in advance.
<img width="1163" alt="1" src="https://user-images.githubusercontent.com/42276898/43967849-23646f04-9cce-11e8-8fc1-cf82f2201973.png">
<img width="1122" alt="2" src="https://user-images.githubusercontent.com/42276898/43967850-238e3b0e-9cce-11e8-9f2a-1f0d07f3b6e4.png">

**Comment by NataliaBB** [comment]
Hi @esrafidan! 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Web Page: https://brizy.io 
Thank you!
Natalia
