### ISSUE TITLE
Feature request - Section, Row & Column hover styles & Link properties

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#457]
Hi there,

I know you guys are really busy with preparing Brizy Pro. However I would like to make a feature request for Brizy.

In order to create more interactive and interesting elements with Brizy it would be really nice if rows, columns and perhaps even sections have onHover styles which could be easily edited through Brizy's interface.

---

### An example:

I have a column which holds a review. It contains the review text itself, a name and perhaps the reviewers function title.

Instead of always having to put a button with the link it would be really nice if we could just click the column that holds the review and make the column itself a link.
In order to put more focus on the entire column it would be great if we for example could apply hover styles to it so the user immediately knows they can click on it.

---

This could also be applicable to rows or perhaps even an entire section. To keep it short I will keep it at the above example.

I can already apply this hover effect myself using CSS. However not every Brizy user is able to do that. Same goes for making a column into a link. This could be done by Javascript, but that's even harder for non-coders.

I know you guys are already working non-stop working on the pro version, but if you guys could please let me know if this (or anything similiair) is something we can expect in a future version that would be great.

Best regards,

Christiaan

**Comment by bagrinsergiu** [comment]
Hi Christiaan,

Section, Row & Column hover styles & Link properties features is in our doing list planned in 2-3 weeks. 

Thanks for suggestion.

I added this suggestion in our public roadmap: Section, Row & Column hover styles & Link properties

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
