### ISSUE TITLE
The plugin doesn't load, stuck at the loading animation screen

### ISSUE THREAD

**Issue by imsurya** [ThemeFuse/Brizy#458]
Hello there,

 I installed the brizy plugin. Then i started to edit my blog front page that is "Home" with the brizy editor. But the Brizy editor hangs at the loading screen with the animation of a loading sign. From here it just keeps loading but nothing happens. could you please help me fix this problem? 

![load error brizy](https://user-images.githubusercontent.com/7498357/43985299-aa3e3540-9d06-11e8-9dd2-a7d2b7cdde21.PNG)
Thank You

**Comment by NataliaBB** [comment]
Hey @imsurya 
Thanks for reporting this!

Please give us a short message on our FB chat
https://jmp.sh/YniVQI7 
Cheers!
Natalia

**Comment by Sainory** [comment]
I have the same problem bro

**Comment by NataliaBB** [comment]
Hi @imsurya  and @Sainory 

Please, give me a message on our FB chat and mention this  inside:

https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
