### ISSUE TITLE
Feature request - Archives loop customization + frontend posting

### ISSUE THREAD

**Issue by widevisions** [ThemeFuse/Brizy#460]
Hi guys,
a couple of ideas for additional functions.
Would be very nice to have two templates, one for each element in the archives loop (categories, tags for posts and CPTs) and one for the whole archive page, so we could easily design original layouts.
Even better if this would be possible also for authors (authors archives and authors page).
A frontend posting element with the possibility to add ACF fields would also be very nice.
I hope I didn´t miss the same request elsewhere.
Kind regards

**Comment by bagrinsergiu** [comment]
Hi @widevisions 

With last Pro version is possible to design original layouts. We added ( Posts, Archive, Gallery, Carousell, Popup, ...).   

Thanks for suggestion.
Sergiu

**Comment by bagrinsergiu** [comment]
:) ACF, Pods and Toolset is also available.
