### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by ternmarketing** [ThemeFuse/Brizy#466]
I see you have SalesForce integration on the plan. Could you also please add integration with Pipedrive as well? Thanks.

**Comment by NataliaBB** [comment]
Hi @ternmarketing 

Thanks for your suggestion.

Added into our Roadmap - https://trello.com/c/SJcFPC1Y/35-form-integrations

I’m closing this issue to keep the issue database slim.
Best Regards, Natalia
