### ISSUE TITLE
Font colors not showing correctly now

### ISSUE THREAD

**Issue by Supo65** [ThemeFuse/Brizy#468]

**Comment by Supo65** [comment]
Hi is anyone else having an issue with the colors not showing correctly. Trying to set some text colors, they show correctly in the editing mode but when I view the page the colors show up black. It was working fine but now can't get my colors to work. Makes me leery about changing any other colors. Put some screenshots to show.

![screen shot 2018-08-15 at 9 36 44 am](https://user-images.githubusercontent.com/40869456/44153895-fc094f66-a06e-11e8-9dbb-3a75a1d5135d.png)
![screen shot 2018-08-15 at 9 36 55 am](https://user-images.githubusercontent.com/40869456/44153896-fc1f2a16-a06e-11e8-8063-0f05ad3deefe.png)

**Comment by Supo65** [comment]
Not sure if the text box got corrupted or not but ended up adding a new text box and that seemed to fix the problem.

**Comment by NataliaBB** [comment]
Hi @Supo65 
Please, send me a message and WP credentials via Facebook Chat and mention this issue inside:

https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

Thank you!
Regards, Natalia
