### ISSUE TITLE
Changing link color

### ISSUE THREAD

**Issue by Supo65** [ThemeFuse/Brizy#469]
Another question, is there a way to change a link color. I have my telephone number at the top and I have set to all white. When I view on my desktop it shows up right but when I view on my mobile device it's blue. I liked to have it all white if possible.

It may be because it lets you connect to you phone with just a click.

**Comment by NataliaBB** [comment]
Hey @Supo65!
I've tried to reproduce your question in a video, and on my mobile version, the colour is seated as on the desktop:

https://jumpshare.com/v/3AF5lBBueIGee0d6EdfQ

Unfortunately, we don't have right now another possibility to get a link colour besides to copy the code of the needed one.

Let me know if I understand you correctly, and feel free to ask for any details.

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
