### ISSUE TITLE
ability to add custom html attributes

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#47]
Would be nice if elements (such as text) had ability to add custom attribute such as data, itemprop or style.
(i know inline style isn't good but sometimes necessary)

**Comment by dnnsjsk** [comment]
+1 for custom attributes everywhere! let us use all those delicious libraries with Brizy!

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/29Ycq8P0/143-element-custom-html-attributes

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
