### ISSUE TITLE
Drop shadow on type

### ISSUE THREAD

**Issue by Supo65** [ThemeFuse/Brizy#470]
Like to know if it's possible to add a drop shadow to  my text, if so, can someone please share how. Thanks.

**Comment by NataliaBB** [comment]
Hi @Supo65!

Right now, You can add CSS code for text shadow. 
I added this feature to our roadmap:
https://trello.com/c/jGWjlNz0/104-text-shadow

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Regards, Natalia
