### ISSUE TITLE
Doesnt Display Custom Global Elements

### ISSUE THREAD

**Issue by neo10** [ThemeFuse/Brizy#471]
![1](https://user-images.githubusercontent.com/42423778/44179628-2e110100-a0f8-11e8-914e-593e4521ff69.png)
![2](https://user-images.githubusercontent.com/42423778/44179629-2e110100-a0f8-11e8-9e16-ddb757b6ab26.png)

Also my custom Elements disappeared from Picture 1.

Chrome WP Plugin Windows 10

Please help!

**Comment by baromus** [comment]
I Natalia I think I just messaged you

**Comment by neo10** [comment]
It was a error from the migration of a website using duplicator on WordPress
And, btw. Nobody uses Facebook these days.

baromus <notifications@github.com> schrieb am Di., 21. Aug. 2018, 15:44:

**Comment by baromus** [comment]
How do I fix it?

**Comment by NataliaBB** [comment]
Hi @baromus 
Natalia here. If you still have this issue after 1.0.45 Version, please send us a message via our Facebook chat, or on my email natalia@brizy.io. Please mention this issue number -#471 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
