### ISSUE TITLE
Bug: White spaces in text are not getting rendered

### ISSUE THREAD

**Issue by toton333** [ThemeFuse/Brizy#472]
Not sure if it was intentional or bug, but if we try to make white space in text it doesn't get rendered/updated to the actual page.

**Comment by NataliaBB** [comment]
Hi @toton333 

Can you give me a message via Facebook Chat?
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

Thanks!
Regards, Natalia

**Comment by toton333** [comment]
Hi Natalia, thanks for the reply.
I tried to message via brizy.io, but it is for Brizy Pro clients only it says. I left the message there anyway.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
