### ISSUE TITLE
How to set the home page?

### ISSUE THREAD

**Issue by awesomesaas** [ThemeFuse/Brizy#475]
I created a home page in Brizy and it displays perfectly on desktop and mobile as you can see here: http://d.bbg.li/QXG98K

But if I set that as the home page in the Reading settings (http://d.bbg.li/wBOc32), it makes the page display almost like an iframe inside the 2017 WP Theme as you can see here: http://d.bbg.li/RIjBqL

Thanks for any guidance on how to set this as the home page without the interference of the default theme.

**Comment by bagrinsergiu** [comment]
Hi @awesomesaas 

I recommend to switch to Astra or Ocean WP Themes ( Free versions) or The Core by themefuse. 

Sergiu

**Comment by awesomesaas** [comment]
Thanks. That solved it!
