### ISSUE TITLE
Headers/Footer problem

### ISSUE THREAD

**Issue by Supo65** [ThemeFuse/Brizy#478]
Hello, i'm trying to use a plugin, Headers and Footers Scripts, which allows you to easily add scripts to your header or footer but when I try to it causes some of my blocks not to show correctly. Has anyone else come across this??? Thanks.

**Comment by NataliaBB** [comment]
Hi @Supo65!

Can you give me WP credentials via Facebook Chat and mention this issue inside:
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io 

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
