### ISSUE TITLE
column gutter

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#48]
It may be possible to emulate column gutter with margin/padding but it's useful when edit complex grid and if need to adjust space between columns equally.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/fC19PBhI/137-column-gutter

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
