### ISSUE TITLE
Search and Filter Plugin not functioning

### ISSUE THREAD

**Issue by baromus** [ThemeFuse/Brizy#480]
I love this page builder, but when I place the short code to my post search and filter it appears on the page, but when I try and use the filter it doesn’t work. It just resets the filter. Please help or I may have to abandon Brizy, and I don’t want to.

**Comment by NataliaBB** [comment]
Hi @baromus!

Can you give me WP credentials via Facebook Chat and mention this issue inside:
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io 

Thanks!
Regards, Natalia

**Comment by baromus** [comment]
I was told the chat was for pro members only

**Comment by NataliaBB** [comment]
Hi @baromus!
Yes, the chat is for the Pro only, but bugs are also solved via chat.
I will change the boots messages, to not make more confusion for the users. Sorry for this inconvenience. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
