### ISSUE TITLE
Insert short code

### ISSUE THREAD

**Issue by oconrard** [ThemeFuse/Brizy#486]
Hi all,

On the page https://chasseengaume.be/home-br/ I insert a short code to show a map.
I create a second block to add an other short code for an other map.
It works until the I insert the short code. After few seconds the element disappear and the short code is not saved.

It seems that it's not possible to insert two short code in the same page.

Could you check and revert to me

Regards

Olivier

**Comment by oconrard** [comment]
Hi Natalia,

After some some test, it’s seems working, but on the page editor with Brizy the element with the short code is not visible (see attachment)

Regards

Olivier

**Comment by NataliaBB** [comment]
Hey @oconrard!
You sent these attachments via email, but GitHub can't read them. Please try to insert the images from your GitHub account.

Thanks!
Natalia

**Comment by jgabjanssen** [comment]
Hi Guys,

I have the exact same problem. add the shortcode, it works. want the change the shortcode the block is missing. @NataliaBB im contacting you on facebook  chat.
Greets,
Jeroen

**Comment by jgabjanssen** [comment]
@NataliaBB done.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
