### ISSUE TITLE
Feature Request: Ability to name saved rows

### ISSUE THREAD

**Issue by visionlaunchers** [ThemeFuse/Brizy#487]
When you have a number of saved row templates that were started from scratch, it is hard to find the right row when all you see are "Started from scratch" preview icons for each saved row. If we had the ability to add a title to each saved row, that would make finding what we need MUCH easier.

**Comment by bagrinsergiu** [comment]
Hi @visionlaunchers 

Thanks for your suggestion.

Added into our Roadmap - https://trello.com/c/Bey1hFce/111-blocks-thumb-generation

I’m closing this issue to keep the issue database slim.
Best Regards, Sergiu
