### ISSUE TITLE
Form color (dropdown's multiselector)

### ISSUE THREAD

**Issue by yerarto** [ThemeFuse/Brizy#491]
Hi! I've created a form with a background dark color and the types are white. When I select the dropdown menu from the multiselector I cannot select the background color of the dropdown menu or the type color.

There is any way to do it? 

<img width="943" alt="captura de pantalla 2018-08-23 a las 10 36 04 a m" src="https://user-images.githubusercontent.com/42446178/44528639-7021e000-a6c0-11e8-92d9-b8f5e76adf74.png">
<img width="944" alt="captura de pantalla 2018-08-23 a las 10 36 16 a m" src="https://user-images.githubusercontent.com/42446178/44528641-7021e000-a6c0-11e8-93c9-7c62e92df95b.png">

**Comment by NataliaBB** [comment]
Hi @yerarto!

Thanks for your message.
The background fields are white by default and they can not be changed.
But we added this improvement in our to-do list and we will fix this asap.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hey!
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
