### ISSUE TITLE
[ Feature Request ] MicroThemer Integration

### ISSUE THREAD

**Issue by shamrockoz** [ThemeFuse/Brizy#492]
This is way too early to request - but Microthemer and Elementor now have integration.

Any chance this could be applied to Brizy?

Take a look at MicroThemer's video on this subject.

https://www.youtube.com/watch?v=LVonsMV002g

**Comment by NataliaBB** [comment]
Hi @shamrockoz 

Thank you for your suggestion!
Added into our roadmap:
https://trello.com/c/SJcFPC1Y/35-form-integrations

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
