### ISSUE TITLE
Dynamic Content

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#493]
Please, add post meta (author/tags/categories/comments), author box, blog title as dynamic content, so that we can use them for our blog posts. Especially the meta.

**Comment by NataliaBB** [comment]
Hi @logaritym 
Yes, they all are added to the dynamic content.
Thank you!

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
