### ISSUE TITLE
Border Radius on Images

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#494]
Border Radius can't be edited when switching to mobil view. When images are not perfectly square they can't be made round in the mobile view. Even square images must be scaled below the border radius set on the Desktop view. Please add border radius to mobil view.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/Eh2pC3Xo/6-image-border

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
