### ISSUE TITLE
Edit with Brizy when Gutenberg is activated

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#495]
As WordPress is rolling out the Gutenberg Editor and now has a Call-To-Action to try/active it I ran into problems editing my page. As Gutenberg takes over the screen there is a icon/button missing on the Gutenberg Editor to use Brizy. I have to take a detour over classic editor or use the "Edit with Brizy" link in the pages index.

**Comment by NataliaBB** [comment]
Hi @MaxZiebell!
Thanks for reporting this. We notice this too, and we add this issue in our do to list. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by ViorelEremia** [comment]
Fixed in the pull request: https://github.com/ThemeFuse/Brizy/pull/725
