### ISSUE TITLE
[Feature Request] Custom Maintenance Mode

### ISSUE THREAD

**Issue by WhiteX** [ThemeFuse/Brizy#499]
Hello,
there is a good feature in one of your competitor's page builder. In their PRO version you can enable maintenance mode and load a custom page template that will be shown for the visitors. It's a perfect combination to quickly create a coming soon page.
What do you think?
(If there's a plugin that already does this, please send a link, but anyway, integrating it in Brizy, would be very handy).
Thanks!

**Comment by WhiteX** [comment]
Up.

https://wordpress.org/support/topic/feature-request-let-users-build-a-custom-page/

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/ZdpDvOME/161-custom-maintenance-mode

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
