### ISSUE TITLE
responsive

### ISSUE THREAD

**Issue by joelmwasserman** [ThemeFuse/Brizy#5]
my current site i just built
http://joelwasserman.me/ is not working correctly on my mobile...in the responsive mobile preview it looks totally different to how it is on my phone
![img_0530](https://user-images.githubusercontent.com/38677738/39463722-55255cc4-4cce-11e8-9a7b-2b327de45c60.PNG)

**Comment by bagrinsergiu** [comment]
Interesting looks like something is up with the viewport, we'll take a look, thanks for pointing it out.
