### ISSUE TITLE
Settings Box Z-Order Issue With Divi

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#50]
When using Brizy within Divi and using the default template (where the menu shows), the settings box of the top module can disappear under the menu.

![2018-05-22_22-32-03](https://user-images.githubusercontent.com/39112114/40402295-6ac8048e-5e10-11e8-8fd0-54c5cb384a63.jpg)

**Comment by bagrinsergiu** [comment]
Thanks for letting us know. We'll look into it.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
