### ISSUE TITLE
Features request: Comments and Social Share element.

### ISSUE THREAD

**Issue by Emilybkk** [ThemeFuse/Brizy#504]
It would be good if we can add Comment element to page. Also the share element that will grab the URL and other Open Graph of the page for social sharing.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/7hIuY5Jr/160-comments-and-social-share-element

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
