### ISSUE TITLE
Download Action on Button

### ISSUE THREAD

**Issue by bivers13wbp** [ThemeFuse/Brizy#509]
Hello,
Is there a way to add a download attribute to a button? Instead of directing the user to a new page or an anchor, I would like them to download the image that is in the same block. Any thoughts on how to do this?
Thanks,
Ben

**Comment by bagrinsergiu** [comment]
Hi 

Bit of a workaround this but you could add your file on Dropbox, filetransfer, google docs and insert link in brizy editor. 

We plan an Download Button feature in future demo link: https://trello.com/c/lA4gJ3bA/53-download-button-option

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
