### ISSUE TITLE
Brizy Forced Into Boxed Template - Divi

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#51]
This may be unavoidable, I don't know, but there isn't a way to make Brizy go full width when using the default template within Divi. It always stops short and is essentially a boxed layout. 

Another problem with this is that the Divi menu is hidden inside of the Brizy and Blank Page templates.  

This is a local dev site so I don't have a login for you.

**Comment by bagrinsergiu** [comment]
Thanks for letting us know. We'll look into it.

**Comment by bagrinsergiu** [comment]
This may be unavoidable, I don't know, but there isn't a way to make Brizy go full width when using the default template within Divi. It always stops short and is essentially a boxed layout.

Duplicate: https://github.com/ThemeFuse/Brizy/issues/65

---

Another problem with this is that the Divi menu is hidden inside of the Brizy and Blank Page templates.

This is the same issue: https://github.com/ThemeFuse/Brizy/issues/50 ?

**Comment by CJKrets** [comment]
#51 and #65 appear to be related.

#50 is completely different and related to the editor box falling under the
menu. (z-order)

~ Corey

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
