### ISSUE TITLE
"Edit with Brizy" Page Not Loading after Migration

### ISSUE THREAD

**Issue by gstron** [ThemeFuse/Brizy#510]
Hi,

I migrated my website to a new server using BackupBuddy, and I can't edit the pages now using Brizy. I suspect it had something to do with the transfer.

Thanks!

~Graham

PS - FYI, when I updated Brizy to the Aug. 22, 2018 release, I received two errors at the top of the page - one was ""Warning: base64_decode() expects parameter 1 to be string, array given..." and the other was similar but mentioned JSON.

EDITED: The actual code for the error described in the "PS" is as follows:

<br />
<b>Warning</b>:  base64_decode() expects parameter 1 to be string, array given in <b>/home/strongwe/public_html/courthousehotel.ca/wp-content/plugins/brizy/editor/api/project.php</b> on line <b>47</b><br />
<br />
<b>Warning</b>:  json_decode() expects parameter 1 to be string, array given in <b>/home/strongwe/public_html/courthousehotel.ca/wp-content/plugins/brizy/editor/api/project.php</b> on line <b>51</b><br />

This code appears before the HTML tag.

**Comment by gstron** [comment]
HI Natalia,

I don't know what Facebook Chat is -- I'm not on it. Can I email you the credentials?

~Graham

**Comment by NataliaBB** [comment]
Hi @gstron!

Sure, please send me an email at chitoroaganataliav@gmail.com
I will need : your project url + wp credentials + ftp credentials. 


Thank you!
Regards, Natalia

**Comment by gstron** [comment]
Hi!

Any news on what's causing this issue? I need to get this website up and running soon.

Thanks!

~Graham

**Comment by gstron** [comment]
Never mind -- I got it working.

~Graham

**Comment by lindseywb** [comment]
Hey Graham, can you let me know what you did to get it working? I had the same thing happen to me.

**Comment by gstron** [comment]
@lindseywb Yes. Originally, I migrated using BackupBuddy -- my go-to. After doing some digging, I found that Unyson (which comes with the template) also does backup. I used that to migrate instead, and all worked fine.

~Graham

**Comment by Lazinsky** [comment]
warning doing update base64_decode() expects parameter 1 to be string, array given in

**Comment by NataliaBB** [comment]
Hello!
Natalia here!
If you still have this issue, please submit a ticket here: https://support.brizy.io/hc/en-us

Thank you!
Regards, Natalia
