### ISSUE TITLE
Brizy fatal error failed to open stream

### ISSUE THREAD

**Issue by Ric-01** [ThemeFuse/Brizy#52]
Hi all,

I did an update of Brizy (and Unyson) today, because it was offered in my Wordpress admin.

After that the WP admin shows a white page.

This is the error:

Notice: Use of undefined constant DIR - assumed 'DIR' in /var/www/web1035/html/wordpress/wp-content/plugins/brizy/vendor/autoload.php on line 5

Warning: require_once(DIR/composer/autoload_real.php) [function.require-once]: failed to open stream: No such file or directory in /var/www/web1035/html/wordpress/wp-content/plugins/brizy/vendor/autoload.php on line 5

Fatal error: require_once() [function.require]: Failed opening required 'DIR/composer/autoload_real.php' (include_path='.:/opt/php/5.2.17/share/pear:/usr/share/php/pear') in /var/www/web1035/html/wordpress/wp-content/plugins/brizy/vendor/autoload.php on line 5

I need help, what to do now?

Thanks and greetings, Erich

**Comment by bagrinsergiu** [comment]
Hi Erich,

Temporary you can disable Brizy. The magic constant __DIR__ was added in PHP version 5.3.0. You need to upgrade php to a newer version or wait next update with a fix. It will take 3-4 days.

Thanks
Sergiu

**Comment by Ric-01** [comment]
Hi all, 
it was so simple and I feel blamed: the htaccess overrided the PHP version 7.2 with th 5.2. 
Sorry and best regards
Ric
