### ISSUE TITLE
WT...Nothing works...this is disappointing and I must go back to Divi

### ISSUE THREAD

**Issue by DigitalDez** [ThemeFuse/Brizy#524]
I have been using Divi, Bakery, Elementor, and Dragify for quite sometime and I am really impressed with the way Brizy works IN THE DEMO VIDEOS. I actually have a themefuse account and have tried to use Brizy with them. Thought it was Edge and used Chrome then Firefox. Still I can't figure out why there is no response to Brizy's functions. My last try was using the Keynote theme on themfuse, loaded up Brizy +Pro and even the theme had issues importing the theme to WP. Then, once the theme had loaded enough assets, i went to edit it and nothing was responding. try to replace an image and that would just click off. Tried to add a block and it never happened. went to another browser, same thing. This isn't the first time either. Back to Divi I go because I need to get work done. Any insight will be most welcome if not I must get a refund on the lifetime. thanks!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
