### ISSUE TITLE
Media not showing up

### ISSUE THREAD

**Issue by stopcollaboratelisten** [ThemeFuse/Brizy#526]
Hello. I manage the page at address liberty.earth. I have had intermittent reports of people not being able to see the logo on our page. It seems to be an Internet Explorer problem, as I have visited the page on Safari and Chrome and cannot seem to replicate the problem.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
