### ISSUE TITLE
After update to version 1.0.26 links are no longer working

### ISSUE THREAD

**Issue by btvbill** [ThemeFuse/Brizy#529]
My home page "read more" and footer navigation links were working fine before I updated to version 1.0.26. Now, they don't work or show properly, despite looking normal in the Brizy edit page. I have restored a backup version to another URL for testing using the 1.0.25 version and it looks ok but I cannot edit. Brizy just spins the circle without doing anything. Please advise.

**Comment by btvbill** [comment]
Thanks Sergiu. I just did as you requested. Posted to Jumpshare and also messaged you on FB.

**Comment by btvbill** [comment]
I think I figured it out. Creating links was VERY fussy and that's what caused the issues. I found that I was able to resolve things but copy/pasting links VERY carefully, rather than typing them in. Seems to be working for now. Thanks.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
