### ISSUE TITLE
Sandalone version 

### ISSUE THREAD

**Issue by ang3lx** [ThemeFuse/Brizy#53]
Is possibile to have a sandalone version?

**Comment by ash-f** [comment]
I think he means non-WP version.
Probably like Bitblox but self hosted app I think.
https://www.bitblox.me/

**Comment by bagrinsergiu** [comment]
Hi @ang3lx @ash-f,

@ash-f  - Thank you for details.
@ang3lx - Can you give me more details why you need it sandalone?

**Comment by ang3lx** [comment]
Hi @bagrinsergiu
it would be very useless to be able to use your editor in a CMS and instead to download the content in an html page, save the content into mysql database
<div id = "brizy-content">
.......... all my html edited with editor
</div>

on click of "Save HTML" call php script that intead of force dowload of entire page,
save content of #brizy-content to MySQL

**Comment by bagrinsergiu** [comment]
Hi @ang3lx 

I understand what you want to do. Can you give details where you want to integrate editor?

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
