### ISSUE TITLE
Installation of pro version

### ISSUE THREAD

**Issue by chetpat** [ThemeFuse/Brizy#530]
Is it required to deactivate brizy free version after installation of pro version??? Because i could't find the pro features or editing interface of pro version...

**Comment by vitog** [comment]
How do I install Brizy pro after I have been using unyson template, and built with brizy. I bought lifetime Brizy with a different email then the site for wordpress

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
