### ISSUE TITLE
Unable to Change Page Template

### ISSUE THREAD

**Issue by ConversionPerk** [ThemeFuse/Brizy#532]
Dear Support,

I built page using brizy but now I'm unable to change template of my newly created page to "Landing Page" to display menu bar, footer etc.. I had done this for home page and it has worked properly that time but now I'm getting this error:

Fatal error: Cannot use object of type WP_Error as array in /home/arogyxq6/public_html/new/wp-content/themes/medina/framework-customizations/extensions/shortcodes/shortcodes/portfolio/views/view.php on line 113

Please help.

Thanks,

**Comment by NataliaBB** [comment]
Hi @ConversionPerk 

Natalia here, Brizy team!
Please, send me your WP + FTP credentials via Facebook Chat and mention this issue inside:
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
