### ISSUE TITLE
Brizy Pro: Single post dynamic post title displays template title when Yoast SEO is installed

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#534]
The dynamic post title does not display the post title but the post template when Yoast SEO is installed and activated (local installation). I have tried with GeneratePress and also Twenty Seventeen theme.

**Comment by NataliaBB** [comment]
Hi @quantumleap33 

Natalia here,
Please send me a message via Facebook Chat and mention this issue inside:

https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
