### ISSUE TITLE
Brizy Pro: Dynamic content does not update when previewed with the eye icon

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#536]
Any changes on dynamic content for a template are not updated when the page is previewed by clicking the eye icon. The template would need to be saved first in order for the preview to work in which case it's not really a preview.

**Comment by NataliaBB** [comment]
Hey @quantumleap33 

Let's discuss this bug on our chat, please. I need to get your WP and FTP credentials.

Thank you!
Regards, Natalia

**Comment by quantumleap33** [comment]
Hi Natalia
1) What chat are you referring to?
2) I am testing locally at the moment but the case is quite generic and I didn't have any other plugings installed. It can also happen with the new gallery lightbox feature where you would still need to update the page to preview the lightbox(have a look here: https://youtu.be/YRopxJ34zTM?t=511). Have you tried reproducing it?

**Comment by NataliaBB** [comment]
Hi @quantumleap33 
Sorry for misunderstanding

I meant our Facebook Chat:
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

Regards, Natalia

**Comment by quantumleap33** [comment]
@NataliaBB Ok tried to login but says that Jumpshare is down for maintenance. Looks like a bit of a mission for a relatively simple issue...lol

**Comment by codeclinic** [comment]
I've noticed this too, but it only seems to relate to some changes.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
