### ISSUE TITLE
Site broken after migrating

### ISSUE THREAD

**Issue by lindseywb** [ThemeFuse/Brizy#539]
Hi,
After I pointed the domain to the folder on the server the site completely broke. None of the pages look how they are supposed to. All of the content is in the WordPress editor. When I try to edit them with Brizy, none of the blocks that I created are there.
Thank you

**Comment by lindseywb** [comment]
Actually, only some of the content on some pages in in the WordPress editor.

djdancedaddy.com

**Comment by NataliaBB** [comment]
Hi @lindseywb 

Natalia here, Brizy team!

Can you give me WP + FTP credentials via Facebook Chat and mention this issue inside:
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

Regards, Natalia

**Comment by lindseywb** [comment]
Natalia,

Due to time constraints we recreated the site.

Thanks,
Lindsey

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
