### ISSUE TITLE
Element position setting

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#54]
Since there's z-index setting, I'd like to have position settings to create off-grid layouts or sticky elements.
Settings such as:
*absolute/relative/fixed
*top/left/bottom/right

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/K0wVI4Lg/141-element-position-setting

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
