### ISSUE TITLE
Colour Gradient - For Icons 

### ISSUE THREAD

**Issue by vitog** [ThemeFuse/Brizy#540]
I am looking to do a colour gradient over filled icons is this possible

**Comment by forcedlogic** [comment]
Icons are vector images. Unless I am wrong..you can't just color the vector without the source having the color applied first. To test this theory you can download yellow pencil which will allow you to play with the css. You'll notice that if you want to apply a gradient to say a background with text...you need to apply a css property background-clip: text. There is nothing you can do to clip the icon. Again I could be wrong...it appears there is no native way without hacks.

**Comment by vitog** [comment]
Hmm OK. Thanks for the info.

**Comment by NataliaBB** [comment]
Hi @vitog!

Gradient Element from our roadmap: https://trello.com/c/Ls3RZZa2/61-element-gradient 

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
