### ISSUE TITLE
Emails will not submit in contact form

### ISSUE THREAD

**Issue by jamiedixon7** [ThemeFuse/Brizy#541]
I have configured the email address via the wordpress plugin. but my messages still wont submit. 

Website is  www.buildtecconstruction.co.uk email is ben@buildtecconstruction.co.uk

**Comment by NataliaBB** [comment]
Hi @jamiedixon7 
Natalia here, Brizy team!

Can you give me WP + FTP credentials via Facebook Chat and mention this issue inside:
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

Thank you!
Regards, Natalia

P.S please mention the github link in the message.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by maatinito** [comment]
Hi, 
I'm trying to setup a form and I don't receive any mail on submit.
Reading at the logs talking about 'wp form integration' I even created a new page with a predefined  form, setting up the WP connector correctly but nothing. 
I installed WP SMTP plugin & Check email plugins and I correctly receive test mails 
I don't know how to investigate more .
Any tips ? 
(URL: http://kahekaro.com/fr_fr/contact)
