### ISSUE TITLE
Brizy does not switch templates

### ISSUE THREAD

**Issue by logaritym** [ThemeFuse/Brizy#542]
This is a post from my blog which was in Brizy template. I could not change the template to default on the edit screen. I click default, then update and it still stays Brizy. I changed it from the wp back-end side.
http://box2074.temp.domains/~puzzleq4/movie-conundrums-2/

**Comment by NataliaBB** [comment]
Hi @logaritym 

Can you send me please a private message on our FB chat?

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
