### ISSUE TITLE
Dynamic Post Content problem

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#545]
Hi
I would like to inform about an issue.

1. When I switch the layout of the post to brizy template layout the post content loses the HTML tag <p> so there are no paragraphs in the content.

Thanks

**Comment by pellissierjp** [comment]
Hi, I think this is the issue I've pointed out as well.
As long as all the text in the editor is only paragraph, Brizy displays it correctly. But the moment we give any heading a html tag, like H1, H2, etc...it loses all formatting.
Confirmed on 6 themes, and others are experiencing same issues.

**Comment by peleroberts** [comment]
Experiencing the same also

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
