### ISSUE TITLE
How to use theme header & footer in the Brizy template

### ISSUE THREAD

**Issue by shaonsina** [ThemeFuse/Brizy#549]
I would like to use Brizy builder. But the problem is that how could I use theme header & footer together in the Brizy template

**Comment by forcedlogic** [comment]
Header and footer currently is not yet working. So your going to need to wait until it's released.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by thewebstylist** [comment]
I would luv to see some tutorial videos on how to customize header and footers for mobile view!

**Comment by vir-gomez** [comment]
It is a possibility to set a custom menu in the free version of brizy theme builder or it is just released for the paid version? I am trying to researching for a new page builder to re-[design my web](https://virgomez.es/).
