### ISSUE TITLE
Shortcut commands

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#55]
Would be nice if there's shortcut commands for frequent action.
Such as open "More Settings"

**Comment by bagrinsergiu** [comment]
@ash-f 

Hi, 

Thanks for suggestion. Added to to do list. 

Right now we have 2 Shorcuts :) ( CMD+Z, CMD+Y )

Sergiu

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/kQhpbFaw/76-shortcut-commands

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
