### ISSUE TITLE
[FEATURE REQUEST] Sortable Tabs

### ISSUE THREAD

**Issue by pilpfiction** [ThemeFuse/Brizy#552]
Provide a way to sort / rearrange tabs once created.

**Comment by anselmelly** [comment]
Also include the ability to define an `active tab` on page load

**Comment by bagrinsergiu** [comment]
I added suggestions in our public roadmap: 

1. https://trello.com/c/9HrtnkFu/130-dnd-for-tabs-accordions
2. https://trello.com/c/tZeB9Iyk/133-active-item-for-accordion-tabs

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
