### ISSUE TITLE
Umlaut 

### ISSUE THREAD

**Issue by pilpfiction** [ThemeFuse/Brizy#553]
Since version 26 umlauts are not displayed correctly for block elements.

While in edit mode the umlauts are shown correctly, but not in the published version.

Besides of umlauts also blanks at the end of  a text block are not displayed correctly.

Umlauts in the menu item are displayed correctly.

When reinstalling version 24 all umlauts are correctly displayed. After updating again to 26, umlauts are displayed wrong.

**Comment by NataliaBB** [comment]
Hi @pilpfiction!

Natalia here, Brizy team

Please send me a private message on our FB chat and mention this issue inside.

Thank you!
Regards, Natalia

**Comment by ViorelEremia** [comment]
@pilpfiction can you change this line of code: https://github.com/ThemeFuse/Brizy/blob/master/editor/compiled-html.php#L72
with:
```$content = html_entity_decode( $content, ENT_QUOTES | ENT_HTML5, get_bloginfo( 'charset' ) );```

**Comment by NataliaBB** [comment]
Hello!

This bug was fixed and it will be updated in the next Brizy version. 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
