### ISSUE TITLE
Brizy page editor blank on all blocks

### ISSUE THREAD

**Issue by locnessman** [ThemeFuse/Brizy#554]
Not sure what happened, no new plugins added, nothing was updated. All of a sudden when i try to edit any page built with Brizy i get a grey screen saying "An error happened while trying to display this block
You canopen an issueorremove this block"

**Comment by NataliaBB** [comment]
Hi @locnessman! 
Natalia here, Brizy team.

Most probably there is a theme bug. But let's check this in a private message.

So, please send me your WP credentials via Facebook Chat and mention this issue inside:
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

Thank you!
Regards, Natalia

**Comment by locnessman** [comment]
I tried to message you in messenger. No reply



JOHN WARRINER

CSR Support | Marketing
Crazy Lennys E-Bikes

Text /Call : 608.371.7593<tel:608.371.7593>

Location  : Madison, WI


[facebook]<https://www.facebook.com/CrazyLennysEbikes/> [instagram]  [pinterest] <https://www.pinterest.com/crazylennysebikes/pins/>  [twitter]  [snapchat]






________________________________

**Comment by NataliaBB** [comment]
Hi @locnessman John!
Deep apologies for my late reply.

Please, mention this issue inside your FB message. It's very important to do this because in this way I can see you are coming from GH.

Now, I introduced a new file in our bot message: WP credentials. When you send me a message, choose this field https://jumpshare.com/v/iXkecYSUSlGEguktLrB4.

Waiting.
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi @KarineSabattier! 

Can you give me WP credentials via Facebook Chat and mention this issue inside:
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io

P.S In the future, please write a separate post, not as a comment on a bug report or a feature request.
Thanks!

Regards, Natalia

**Comment by KarineSabattier** [comment]
Hi!

Tks for your reply,

I'm new on Github and I don't know how can I response with you by facebook
chat. Can you explain me please?

Have a great day!

Le mar. 11 sept. 2018 à 05:34, NataliaBB <notifications@github.com> a
écrit :

**Comment by NataliaBB** [comment]
Hello @KarineSabattier!

You can send me the WP credentials on my email: chitoroagantaliav@gmail.com

My Best Regards, Natalia

**Comment by KarineSabattier** [comment]
Hi,

On this page:
http://jesuisdeuxieme.netlabs.ca/deuxieme-a-nouveau/

Here the credentials:

login: karine
Pass: Kapulet!

Le mar. 11 sept. 2018 à 05:38, NataliaBB <notifications@github.com> a
écrit :

**Comment by KarineSabattier** [comment]
I'm sorry,

pass: Kapu99let!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
