### ISSUE TITLE
How to disable google font and use my custom font?

### ISSUE THREAD

**Issue by wangneo** [ThemeFuse/Brizy#555]
Hi
Google font is not support our language, Can I disable it and use my custom font?
We don't need to upload or install font, only need to use css to custom the computer default font.
How to do that?
Or can you give me an css in theme to overwrite brizy css, make me can setting the computer default font?
We need this very much.

**Comment by NataliaBB** [comment]
Hi @wangneo!

Natalia here!

Unfortunately, you can not disable the current custom fonts and add yours.
We have this feature in our roadmap and it will be available soon

https://trello.com/c/JKK5n0wa/82-custom-fonts

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
