### ISSUE TITLE
woocommerce product page Brizy styling

### ISSUE THREAD

**Issue by SpaceProg** [ThemeFuse/Brizy#557]
Hello! 
Could you, please, help me? 
I am creating my site with Brizy and can't set brizy's style to woocommerce products. 
The problem is that I can only add some Brizy's block in product's description area, but structure of the products' pages is not changing, and I can't apply Brizy styles such fonts, colors and so on to the all parts and elements of the products' pages. As a result the pages doesn't look awersome.
I have seen video on youtube and in that example all elements of product page had Brizy style and looked very good. How can I do my site similary? How can I use Brizy on the whole page?
Thank you.

![image](https://user-images.githubusercontent.com/13136814/45074706-3227b180-b0ed-11e8-842d-033de467349d.png)

**Comment by NataliaBB** [comment]
Hello @SpaceProg!

You need to set this styling details from your WP dashboard. Brizy doesn't have style option for WOO products. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by abdul1903** [comment]
@NataliaBB is this option on Brizy's plans...?
