### ISSUE TITLE
Please remove the zoom animation of row/column setting button

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#56]
it's hard to click since zoom takes some time.
I think it would be easier to click button that is without animation, since I can click bigger button immediately.

**Comment by DimiBaitanciuc** [comment]
Here is the reason why we choose this solution: http://jmp.sh/ppnTMAL 
I've never encountered issues clicking the settings button for row / column.

**Comment by ash-f** [comment]
Thank you. I mean zoom itself is ok but transition is kinda annoying.
Probably without transition, it would be more comfortable.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/dyX1LHEt/166-please-remove-the-zoom-animation-of-row-column-setting-button

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
