### ISSUE TITLE
Brizy Pro 0.0.3 installed but is impossible to activate it

### ISSUE THREAD

**Issue by mariobarretta** [ThemeFuse/Brizy#563]
After the classic installation i receive ever this message 

Brizy Pro is inactive. Please install and activate Brizy first.!

and, in the plug in list, is not present  the settings option.
Someone can help me?

**Comment by NataliaBB** [comment]
Hi Mario!
Natalia here, Brizy team!

Do you have Free Version active? Brizy PRO works only when FREE is active.
Please check.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hey!

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards, Natalia

**Comment by mariobarretta** [comment]
Hi @NataliaBB  i'm sorry for delay .
i've installed, after, the free version but i do not found where to insert my license key to activate the pro version.
i see the free version with the settings but the pro has not ant setting

**Comment by NataliaBB** [comment]
Hi @mariobarretta 
You don't need a license right now. The key will be needed when we will have an "official" PRO launch. Now, you just need to install the PRO and start to edit your pages. 

Brizy PRO have now 3 features: Role Manager, Dynamic Content and Gallery.
Every week we will add a new feature. More info here:
https://brizy.io/blog/brizy-pro-launch/

Best Regards, Natalia

**Comment by mariobarretta** [comment]
Hello,
thank You but this mean that everyone can use and have these features?

**Comment by NataliaBB** [comment]
Hi @mariobarretta 
Yes, everyone who has PRO active. 
As I said, the Keys will be active when PRO version will have more feature. We plan for mid-October the full release.

Best Regards, Natalia

**Comment by mariobarretta** [comment]
OK Thank You.
Has been strange for me to read your words because actually evryone that shaer the brizy pro package can use it without having a license code.
I'll wait until the effective exclusive release 👍 
What will happen to all people that does not have a license code and has installed the pro package?

**Comment by NataliaBB** [comment]
Hey @mariobarretta!

Not all of the features and updates will be released till the official PRO release. We keep most of them after the release. 
Regarding your last question - even if the have PRO installed they will not receive updates. 

My Best Regards, Natalia

**Comment by mariobarretta** [comment]
Ok thankYou but they can use the pro version without having a license is correct? 
I'm asking you only to know what is the plus to have a PRO version rescpect those that are using the actual disposable pro version.
Thank You
