### ISSUE TITLE
Gallery alignment [BUG]

### ISSUE THREAD

**Issue by UniversalDesignz** [ThemeFuse/Brizy#567]
Hi guys,

I have notice there is a bug with the Gallery this seems like it's to do with the blank images and inserted images as you can see in the image. When a image gets inserted it goes back to normal.

![gallery issue](https://user-images.githubusercontent.com/15095585/45208714-25d55d00-b283-11e8-9412-fcce5846fc7a.png)

Kindest Regards
Jay

**Comment by NataliaBB** [comment]
Hi @UniversalDesignz 

Natalia here, Brizy team!

Thanks for reporting this!
Could you please send us your WP credentials via our FB chat:
https://jumpshare.com/v/i5bFUpOUtAAI3EVSuMMJ
Web Page: https://brizy.io 

Please, mention this issue inside the chat.

Thank you!
Regards, Natalia

**Comment by UniversalDesignz** [comment]
Hi @NataliaBB 

Sorry about the delay. I don't trust Facebook like many others and I have install Brizy just on my playground I can surely create you an admin credentials. Do you have any other alternative way for me to provide you with it?

Kindest Regards
Jay Vijay

**Comment by NataliaBB** [comment]
Hi Jay!
I understand, Facebook is a temporary solution to communicate with our customers. 
You can send me the credentials on my email: chitoroaganataliav@gmail.com

Thank you!
Regards, Natalia

**Comment by UniversalDesignz** [comment]
Hi @NataliaBB 

Sent, please check your inbox.

Kindest Regards
Jay Vijay

**Comment by NataliaBB** [comment]
Hi @UniversalDesignz 

Thanks! Already added this issue to our dev team. I will write a notification via your email when we will have the results.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
