### ISSUE TITLE
Image filename and attributes

### ISSUE THREAD

**Issue by aplusodesign** [ThemeFuse/Brizy#569]
Hi there,
i like brizy a lot incl. pro updates.

Am i right, that all image information (filname, alt and title attributes) are ignored when using brizy? Hence not visible for google?

Thanks and best regards

**Comment by NataliaBB** [comment]
Hi @aplusodesign 

Yes, at this moment they don't show up for search engines. 
But we are working on this module, it will be improved soon.

Thank you!
Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
