### ISSUE TITLE
LInk Color

### ISSUE THREAD

**Issue by mamionajourney** [ThemeFuse/Brizy#570]
The font color changes to light blue when I create a link. I can't change it to my theme color.

**Comment by NataliaBB** [comment]
Hi @mamionajourney! 

This is a style option which is needed to be improved.
For now, you can select the code colour of your theme (text) and past on the linked font colour. See this video: https://jumpshare.com/v/sykUo897quNQAA8UJZxx 

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by Paul-Huntsberry** [comment]
I see the video with the workaround for changing the text link color, but that only will change a single text color link. I would like to change the color of the all text links and hover colors to be one of the **global** custom colors in Brizy, but currently it defaults to a cyan color. How do you change the color of all the text links globally? Even if the theme (currently testing with OceanWP) link color is changed in the theme customization / General Styling, the link color is somehow overwritten to the cyan color.

It also seems to add an additional text space in front of and after the text link that does not appear in the brizy editor, but does appear incorrectly on the live page. See screenshots of the word "mind" which is a link.

![screen shot 2018-09-24 at 8 07 05 pm](https://user-images.githubusercontent.com/17347127/45990553-b3f86400-c035-11e8-8fc9-728e937dab82.png)
![screen shot 2018-09-24 at 8 07 48 pm](https://user-images.githubusercontent.com/17347127/45990554-b490fa80-c035-11e8-8bfd-365322122015.png)
![screen shot 2018-09-24 at 8 08 31 pm](https://user-images.githubusercontent.com/17347127/45990555-b490fa80-c035-11e8-859a-86c9c1497f44.png)

Is there a suggested theme to test with Brizy at this time?

Thanks,
Paul

**Comment by NataliaBB** [comment]
Hi Paul @Paul-Huntsberry 

You can set the colour for links globally only with custom CSS.  You need also to write the code including this tags:
a { color: red!important }
a: hover { color: blue!important }

The theme (even OceanWP) will not allow you to set links globally without CSS code. 
My Best Regards, Natalia
