### ISSUE TITLE
Copy & Paste Text has style problems

### ISSUE THREAD

**Issue by hlaporthein** [ThemeFuse/Brizy#575]
When I paste some text in default style. Text color has changed. I think it shouldn't be happened like that from UX point. Sorry, you did that action intentionally, close my issues. I just only suggest.

**Comment by NataliaBB** [comment]
Hi @hlaporthein!

Can you send me more details of our FB chat? Please include this issue in your message: 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45360918-8d6c0f00-b5d9-11e8-9d4f-a2ef7270069c.png)


Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
