### ISSUE TITLE
No showed photo on editor

### ISSUE THREAD

**Issue by bendiro** [ThemeFuse/Brizy#578]
Hi Staff,
yesterday after last update I'm not able to see photo on page editor. I can change it, I can open media gallery but when I choose a picture the editor doesn't show it. 
But when I publish the page I can see photos on published page.

Thanks
Roberto

**Comment by NataliaBB** [comment]
Hello Roberto!

Please, send me a message via our Facebook chat. 
Please mention this issue inside.

Thank you
Regards, Natalia

**Comment by NataliaBB** [comment]
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45426888-1e102100-b6a6-11e8-879b-c7e3fde639ed.png)

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
