### ISSUE TITLE
Form button text cannot be edited!

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#58]
Guys, the form button text cannot be edited at all from "Button" to anything else. A button element works fine but the form button is not.

**Comment by bagrinsergiu** [comment]
Hi @quantumleap33, 

It is working fine for me on Windows + Chrome and Mac + Chrome: http://jmp.sh/mjD8A3y
Can you give me more details ( OS, Browser, ...) ?

Thanks for reporting
Sergiu

**Comment by quantumleap33** [comment]
Hi, yeah, it seems to be working on Chrome. But not on Firefox. I am on Win10 with latest vesion of Firefox here...

**Comment by bagrinsergiu** [comment]
@quantumleap33 

Added in to do list.

**Comment by bagrinsergiu** [comment]
Solved in 1.0.9

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Sergiu
