### ISSUE TITLE
My mobile view doesn't show in browsers

### ISSUE THREAD

**Issue by mindset305** [ThemeFuse/Brizy#580]
Hello, I finished creating a website with brizy using the OceanWP theme and I noticed my mobile view doesn't show in browsers. 

Here is my website: https://rooferss.com/

I have no issues with desktop just mobile for some reason.

**Comment by NataliaBB** [comment]
Hey @mindset305 

Please, send me a message on our Facebook chat.
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45426824-f1f4a000-b6a5-11e8-848c-3db3e46d80e6.png)

Please include this link in your message.
Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi @mindset305 

Open https://brizy.io/ and you will find the Facebook icon in the right corner of the page.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
