### ISSUE TITLE
broken images

### ISSUE THREAD

**Issue by Rikkab** [ThemeFuse/Brizy#583]
Hello,

I have several images throughout my site that appear broken when visiting the live page however, when in preview mode images appear normal. 

How do I rectify this?

Best regards, 

Rikka

**Comment by NataliaBB** [comment]
Hi Rikka!

Please, send us your WP credentials via our Facebook chat.
Please, mention this issue in your message.

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45427203-f8374c00-b6a6-11e8-825e-ebef5a28d9df.png)


Thank you
Best Regards, Natalia

**Comment by Rikkab** [comment]
I have resolved this issue.

Thank you.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
