### ISSUE TITLE
Future Request: Dynamic Content | Block/Row/Column Background Image | Link to Featured Image, etc

### ISSUE THREAD

**Issue by pellissierjp** [ThemeFuse/Brizy#587]
Please allow the background images for blocks, rows, and columns to draw dynamic content, like featured image.

Regards,
JP

**Comment by NataliaBB** [comment]
Hi @pellissierjp 
Natalia here, Brizy team
Sorry for my late reply, background images for blocks will be added right in the next update. For the rest - still working.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
