### ISSUE TITLE
Active brizy will lost oceanwp theme's custom

### ISSUE THREAD

**Issue by wangneo** [ThemeFuse/Brizy#588]
Hi, I'm using Oceanwp theme, but When I using brizy, Oceanwp custom will be nothing but widget, any one has same issue?

**Comment by NataliaBB** [comment]
Hi @wangneo 
We work on this issue now. I will come back with a reply when it will be fixed.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hey @wangneo 

Fixed!

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
