### ISSUE TITLE
Why no dynamic content but template option in free version?

### ISSUE THREAD

**Issue by toton333** [ThemeFuse/Brizy#589]
Hi, there is a template option in Brizy free, but what is the use of that if no dynamic contents are available in the free version?

**Comment by NataliaBB** [comment]
Hi @toton333 
Natalia here.

Now you can create 404 pages, archives, woo pages and so on. 
Further, in the free version, we will extend the Dynamic Content functionality, but in limited options.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
