### ISSUE TITLE
Float form button to the right

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#59]
It would be nice for the form button to be automatically float to the right when the form fields' widths are smaller.

**Comment by bagrinsergiu** [comment]
Hi @quantumleap33,

I understand what you mean. Fields (33% + 33%) + Button (33%)
We plan to this and a lot of others improvements to form in future

Thanks for suggestions
Sergiu

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/zOIzZUHS/69-inline-button-in-forms

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
