### ISSUE TITLE
Left side bar is blank when you activate the 'Pro' and shows fine when you have the free version 

### ISSUE THREAD

**Issue by naturalcollection** [ThemeFuse/Brizy#592]
Left side bar is blank when you activate the 'Pro' and shows fine when you have the free version - it is therefore impossible to edit anything in the pro other than what is there already since the left grey bar at the top is just blank
![blank](https://user-images.githubusercontent.com/43218600/45446884-f4ff8880-b6c5-11e8-8761-cd7690c16557.png)

**Comment by naturalcollection** [comment]
@DimiBaitanciuc

**Comment by NataliaBB** [comment]
Hey @naturalcollection!

In the Role Manager tab, try to set full access option for all users, 
https://jmp.sh/x9UfOKh
 
Regards, Natalia

**Comment by naturalcollection** [comment]
Thank you but this does not appear to work. Still got the issue and have
tried cache and that's not it either. It's also a Themefuse theme. Really
annoying as I paid a lot for the product.

**Comment by NataliaBB** [comment]
Hi @naturalcollection 
Sorry for my late reply and for this inconvenience. I've fixed this bug in your dashboard!

Please, send me a message via our Facebook chat or on my email chitoroaganataliav@gmail.com if you have any other questions related  to this issue (or any other)
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
