### ISSUE TITLE
[Feature Request] - Download Button

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#597]
A separate option to access the media library to add/upload PDF etc.

**Comment by NataliaBB** [comment]
Hi @curiousprojects 

This feature is in our do to list: 
https://trello.com/c/lA4gJ3bA/53-download-button-option

Best Regards, Natalia

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
