### ISSUE TITLE
Brizy migration problem

### ISSUE THREAD

**Issue by tzils** [ThemeFuse/Brizy#598]
Hi guys, I try to migrate brizy installation using all in one migration plugin, but it stops at about last step and can't finish. Proviously it's never happend. Below the lines i get when i try to access the address where i should see the website:

Warning: require_once(__DIR__/composer/autoload_real.php) [function.require-once]: failed to open stream: No such file or directory in /wp-content/plugins/brizy/vendor/autoload.php on line 5

Fatal error: require_once() [function.require]: Failed opening required '__DIR__/composer/autoload_real.php' (include_path='.:/:/usr/local/php5/lib/pear') in /wp-content/plugins/brizy/vendor/autoload.php on line 5

**Comment by NataliaBB** [comment]
Hi @tzils 
Natalia here, Brizy team!

Please send me a message on our Facebook chat and mention this issue inside.
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45555540-bdb5e680-b841-11e8-8f77-9676b2e6e3c3.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
