### ISSUE TITLE
IP on my server gets blocked

### ISSUE THREAD

**Issue by dwsworks** [ThemeFuse/Brizy#599]
Using Brizy had blocked my IP on my web server. 

They said that my IP was doing some type o malicious activity

mod_security triggered 

Also, I observed that I have nothing else installed on my WordPress install except brizy, It blocked my IP several times. Unable to work on my project.

**Comment by NataliaBB** [comment]
Hi @dwsworks 
Natalia here, Brizy team.

Please send us a message on our Facebook chat, mention this issue inside your message.
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45553627-1e8ef000-b83d-11e8-8d80-a162114abe0a.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
