### ISSUE TITLE
Reorder Blocks preview does not refresh with updated block content

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#60]
When trying to reorder blocks that have been started with existing template blocks, change them, then try to reorder them the thumbnail preview on the pane at the right still displays the original template thumbnail and not the updated block thumbnail.

**Comment by bagrinsergiu** [comment]
Hi @quantumleap33,

It is in out to do list. We need more time to finish this task. 

We have 2 options: 
1. Browser Screenshots 
2. Server Side screenshots

With browser it is not possible to
1. Automate screenshots 
2. Screens for blocks with iframes (maps, video, ...)

With server side we don't have access to 
1. WP content 
2. WP Specific shortcodes + Menu + ...

Thanks for suggestions
Sergiu

**Comment by quantumleap33** [comment]
Yeah, it seems challenging! Maybe with either solution try and replace dynamic elements with some sort of placeholder?

**Comment by bagrinsergiu** [comment]
@quantumleap33 

Nope. I like screens :)

**Comment by quantumleap33** [comment]
Me too! I meant the content inside the screens that cannot be generated?

**Comment by bagrinsergiu** [comment]
@quantumleap33 - in 1 week i plan to start with this feature again. Thanks for suggestion

**Comment by NataliaBB** [comment]
Hi!
This feature is added in our roadmap: https://trello.com/c/Bey1hFce/111-blocks-thumb-generation

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
