### ISSUE TITLE
Error shown modifying a page with Brizy Pro

### ISSUE THREAD

**Issue by Alliance8791** [ThemeFuse/Brizy#600]
When i try to modify a page with Brizy, it prompts this:
Warning: Invalid argument supplied for foreach() in /web/htdocs/xxxxxxxxxxxxxxxx.it/home/test/wp-content/plugins/brizy-pro/content/providers/acf.php on line 17

I have Brizy Pro 0.0.4

**Comment by NataliaBB** [comment]
Hi @Alliance8791 

We discussed on chat, and I've sent you the zip file and instruction.
Please let me know if everything works now.

Thank you!
Regards, Natalia

**Comment by Alliance8791** [comment]
This problem is solved, now we are trying to solve the problem of the #.
Ciao


Il giorno ven 14 set 2018 alle ore 15:43 NataliaBB <notifications@github.com>
ha scritto:

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
