### ISSUE TITLE
[BUG] Dynamic Content > Not showing Post Title and Featured Image

### ISSUE THREAD

**Issue by EdwinDJanssen** [ThemeFuse/Brizy#601]
Instead of showing the post title, it shows the title of the template. And the featured image isn't shown in a single post, only on the archived post page, which is controlled by the WP Theme.

See screenshots. The Post Title here is "Random Heading", but instead it says "Single Posts" which is the name of the Brizy template.

I'm using the Astra Theme, but I've tested this w/ other themes, same result.

<img width="425" alt="screen shot 2018-09-14 at 15 38 02" src="https://user-images.githubusercontent.com/42695419/45553449-3615ab00-b834-11e8-9701-19f88784e765.png">

<img width="1070" alt="screen shot 2018-09-14 at 15 43 02" src="https://user-images.githubusercontent.com/42695419/45553735-f7ccbb80-b834-11e8-8e66-22626e84e0bc.png">

<img width="311" alt="screen shot 2018-09-14 at 15 39 15" src="https://user-images.githubusercontent.com/42695419/45553752-01562380-b835-11e8-9414-f6d3bb6d38ac.png">

<img width="1156" alt="screen shot 2018-09-14 at 15 39 52" src="https://user-images.githubusercontent.com/42695419/45553760-061ad780-b835-11e8-9b3f-816cf1b9e98a.png">

<img width="1090" alt="screen shot 2018-09-14 at 15 45 18" src="https://user-images.githubusercontent.com/42695419/45553855-42e6ce80-b835-11e8-87a9-bd3670f5c385.png">

**Comment by EdwinDJanssen** [comment]
Found it > Yoast Plug-in is causing the above problems. Yoast is a very important plug-in to have, so I hope this issue will be solved....

**Comment by alecszaharia** [comment]
Acest bug a forst rezolvat deja.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
