### ISSUE TITLE
Issue with Images not showing on page

### ISSUE THREAD

**Issue by sueanned3** [ThemeFuse/Brizy#602]
When I add an image box or use one of your blocks with an image and change the image, the image shows up in the image holder but will not show up on the page nor can I save it. 

![about new brizy successful blogging](https://user-images.githubusercontent.com/43273083/45557251-2d5caf00-b80b-11e8-906e-22a6b4a49c63.png)

Thanks!
Sue

**Comment by NataliaBB** [comment]
Hi Sue @sueanned3 

Natalia here! 
Could you please send me a message on our Facebook chat? Please, mention this issue inside: 
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45613864-49ad5580-ba70-11e8-8371-cdefed3f9fc2.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
