### ISSUE TITLE
Products Page

### ISSUE THREAD

**Issue by Rikkab** [ThemeFuse/Brizy#604]
Hello, 

I have built a product page with the woocommerce tool. However, when I click the add to cart, nothing happens or the page reloads when testing the page. 

Please advise how to rectify. 

Best regards, 

Rikka

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
