### ISSUE TITLE
Issue with Video Container

### ISSUE THREAD

**Issue by vr0nsky** [ThemeFuse/Brizy#605]
Hello Sergiu,
pls, did you solved this bug:

https://github.com/ThemeFuse/Brizy/issues/412

**Comment by NataliaBB** [comment]
Hi @vr0nsky!
Natalia here, Brizy team

Sorry for my late reply!
Please send me a message via our Facebook chat and mention this issue inside. 
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
