### ISSUE TITLE
Icons shows small in Edge and do not show at all in in IE 11

### ISSUE THREAD

**Issue by ysandhu** [ThemeFuse/Brizy#606]
when i use icon in brizy editor . They look fine in chrome. but any variation to icon size is not shown in edge browser and no icons are shown in IE 11 at all.

I have brand new install of wordpress with only Brizy installed with default theme.

Thanks

**Comment by NataliaBB** [comment]
Hi @ysandhu 
Natalia here.

Unfortunately, the IE is a problem for us at this moment, so we must work and improve this module a lot. 
I added this issue on our roadmap, so you will be able to see it when it will be fixed. 

https://trello.com/c/3mT4htSU/119-icons-for-ie

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
