### ISSUE TITLE
Loading time takes forever in both Free and Pro versions

### ISSUE THREAD

**Issue by EduceSolutions** [ThemeFuse/Brizy#607]
Hi, I have bought your Pro package and after installing V4, the loading time became unacceptable to the point I have to remove the plugin to be able to edit my site. 

Today it happen again even with the free version so I have to stop working!

**Comment by NataliaBB** [comment]
Hi @EduceSolutions 
Do you have some extensions added in your browser?  (Adblock, for example?)
Please, test the editor on different browsers. 

If you still face this problem, send me a message on our facebook chat.

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
