### ISSUE TITLE
Mobile page not appeared properly

### ISSUE THREAD

**Issue by EduceSolutions** [ThemeFuse/Brizy#608]
The mobiles version has issues with margin and doesn't look even with many letters missing on one end on the free version (I had to remove my Pro plug in because of the loading time).

**Comment by NataliaBB** [comment]
Hi @EduceSolutions 

I would like to test this issue from your WP dashboard.
Please, send me your credentials via our Facebook chat/or on my email: chitoroaganataliav@gmail.com

Thanks
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
