### ISSUE TITLE
Icons not appeared in both desktop and mobile versions

### ISSUE THREAD

**Issue by EduceSolutions** [ThemeFuse/Brizy#609]
All the icons that I set up could be sent on editor but not on the preview or live version of my site.

**Comment by NataliaBB** [comment]
Hi @EduceSolutions

Please, send me your credentials via our Facebook chat/or on my email: chitoroaganataliav@gmail.com

Thanks
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
