### ISSUE TITLE
Not Able to Use Brizy on my Home Page Anymore

### ISSUE THREAD

**Issue by jessikajake** [ThemeFuse/Brizy#614]
I have the tThemefuse theme Reel Story, and though this page still looks good: https://emanantwellness.com/true-you/
my home page won't show the Brizy content anymore. 
Home page = https://emanantwellness.com

In the past, you helped me change the page template so that I could still use the normal header/footer (and you can see these on the "true-you" page above still). In order to show header/footer and have full width pages I have been picking the "Visual Builder" as the page type. This still works for the true-you page. 

For the home page however, even if I set the page to Brizy Editor, I still see the old home page that I made way back. The Brizy content is still there (thank goodness). I just can't get it to apply to the home page. Ideally it would work like the true-you page (which is set to "Visual Builder" as the page type, but was created using the Brizy editor.) Thanks in advance for your help!

**Comment by jessikajake** [comment]
I think the issue may be-- page that existed prior to Brizy are reverting back to Visual Builder content. This page also reverted back to old (VB) content: https://emanantwellness.com/somatics

As with the home page, if I launch Brizy, I can still see the new page we made (as an admin). Let me know if you can help soon bc I think I can call my server company up and revert my site back to a snapshot.

**Comment by jessikajake** [comment]
(The "true-you" page was created *after* I bought Brizy and it is fine.)

**Comment by kevinpauls** [comment]
I am also running into this same issue. Since the most recent update I can see my page in the page builder but it only publishes the default theme not the Brizy Template.

**Comment by jessikajake** [comment]
Update: we decided to revert our site for now. Please let me know when this is sorted out. Thanks!

**Comment by jessikajake** [comment]
Can you let us know when this is issue is fixed? Thanks!

**Comment by NataliaBB** [comment]
Hello @jessikajake 
Fixed at your side!

You need to disable Unsyon framework on the pages created with Brizy.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by jessikajake** [comment]
How do I do that? 


Sent on my Virgin Mobile Samsung Galaxy S8+.
-------- Original message --------From: NataliaBB <notifications@github.com> Date: 10/11/18  12:01 AM  (GMT-08:00) To: ThemeFuse/Brizy <Brizy@noreply.github.com> Cc: jessikajake <jessikajake@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [ThemeFuse/Brizy] Not Able to Use Brizy on my Home Page Anymore
  (#614) 
Hello @jessikajake

Fixed at your side!
You need to disable Unsyon framework on the pages created with Brizy.
My Best Regards, Natalia

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ThemeFuse/Brizy","title":"ThemeFuse/Brizy","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/ThemeFuse/Brizy"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NataliaBB in #614: Hello @jessikajake \r\nFixed at your side!\r\n\r\nYou need to disable Unsyon framework on the pages created with Brizy.\r\n\r\nMy Best Regards, Natalia"}],"action":{"name":"View Issue","url":"https://github.com/ThemeFuse/Brizy/issues/614#issuecomment-428843666"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ThemeFuse/Brizy/issues/614#issuecomment-428843666",
"url": "https://github.com/ThemeFuse/Brizy/issues/614#issuecomment-428843666",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [ThemeFuse/Brizy] Not Able to Use Brizy on my Home Page Anymore (#614)",
"sections": [
{
"text": "",
"activityTitle": "**NataliaBB**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@NataliaBB",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"ThemeFuse/Brizy\",\n\"issueId\": 614,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"ThemeFuse/Brizy\",\n\"issueId\": 614\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/ThemeFuse/Brizy/issues/614#issuecomment-428843666"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 380285929\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by jessikajake** [comment]
Please reopen or otherwise help me. The home page is fixed, but you reverted this page back to the old version: https://emanantwellness.com/somatics/

Can you make sure that one shows the Brizy version as well? Thanks!
