### ISSUE TITLE
Wordpress Shortcode

### ISSUE THREAD

**Issue by DAVidjovan** [ThemeFuse/Brizy#615]
I can't click on the WP widget shortcode to edit it.
here is the page dancehallcelebrities com

**Comment by NataliaBB** [comment]
Hi @DAVidjovan!
Natalia here.

I'm not sure if I understand you correctly. You may have 2 points:
1. When you add a WP widget, the editing sidebar doesn't appear: https://jumpshare.com/v/B8gN3eZ6QfnT4HJUK5Kg 

2. When you add a WP widget, you can not edit as you wish (due the limited editing options from the sidebar)

Please, specify!
Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
