### ISSUE TITLE
Icons Not Showing in Editor

### ISSUE THREAD

**Issue by charlottenj11** [ThemeFuse/Brizy#616]
I just installed Brizy but icons are not showing in the editor when I drag/drop.

I've read that many others had this problem and it was resolved but nowhere does it state what the solution was. How do I fix this?

Browser: Chrome (Trying clearing cache.)
WP: 4.9.8
PHP: 7.1.17

Thanks...

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by charlottenj11** [comment]
Hi Natalia,

I'm sorry, I forgot all about it. After I submitted that issue I figured
out a workaround. Yes, closing is fine.

Many thanks,

Charlotte Melillo, PMP
*Certified Project Management Professional*
16 LinkedIn Recommendations
<https://www.linkedin.com/in/charlotte-melillo-pmp-6124701b/>
732.570.7721
