### ISSUE TITLE
Pages frequently disable content 

### ISSUE THREAD

**Issue by rkgraham12** [ThemeFuse/Brizy#618]
When editing pages with Brizy, it must be "active" to show content properly on the pages built with the builder. (ie.. when going "back to WP editor" the content made in Brizy will not be shown as created.)

Is this a known bug, something being worked on, or something I am missing?

Video of bug
https://www.dropbox.com/s/orburd2m82fm1m1/BrizyBug.mp4?dl=0

**Comment by NataliaBB** [comment]
Hi @rkgraham12 
Natalia here, Brizy team!

When you edit a Brizy page (and afterwards will save that page) with wp builder, the Brizy editor will be disabled. Therefore all content will disappear. And Yes, Brizy should be active all the time.  
To go back with Brizy, you just need to click on "edit with Brizy "  button.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
