### ISSUE TITLE
Row grey icon almost invisible in full width

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#62]
When you add a row and you are in full width mode, the grey row arrow is half hidden between the left bar making it very difficult to select.
https://imgur.com/a/XT55uAO

**Comment by bagrinsergiu** [comment]
Hi @quantumleap33,

Yes is a problem. I added it to our list of features/ improvements. 
Thanks for suggestion.

Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/ymZMC9u2/167-row-grey-icon-almost-invisible-in-full-width

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
