### ISSUE TITLE
Menu Anchor

### ISSUE THREAD

**Issue by ysandhu** [ThemeFuse/Brizy#620]
I use Menu Achor a lot. It is just a way to jump to particular position on page. I know I can use code block.. but that create a section and it is visible. 

Is it possible to add something like what elementor used.
https://docs.elementor.com/article/62-menu-anchor

This is the most useful tool one you have one pager website.

Thanks

**Comment by NataliaBB** [comment]
Hi @ysandhu!
Natalia here.

Did you try to use our Anchor option? 
https://jumpshare.com/v/OXm6iJxNKdEsEJAxSDmM

Regards, Natalia

**Comment by ysandhu** [comment]
That looks great. Thanks for pointing out. I was more looking for actually assigning an Achor at particular section/element and use it via menu options. Even from different pages to get to that point.

Thanks

**Comment by NataliaBB** [comment]
Hi @ysandhu 
Great! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by ysandhu** [comment]
Please keep issue open. this option only links anchor with in same page. I was asking if I can create a anchor for block with specific name and use it anywhere.

**Comment by ysandhu** [comment]
Please refer to how elementor does. It lets you create an anchor with specific name anywhere and then you can create a mneu entry .. even to refer if on diff page.

**Comment by kguldent** [comment]
Indeed please leave this open. Keep in mind that blocks are not rendered according the actual template but keep the original (see an issue that you are trying to resolve). The ability to create anchorpoints in a page (be it on a row / a column / a block) is a (nowadyas) basic feature in all builders.

**Comment by MaxZiebell** [comment]
+1 individual anchor names on sections.
