### ISSUE TITLE
[BUG] Form error - cannot edit plugin settings

### ISSUE THREAD

**Issue by jwarnox** [ThemeFuse/Brizy#621]
When clicking a form button to edit the plugin settings, nothing happens and get this console error:

editor.pro.js?ver=2:1 Uncaught TypeError: Cannot read property 'sectionPopup' of undefined
    at Module.i (editor.pro.js?ver=2:1)
    at Object.getItems (editor.js?ver=1.0.57:1)
    at r.B.renderPortal.e [as renderPortal] (editor.js?ver=1.0.57:1)
    at x.a.getActive.setTimeout (editor.js?ver=1.0.57:1)

I am using Brizy Pro 0.0.5

I need to edit the send to email details

regards,
Jamie

**Comment by NataliaBB** [comment]
Hi Jamie!
Natalia here!
It seems we have a JS conflict.

Please, send me your WP credentials via our Facebook chat, or on my email: chitoroaganataliav@gmail.com

Thanks!
Regards, Natalia

**Comment by jwarnox** [comment]
Hi Natalie,

I have emailed you some temp admin creds for you to login and have a look.

thanks,
Jamie

**Comment by NataliaBB** [comment]
Hi Jamie!
This bug has been solved in the 1.0.31 Version.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
