### ISSUE TITLE
Gallery Feature/Addon [Pro]

### ISSUE THREAD

**Issue by peleroberts** [ThemeFuse/Brizy#622]
Is it possible for the gallery [pro] to have the option of adding text [heading] over the top of the gallery and then adding an overlay color to the whole gallery so the heading stands out ?

Thanks

**Comment by bagrinsergiu** [comment]
Hi Pele

We plan to extend Gallery ( adding text [heading], horizontal grid, tags (tabs), ... ) but we need time :)

I added this suggestion in our public roadmap: https://trello.com/c/7Ol4FS3W/163-gallery-heading-overlay-color

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
