### ISSUE TITLE
Brizy Template will not publish over the base template we had before

### ISSUE THREAD

**Issue by vitog** [ThemeFuse/Brizy#623]
Please help as this is extremely urgent.

**Comment by NataliaBB** [comment]
Hi @vitog 
Please, me a message via our FB chat. Please mention this issue inside your message.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by MadelieneE** [comment]
Hi I made a template and was wondering how I can download the files?

**Comment by vitog** [comment]
You can download, All in One Migration. And Export your files. 

Sincerely, 

Vito Giovannetti 
Phone: 647 267 7498

**Comment by MadelieneE** [comment]
Thank you for your reply. I am really new at this. So in learning as I go.

Regards
Madeliene Edwards

**Comment by vitog** [comment]
My Pleasure!

Sincerely,

Vito Giovannetti

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
