### ISSUE TITLE
Issue with AFC

### ISSUE THREAD

**Issue by Estes-GG** [ThemeFuse/Brizy#629]
Invalid argument supplied for foreach() in /app/public/wp-content/plugins/brizy-pro/content/providers/acf.php on line 17

See screenshot
<img width="1518" alt="screen shot 2018-09-18 at 1 53 31 pm" src="https://user-images.githubusercontent.com/30507492/45709808-82216200-bb4a-11e8-8845-8067da1ab4a1.png">
.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
