### ISSUE TITLE
size of embed element code popup

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#63]
Would be nice if it's re-sizable or close to full screen.
It's awkward to edit codes.

**Comment by bagrinsergiu** [comment]
H @ash-f,

Thank you for suggestion. We planned it for iFrames and other small piece of codes. 
Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/KWkMGXLO/150-embed-element-code-popup

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
