### ISSUE TITLE
Carousel On mobile view

### ISSUE THREAD

**Issue by anselmelly** [ThemeFuse/Brizy#633]
Might be a bug.
The carousel on mobile view shows ridiculous width :smile: 
This makes it not visible on responsive screens
on Chrome & firefox

![conm__01](https://user-images.githubusercontent.com/192270/45757517-3ba43400-bc2c-11e8-80d0-d6841cff052c.png)

**Comment by pilpfiction** [comment]
I had the same issue. Restarted by using carousel layout as provided by brizy and then added and substituted with content step-by-step. Now the carousel works on my mobile, but don't know why it didn't work with the first try. The preview while editing the page in brizy shows the carousel correct in both cases.

**Comment by NataliaBB** [comment]
Hi @anselmelly and @pilpfiction 
Natalia here! 
Sorry for this late reply. We fixed this bug, it will be updated in the next plugin version.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
