### ISSUE TITLE
feature request: SVG as image

### ISSUE THREAD

**Issue by margjordan** [ThemeFuse/Brizy#635]
Please consider adding the ability to use .svg's as images

**Comment by NataliaBB** [comment]
Hi @margjordan!

Thanks for your suggestion!
We added to our public roadmap: https://trello.com/c/wrfhV9sj/7-image-svg-support

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
