### ISSUE TITLE
Feature Request: Style Form E-Mails

### ISSUE THREAD

**Issue by vagrantjo** [ThemeFuse/Brizy#636]
Please add the ability to style the e-mails that are sent via forms. Or at least put some effort into a default styling, right now the e-mail it just sent as plain text with the title "Contact Form" sent from "Wordpress". This is similar to Divi's forms. I switched to WP Forms because of this oversight. It's an easy feature to add. And it makes it a lot easier for clients to read.

**Comment by NataliaBB** [comment]
Hi @vagrantjo 

Thanks for your suggestion!
We added into our public roadmap: https://trello.com/c/okiBczzz/120-form-style

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
