### ISSUE TITLE
I can't put an email address for forms

### ISSUE THREAD

**Issue by paulfuentes** [ThemeFuse/Brizy#64]
I don't find where put my email address for catch the messages from form. Where is it?

**Comment by bagrinsergiu** [comment]
Hi Paul @paulfuentes ,

We have a issue with form configurations. We plan to fix it in next update.
Sorry for the inconvenience.

Sergiu

**Comment by mlnepost** [comment]
is this already solved? can't seem to connect my e-mailadress either..

**Comment by bagrinsergiu** [comment]
Hi @mlnepost,

It is in work right know. We plan to add it in next big update. (~6 days)

Thanks for reporting
Sergiu

**Comment by Massimoivaldi** [comment]
hi, any news about this bug fix?

**Comment by bagrinsergiu** [comment]
Hi

This has been fixed and will be included in the next update (1.0.12), thanks for reporting.

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Sergiu
