### ISSUE TITLE
Goes on loading doesn't shows editor when i changed to default template

### ISSUE THREAD

**Issue by tracygipson** [ThemeFuse/Brizy#640]
I just changed my page to default template from brizy template.
and the page just loads but doesn't open the editor. I tried reloading the page but still does the same thing editing page doesn't show up!
![screenshot 12](https://user-images.githubusercontent.com/9466279/45811634-3ce86600-bceb-11e8-8ad5-93e54dc40dde.png)

**Comment by camelon02** [comment]
I am having the same issue today. Everything was fine until now. I uninstalled and reinstalled both the regular and pro versions of the plug in. Hosting on Siteground Go Geek.

**Comment by NataliaBB** [comment]
Hi @camelon02 , Hi @tracygipson ! 

Please, send me your wp credentials via our Facebook chat, mention this issue inside (url link). Thanks

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45939869-54bb3500-bfde-11e8-9ab3-8871d9a93429.png)


Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
