### ISSUE TITLE
It is not updating

### ISSUE THREAD

**Issue by leeeunhwa1017** [ThemeFuse/Brizy#643]
I made a nice page and hit UPLOAD button but it is not updating at all

**Comment by NataliaBB** [comment]
Hi @leeeunhwa1017!
Natalia here!
Please update both versions (Free and PRO).
If the problem still appears, please send me a message via our Facebook chat, and mention the issue inside (url link)
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45940547-6d2d4e80-bfe2-11e8-8dcb-dc7392524980.png)

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
