### ISSUE TITLE
brizy has encountered an unrecoverable error.

### ISSUE THREAD

**Issue by McScience** [ThemeFuse/Brizy#644]
Update Failed: Could not copy file. brizy / README.md 
will appear and will not be updated.

![123](https://user-images.githubusercontent.com/43457831/45854160-96e93a00-bd84-11e8-94a1-c7cf81cb3290.jpg)

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
