### ISSUE TITLE
can I edit the name of new section 

### ISSUE THREAD

**Issue by jithins123** [ThemeFuse/Brizy#645]
Is it possible to edit the name of a section, so that when I link it to a certain section using internal anchor to the section, it shows website.com/#about_us instead of website.com/#rbfefuxz something like this

**Comment by NataliaBB** [comment]
Hi @jithins123 
Natalia here!
No, for the moment you can not edit the name of any sections. 

But, added into our rodmap:
https://trello.com/c/92i5vRTQ/122-custom-name-blocks

we have also in our roadmap the blocks thumb option: 
https://trello.com/c/Bey1hFce/111-blocks-thumb-generation

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
