### ISSUE TITLE
Full height sliders no longer displaying correctly

### ISSUE THREAD

**Issue by fbu87** [ThemeFuse/Brizy#646]
After updating from v1.0.28 to v1.0.32 the Full Height setting no longer works for section sliders.

**Comment by NataliaBB** [comment]
Hi @fbu87 
Natalia here!

Can you send me a message via our Facebook chat? Please mention this issue inside.
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45942213-3c511780-bfea-11e8-940c-27b249bd0b18.png)



Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
