### ISSUE TITLE
Removing margins hides options

### ISSUE THREAD

**Issue by ReisHill** [ThemeFuse/Brizy#647]
When playing with the Carousel feature, I removed the margins to create a thinner design. However this stopped me from opening the carousels features to uplicate a page etc as the container options where showing above the carousel options.

I have increased the top margin in the screenshot to show you what I mean.
Hope this helps

![screen shot 2018-09-22 at 10 45 12](https://user-images.githubusercontent.com/43493429/45915904-25c58780-be55-11e8-8df2-ce2a8f874dcb.png)

**Comment by NataliaBB** [comment]
Hi @ReisHill!
Natalia here

We work on this issue right now and we will come with an update when it will be fixed.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
