### ISSUE TITLE
Unable to Upload Images

### ISSUE THREAD

**Issue by chapelno** [ThemeFuse/Brizy#648]
When editing a page using Brizy I am not able to upload photos.  After clicking the cloud/arrow icon to upload the image the screen goes gray as if a popup or something is supposed to appear, but it doesn't.  See the before and after images attached.  

I'm using the Core Child theme with Wordpress 4.9.8.  Brizy version 1.0.33.  Experiencing the issue using Chrome on a Mac and PC and Firefox on a PC.  

Any thoughts?

<img width="1440" alt="before" src="https://user-images.githubusercontent.com/43507716/45923304-74504180-bea8-11e8-9dfc-9e06ccc3015e.png">

<img width="1440" alt="after" src="https://user-images.githubusercontent.com/43507716/45923305-7914f580-bea8-11e8-9b1c-fdadc213b8a8.png">

**Comment by NataliaBB** [comment]
Hi @chapelno !

Natalia here!
Can you please send a message via our Facebook chat? Please, mention this issue inside (url link)

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45941595-97353f80-bfe7-11e8-9644-f6fac15ef1f1.png)


Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi @chapelno! 
 
Disabled and enabled the A3 fixed W3 total cache plugin and the images start to load.

Further, if you will have this kind of issues, just check the installed plugins (in case in the console you will not find any errors code)

Thank you!
Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by chapelno** [comment]
Thank you for that - it appears that there is some conflict between
the plugin and Brizy.

**Comment by chapelno** [comment]
Well, one more question now.  I've updated this page -
https://vetsappeals.com/legal-services/va-benefits-appeals/how-va-rates-mental-disorders/
- using Brizy, but the version I created weeks ago using the Wordpress
visual builder is still the one that appears.  I just edited it this
morning (by uploading those photos) but Wordpress shows the latest edits as
weeks ago.

What do I need to do to get the Brizy version to show? Thanks again.

[image: image.png]

**Comment by NataliaBB** [comment]
Hi @chapelno 
You need to disable Unsyon and continue to edit with Brizy. If you use moth editors in the same time, the Unsyon will rewrite all Brizy changes.
We still looking how to save this issue, hope to find a solution very soon.

Best Regards, Natalia

**Comment by chapelno** [comment]
Hm.  If I disable Unyson, all my other non-Brizy pages go haywire.  So it
seems like you're telling me I either need to redesign the whole site in
Brizy.  Until I can do that, though, I should continue using the older
editor.  Right?
