### ISSUE TITLE
Issues vertical text

### ISSUE THREAD

**Issue by floword22** [ThemeFuse/Brizy#649]
Hi,
I’ve got a problem with the text: every text come vertically and I don’t know how to change that. Can someone help me please ?
Thanks a lot !

**Comment by NataliaBB** [comment]
Hi @floword22 
Natalia here!

Can you give me a screenshot for this issue?

Thanks!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
