### ISSUE TITLE
some issue the new post update version 0.0.8

### ISSUE THREAD

**Issue by jamaalhassan** [ThemeFuse/Brizy#652]
![post fix](https://user-images.githubusercontent.com/43518055/45954416-e473da00-c004-11e8-8ac3-8e5793b05b62.gif)

**Comment by NataliaBB** [comment]
Hi @jamaalhassan!

Thanks for reporting this! We would like to investigate this issue from your dashboard.
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by HQRaja** [comment]
I'm facing the exact same issue.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
