### ISSUE TITLE
[Post - Enhancement] Request for pagination and lazy-load for Post

### ISSUE THREAD

**Issue by pawaphop** [ThemeFuse/Brizy#653]
Could we have a pagination and a lazy-load features on the Post elements? Just like many portfolio plugins. That would be awesome.

BTW, I couldn’t post in Brizy’s community, and couldn’t leave any comment in brizy.io website. The captcha mighy be broken, please take a look.

**Comment by NataliaBB** [comment]
Hi @pawaphop 

At the moment pagination is not supported, but we will work on it.
Lazy-load features  - are coming in the next few updates.

About comments on Brizy's community - thanks, we will take a look.

Thank you!
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
