### ISSUE TITLE
Brizy content not showing

### ISSUE THREAD

**Issue by svfreebird** [ThemeFuse/Brizy#654]
So, when I try to edit a page in Brizy it allows me to edit it but when I save it, nothing shows up on the actual page when I try viewing it on my website. It also doesn't load the image when I try uploading one into the editor.

**Comment by codeclinic** [comment]
The new cookie blocking tools in Firefox can cause similar issues. You might want to check that https://static.brizy.com isn't being blocked.

**Comment by NataliaBB** [comment]
Hi @svfreebird 
Natalia here, Brizy team.
Sorry for my late reply.
If you still have this issue on your page, please send me a message and include this issue number inside - #654 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
