### ISSUE TITLE
Background images not loading

### ISSUE THREAD

**Issue by svfreebird** [ThemeFuse/Brizy#655]
My background images are not loading in the editor and when I try to upload one and save it to my website it deletes my content on that page. 

The only images that will load and that I can see when I upload them to the page are the pre-packaged images that come with Brizy.

**Comment by NataliaBB** [comment]
Hi @svfreebird 

Please send me a message via our Facebook chat and mention this issue inside: 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by sondes** [comment]
I can confirm the same behavior in Firefox 65.0 (64-bit) and Chrome 72.0.3626.96 (Official Build) (64-bit).

Row backgrounds are not visible in the live editor but can be seen in the preview and on the front end of saved pages.

![brizy - row backgrounds not visible in live editor](https://user-images.githubusercontent.com/913448/52499995-12178500-2b9a-11e9-91c6-091f773cb2aa.png)
