### ISSUE TITLE
Problem with menu spacing

### ISSUE THREAD

**Issue by simulateurequestre** [ThemeFuse/Brizy#658]
Hello,
I've got a problem on my menu spacing, i've creating my menu on WP as they explained. And then on brizy everything appears without any space. If I click on the spacing option and change it, nothing changes.

Do you know how to do it ? 
![report bug 2](https://user-images.githubusercontent.com/43602066/46067927-4143d180-c178-11e8-9101-0baa68953ac8.JPG)
![report bug](https://user-images.githubusercontent.com/43602066/46067928-4143d180-c178-11e8-8115-257adb1e78cc.JPG)

**Comment by NataliaBB** [comment]
This bug was related to the Theme used. 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
