### ISSUE TITLE
Feature Suggestion: Header Animations

### ISSUE THREAD

**Issue by dnnsjsk** [ThemeFuse/Brizy#66]
I’m sure you guys are working on header and footer options. It would be awesome to have some animation options for headers when scrolling down (and the header becomes sticky)

Options could include resizing of the header container when scrolling down, resizing of the logo etc.

**Comment by bagrinsergiu** [comment]
@dnnsjsk,

It is in our to do list. Demo Link: http://test-de12d4.bitblox.site:9000/editor/brizy

**Comment by ash-f** [comment]
Would be nice if it cloud use "Headroom" effect buy just sticky.
Lately many of modern websites have this.
https://wicky.nillia.ms/headroom.js/

**Comment by bagrinsergiu** [comment]
Hi 

Added to Brizy Roadmap: https://trello.com/c/85d4Eyxs/45-element-block-header-footer

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
