### ISSUE TITLE
[Feature Request] Support for CSS #id selector

### ISSUE THREAD

**Issue by jjdbrinker** [ThemeFuse/Brizy#660]
Hi guys! 
I'm a big fan of the editor, but I didn't find any options to add an #id CSS selector to rows. This would be extremely useful if you're trying to create a single page with anchors instead of URLs. 

How feasible is this?

**Comment by MaximPro** [comment]
Please allow to easily see all css effects in text for every element to see as a list on the sidebar, just like yellow pencil does it.
Also, if not yet done, only do static id's, not like divi, wich changes the id's!

**Comment by NataliaBB** [comment]
Hello @jjdbrinker . @MaximPro 
This feature is added in our to do list: https://trello.com/c/28aUD9q8/108-yellow-pencil-visual-css-style-editor

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
