### ISSUE TITLE
Multisite/Domain Mapping Breaks Brizy Editing

### ISSUE THREAD

**Issue by willhousecreative** [ThemeFuse/Brizy#661]
I have a multisite installation with a mapped domain. I wanted to edit a page and clicking the "Edit with Brizy" link takes me to http://[mappeddomain]/contact/?brizy-edit 

This completely breaks Brizy.

Interestingly, the other quick links presented when hovering over pages (i.e. Edit | Quick Edit | Trash) all link to something like: http://[multisitedomain]/[multisite-site]/wp-admin/post.php?post=25&action=edit

So, it looks like Brizy's edit links are different then those presented by Wordpress. 

To get around this I manually enter my edit page URL with something like: http://[multisitedomain]/[multisite-site]/contact/?brizy-edit

Not ideal because Clients/Editors/Contributers would have no idea to do this so I can no longer allow them to edit their own pages. 

Apart from the above, what is the support for Brizy and Wordpress multisite? 

As a matter of record, here is the other issue I found related to Multisite [https://github.com/ThemeFuse/Brizy/issues/427](url)

**Comment by NataliaBB** [comment]
Hi @willhousecreative 
Natalia here!

Please send me your WP credentials via our Facebook chat and mention this issue inside. 

https://brizy.io/
![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)



Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by yournet** [comment]
Are there any news regarding this issue?

I have a similar problem, although I don't use domain mapping but just subdomains. It is a complete clean installation with Brizy and Brizy Pro activated on network-level.

It is working on the main site (that don't use a subdomain), but not working on the child sites (that use subdomains). When I click on "Edit with Brizy" it just opens the site but without Brizy.

**Comment by cmbc58** [comment]
Just experienced the same problem. Has this been an unresolved issue for over a year?? Can hardly believe that...
