### ISSUE TITLE
Text Blocks Not "Undo-able"

### ISSUE THREAD

**Issue by codeclinic** [ThemeFuse/Brizy#664]
When editing text blocks, it seems that a lot of the time you can't undo the changes with the undo button.

So for example... Say I make a bunch of edits to the page, then I decide to change some text. I add a new text block to the page and edit this. So, I paste over the default text with my new text but realise that I've now lost the formatting (eg colour or markup, etc) and press the undo button to return it back to it's initial/ prior state. 

The undo button ignores the text changes and continues down the history of changes undoing those. It's as if the text edit isn't recorded but everything else before it was. So, I can click undo and revert any number of actions prior to the text edit, but the text edit itself can not be reverted. This happens frequently, although it appears that prior text edits can  be undone as long as they are not current/the most recent edit. Once I've tried to -unsuccesfully- undo a current text edit, it seems that this one edit is permanently lost from the edit history. So, even if I do edit elsewhere, that one text edit can no longer be undone since it appears that it was never recorded as being an edit.

**Comment by NataliaBB** [comment]
Hi Phil! @codeclinic 
I would like to look on this issue from your admin panel and to do some tests.
Therefore, Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
