### ISSUE TITLE
Saved / Global Block Previews

### ISSUE THREAD

**Issue by codeclinic** [ThemeFuse/Brizy#665]
When saving a block, this block is saved with the "Started From Scratch" image rather than a thumbnail preview of the actual saved block. So all saved blocks have the same preview image in the editor.

The exception to this rule is when saving a block that was originally added to the page from the starter content blocks (templates). If one of these is added to a page, edited then saved, it will show in the "saved" tab using the original preview image as shown under the template Blocks tab. This is true regardless of what changes have been made to this block prior to it being saved. So, with viewing it fully it appears to be the same as the built-in template blocks, and can look nothing like the actual saved content if it was significantly customised.

So, either way, the saved blocks are not very easy to work with since you have to remember what a saved block actually looks like. These preview really need to reflect the actual saved block content. Ideally we should be able to name them too, inorder to make them useful on a larger site.

Long term it's be really useful to be able to export & import saved blocks from one site to another.

**Comment by codeclinic** [comment]
The above also applies when saving a block as a Global.

**Comment by NataliaBB** [comment]
Hi Phil @codeclinic 

We have this option in our to list - https://trello.com/c/Bey1hFce/111-blocks-thumb-generation
We will try to manage asap with it.

Thank you!
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
