### ISSUE TITLE
Premade Block Images

### ISSUE THREAD

**Issue by codeclinic** [ThemeFuse/Brizy#666]
When adding some pre-made (template) blocks [from the page builder pop-up] the default images do not show. If you click on the image to edit it, the image is there, but the image does not appear on the page.

However, if you move the focal point of the image, the image will from this point be shown on the editable page.

It looks like these images are added by JS, and because they are added from premade blocks the relevant JS script which loads them is not trigger as it would be if the image/block was manually added. Moving the image focal point evidently triggers the script which would normally reload the image.

**Comment by NataliaBB** [comment]
Hi Phil @codeclinic 
I suppose you have there a conflict with another plugin.  Did you check the console on the code source errors?
Please, give me more details on our Facebook Chat message and mention this issue inside.


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by codeclinic** [comment]
I have tried this on a clean install with no other plugins beside Brizy in use.

**Comment by NataliaBB** [comment]
@codeclinic 
Let me test please the plugin on your dashboard.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
