### ISSUE TITLE
Doing a Ctrl Z n footer gave me error

### ISSUE THREAD

**Issue by sarika** [ThemeFuse/Brizy#667]
Screenshot
https://cl.ly/056c446e5be3

**Comment by NataliaBB** [comment]
Hi @sarika!
Natalia here, Brizy team.
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by jonbonnar** [comment]
did you resolve this? my footer also keeps crashing

**Comment by NataliaBB** [comment]
@jonbonnar 
If you have the same issue, please send us a message via our Facebook chat and we will look on this error.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
