### ISSUE TITLE
Can't load editor and warnings appearing on site

### ISSUE THREAD

**Issue by thealikhan** [ThemeFuse/Brizy#668]
Updated the plugin earlier today and now the following warnings are appearing:
Warning:  base64_decode() expects parameter 1 to be string, array given in /home/alikhan8/public_html/wp-content/plugins/brizy/editor/api/project.php on line 47
Warning:  json_decode() expects parameter 1 to be string, array given in /home/alikhan8/public_html/wp-content/plugins/brizy/editor/api/project.php on line 51

I also can't access the editor at all. Would love some help as the site is now live.

Thanks!

**Comment by NataliaBB** [comment]
Hi @thealikhan 

This issue was fixed in the 1.0.36 update.

Thank you!
My Best Regards, Natalia
