### ISSUE TITLE
Brizy and astra theme pro with hooks

### ISSUE THREAD

**Issue by GRP2016** [ThemeFuse/Brizy#669]
Brizy is so great but at the moment I cannot use it😞because I have astra pro theme wich allows hooks. But when I use them it gets a fatal error. Without brizy not. Maybe there is a workaround ?

**Comment by NataliaBB** [comment]
Hey Gian! @GRP2016 
Sorry for the inconvenience.
We know about this issue and @bagrinsergiu and the team are working now on this. We are also in discussion with Astra team for this question and we really hope to solve this in the very near future.

Thank you!
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
