### ISSUE TITLE
Section background image upload

### ISSUE THREAD

**Issue by webangon** [ThemeFuse/Brizy#67]
Isn't section background image should open wordpress media uploader instead of default browser uploader?
![capture](https://user-images.githubusercontent.com/7946657/40716080-994feba4-6429-11e8-8adc-2740e7dabc02.PNG)

**Comment by bagrinsergiu** [comment]
Hi @webangon 

Yes. It is. http://dl4.joxi.net/drive/2018/05/30/0028/0732/1860316/16/44a3c3514a.jpg

However I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Thanks for reporting
Sergiu
