### ISSUE TITLE
Button hover styling

### ISSUE THREAD

**Issue by cmbc58** [ThemeFuse/Brizy#670]
Is there a way to style a button in hover state. If so it is not very obvious! (Or perhaps it is and I am being dim.) I want to change the border in the main button:
http://lovefromkate.co.uk/lfk1/brizy

**Comment by cmbc58** [comment]
Just found the tab - BUT it's not that obvious! Could it be somehow be made clearer?? I can't be the only one who has been hunting for it...

**Comment by NataliaBB** [comment]
Hi Ben @cmbc58 
Natalia here!
We know about this inconvenience and we have in our to do list this improvement, but for the moment we don't have solutions.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
