### ISSUE TITLE
Responsive needed imrovements or issues

### ISSUE THREAD

**Issue by Josecarpeniet** [ThemeFuse/Brizy#672]
Hi

Brizy should be more customizable in responsive. Some improvements that I would like (Maybe you have already detected it, and you are going to change this in the future):

- Elements can't be reordered.
- Add elements only in mobile version should be more natural because I can add them in desktop and then hide them there to show them just in mobile, but that means Brizy has to adapt it to responsive view and the results are not so good.
- Some background images look nice on the desktop but my iPhone doesn't show them but android is showing them (I don't know if this is an issue or what).
- Some Images have an excellent display on the desktop view but terrible in mobile (maybe I haven't learned how to resize or modify them).

**Comment by DimiBaitanciuc** [comment]
Good points, thanks for adding this issue. You've forgotten about Tablet mode :) and breakpoints control. No worries, we have everything in mind, there is still room for improvement and we'll get there one step at a time. 

Thanks again.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
