### ISSUE TITLE
Version 1.0.35 update

### ISSUE THREAD

**Issue by century4biz** [ThemeFuse/Brizy#673]
Hi There,

I just update to Version 1.0.35 after few minute using previous version, but when I try to edit my page (same page and other) open up edit with brizy, my page become mess up, big icon all over the place, white space and all lost, including the brizy panel. I am a beginner making website, I dont know what happen, I dont know what to do, please help me.

Thank you.

**Comment by nivelsur** [comment]
Hello,
You could show a screenshot or indicate the URL of your site

**Comment by century4biz** [comment]
this what it look like...
![capture](https://user-images.githubusercontent.com/43682452/46239393-a68f0100-c3ca-11e8-9d26-538c0d4ac6b5.PNG)

**Comment by nivelsur** [comment]
the section you want to edit this with the brizy template?
https://tmpsee.com/VmFOM1dyZGtUUGhWcUk5REVHaSsvUT09

**Comment by century4biz** [comment]
cannot access what you try to show...

**Comment by TCDTRapla** [comment]
If it helps (I had the same problem), see the screenshot below
If I remember : see Brizy template and try with another out of the Brizy template...
![capture d ecran 2](https://user-images.githubusercontent.com/28975080/46273273-1cbf6f00-c555-11e8-8493-4f1a65420615.png)

**Comment by century4biz** [comment]
unfortunately, that panel don't even exist....
I even try from the outside at page attribute...
![capture2](https://user-images.githubusercontent.com/43682452/46296641-677ccd80-c5cd-11e8-9fa8-262010b310fd.PNG)
 and even try to : Deactivate > Delete (uninstall) and then install it back... same result..

but, Thank You : )

**Comment by TCDTRapla** [comment]
Try with the new version Brizy free 1.0.36
It's new one from this day pm

**Comment by century4biz** [comment]
yeah, already done that too...

**Comment by TCDTRapla** [comment]
And still no access to the panel and the page template? Very strange.
All your pages were made with Brizy?
Well this is my limit to help you ... Sorry
May be contact Brizy via Messenger. Bye

**Comment by NataliaBB** [comment]
Hi @century4biz!
Natalia here, Brizy team!
I would like to test the plugin in your dashboard.
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)


Thanks, @TCDTRapla for assisting on this issue!
Thank you!
Regards, Natalia

**Comment by century4biz** [comment]
Thank You, @NataliaBB ..

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
