### ISSUE TITLE
Trying to get property 'post_type' of non-object in brizy/admin/templates.php on line 399

### ISSUE THREAD

**Issue by KyleAtDND** [ThemeFuse/Brizy#674]
There's some circumstances where the Brizy runs getTemplateForCurrentPage(), but it isn't on a page. On my server, it seems to be when Varnish is doing some activity. I've put the $_SERVER global below. Could we get some extra checks on this to prevent this error:

[28-Sep-2018 12:54:18 UTC] PHP Notice:  Trying to get property 'post_type' of non-object in /home/******.cloudwaysapps.com/dvantkzwxu/public_html/wp-content/plugins/brizy/admin/templates.php on line 399
[28-Sep-2018 12:54:18 UTC] Array
(
    [SERVER_SOFTWARE] => Apache/2.4.10 (Debian)
    [REQUEST_URI] => /feed/
    [USER] => ***********
    [HOME] => /home/******.cloudwaysapps.com/***********
    [SCRIPT_NAME] => /index.php
    [QUERY_STRING] => 
    [REQUEST_METHOD] => GET
    [SERVER_PROTOCOL] => HTTP/1.0
    [GATEWAY_INTERFACE] => CGI/1.1
    [REDIRECT_URL] => /feed/
    [REMOTE_PORT] => 42282
    [SCRIPT_FILENAME] => /home/******.cloudwaysapps.com/***********/public_html/index.php
    [CONTEXT_DOCUMENT_ROOT] => /home/******.cloudwaysapps.com/***********/public_html/
    [CONTEXT_PREFIX] => 
    [REQUEST_SCHEME] => http
    [DOCUMENT_ROOT] => /home/******.cloudwaysapps.com/***********/public_html/
    [REMOTE_ADDR] => 127.0.0.1
    [SERVER_PORT] => 80
    [SERVER_ADDR] => 127.0.0.1
    [SERVER_NAME] => www.websiteurl.org
    [SERVER_SIGNATURE] => <address>Apache/2.4.10 (Debian) Server at www.websiteurl.org Port 80</address>
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [HTTP_X_FORWARDED_FOR] => 94.46.***.***, 127.0.0.1
    [HTTP_CF_CONNECTING_IP] => 94.46.***.***
    [HTTP_X_VARNISH] => 620922746, 1082120
    [HTTP_X_MAXCDN_CACHESTRING] => *****-*****.raikfcquaxqncofqfm7/feed/
    [HTTP_X_URI] => /feed/
    [HTTP_X_REQUEST_SCHEME] => https
    [HTTP_VIA] => 1.1 squid.org (squid/3.5.20)
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.1
    [HTTP_REFERER] => 
    [HTTP_ACCEPT_LANGUAGE] => en
    [HTTP_ACCEPT_CHARSET] => windows-1251,utf-8;q=0.7,*;q=0.7
    [HTTP_ACCEPT] => image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, application/vnd.ms-powerpoint, application/vnd.ms-excel, application/msword, */*
    [HTTP_CF_VISITOR] => {\"scheme\":\"https\"}
    [HTTP_CF_RAY] => 46165b8f8d6c63d9-DFW
    [HTTP_CF_IPCOUNTRY] => US
    [HTTP_ACCEPT_ENCODING] => gzip
    [HTTP_CONNECTION] => close, close
    [HTTP_X_VERSION] => 2614
    [HTTP_X_APP_USER] => ***********
    [HTTP_X_APPLICATION] => varnishpass
    [HTTP_X_FORWARDED_HOST] => www.websiteurl.org
    [HTTP_X_FORWARDED_PROTO] => https
    [HTTP_HOST] => www.websiteurl.org
    [HTTP_X_REAL_IP] => 94.46.***.***
    [proxy-nokeepalive] => 1
    [SERVER_ADMIN] => [no address given]
    [TZ] => America/Chicago
    [WPR_ENC] => _gzip
    [WPR_SSL] => -https
    [HTTPS] => on
    [cw_allowed_ip] => 1
    [REDIRECT_STATUS] => 200
    [REDIRECT_SERVER_ADMIN] => postmaster@websiteurl.org
    [REDIRECT_TZ] => America/Chicago
    [REDIRECT_WPR_ENC] => _gzip
    [REDIRECT_WPR_SSL] => -https
    [REDIRECT_HTTPS] => on
    [REDIRECT_cw_allowed_ip] => 1
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1538139257.1394
    [REQUEST_TIME] => 1538139257
)

**Comment by ViorelEremia** [comment]
The function ```getTemplateForCurrentPage``` should run in any part of the wordpress. It defines the which template to run on that part where you are for example if you are on the archive category page ```Cars``` it defines the template by rules added in Admin Dashboard -> Brizy -> Templates. 
So if you have a template added for category ```Cars``` then this function will extract it. In this function, we use the default wp functions to define where we are 404, author, search, ... etc.
 And this global $_SERVER doesn't help us because I think Wordpress use the $GLOBALS for checking the location. Can you send your ftp/admin credentials because I can't understand from my environment how that can happen ```viorel@themefuse.com```

**Comment by NataliaBB** [comment]
Hi Kyle @KyleAtDND 
Natalia here, Brizy team!

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by KyleAtDND** [comment]
I just tested it and it happens whenever I got to websiteurl.org/feed/. Seems to be trying to load a template for the RSS feed. Easy fix would be to check if the variable is an object, and abort if it is not (because if it isn't an object, you won't be able to get a result for getTemplateForCurrentPage()).

**Comment by ViorelEremia** [comment]
@KyleAtDND to add an if is not always a solution. Can you try to add this [commit](https://github.com/ThemeFuse/Brizy/commit/2e80251dbd9fc85df20cc1e94e7e5c112d4aed59) to your server?
There's one change in the file ```admin/templates.php```.

**Comment by KyleAtDND** [comment]
@ViorelEremia, great solution! Does the trick.
