### ISSUE TITLE
Brizy plugin not loading pages -- constant spinning

### ISSUE THREAD

**Issue by nrenae** [ThemeFuse/Brizy#677]
The Brizy plugin is constantly attempting to load up pages, but never finished the loading cycle. Please fix this issue.
<img width="1193" alt="screen shot 2018-09-29 at 1 03 48 am" src="https://user-images.githubusercontent.com/43693094/46241248-943da480-c383-11e8-832f-cbcc55cfe4b9.png">

**Comment by NataliaBB** [comment]
Hi @nrenae 
Natalia here, Brizy team!

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by Ayes80** [comment]
Over the last 3 month's I have issues with my Brizy plugin, I have removed the plugin and then installed. I have cleared my cache and still the same issue. I have the latest version etc, etc. Can anyone assist?

The screen is permanently looking like this:
![brizy screenshot](https://user-images.githubusercontent.com/46242652/50540814-bae0c680-0b90-11e9-8cd4-9daab417a272.png)
