### ISSUE TITLE
EMBED option not working in BRIZY EDITOR after latest update. 

### ISSUE THREAD

**Issue by mdhymadmct** [ThemeFuse/Brizy#678]
![image](https://user-images.githubusercontent.com/43704480/46247471-893d4f80-c429-11e8-8c4e-091749713a8f.png)
![Uploading image.png…]()
![brizy error](https://user-images.githubusercontent.com/43704480/46247461-5eeb9200-c429-11e8-9a7c-310d632ac417.jpg)

![Uploading image.png…]()

When iam trying to add HTML coding language using EMBED option. 

It is not working . Appears Normal text as like TEXT option .
Pls resolve this issue
Earlier it was working fine.

**Comment by NataliaBB** [comment]
Hi @mdhymadmct!
Sorry for this inconvenience!
We fixed this issue in today's update - 1.0.36.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
