### ISSUE TITLE
Some bugs after updating

### ISSUE THREAD

**Issue by allardo** [ThemeFuse/Brizy#679]
Hi there,

Loving Brizy and site is coming along nicely! Unfortunately some problems occured after updating free version..

Pictures which previous worked and showed are not shown in the live version, in the brizy edit they show but not live. Pictures disappear only after updating a page.. Almost every page of my website have no pictures now anymore.. This page is affected by it the most: https://markyourspot.nl/ons-werk/

Next to that: in the Brizy edit mode, when I would like to add a block the icons of the content blocks are mixed up i think. If I add a text block I get a button and some other icons are mixed up as well.

Hope you can help me get this fixed, very hard to get the site ready now!

**Comment by NataliaBB** [comment]
Hi @allardo 
Regarding the toolbar issue -  it has been fixed in today's update.
Regarding the image issue -  it was a http/https problem,  we solved using the ForceHTTPS plugin.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
