### ISSUE TITLE
Transparent settings panel

### ISSUE THREAD

**Issue by LordNorman** [ThemeFuse/Brizy#68]
Is there a way you could make the settings panel transparent so as to see what you are changing underneath? When applying margin or padding to the element underneath you cannot see what is happening.

<img width="419" alt="screen shot 2018-05-30 at 9 11 06 pm" src="https://user-images.githubusercontent.com/39765533/40717808-17a85596-6451-11e8-8c3b-fb9f115800c7.png">

**Comment by bagrinsergiu** [comment]
Hi @LordNorman, 

Hey, this is a very interesting idea. Thanks for suggestion

Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/azyn1ewb/144-right-panel

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
