### ISSUE TITLE
Bulk load images

### ISSUE THREAD

**Issue by cmbc58** [ThemeFuse/Brizy#680]
Are there plans to add feature so that we can bulk load images to galleries and carousels. Only being able to do this one image at a time is really time consuming. I think it is VITAL to add this feature as it is available in both Divi and Elementor - the main competitors.

Sorry if this has already been asked for. I have tried to search both this site and the Trello Roadmap board, but could find nothing.

**Comment by NataliaBB** [comment]
Hi Ben @cmbc58!

Yes, we have in plan to add bulk load images. We will return to this improvement (and many other) after full PRO release!

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
