### ISSUE TITLE
Multisite - Incorrect icons.svg file URL caused security problem

### ISSUE THREAD

**Issue by nhanledev** [ThemeFuse/Brizy#683]
I test the plugin in multisite environment.
The installation use custom `wp-contents` folder (bedrock).

The builder works great in multisite with subdomain = false.
When the subdomain = true, icons.svg file request to load from root domain instead of current subdomain, that causes

```
editor.vendor.js:53 Unsafe attempt to load URL https://mydomain.com/app/plugins/brizy/public/editor-build/editor/icons/icons.svg from frame with URL https://test.mydomain.com/?brizy-edit. Domains, protocols and ports must match.
```
![capture](https://user-images.githubusercontent.com/28459250/46257208-396d8f80-c4e0-11e8-91b7-84df67011559.PNG)

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
