### ISSUE TITLE
Include Divi-Builder & Yellow Pencil Design Features in Brizy

### ISSUE THREAD

**Issue by MaximPro** [ThemeFuse/Brizy#684]
Just look what Divi-Builder & Yellow Pencil already can, especially those great designing features like gradients etc and include it nicely in Brizy!

This would be the Best!
Thx for developing!

**Comment by NataliaBB** [comment]
Hi @MaximPro 
Natalia here, Brizy team

Gradients are in our to-do list: https://trello.com/c/Ls3RZZa2/61-element-gradient 
Check other design features there, and vote for them. If you have any other special request, feel free to ask and we will include in our to do list.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
