### ISSUE TITLE
Running into a weird issue on the site where I'm testing Brizy and Brizy Pro.

### ISSUE THREAD

**Issue by webfocusdesign** [ThemeFuse/Brizy#685]

**Comment by NataliaBB** [comment]
Hi @webfocusdesign 
Natalia here!

Please, give us more details on your question. 
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
