### ISSUE TITLE
reordering blocks

### ISSUE THREAD

**Issue by disbound** [ThemeFuse/Brizy#688]
When trying to reorder blocks the individual blocks do not move to where the item is placed. They fall in random order and will not switch placement.

**Comment by NataliaBB** [comment]
Hi @disbound!

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
