### ISSUE TITLE
[Feature Request] Images from `External URL` support

### ISSUE THREAD

**Issue by nhanledev** [ThemeFuse/Brizy#689]
**Issue**

When using cloud storage to store file, or the images are imported from external URL, Brizy could not render it properly (404 error).

The images are returned from the site's domain name, which look like `https://domain.com/?brizy_media=wp-05094c57241322db805824da9b1ffb9a&brizy_crop=iW%3D638%26iH%3D408%26oX%3D46%26oY%3D0%26cW%3D545%26cH%3D408&brizy_post=2`, I have to turn off the cloud storage and use native file store at wp-content/uploads, and I don't like it.

**Comment by cuongtalentccc** [comment]
Love this feature that we can upload the image from external URL

**Comment by DimiBaitanciuc** [comment]
Thanks for the suggestion, we'll look into it.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
