### ISSUE TITLE
Phone (number) in forms not displaying properly

### ISSUE THREAD

**Issue by LordNorman** [ThemeFuse/Brizy#69]
When viewing the form the number entry is smaller than the other boxes.

<img width="541" alt="screen shot 2018-05-30 at 9 44 56 pm" src="https://user-images.githubusercontent.com/39765533/40718400-2cb97152-6453-11e8-88c3-65605fa2745a.png">

<img width="483" alt="screen shot 2018-05-30 at 9 45 23 pm" src="https://user-images.githubusercontent.com/39765533/40718479-817e0324-6453-11e8-816b-3b1d767f40ff.png">

**Comment by bagrinsergiu** [comment]
Hi @LordNorman,

Thanks for reporting. 
Sergiu

**Comment by bagrinsergiu** [comment]
Hi @LordNorman,

Can you give me a demo link with your page? I con't reproduce it on my side. 

http://dl4.joxi.net/drive/2018/06/03/0019/0888/1307512/12/d4853fdd42.jpg

Thanks 
Sergiu

**Comment by LordNorman** [comment]
Hi Sergio

I’m currently on a local site. Am hoping to have it online in next week or so. If it’s still doing it I will get back in touch.

Thanks again
Gregg

On 3 Jun 2018, at 9:35 pm, bagrinsergiu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @LordNorman<https://github.com/LordNorman>,

Can you give me a demo link with your page? I con't reproduce it on my side.

http://dl4.joxi.net/drive/2018/06/03/0019/0888/1307512/12/d4853fdd42.jpg

Thanks
Sergiu

**Comment by bagrinsergiu** [comment]
@LordNorman 

Hi Gregg,

Can you gime me theme name + link?

editor - http://prntscr.com/jovt9s
preview - http://prntscr.com/jovtpg
preview mobile - http://prntscr.com/jovu0p

Thanks 
Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu
