### ISSUE TITLE
Add link

### ISSUE THREAD

**Issue by gapabon** [ThemeFuse/Brizy#693]
When added link in button, this can not update. 

![1](https://user-images.githubusercontent.com/10568589/46358548-333cf780-c635-11e8-86e1-7df87a82a0a9.png)

loading... loading... loading........

![2](https://user-images.githubusercontent.com/10568589/46358549-333cf780-c635-11e8-85af-e0d34d16ee46.png)

**Comment by gapabon** [comment]
Right. Is 1.0.36 with pro 0.0.9.

Thanks,

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
