### ISSUE TITLE
Icons rendering at wrong sizes in Microsoft Edge

### ISSUE THREAD

**Issue by witworm** [ThemeFuse/Brizy#694]
For every occurrence of a Brizy icon in Microsoft Edge, the scale and crop is completely off. It's either too big and cropped, or much smaller than the wysiwyg preview. They look perfectly fine in Chrome, Firefox, and Safari.

Here's the website of record: [www.chiefcustomer.com](www.chiefcustomer.com)

Comparison:
![cc-icons-in-chrome](https://user-images.githubusercontent.com/3484781/46361198-04c21b00-c63b-11e8-8a23-bb6602d9bba1.png)
![cc-icons-in-edge](https://user-images.githubusercontent.com/3484781/46361274-2b805180-c63b-11e8-865d-8db105e992ee.png)

**Comment by NataliaBB** [comment]
Hi @witworm 

Natalia here, Brizy team
At this moment, Brizy does not support Icons on IE, but we have this improvement in our to do list: 
https://trello.com/c/3mT4htSU/119-icons-for-ie

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
