### ISSUE TITLE
Hyperlink format

### ISSUE THREAD

**Issue by chrizjr** [ThemeFuse/Brizy#696]
Hi,

The hyperlink option of the text box will automatically **force** the **color blue** and **line break**, which is _unchangeable_.

-----------------------------------------------
e.g. 
Aim: Please (hyperlink)  click  (/hyperlink) here for more details.

Result:
Please
click 
here for more details.

-----------------------------------------------
I have tried to remove the line break and colour format in classic edit but in vain. 

Thanks for your kindly help and for developing such a great tool!

Best,
Chris

**Comment by NataliaBB** [comment]
Hi @chrizjr !
Natalia here, Brizy team
Sorry for this inconvenience.

We have this improvement in our to do list: https://trello.com/c/abkAqzvg/102-text-link-color-hover-color. We will try to update this option asap.

Thank you!
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
