### ISSUE TITLE
Brizy page not showing Live

### ISSUE THREAD

**Issue by jo-mansura-v** [ThemeFuse/Brizy#697]
Hi guys,
I made my page a Brizy page and all was fine. But suddenly, I click on the link and find that the live view has reverted to the ugly old template page! (I have made it blank for now) I clicked on “Edit with Brizy” and all my changes are visible, but whether I update or preview, only the old page comes up. Please help.

**Comment by NataliaBB** [comment]
Hi @jo-mansura-v 
Natalia here! 

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
