### ISSUE TITLE
Insert Video does not let us Embed Video from WP media and FTP etc [BUG]

### ISSUE THREAD

**Issue by UniversalDesignz** [ThemeFuse/Brizy#698]
Hi @NataliaBB 
Why is insert videos restricted to youtube and vimeo? How can we embed an video from my wp media, ftp or any other site?

Kindest Regards
Jay

**Comment by cuongtalentccc** [comment]
I want to embed video with external URL that from my cloud storage.

**Comment by NataliaBB** [comment]
Hi @UniversalDesignz, @cuongtalentccc 
Right now you can add video only from youtube and vimeo. We will add the wp library soon: https://trello.com/c/roS1N0WS/32-video-from-wp-library

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
