### ISSUE TITLE
Yoast SEO plugin and Brizy - Alt attributes

### ISSUE THREAD

**Issue by BogdanGCondurache** [ThemeFuse/Brizy#7]
**Alt attributes** for pages using Brizy are not recognised by Yoast SEO plugin, even if the alt texts are set for images in the Media Library

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/AVcWpZXo/85-yoast-seo-brizy-alt-attributes

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu

**Comment by bagrinsergiu** [comment]
@alecszaharia - asta cred ca e acelas ca si cu image title/ alt

**Comment by alecszaharia** [comment]
Corect.
