### ISSUE TITLE
Every New Pro Update is Launced, Its useless

### ISSUE THREAD

**Issue by dwsworks** [ThemeFuse/Brizy#700]
Yes, Its Useless, as we are waiting for updates, and we just get to download the updated pro zips, but not knowing exactly what has been changed in the update and how to use it. We are just enjoying downloading the updates, and trying to find nothing in it. Please let us know how to use the new updates, and give us some info about the update. Each update email has 

We’ve just added Toolset and Pods support in Brizy Pro. Starting today you can create and display dynamic custom fields added with any of these two popular plugins.

Tell us how to use it. Where are the updated options in the Brizy which we can use with those plugings. I spent hours searching youtube videos and brizy videos to find nothing to show how to use those plugins.

Please let us know what updates are you doing and how to use each of them. We have paid money to see nothing working still.

**Comment by DimiBaitanciuc** [comment]
Hi @dwsworks, every newsletter comes with an extensive blog post that explains what was added with examples. In every newsletter, we include a button at the bottom that has a link as @dmccan mentioned that goes to the blog post. 

The same link can be found on the image in the newsletter: https://jmp.sh/JwfX3gS. 

Is it possible you are viewing the newsletter in a text-based email client and the links are not there or something? 

Here is the link if you can' find it in the newsletter: https://brizy.io/blog/brizy-pro-toolset-and-pods/ 

These dynamic content tools are not very easy to grasp I give you that, I have problems understanding all their options my self but an explanation of what dynamic content is and some basic examples of Toolset and Pods in Brizy you can find in that article, just to give you an idea. If you have more questions come and join our facebook group: https://www.facebook.com/groups/brizy/

**Comment by DimiBaitanciuc** [comment]
I'll close this issue, but please feel free to open it again ;)

**Comment by dwsworks** [comment]
Yes but without solution, plz let us know how to use the features added, so we can usethem.

Sent from Yahoo Mail on Android 
 
  On Fri, 5 Oct 2018 at 17:43, Dimi<notifications@github.com> wrote:   
I'll close this issue, but please feel free to open it again ;)
