### ISSUE TITLE
WaaS / SaaS cloud based service clarification

### ISSUE THREAD

**Issue by MarpoOcknew** [ThemeFuse/Brizy#701]
I wanted to check what is and isn't allowed with the pro version.

I was planning to use this for creating sites for clients that would all be hosted on a single WordPress multisite to keep the management for all of the sites simple.

It states that you can use Brizy to create client websites and whitelabel it but that you can't use it as a WaaS / SaaS cloud based service and wanted to know what counts as a WaaS/SasS in this instance.

Thanks.

**Comment by nhanledev** [comment]
I think it will not be counted as WaaS, because multisite is only the way we manage multiple WordPress installations. The multisite is not a service itself. The only WaaS and/or SaaS I know are the WordPress.com, and the EduBlogs.org. But it will be very nice if the term WaaS/SaaS are well defined since the beginning.

**Comment by DimiBaitanciuc** [comment]
As long as you create those websites as separate projects yourself you are ok. The multisite you can use for convenience exactly as @nhanledev said, the multi-site is the way you manage your installs, not the service itself. 

A Saas / Waas would be a site similar to Wix for example where a client goes to create a website, selects a theme from a list of websites (made by you with Brizy Pro) and pays a recurring fee for your services (hosting/theme/editing capabilities, etc).

Hope this makes sense. 

(By the way, we are putting together a Brizy Author Program, where theme authors will be able to bundle Brizy Pro with their themes. This program we plan to extend to a Waas/Saas program in the future so Waas Saas, will be possible but once we have that program in place in the future, most likely 2019)

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
