### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by IMstorm** [ThemeFuse/Brizy#703]
Hi I noticed the images on my page are not displaying on the live version and also the FB group seems to be missing all the comments.

**Comment by ordastrategic** [comment]
Hi also cannot see some images. Mainly in the header. On the desktop version i have a video and mobile i have a picture but all i see is the overlay. any ideas?

**Comment by NataliaBB** [comment]
Hi @IMstorm , @ordastrategic 

Natalia here.
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
