### ISSUE TITLE
Account not approved yet

### ISSUE THREAD

**Issue by lexmarketing** [ThemeFuse/Brizy#706]
I bought the PRO LTD yesterday - there's almost 24 hours -, but I still can't access my account.

Seems like my account was automatically created when I made the payment, but somehow it's still unapproved. Whenever I try to login, the page returns me the following message:

"Your account has not yet been approved. You will be notified via email once a site administrator has reviewed your account and enabled access."

I received the confirmation e-mail.from Brizy and the invoice some minutes after buying, so Avangate processed the payment I suppose. 

Could you please help me? 
‌
The invoice data is below:

Invoice No: BV34713851

Date: October 04, 2018

Order No: 81733980

**Comment by alexluncashu** [comment]
Hi,

try now. this is because you have applied for affiliate and we approve affiliate manually. In order to activate your affiliate account, you should replay to our email where we ask about how you plan to promote Brizy. 
I have activated your account without the affiliate.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
