### ISSUE TITLE
#PostContent for Custom Taxonomy - issue

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#709]
When I tried and add the #PostContent for a custom Taxonomy it loads a copy of the current page?
https://johnnewman.ca/testimonials/

**Comment by NataliaBB** [comment]
Hi @curiousprojects 

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
