### ISSUE TITLE
Block settings behavior

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#71]
Delete button position need to be changed or it should show confirmation message before delete.
I often delete blocks accidentally since it's the same position with setting button itself.
I unconsciously click it to close settings.

**Comment by bagrinsergiu** [comment]
Hi @ash-f,

1. Block button of for all elements?

**Comment by bagrinsergiu** [comment]
Hi,

It is not possible to add confirmation for delete button only for blocks. If we add for blocks we must add for widgets, global styles sidebar, ... I don't think this is a good experience i tried this discomfort on leadpages - every time you wanted to delete an item needs a confirmation.

We have Redo/ Undo Feature for mistakes. 

Sergiu

**Comment by bagrinsergiu** [comment]
mmm How can i reproduce your screen: http://dl4.joxi.net/drive/2018/06/11/0028/0732/1860316/16/cb0746af45.jpg

Can you give me more details ( PC or Mac, Browser, Screen Resolution, .. )

Thanks

**Comment by ash-f** [comment]
No that's my draft idea to improve UX of the block option.
I Photoshop'ed it.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/Q9G05VgU/170-block-delete-button

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
