### ISSUE TITLE
Posts short code config icon not working

### ISSUE THREAD

**Issue by skynet01** [ThemeFuse/Brizy#711]
Found an issue, happens with Architect theme but looks like others are affected as well. Add a posts shortcode to the page which will create 3 featured images along with title and description. Pressing top right gray up arrow icon results in nothing happening. I expect this is where the options for this module would be (Vertical vs horizontal as well as how many posts to show perhaps?)
 
Console logs the following error

`Uncaught TypeError: e.map is not a function
    at g (editor.js?ver=1.0.63:1)
    at ip (editor.js?ver=1.0.63:1)
    at lp (editor.js?ver=1.0.63:1)
    at getItems (editor.js?ver=1.0.63:1)
    at Object.getItems (editor.js?ver=1.0.63:1)
    at r.B.renderPortal.e [as renderPortal] (editor.js?ver=1.0.63:1)
    at w.a.getActive.setTimeout (editor.js?ver=1.0.63:1)
g @ editor.js?ver=1.0.63:1
ip @ editor.js?ver=1.0.63:1
lp @ editor.js?ver=1.0.63:1
getItems @ editor.js?ver=1.0.63:1
getItems @ editor.js?ver=1.0.63:1
B.renderPortal.e @ editor.js?ver=1.0.63:1
w.a.getActive.setTimeout @ editor.js?ver=1.0.63:1
setTimeout (async)
B.show.e @ editor.js?ver=1.0.63:1
props.manualControl.node.addEventListener.e @ editor.js?ver=1.0.63:1`

**Comment by NataliaBB** [comment]
Hi @skynet01 
Natalia here, Brizy team


Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
