### ISSUE TITLE
Blank media upload

### ISSUE THREAD

**Issue by cTraderGURU** [ThemeFuse/Brizy#712]
hi all, have a big problem, on image and cover video when open upload image load black page

![screenshot_2018-10-06 break out strategy ctrader](https://user-images.githubusercontent.com/41258919/46573086-5ac2f580-c990-11e8-93eb-9acddae46e9b.png)

**Comment by Chrisalees** [comment]
I have left a message on the FB community page tonight with the exact same issue. Any ideas anyone?

**Comment by NataliaBB** [comment]
Hi @Chrisalees @cTraderGURU 

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by Chrisalees** [comment]
Hi, thanks for the message.
Have posted on Facebook just now. and also yesterday to see if anyone had any suggestions. No responses yet!

Chris

**Comment by NataliaBB** [comment]
Hi Chris! @Chrisalees 

Send me a private message via our Facebook chat, not on the Facebook community group.

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)



Thank you!

Regards, Natalia

**Comment by cTraderGURU** [comment]
message sent, now what to do ? fix this bug ? i can't post image only with embed code now

**Comment by cTraderGURU** [comment]
solved, conflict with this plugin https://it.wordpress.org/plugins/wordpress-popup/ in my case

**Comment by NataliaBB** [comment]
Thank you @cTraderGURU 
Added to our plugin lists incompatibility, to be solved.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
