### ISSUE TITLE
Corrupted file compression

### ISSUE THREAD

**Issue by cTraderGURU** [ThemeFuse/Brizy#713]
Hi, this file in asset **../wp-content/plugins/brizy/public/editor-build/editor/css/editor.css** is corrupted, i solve it if decompress source code

**Comment by NataliaBB** [comment]
Hi @cTraderGURU 

This issue will be fixed in the next few updates.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by cTraderGURU** [comment]
Thanks
