### ISSUE TITLE
Add elements - Form is write wrong

### ISSUE THREAD

**Issue by John-Henrique** [ThemeFuse/Brizy#714]
![brizzy form error](https://user-images.githubusercontent.com/332925/46586404-4811f480-ca54-11e8-888a-5438d8421f03.png)
Is 'Text', the correct is 'Form' (or contact), I think this is a error from translation

**Comment by NataliaBB** [comment]
Hi @John-Henrique 
Thank you!

We will look into it.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
