### ISSUE TITLE
Content is Not Loading 

### ISSUE THREAD

**Issue by laurel1234** [ThemeFuse/Brizy#715]
There is  a problem with the content loading and it only appears to be on the first page.  Every site I've created with Brizy is having this issue.  Subsequent pages load fine.  It's just the first page.  

Please help.  Thank you.  

By the way, I am not able to chat via anything having to do with Facebook.  Please advise how to handle this matter another way.  

Thank you.

**Comment by NataliaBB** [comment]
Hi @laurel1234 
Natalia here!

Please send me an email at natalia@brizy.io

Thank you!
Best Regards, Natalia

**Comment by mikes1991** [comment]
Hi, 

same here! My Brizy edit page is just loading and nothing happens. I'm disappointed. I have a lot of work left on the web. I need it to work. Thank you for fixing it.
![screen-edit-page](https://user-images.githubusercontent.com/41758560/46725665-f5675100-cc7c-11e8-9320-15d3fb940336.png)

**Comment by NataliaBB** [comment]
Hello @mikes1991 
Natalia here!
Try to disable all plugins and load again the editor page.  It may be a conflict with Autoptimize or W3 total cache plugins. If you didn't manage, please  send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by laurel1234** [comment]
> Hi,
> 
> same here! My Brizy edit page is just loading and nothing happens. I'm disappointed. I have a lot of work left on the web. I need it to work. Thank you for fixing it.
> ![screen-edit-page](https://user-images.githubusercontent.com/41758560/46725665-f5675100-cc7c-11e8-9320-15d3fb940336.png)








> Hi @laurel1234
> Natalia here!
> 
> Please send me an email at [natalia@brizy.io](mailto:natalia@brizy.io)
> 
> Thank you!
> Best Regards, Natalia

Natalila:

Thanks!  Just resent the original message I'd sent to you via email.  Please check the email address you provided above.

LG

**Comment by laurel1234** [comment]
Natalila:

Thanks! Just resent the original message I'd sent to you via email. Please check the email address you provided above.

LG

> Hello @mikes1991
> Natalia here!
> Try to disable all plugins and load again the editor page. It may be a conflict with Autoptimize or W3 total cache plugins. If you didn't manage, please send me a message via our Facebook chat and mention this issue inside.
> 
> ![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)
> 
> Thank you!
> Regards, Natalia

Natalila:

Thanks! Just resent the original message I'd sent to you via email. Please check the email address you provided above.

LG

**Comment by NataliaBB** [comment]
Ok @laurel1234 
Let's discuss via email. Thank you!

Regards. Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by laurel1234** [comment]
I wish this issue was rectified but it is not.  The content still does not load.  I've sent multiple email messages without a response but will try to simply rebuild the structure of the pages from scratch to see if that helps mitigate.  

Was hoping to opt into the Premium version but not justifiable where I can't get the standard version to operate properly.
