### ISSUE TITLE
Border and shadows in image

### ISSUE THREAD

**Issue by arnaldozyl** [ThemeFuse/Brizy#72]
I could not find a way to put border and shadows on the images.

**Comment by bagrinsergiu** [comment]
Hi @arnaldozyl, 

Image Shadows feature is in our doing list. Image Border is not available for the moment. 

Thanks for suggestions.
Sergiu

**Comment by madz00** [comment]
Also I expected to find box shadows for any element, I hope this also is in your doing list!

**Comment by bagrinsergiu** [comment]
Shadow is planned in (1.0.19) on Monday

**Comment by arnaldozyl** [comment]
Thanks

Em dom, 15 de jul de 2018 01:19, bagrinsergiu <notifications@github.com>
escreveu:

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/owzj4GCb/100-element-borders-individually

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
