### ISSUE TITLE
Adding a new page with Brizy throws a link expired error

### ISSUE THREAD

**Issue by nicored** [ThemeFuse/Brizy#723]
Wordpress Admin -> Pages -> Add New -> Brizy

<img width="255" alt="screen shot 2018-10-10 at 11 12 58 pm" src="https://user-images.githubusercontent.com/8218806/46739068-08147100-cce3-11e8-82cb-1de8af71d01e.png">

<img width="841" alt="screen shot 2018-10-10 at 11 13 04 pm" src="https://user-images.githubusercontent.com/8218806/46739090-1b274100-cce3-11e8-944c-4ecd2ec35f1f.png">

Fails in check_admin_referer() in wp-includes/pluggable.php 

Any idea what this could be?

**Comment by NataliaBB** [comment]
Hi @nicored 
Natalia here, Brizy team 

We are working now on this issue. For the moment I can suggest to disable Gutenberg or click Classic Editor and then Edit page with Brizy.

Thank you
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
