### ISSUE TITLE
Issue with loading images

### ISSUE THREAD

**Issue by mjain96** [ThemeFuse/Brizy#726]
Hi, I am having an issue with loading image in my blocks. When I change the preset image to another image it shows as a blank. The new image does not load onto the site. I have attached pictures below to show the problem.
<img width="1280" alt="screen shot 2018-10-10 at 1 10 29 pm" src="https://user-images.githubusercontent.com/44038802/46763241-213f0280-cc8e-11e8-93dc-c807f3e1a3d9.png">
<img width="1280" alt="screen shot 2018-10-10 at 1 10 29 pm" src="https://user-images.githubusercontent.com/44038802/46763262-2d2ac480-cc8e-11e8-9053-2ba97d381a6a.png">
<img width="313" alt="screen shot 2018-10-10 at 1 10 44 pm" src="https://user-images.githubusercontent.com/44038802/46763266-2dc35b00-cc8e-11e8-8952-022c5e0372a4.png">

**Comment by NataliaBB** [comment]
Hi @mjain96 
Natalia here, Brizy team

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by laurel1234** [comment]
I've had the same problem and it seems associated with certain images. Some images will load fine while other images won't and all are JPEG.

**Comment by NataliaBB** [comment]
Hi!
This issue has been fixed.
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
