### ISSUE TITLE
[bug] Template editor Text element displays "No Matches" when adding placeholders

### ISSUE THREAD

**Issue by n2history** [ThemeFuse/Brizy#727]
When editing a Brizy template, the Text editor element does not display post placeholders like "#Title" or "#Subtitle". When I am editing a Text element and type "#", the editor responds that there are no matches. See the attached image.

![brizy-template-text-element-edit](https://user-images.githubusercontent.com/44040862/46769342-19448a00-ccb1-11e8-9e76-a4da2049dfb3.jpg)

**Comment by NataliaBB** [comment]
Hi @n2history 

Natalia here, Brizy team 

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by n2history** [comment]
I ended up going with another framework editor that is more mature and has loads of documentation. (I found Brizy quite challenging without much documentation--not sure how long I would have stuck it out even if I did not run across this problem.) Thanks for your offer to help.
