### ISSUE TITLE
Page content duplicated in the footer

### ISSUE THREAD

**Issue by hayleydrapkin** [ThemeFuse/Brizy#73]
After page it developed and published, it duplicates itself **in the footer** of the visual page builder template. How do I delete this?

**Comment by hayleydrapkin** [comment]
This problem has been corrected. It was an issue with the theme footer. Now, the menu is displaying incorrectly in the header of the page on mobile but only on the Brizy pages. Everything else is working normally.

**Comment by DimiBaitanciuc** [comment]
@bagrinsergiu find the login details here: https://www.facebook.com/brizy.io/inbox/?selected_item_id=100003322940010

**Comment by bagrinsergiu** [comment]
Hi

This has been fixed and was included in version (1.0.13), thanks for reporting.

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Sergiu

**Comment by hayleydrapkin** [comment]
Hi,

I just updated the plugin and am now unable to edit my pages in Brizy at all. How do I correct this ASAP? 

Let me know.

**Comment by bagrinsergiu** [comment]
Hi 

Can you give me WP credentials via Facebook Chat and mention this issue inside: http://dl4.joxi.net/drive/2018/05/10/0028/0732/1860316/16/cb53437dfd.jpg

Thank you.
Sergiu

**Comment by bagrinsergiu** [comment]
This has been fixed and was included 1.0.17 update

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you report.
Sergiu
