### ISSUE TITLE
Crash Brizy Builder

### ISSUE THREAD

**Issue by Wolf-Byte** [ThemeFuse/Brizy#730]
I am having a play around with Brizy and I am very impressed. 👍 I have just come across a bug I thought I would point out.

Replication steps (Tested in google chrome)

1. Create a section
2. Add a text module the column on the left
3. Click within the column on the right and drag it into the column on the left
4. Right-click the column on the right
5. Boom

![brizy crash](https://user-images.githubusercontent.com/33579592/46802162-82310e00-cd54-11e8-8af3-1ae03a0b1996.gif)

**Comment by NataliaBB** [comment]
Hello @Wolf-Byte 
Sorry for my late reply.

Please, please, send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
