### ISSUE TITLE
Post Content and Post Exerpt

### ISSUE THREAD

**Issue by ProfitGlen** [ThemeFuse/Brizy#732]
Please fix the Post Content and Post Excerpt. When adding the elements they don't function properly. It says "no matches" and it does not dynamically add my content to my published blog page. In fact, the Post Content adds the wrong content.

**Comment by NataliaBB** [comment]
Hi @ProfitGlen !
Natalia here, Brizy team!
Thanks for reporting this.

It will be fixed within next few updates.

Thank you!
Regards, Natalia

**Comment by ViorelEremia** [comment]
@ProfitGlen have you the version 1.0.39? or 1.0.39
we are preparing a new update this week with some dynamic content improvements can you check with the latest version 1.0.39 for the free version and 1.0.10 for pro

**Comment by ViorelEremia** [comment]
Issues have been resolved in the latest releases. 
If the issue still exists, please open a new issue.
