### ISSUE TITLE
Animated Gifs not working anymore when used inside Brizy editor and frontend

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#733]
Hi there,

On the website 'clothweaver.com' my client has animated gifs. However these gifs don't animate anymore when I updated Brizy to the latest version, free & pro.

When viewing the gifs from the backend in the media browser they do animate.

If needed I can provide login credentials.

Best regards,

Christiaan

**Comment by NataliaBB** [comment]
Hi Christiaan @Infusednl 
Yes, please send me a message via our Facebook chat to inspect this bug.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
