### ISSUE TITLE
An error happened while trying to display this block

### ISSUE THREAD

**Issue by samuibayside** [ThemeFuse/Brizy#738]
What to do when the block disapear and shows this error?

An error happened while trying to display this block

There are only two options, delete block or open an issue. I have already lost everything before.

It seems to be related to making the block global.

What to do please?

**Comment by NataliaBB** [comment]
Hello @samuibayside @2Ben 
Natalia here, Brizy team
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by willhousecreative** [comment]
I had this issue today. I was trying to update some text in a block. When I went to change the color it gave me a block error. I was able to recreate the error three times and took a gif of the screen so you can see the error. 

Part of what I needed to do is unlink a string of text. There does not seem to be a clear way to do this. I realize the link issue has also been raised here: [https://github.com/ThemeFuse/Brizy/issues/483]() and similarly here: [https://github.com/ThemeFuse/Brizy/issues/306]()

To "fix" this issue, I used the "Back to Wordpress" menu item at the bottom left of the Brizy interface and came back to the page using the "Edit with Brizy" and the block re-appears. But, as I start in to edit it, eventually the error comes back.

![block-error](https://user-images.githubusercontent.com/19369150/46973517-57a5c480-d076-11e8-906b-f1b08b7ec062.gif)

**Comment by samuibayside** [comment]
I have just found out that this error just happens to me when I activate the block as Global, after I have done a lot of editing. 

Basically, let's say I start a new block, and insert a lot of photos and texts. Then, if I try to make it global, after all this editing, the block will disappear and will never come back. I will have to delete it and start it all over.


@NataliaBB I tried contacting you via the messenger but it didn't work.

**Comment by jonbonnar** [comment]
Got same issue, have had it for weeks

**Comment by NataliaBB** [comment]
Hi @samuibayside 
Please, mention this issue inside your message, or select the WP credentials from the bot messages.

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi @jonbonnar 
If you had this error for weeks, then it is not a migration bug. 
Please, give me more details on our Facebook chat:


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia


se send me a message via our Facebook chat and mention this issue inside.

**Comment by NataliaBB** [comment]
Hi All!
If you still have this issue after the current 1.0.45 version, please send me a message via our Facebook chat and mention this issue inside - #738 


I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by grzeche** [comment]
Hello,
I have version 1.0.46 and have this same problem. All plugins was updated, any others were disabled - unfortunatelly nothing better. I found one error in console:

> editor.vendor.js?ver=1.0.72:53 TypeError: Cannot read property 'type' of undefined

Could you help me?
Thank you in advance
Greetings

![image](https://user-images.githubusercontent.com/45048012/48507707-f461aa80-e84c-11e8-8522-f085b4ef4ebf.png)

**Comment by iZEVS** [comment]
Hello,
This bug appeared again after today's update. Version 1.0.65
It appears when you click on ANY of block settings circle.
Please FIX it ASAP!
Thank you!

**Comment by iZEVS** [comment]
Brizy Pro 0.0.19 solved that problem. Thank you!
