### ISSUE TITLE
Whitelabeling

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#74]
It would be great to be able to whitelabel all parts of Brizy so potential customers don't have to see the Brizy branding. That would be useful for customer sites, multi site installations and particularly WordPress turnkey solutions (WaaS) where a clean whitelabel environment is essential.

**Comment by bagrinsergiu** [comment]
@quantumleap33 - What means WaaS? Wordpress Saas?

I see 2 different products 
1. Agency Whitelabel
2. Multi Site Whitelabel (Ex: squarespace, shopify) WP SAAS right? 

@DimiBaitanciuc - Can you give as more details?

**Comment by quantumleap33** [comment]
Exactly as you said. Whitelabel as an agency of freelancer and whitelabel as part of a turnkey Waa(Website As A Service) solution like Squarespace, Shopify, etc, as you described!

**Comment by bagrinsergiu** [comment]
Hi @quantumleap33 

Lifetime license:

Includes - Unlimited Clients Projects + Support + Whitelabel
Does not includes -  Resell ( Themeforest, MojoThemes, CreativeMarket, ... ) and Waas/ Saas Services

**Comment by quantumleap33** [comment]
Oh no. I was really hoping the WaaS would be covered! It could add such great value to the system if the user would be able to make a full fledge site just with Brizy(including various email marketing integrations). Are there any plans for inclusion in the future?

**Comment by quantumleap33** [comment]
What about the free version of Brizy? Would that accomodate WaaS?

**Comment by bagrinsergiu** [comment]
Q: Oh no. I was really hoping the WaaS would be covered! It could add such great value to the system if the user would be able to make a full fledge site just with Brizy(including various email marketing integrations). Are there any plans for inclusion in the future?

A: We plan a standalone version. No WP just editor + Symfony on backend.

**Comment by bagrinsergiu** [comment]
Q: What about the free version of Brizy? Would that accomodate WaaS?

A: Yes. You can use free version with an Saas service (Waas)

**Comment by quantumleap33** [comment]
Standalone + Symfony would be for designing websites out of WordPress? Kind of like a page builder for creating dynamic websites?

**Comment by bagrinsergiu** [comment]
@quantumleap33 

Yes. Standalone version ca be used for Shopify Apps, Drupal Module, Instapage Saas service and so on...

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/SgWWgwQw/78-whitelabeling

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
