### ISSUE TITLE
Brizy builder not working

### ISSUE THREAD

**Issue by ravijoshi966** [ThemeFuse/Brizy#740]
I used Brizy page builder to build a website, after update Brixy is not working.
![image](https://user-images.githubusercontent.com/44109368/46902219-ff888a00-cede-11e8-85cf-436dc0e89998.png)

**Comment by NataliaBB** [comment]
Hi @ravijoshi966 
Natalia here!
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
