### ISSUE TITLE
Size of Videoplayer bugged (+audio issue)

### ISSUE THREAD

**Issue by Idontwannasignup1111** [ThemeFuse/Brizy#742]
I might have noticed a minor bug when it comes to playing back YouTube-Videos via a Video Slider block: When having several videos, all after the first appear improperly scaled (see picture), only when manually changing the size of the browser video seems to fix it. Secondly, is there a setting that I've overlooked for muting the YouTube videos? Since atm, all videos are playing sound over each other. Any help is appreciated 
![temp](https://user-images.githubusercontent.com/44142687/46920003-fc2cf580-cfe7-11e8-9b12-3ebdd63eb140.png)

**Comment by rycillic** [comment]
Iam here for the same isue. I have a slider and only of the first the video its the right size. The other are glitching in to corrner. Tried a lot of stuff chaning etc but it didn't work.
![1](https://user-images.githubusercontent.com/44146687/46922614-d74a7980-d00b-11e8-9464-13a4c9e13acb.PNG)
![2](https://user-images.githubusercontent.com/44146687/46922615-d7e31000-d00b-11e8-899f-32718dd78ae0.PNG)

**Comment by marcellefter** [comment]
Hi!
The bug was fixed and will be in the next updates. I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Thank you!
Marcel

**Comment by Idontwannasignup1111** [comment]
Hey Marcel, many thanks for fixing the size issue!

 

The audio bug, however, is still ongoing: The sound of the Youtube-Videos plays automatically and cannot be muted, a behaviour you definitely don’t want to have for unsuspecting visitors 😊

 

Should I start a new issue on github for that?

 

Regards,

Matthias

 

Von: Marcel Lefter <notifications@github.com> 
Gesendet: Freitag, 23. November 2018 16:58
An: ThemeFuse/Brizy <Brizy@noreply.github.com>
Cc: Idontwannasignup1111 <sucking.sux@gmail.com>; Author <author@noreply.github.com>
Betreff: Re: [ThemeFuse/Brizy] Size of Videoplayer bugged (+audio issue) (#742)

 

Hi!
The bug was fixed and will be in the next updates. I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Thank you!
Marcel

**Comment by Idontwannasignup1111** [comment]
I take that last e-mail back, since this behaviour  seems only to occur when viewing the website as a logged-in user. 

 

Overall though, the video-playback is still somewhat tricky depending on the browser, but it’s getting better update by update 😊

Greetings

 

Von: Matthias Tonitz <matthias@tonitz.at> 
Gesendet: Freitag, 30. November 2018 11:14
An: 'ThemeFuse/Brizy' <reply@reply.github.com>; 'ThemeFuse/Brizy' <Brizy@noreply.github.com>
Cc: 'Idontwannasignup1111' <sucking.sux@gmail.com>; 'Author' <author@noreply.github.com>
Betreff: AW: [ThemeFuse/Brizy] Size of Videoplayer bugged (+audio issue) (#742)

 

Hey Marcel, many thanks for fixing the size issue!

 

The audio bug, however, is still ongoing: The sound of the Youtube-Videos plays automatically and cannot be muted, a behaviour you definitely don’t want to have for unsuspecting visitors 😊

 

Should I start a new issue on github for that?

 

Regards,

Matthias

 

Von: Marcel Lefter <notifications@github.com <mailto:notifications@github.com> > 
Gesendet: Freitag, 23. November 2018 16:58
An: ThemeFuse/Brizy <Brizy@noreply.github.com <mailto:Brizy@noreply.github.com> >
Cc: Idontwannasignup1111 <sucking.sux@gmail.com <mailto:sucking.sux@gmail.com> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Betreff: Re: [ThemeFuse/Brizy] Size of Videoplayer bugged (+audio issue) (#742)

 

Hi!
The bug was fixed and will be in the next updates. I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Thank you!
Marcel
