### ISSUE TITLE
Bloom optin displays nothing in the Brizy builder preview

### ISSUE THREAD

**Issue by Josecarpeniet** [ThemeFuse/Brizy#745]
Hi,
Bloom optin displays nothing in the Brizy builder preview. When you visit the page or post the optin is there, but is very hard to work like this in the builder.
![captura de pantalla 2018-10-15 a las 9 32 02](https://user-images.githubusercontent.com/26742826/46926238-7306d480-d062-11e8-9079-e603e761cd9d.png)

**Comment by NataliaBB** [comment]
Hi @Josecarpeniet 
Natalia here, Brizy team
Sorry for the inconvenience. 
Yes, this is an issue which needs to be improved. I understand it's quite complicated to work with this, I can only suggest to use a symbol in that form (".") 

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
