### ISSUE TITLE
Role Editor

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#75]
I believe it's essential to implement a role editor that gives certain editing right to particular user roles. Especially useful functionality would be to only allow editing text for particular user roles so that they don't break the page layout.

**Comment by bagrinsergiu** [comment]
Hi @quantumleap33 

We finished this feature 2 days ego (It is a Pro feature). We plan to launch with Pro version in 1-2 months.

Thank you for suggestion

**Comment by DimiBaitanciuc** [comment]
@quantumleap33 @bagrinsergiu - we plan to launch the Pro in 3-4 months. Don't expect it in 1-2 and then be disappointed if things delay. In software development, things always tend to pop up. 

Expect it in 3-4 and let us surprise you in 2 :)

**Comment by quantumleap33** [comment]
You go it, thanks!

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/FYiOSfGA/36-role-manager

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
