### ISSUE TITLE
Image not loading in chrome both mobile and desktop

### ISSUE THREAD

**Issue by graciashtg** [ThemeFuse/Brizy#750]
i try to open in internet explorer and the image appear but when i open the website with chrome or firefox, the image on the page get broken. 

here is my website: https://kembinainsanrabbani.ml/

**Comment by NataliaBB** [comment]
Hi @graciashtg 
Natalia here!

You have a hosting error. I would like to inspect from your dashboard, therefore, please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by graciashtg** [comment]
thank you for your reply. sorry to make you wait. My server is now back on service. You can check it. 

Thank you

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
