### ISSUE TITLE
impossible to load video and image

### ISSUE THREAD

**Issue by Diegobia** [ThemeFuse/Brizy#754]
hello
i just started bulding. everything is working but can't  load no image or video. Can you help?

http://www.mvtprofessional.eu/prova/?brizy-edit

**Comment by NataliaBB** [comment]
Hello @Diegobia 
Natalia here!

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by nerdministrynetwork** [comment]
I am having the same problem. Using media cloud offload to Amazon S3 with Imgix CDN. I tried the messenger, but was referred to here.

**Comment by NataliaBB** [comment]
Hi @Diegobia 
This issue has been fixed at your side.

@nerdministrynetwork 
If you still have this problem after update to 1.0.45 Version, please send us a message via our Facebook chat. To not be referred here, please mention the WP credentials and the issue number - #754

Regards, Natalai

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
