### ISSUE TITLE
Brizy NOT WORKING

### ISSUE THREAD

**Issue by Kamal75** [ThemeFuse/Brizy#755]
Hello, I have this website amexbuilders.my I am using Brizy Plugin on Wordpress, everything is fine until suddenly the brizy editor stopped working and it shows me this when I open it.
![capture](https://user-images.githubusercontent.com/44286639/47203228-2f89ce80-d3b2-11e8-8816-84329f174edd.PNG)

**Comment by Kamal75** [comment]
Hi, NataliaBB,
Thanks for the fast support

**Comment by NataliaBB** [comment]
Hi @Kamal75 
My Pleasure ;) 

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
