### ISSUE TITLE
I can't type the numbers to change the column width

### ISSUE THREAD

**Issue by Josecarpeniet** [ThemeFuse/Brizy#757]
I can't type the numbers to change the column width.

![captura de pantalla 2018-10-20 a las 11 20 37](https://user-images.githubusercontent.com/26742826/47251027-61a53a00-d45f-11e8-878a-d4db18acc6ce.png)

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/51AHKcZv/178-column-type-the-numbers-to-change-the-column-width

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
