### ISSUE TITLE
Brizy Edit GUI Not Loading Properly

### ISSUE THREAD

**Issue by hjtse** [ThemeFuse/Brizy#758]
I just installed new Themefuse theme. 
https://demo.themefuse.com/?theme=car-repair-wordpress-theme

The website loads fine as expected. However when I try to edit the homepage with Brizy, the GUI is all messed up. I have deactivated all plugins, and did a fresh install of the theme but still getting the same issue. Here are the 4 default plugins that come with the theme. Last chrome browser and wordpress version running off SiteGround hosting. 

https://repairadrone.com

![screen shot 2018-10-20 at 12 40 14 am](https://user-images.githubusercontent.com/5474554/47252903-bebdd300-d400-11e8-8f95-0866db90c164.png)
![screen shot 2018-10-20 at 12 26 08 am](https://user-images.githubusercontent.com/5474554/47252883-828a7280-d400-11e8-83af-e644ecd242ce.png)
![screen shot 2018-10-20 at 12 35 59 am](https://user-images.githubusercontent.com/5474554/47252882-828a7280-d400-11e8-96b2-865155b5c335.png)

**Comment by NataliaBB** [comment]
Hello Han @hjtse !

This bug was fixed. As I mentioned in our chat messages, it is a Siteground error.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
