### ISSUE TITLE
Brizy fatal error (undefined function brizy() ) When using Ajax

### ISSUE THREAD

**Issue by junglewp** [ThemeFuse/Brizy#76]
Hello,
I wanted to point out that we found a bug in Brizy. I am requiring wp-config trough an external PHP script in our Plugin and it seems that Brizy has a function that is not defined. The same error is also present in other website, this was easily found on Google while looking for the error...

```
`<b>Fatal error</b>:  Uncaught Error: Call to undefined function brizy() in [redacted]/wp-content/plugins/brizy/public/hooks.php:115
Stack trace:
#0 [redacted]/wp-content/plugins/brizy/brizy.php(32): include_once()
#1 [redacted]/wp-settings.php(305): include_once('/srv/users/serv...')
#2 [redacted]/wp-config.php(26): require_once('/srv/users/serv...')
#3 [redacted]/wp-load.php(37): require_once('/srv/users/serv...')
#4 {main}`
 thrown in &lt;b&gt;[redacted]/wp-content/plugins/brizy/public/hooks.php&lt;/b&gt; on line &lt;b&gt;115&lt;/b&gt;&lt;br /&gt;
```

We also found the same bug on the following website as well : https://doctorsmaps.com/static/ext/indeed-membership-pro/public/ajax-upload.php

Kind regards,
Franck

**Comment by bagrinsergiu** [comment]
Hi 

In last update 1.0.9 we added a fix for this issue. Can you confirm if it is working with last changes?

Thanks

**Comment by junglewp** [comment]
Thanks for the fix, I'll test this and get back to you!

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you suggestion.
Sergiu
