### ISSUE TITLE
Deleted all my content after new update. How can I backup before an update?

### ISSUE THREAD

**Issue by alexsnkwz** [ThemeFuse/Brizy#760]
Deleted all my content after new update. How can I backup before an update?

thanks :)

**Comment by 4Designs** [comment]
[All-in-One WP Migration](https://sv.wordpress.org/plugins/all-in-one-wp-migration/) works great for a quick and easy backup before installing an update.

**Comment by NataliaBB** [comment]
Hi @alexsnkwz 
Natalia here!

use All-in-One WP Migration or Duplicate plugins.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
