### ISSUE TITLE
Embed Code Not Working

### ISSUE THREAD

**Issue by Jaybrantley** [ThemeFuse/Brizy#761]
Hi - 

My embedded code will work in the normal wordpress text editor but when going through Brizy and adding the embed element, nothing shows when input. Please advise.

Below is the code

<span data-sumome-listbuilder-embed-id="2a4b5e97be1cba7c3a372ca12fbe4c6788fc9723f3a9652cab181b7690b2e9b3"></span>

**Comment by NataliaBB** [comment]
Hello @Jaybrantley 
Natalia here.
Unfortunately, I don't see your code: https://jmp.sh/KaBZP7J 
If this is JS code, then it will not be seen in the editor mode, it will work only with HTML or CSS code. 
This is an issue which needs to be improved, and it is in our to do list.

For more details, please send me a message on our Facebook chat.
Cheers!
Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
