### ISSUE TITLE
Website Images NOT Loading

### ISSUE THREAD

**Issue by Kamal75** [ThemeFuse/Brizy#763]
Hello,
When I open the website on desktop or mobile most of the website images are not loading, I see this a common issue but, no solution is explained, can you help me please!!
URL: amexinterior.my

**Comment by NataliaBB** [comment]
Hello Kamal!
Natalia here, Brizy team
I've fixed this bug in your page. 

This image issue was fixed and it will be included in the next update.
Thank you!
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by Kamal75** [comment]
Sure, thanks for the support
