### ISSUE TITLE
Save Google Fonts locally and serve them locally or preload option

### ISSUE THREAD

**Issue by rwkyyy** [ThemeFuse/Brizy#764]
I've seen in my projects, load time delays due to Google's network instability.

To solve this issue I use one of the two:
- preload (ex: [here](http://ashton.codes/preload-google-fonts-using-resource-hints/) )
- download them and serve them locally (ex: [here](https://google-webfonts-helper.herokuapp.com/fonts) )

This would be a good feature for performance improvement and it would also help in GDPR compliance.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/JKK5n0wa/82-custom-fonts

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
