### ISSUE TITLE
Not all images work in all browsers

### ISSUE THREAD

**Issue by hollysnails1** [ThemeFuse/Brizy#766]
i am using jupiter theme, and all the images, some of the side images, mostly the background ones do not show up correctly in Firefox or IE Edge 10 . 
but is fine for chrome 
http://inventorx.findbemidji.com/
not showing up in mobile either. iphone 7plus

the main header image isnt showing. 

the background of the second row on right is not displaying either. 

hollysnails@gmail.com

**Comment by oconrard** [comment]
Same problems https://chasseengaume.be/cartegaume/
Works fine on IE by not on Chrome and Firefox (image broken)

Thanks to solve it quickly

Olivier

**Comment by NataliaBB** [comment]
Hi @hollysnails1 
Natalia here.
Your website looks great on Firefox, Chrome, Iphone 7+8, IE Edge 10, 
Please send me a screenshot on which browser you don't see the header image.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi @oconrard 
Natalia here.

You have there an HTTPs error, this bug is fixed at our end and it will be included in the next update.
If you need to be fixed before the update release,  send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by oconrard** [comment]
Natalia,

Please find enclosed two screenshot

Olivier

**Comment by oconrard** [comment]
Hi Natalia

Yes, you can send me the update before the next release.
Where did you found this Https error?

Do you know when the next features will be available ? It a long time now we didn't receive news.

Kind regards

Olivier

**Comment by NataliaBB** [comment]
@oconrard Oliver
Don't send the images via your phone, GitHub doesn't recognize them, and I can not see. 

I need to insert a script in your page through File Manager. Can you give me access to it?

Thank you
Regards, Natalia

**Comment by hollysnails1** [comment]
It was the issue of using the background color and image at the same time the background color has to be set to clear to see the image and will not work with an overlay color 

Since there is no setting for , none , on background color I set it to white instead of grey and then had to set the opacity to 100% see thru to get the image to show up in Firefox ( main top banner image )

**Comment by oconrard** [comment]
Natalia,

Sorry, but for security reasons, I perfer not to give this kind of information.
I will wait the next update. Do you known when this new release will be available?

Regards

Olivier

**Comment by NataliaBB** [comment]
Hello Oliver @oconrard 
We can discuss via email. Mine - natalia@brizy.io

The next update is planned these days.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
