### ISSUE TITLE
Menu Not Chaging

### ISSUE THREAD

**Issue by kpjjf1** [ThemeFuse/Brizy#767]
I have set up 8 categories in the menu. I have changed one from ride to rides. It has not updated and <I cannot find a way too update it. I have tried for 2 days and failed.

**Comment by NataliaBB** [comment]
Hi @kpjjf1 
Natalia here, Brizy team!
I've reproduced your issue with 12 categories for my  menu, and I didn't had any bug with it.

>  It has not updated and <I cannot find a way too update it 
Can you give me please more details. A screenshot? A record of your menu categories?

Thanks!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
