### ISSUE TITLE
Brizy not applying changes

### ISSUE THREAD

**Issue by jeremiahbatac** [ThemeFuse/Brizy#770]
hello team,

I recently upgraded my wordpress and plugins and started to use brizy. The changes I have made doesn't get applied. See attached video url

https://drive.google.com/open?id=1flLJ6bDC4fQUuxZ_ZVRpQPqpROh9IVYV

let me know what else i need to do to make the changes get applied. Thank you.

**Comment by jeremiahbatac** [comment]
any updates yet?

**Comment by NataliaBB** [comment]
Hello @jeremiahbatac  Jeremie!
Natalia here,
I would like to check and fix this issue on your dashboard.  Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by jeremiahbatac** [comment]
Hi Natalia! I have messaged you via facebook. I had to setup my facebook account, sorry for late response.
