### ISSUE TITLE
An error happened while trying to display this block

### ISSUE THREAD

**Issue by filament72** [ThemeFuse/Brizy#771]
"An error happened while trying to display this block" appears for all content blocks on the homepage and some pages for "Haven" theme after importing demo content. I get the header slider and footer but get an error for all others. I am running a local WAMP setup if that matters. Any direction would be great. - thanks

**Comment by NataliaBB** [comment]
Hi @filament72 
Natalia here, Brizy team!
Please, provide us with the theme demo version. I would really appreciate if you can also send me a screenshot from your console.

You can also send us a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by epubpress** [comment]
Seems to work ok on PHP 7.0 but not higher versions.

**Comment by NataliaBB** [comment]
Hi @epubpress 
Natalia here! 
Please update all Brizy pugins, Free and PRO versions. 

If you still face 


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Nataliathis problem then let us know via our Facebook chat

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
