### ISSUE TITLE
[enhancement] Gutenberg integration

### ISSUE THREAD

**Issue by tdechangy** [ThemeFuse/Brizy#774]
Gutenberg becoming quickly an alternative source of interesting blocks I would highly recommend to integrate them into the builder. through a text editor or copying the blocks as additional elements.

I would also recommend to segment clearly the elements by source/functionality. Visual Composer did it pretty well,separating each additional plugin elements in a separate tab. This allows a far quicker navigation without losing feat when many elements are available.

**Comment by DimiBaitanciuc** [comment]
Thanks for the suggestions. When we'll look into Gutenberg (pretty soon) we'll make sure to take these into account.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/4ZczB1y2/145-gutenberg-and-brizy

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
