### ISSUE TITLE
Better positioning of settings box

### ISSUE THREAD

**Issue by Jugibur** [ThemeFuse/Brizy#779]
If you want apply settings on elements near the top, it's often impossible to see the underlying object, i.e.:
![screenshot 23](https://user-images.githubusercontent.com/271000/47517166-a0842700-d887-11e8-8daa-155ba81549b9.png)
Perhaps you could rearrange the box or make it more transparent (althought the latter isn't ideal for adjusting colors)

**Comment by NataliaBB** [comment]
Hi @Jugibur 
Natalia here!
Thanks for the suggestion.

I already added this issue in our roadmap as an improvement:  https://trello.com/c/4TVixrLX/128-transparent-toolbar .

Thank you for your time!
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
