### ISSUE TITLE
IDEA - WP Forms

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#78]
Would love to see a WP Forms integration. Would be even cooler if it were integrated and stylable. :)

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/SJcFPC1Y/35-form-integrations

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
