### ISSUE TITLE
Feature request: Upload custom Shape/Section Dividers

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#782]
Hi there,

I would like to make the following feature request: to be able to upload custom SVG shape/section dividers to Brizy.

For now I do this by uploading my custom SVG images to Wordpress and use these by adding custom CSS classes that contain these shape dividers. However it would make my life a lot easier if we were able to upload our own shape dividers and then be able to use them alongside Brizy's own shape/section dividers.

Best regards,

Christiaan

**Comment by NataliaBB** [comment]
Hello Christiaan! @Infusednl 

We do have this feature in our to do list: https://trello.com/c/wrfhV9sj/7-image-svg-support 

My Best Regards, Natalia

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
