### ISSUE TITLE
transfer plugin all-in one wp migration

### ISSUE THREAD

**Issue by AboveSecond** [ThemeFuse/Brizy#784]
when using that plugin to transfer the files from development to live you can indicate to replace text such as the url by a new text (ex. replace https://website-development.be with https://website.be)
All url's used in the development and that are NOT in Brizy are being replaced. All links that are within the Brizy plugin development are remaining unchanged. This forces you to check and replace all links after going live on the new url.

thx

Roeland
AboveSecond

**Comment by Infusednl** [comment]
Would be awesome if this could be fixed! I also am a huge fan of All In One WP Migration and rely heavy on it for moving websites.

**Comment by forcedlogic** [comment]
All you have to do is regenerate the CSS. Works everytime. Elementor > Tools.

A much bigger problem is the fact that in a development site...you often can not see backgrounds or anything like that. I am not sure why but using Flywheel by Local...it will not show up.

**Comment by NataliaBB** [comment]
Hi Roeland! @AboveSecond @Infusednl @forcedlogic 
Thanks for your suggestion.
I forwarded this request to our team and our main project manager @bagrinsergiu . They will look into it asap.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
