### ISSUE TITLE
Mobile Block Trying To Center Causes Issues

### ISSUE THREAD

**Issue by techguy76** [ThemeFuse/Brizy#787]
When i try and edit a block on mobile and try centering text the block dissapears and I have to refresh the page to get it to come back.

**Comment by NataliaBB** [comment]
Hi @techguy76 
Natalia here, Brizy team!
Please send me a message via our Facebook chat and mention this issue inside - #787

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
