### ISSUE TITLE
Cursor Jumps when adding url to text

### ISSUE THREAD

**Issue by AntonKing60** [ThemeFuse/Brizy#788]
When adding a url to plain text, as the url is being entered, the cursor jumps from the box where the url is being typed, into the text being used for the link.
It does the same thing every time a new character is typed into the url area.

If you continue typing without noticing, whatever url you type is just added in to the text that is being used, on the page

**Comment by kpjjf1** [comment]
This has been brought up several times as it is so annoying when you are trying to add a link. I think it is in progress.

**Comment by NataliaBB** [comment]
Hi Anton @AntonKing60 , @kpjjf1 
Natalia here, Brizy team

Sorry for this inconvenience.
We have this issue in our improvement list: https://trello.com/c/abkAqzvg/102-text-link-color-hover-color.

Please, let us finish the PRO features ready to be released, and we will get back to all our improvements, including this one.

Thank you a lot for the patience!.
My best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
