### ISSUE TITLE
Issues Publishing Update When i do any change

### ISSUE THREAD

**Issue by remf02** [ThemeFuse/Brizy#789]
Hello, Sorry for English, I have some issue editing some text, because when i change the text and push update for publishing, it doesnt work. Please help. Thanks
![keep](https://user-images.githubusercontent.com/8215959/47606662-6ed4a280-d9e4-11e8-838f-66c142aa3e4b.png)

**Comment by lindseykelley** [comment]
I am also having problems with this plugin. It will not let me update my changes. Yesterday.

Today I updated the plugin and now Brizy won't load for me, making the problem even worse.

**Comment by Gopinadh-babu** [comment]
SAme issue, here.... Team can you resolve it asap.

**Comment by mlb107** [comment]
Same! The update button just spins, so even though my edits are showing on the editing end, the site is not being updated for those visiting.

**Comment by NataliaBB** [comment]
Hello @mlb107 @Gopinadh-babu @remf02 
Natalia here, Brizy team

This is a but with our code editor, it can be fixed very quick , just send me a message via our Facebook chat and mention this issue inside - #789 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
