### ISSUE TITLE
Brizy will not load.

### ISSUE THREAD

**Issue by lindseykelley** [ThemeFuse/Brizy#790]
Yesterday I noticed that my pages would not let me update my changes using Brizy.

Today same problem. So I updated the plugin and now none of my pages will load when I try to use the Brizy plug in! Help I need this resolved asap!

How long will it take to fix?

**Comment by NataliaBB** [comment]
Hello Lindsey! @lindseykelley 
This bug was already fixed at your end!

Sorry for the inconvenience.
My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
