### ISSUE TITLE
Can't activate Brizy

### ISSUE THREAD

**Issue by iwanikhalid** [ThemeFuse/Brizy#791]
Hi Brizy.

Can't seem to activate the plugin. Got this error below

`Parse error: syntax error, unexpected '[' in /web/wp-content/plugins/brizy/admin/migrations.php on line 108`

**Comment by NataliaBB** [comment]
Hi Iwani @iwanikhalid 
Natalia here, Brizy team.

Please send me a message via our Facebook chat and mention this issue inside - #791

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by NataliaBB** [comment]
Hi @iwanikhalid 
You have an old PHP version 5.3.23. Brizy works only with 5.4 or a higher version. We recommend to contact your hosting provider and ask them to update, or you can send me the cpanel credentials and we can update by our self

Best Regards, Natalia
