### ISSUE TITLE
Feature - Make Template Display Conditions UI clearer

### ISSUE THREAD

**Issue by dmccan** [ThemeFuse/Brizy#793]
When you view the Display Conditions for Templates you choices are not obvious.  For example, here are the Conditions for "Pages/Books":

![image](https://user-images.githubusercontent.com/2622805/47618845-b66f3300-daa5-11e8-9965-dbfbff0c0343.png)

And here are the Conditions for "Archives/Books":

![image](https://user-images.githubusercontent.com/2622805/47618857-dbfc3c80-daa5-11e8-864b-7fb1a1e579df.png)

Please "Don't Make Me Think" :)  I suggest you change the wording to show "Pages" or "Archives" on the line with the condition.  

Thanks

**Comment by NataliaBB** [comment]
Hello @dmccan 
Natalia here!
Thanks for your suggestion

I've forwarded this request to our dev team. They will look into this improvement asap.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
