### ISSUE TITLE
Update getting stuck despite page looking as it should on the editing end

### ISSUE THREAD

**Issue by mlb107** [ThemeFuse/Brizy#794]
After updating some dates on my website, I updated my site, but the update button just continues to spin without actually making the updates. When I log out and back in, the updates have saved, but when going to the site, it is still in the same state as prior to the updates.

**Comment by NataliaBB** [comment]
Hi @mlb107 
Natalia here, Brizy team

Please send me a message via our Facebook chat and mention this issue inside #794 and I will fix this quickly.

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by valeriocori** [comment]
I had the same problem, but after I've logged out and back in, the hole page is gone! I don't know how to recover it!

**Comment by JJRes** [comment]
I am having the same problem.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
