### ISSUE TITLE
Poor image quality when uploading

### ISSUE THREAD

**Issue by NannaPed** [ThemeFuse/Brizy#796]
I have a problem when I am uploading images to my brizy pages, they turn out with really poor image quality, even if the image itself is in a high resolution - Can anybody help me?

![skaermbillede 2018-10-29 kl 13 37 53](https://user-images.githubusercontent.com/44574466/47650331-3bc71600-db80-11e8-9bf1-ccbee76c3205.png)

**Comment by NataliaBB** [comment]
Hello @NannaPed 
Natalia here! Brizy team
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
