### ISSUE TITLE
Unable to edit using Mobile View

### ISSUE THREAD

**Issue by esims2003** [ThemeFuse/Brizy#798]
![error](https://user-images.githubusercontent.com/18453642/47674968-34067200-db7e-11e8-95fa-0b8b5fe4f991.PNG)
Any time i try to make any edits in Mobile View, I get an error saying that an error has happened trying to display the block.  Does not allow me to make any edits to any blocks in Mobile View.

**Comment by NataliaBB** [comment]
Hi @esims2003 
Natalia here.
This appeared after our migration update.  
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
