### ISSUE TITLE
Block - grey line

### ISSUE THREAD

**Issue by oconrard** [ThemeFuse/Brizy#803]
Hi,

When inserting a new blog, there is always a grey ligne on the top and the bottom of the block. I put the border to 0 but this is not the solution, the only way to mitigate it is to put a grey background color (https://chasseengaume.be/cartegaume/).  Do you known how the erase it? 

Thank a lot
Kind regards

Olivier

**Comment by NataliaBB** [comment]
Hello Oliver! @oconrard 

I see there is a section style conflict with Arwin and Data feed plugin.
I've created an issue for the team in order to solve this problem, for the moment I suggest to deactivate this plugin.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by oconrard** [comment]
Hi Natalia,

Thanks and let me known when the issue will be solve

Kind regards

Olivier
