### ISSUE TITLE
The background video is not displayed correctly when it is set as a slide.

### ISSUE THREAD

**Issue by Jamesjeric** [ThemeFuse/Brizy#804]
When I view in the Brizy builder it looks OK but when in live view it only display a thumbnail of the video.

James Jeric
![brizy](https://user-images.githubusercontent.com/44604245/47710408-f7735e80-dbef-11e8-8f40-0a93b5bb5c44.jpg)

**Comment by NataliaBB** [comment]
Hi @Jamesjeric!
Thanks for reporting this bug. We have this issue on our bug list and the team will work on it.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
