### ISSUE TITLE
Not saving changes

### ISSUE THREAD

**Issue by Jorgetereso** [ThemeFuse/Brizy#805]
Changes made are not begin saved, even when I empty cache the problem still persists. 
When I enter in edit mode through brizy again I see the changes there. Just not visible in the actual site.

**Comment by christianotfg** [comment]
Same problem. Stop working today.

**Comment by Tanya-MCS** [comment]
I'm having the same issue.

**Comment by Tanya-MCS** [comment]
One website will save changes, however, another website won't. It started when I added a video yesterday. Even when I remove the video, it still wont save my changes.

**Comment by wazidalibasha123** [comment]
Today i upgrade to latest Version 1.0.41, now i am also having same issues, from last 3 hours i am trying to edit my page,when i am going to edit with Brizy its showing page like this https://imgur.com/a/vG6YK3z

**Comment by NataliaBB** [comment]
Hello Everyone!  @Jorgetereso @christianotfg @Tanya-MCS @wazidalibasha123 
Natalia here!
We have noticed on different users this issue, but all they are individual (most of them -  server error 500)
Please, let us check on your pages, send me a facebook message and mention this issue inside - #805 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by newdevgirl** [comment]
I am having the same issue. Where is the link to your FB?

**Comment by Jorgetereso** [comment]
Yes, can't find the fbook user either.
Thanks


JORGE TERESO / CREATIVE DIRECTOR
Skype. jorgetereso / M. +54 911 59574375

**Comment by Tanya-MCS** [comment]
I FINALLY GOT MINE TO WORK. For me, it was a matter of updating the plugin.

**Comment by jjrecort** [comment]
Hi, I have the same problem
My WP Version is 4.9.8 | Unyson 2.7.20

I also paid for the pro version almost 3 months ago, and I still didn't get any feeback or info

Thanks!

**Comment by NataliaBB** [comment]
Hello everyone!

If you still have this issue -  please update both plugins to our latest version 1.0.45 for the Free Version and 0.0.12 for the PRO version.

For this kind of bugs, please send me a short notification on our Facebook chat.
Open our website: www.brizy.io, in the right corner you will find the Facebook icon. Hit  WP credentials tab and write me your problem! 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)




Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by Michaeld2018** [comment]
My solution was instead of losing the progress that you made you just go to preview than on the preview page you will enable editing with brizy and than it will save it 100 precent works
