### ISSUE TITLE
Sorry, Safari is not supported

### ISSUE THREAD

**Issue by oconrard** [ThemeFuse/Brizy#806]
For information when opening a page in safari with Brizy builder, I receive this message : **Sorry, Safari is not supported**

**Comment by NataliaBB** [comment]
Hey Oliver.
Brizy back-end doesn't work on Safari, only the front-end mode (preview)

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by oconrard** [comment]
Hi Natalia,

Yes that's why I inform you.
Do you intend to solve that or not ?

Kind regards

Olivier
