### ISSUE TITLE
Error with no arrows

### ISSUE THREAD

**Issue by McScience** [ThemeFuse/Brizy#807]
On the Edit page, the arrow is applied, but on the preview page, no arrow appears.

**Comment by NataliaBB** [comment]
Hello @McScience 
Natalia here.

I'm waiting for your wp credentials....

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
