### ISSUE TITLE
Google Analytics and Google Tag Manager

### ISSUE THREAD

**Issue by techguy76** [ThemeFuse/Brizy#808]
The current issue with Brizy and Themefuse is that it does not allow proper embedding of google tag manager. Google tag manager requires tracking code to be placed in the head tag and at the top of a body tag but not in a div. We need an option or setting in brizy to place google analytics tracking codes specifically the js files that google tag manager requires.

**Comment by Josecarpeniet** [comment]
Yes, this is important.

**Comment by kdub718** [comment]
+1

**Comment by NataliaBB** [comment]
HI @techguy76 
Natalia here!

You can place the google tag manager in the header of your theme
For the moment, we don't plan to improve this module. We plan to add SEO tags, and after, we will find a solution for Google tag manager.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by techguy76** [comment]
Natalia do you know anything about google tag manager? It requires that you install two scripts. One in the head (thats the easy one thanks to themefuse) the other one is supposed to be in the body. However, it can not be in a div. With the way themefuse and brizy is written you can not get a proper install of google tag manager inside of themefuse or brizy.

**Comment by UniversalDesignz** [comment]
Hi @NataliaBB 

Can you please provide an update on this need it in BrizyPro please...
