### ISSUE TITLE
Page missing

### ISSUE THREAD

**Issue by Geekydesigns** [ThemeFuse/Brizy#809]
Not sure what i've done, I can not edit the home page as its missing ? The page is shown in sketch 2 attached but then when I open with Brizy Its missing sketch 1.

Any Ideas
![sketch1](https://user-images.githubusercontent.com/44667632/47843911-f8a3b780-ddb8-11e8-9f76-762e30a43952.png)
![sketch2](https://user-images.githubusercontent.com/44667632/47843912-f8a3b780-ddb8-11e8-8f8a-1e762dc8482c.png)

**Comment by NataliaBB** [comment]
Hi @Geekydesigns 
Natalia here

I may need some more details regarding your question. Can we discuss on our facebook chat? Please mention this issue inside - 809
https://brizy.io/  

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
