### ISSUE TITLE
IDEA - Testimonials

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#81]
My current favorite testimonial plugin is BNE Testimonials. That said, you folks are masters at making things look incredible. Would love to see an exclusive Brizy feature to add testimonials in different ways. 

This is one thing I've seen come up a lot in the various pages I frequent. There just aren't a lot of good options out there.

**Comment by bagrinsergiu** [comment]
Hi,

We don't plan to add testimonials element. We plan to add more testimonial blocks.

Thanks for suggestion 
Sergiu
