### ISSUE TITLE
Safari and Brizy

### ISSUE THREAD

**Issue by aj0610** [ThemeFuse/Brizy#812]
Hello - I re-did my ENTIRE website on Brizy and used safari to do so.  Today it now says that Brizy is not supported by Safari when I try to edit my website.  What is happening?

**Comment by NataliaBB** [comment]
Hello @aj0610 
Natalia here.

Brizy doesn't support the editor mode on Safari, only preview mode.  

My Best Regards, Natalia

**Comment by aj0610** [comment]
Yes I see that now but I created the whole website through safari on Brezy. When did that change?

Cheers!
Andrea Pezzillo 
Www.trade-works.org

**Comment by NataliaBB** [comment]
Hi @aj0610 

We changed a month ago. But you can continue to edit on Chrome the same page. 

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
