### ISSUE TITLE
Phone mode image blocks disappeared

### ISSUE THREAD

**Issue by jlconsult** [ThemeFuse/Brizy#814]
Blocks with images are not shown on a phone
https://avstudiosupport.nl/cubase-met-vienna-ensemble-pro/

https://cl.ly/05aee991545e

https://cl.ly/b495f5238a31

**Comment by NataliaBB** [comment]
Hello @jlconsult 
Natalia here!
I would like to see the back-end of your mobile page version. Please send me a message via our Facebook chat and mention this issue inside #814 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by jlconsult** [comment]
Hi Natalia,

here the screenshot from the Brizi mobile editor
https://cl.ly/914ae61fbcaf

**Comment by NataliaBB** [comment]
Hi!
This issue has been fixed with a temporary solution - adding spacer into images.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
