### ISSUE TITLE
#Post Title - Dynamic content tag not working on Single template for posts

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#815]
The dynamic content tag for retrieving the title is now broken due to the latest updates. (I currently have Brizy 1.0.42 and Brizy Pro 0.0.11)

When I use the **#Post Title** tag for my blog posts it now shows the title for the template name instead of the post title. This used to work perfectly but not anymore.

If needed I can provide login credentials to one of the websites I am experiencing this issue.

Best regards,

Christiaan

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
