### ISSUE TITLE
Blocks Keep Disappearing When Trying To Edit Any Mode But Desktop

### ISSUE THREAD

**Issue by techguy76** [ThemeFuse/Brizy#816]
Ever since I updated to the newer brizy when i try and edit blocks especially in any mode other than desktop the block disappears. It will come back if I hit refresh and have the changes I made but it keeps dissapearing.

**Comment by NataliaBB** [comment]
Hi @techguy76 
What PHP version do you have installed?
Please, give me more details on our Facebook chat. Mention this issue inside #816 
Thank you!
Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
