### ISSUE TITLE
Uploading Image Issue 

### ISSUE THREAD

**Issue by goautomated** [ThemeFuse/Brizy#817]
1. When I upload an image it logs me out of wordpress

2. I hate that there isn't a simple way to upload an image in its original proportions.

Video of issues here: http://share.adviceoffice.co.uk/02becaed4d8d

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
