### ISSUE TITLE
Add Dynamic Data Option to Progress and Counter Elements

### ISSUE THREAD

**Issue by dmccan** [ThemeFuse/Brizy#818]
I have a Toolset field "my-rating" and I was surprised that I was not able to use it with the Progress element.  I would like to enter a number between 0-100 in the Toolset field and have that value shown as a percentage in the template for the custom post type.  Can you please enable this?

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/RZeSEZss/176-dynamic-content-progress-bar

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu

**Comment by dmccan** [comment]
Thanks
