### ISSUE TITLE
IDEA: Custom Pages

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#82]
Would love to be able to use Brizy on pages like archives, 404's, and others like that.

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/adyn27Fb/42-templates

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
