### ISSUE TITLE
Restaurant Template Home Page pulls up Medical Template

### ISSUE THREAD

**Issue by souljoy** [ThemeFuse/Brizy#821]
When you click on the 'Fresh & Delicious' Home Page of the Restaurant template under the Food category, it loads up a medical services home page instead.  All of the other restaurant pages are loading correctly - it's just the home page that's not working correctly.  Look forward to the fix.  Thank you.

**Comment by UomoMacchina** [comment]
I confirm the issue and hope a fix soon or a workaround to be able to apply the correct page.
Thanks.

**Comment by NataliaBB** [comment]
Hi @UomoMacchina @souljoy 
Natalia here.

Thanks for reporting this issue. The team is working on this migration and it will be fixed asap.

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
