### ISSUE TITLE
Brizy page not showing up

### ISSUE THREAD

**Issue by aj0610** [ThemeFuse/Brizy#822]
Hello - The brizy page is not showing up - only the older word press version is showing.  How do i make the new brizy show up?

**Comment by NataliaBB** [comment]
Hello @aj0610 
Natalia here!
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by aj0610** [comment]
Why are you closing this issue?  I need help - My brizy page is not letting
me see nor edit.  I re-did my WHOLE website with brizy - This cannot be
happening.  I need your help not for you to close the issue.
*Andrea Pezzillo*
*Founder & CEO *
*Trade-Works Foundation*
www.trade-works.org


*"If we can influence one, it will impact a community!"*
