### ISSUE TITLE
[BUG] Font Size and Line-Height Problems in v1.0.42 (Mobile/Tablet only)

### ISSUE THREAD

**Issue by NichlasB** [ThemeFuse/Brizy#823]
After updating to v1.0.42, I noticed on mobile that the font size on my site was heavily reduced (from >16px to 16px or even down to 5px in some cases).

Also, the text line-height no longer registers.

I then checked on the new tablet view, and the issue exists there as well.

The global settings for font size and line-height are currently being ignored on mobile/tablet.

Screenshot: https://cl.ly/1928e02c11dd

**Comment by NataliaBB** [comment]
Hi Nichlas @NichlasB 
Natalia here.
We didn't have any changes regarding fonts in the last update. But, we would like to to check and tests your issue. Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
