### ISSUE TITLE
Suggestion for form

### ISSUE THREAD

**Issue by nivelsur** [ThemeFuse/Brizy#826]
Add date field
Add time field
Add attached field
add function to button align horizontal

**Comment by NataliaBB** [comment]
Hi Tomas @nivelsur!
Natalia here!
Thanks for your suggestions.
I added them to our project manager.

Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
