### ISSUE TITLE
Images display in builder, but not in Preview or Live

### ISSUE THREAD

**Issue by grabassenstein** [ThemeFuse/Brizy#827]
The images display perfectly in the Brizy page editor, but once I push to preview or live they won't display. Email me for login credentials.

**Comment by grabassenstein** [comment]
By the way, I'm running:
Brizy 1.0.42
Brizy Pro 0.0.11 
MultiSite (yes, it's multisite wide). All sites EXCEPT my main. So, I suspect it's the htaccess file, but I don't know what to write or change in there, because as I said, my images are viewable in the media library and in the Brizy page editor, but not live.

**Comment by NataliaBB** [comment]
Hi @grabassenstein 
Natalia here!
It may be a server issue, but I need to test and check the console.
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
