### ISSUE TITLE
Savoy Theme (Search Incompatibility)

### ISSUE THREAD

**Issue by franciscoesser** [ThemeFuse/Brizy#829]
​Hello Brizy team.-

First, congrats for your great work!

I have a problem using Savoy Theme with Brizy Builder... 

Exactly with the search, when I active Brizy the Product Search don't work.

I attach a image to show you, please help me... I really want to use both together.

![savoy-brizy](https://user-images.githubusercontent.com/5321053/47978211-caf98f80-e092-11e8-9c22-1c84c851a1d3.png)

Thank you

**Comment by NataliaBB** [comment]
Hello Francisco! @franciscoesser 
I've sent you a reply via our Facebook chat. Waiting for your credentials.

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
