### ISSUE TITLE
IDEA - Page Navigation Customization

### ISSUE THREAD

**Issue by CJKrets** [ThemeFuse/Brizy#83]
I use this quite a bit. Would be so much better if there were the possibility of doing our own within the builder itself.

https://wordpress.org/plugins/wp-pagenavi/

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/SMrXINDT/169-page-navigation-customization

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
