### ISSUE TITLE
[Feature Request] Translation of form messages.

### ISSUE THREAD

**Issue by edugsdf** [ThemeFuse/Brizy#832]
When a message is successfully sent through the form, this text appears: "_Your email was sent successfully_"
It is in the source code: `brizy/public/editor-build/editor/js/preview.js`

Opening the source code, I see that there are other messages. The correct thing is that everything is in the translation file. Can you meet this request?

**Comment by NataliaBB** [comment]
Hello @edugsdf 
Natalia here, Brizy team

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
