### ISSUE TITLE
[Feature Request] WPML compatibility

### ISSUE THREAD

**Issue by tdechangy** [ThemeFuse/Brizy#833]
I still don't see this on the roadmap. Are you willing to integrate it soon as a major feature ?

**Comment by NataliaBB** [comment]
Hi @tdechangy 
Natalia here!
You don't see the WPML in our Roadmap because Brizy is compatible with WPML.  
We worked on improvements this couple of weeks and they will be available within the next updates. 

My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
