### ISSUE TITLE
[Feature Request] CSS text-shadow | Outline text

### ISSUE THREAD

**Issue by rorar** [ThemeFuse/Brizy#835]
[text-shadows](https://www.w3schools.com/cssref/css3_pr_text-shadow.asp)... Basics.
I really miss this simple feature. 
if you're adding white text on video with white parts you can easily put a 0.5px grey colour around your text or a bit blur and it will be readable. :-)

Also a feature to set text outline would be great.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/jGWjlNz0/104-text-shadow

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
