### ISSUE TITLE
Bug on Mobile

### ISSUE THREAD

**Issue by AdrienEquinoxes** [ThemeFuse/Brizy#837]
Hi,

I have a bug when I try to modify the mobile or tablet version : https://ibb.co/iBPkQA

my element disappears and a message appears.

This bug persists since several update.

Have you ever had this problem ?

**Comment by nucaica** [comment]
I have the same problem. Not only on Mobile but also on Tablet. https://github.com/ThemeFuse/Brizy/issues/844

**Comment by NataliaBB** [comment]
Hello Everyone!
Natalia here!

If you have TheCore theme, please update to the latest version.
If you still have this error,  please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia

**Comment by nucaica** [comment]
Natalia why did you close all the three issues without us giving you any input about it being resolved or not?
I still have issues, I'm using a child theme and now I'm also getting the errors in the Desktop version. So Mobile, Tablet and Desktop are not working correctly when editing.
