### ISSUE TITLE
Pro post elements lost after update and fatal error in frontpage!!!

### ISSUE THREAD

**Issue by PriitGit** [ThemeFuse/Brizy#838]
After update brizy 1.0.43 post element not shown anymore?

**Comment by PriitGit** [comment]
And all sites have those errors:
Fatal error: Uncaught ArgumentCountError: Too few arguments to function BrizyPro_Main::filterContentProcessors(), 2 passed in /verymedesigns/wp-includes/class-wp-hook.php on line 286 and exactly 3 expected in /verymedesigns/wp-content/plugins/brizy-pro/main.php:126 Stack trace: #0 /verymedesigns/wp-includes/class-wp-hook.php(286): BrizyPro_Main->filterContentProcessors(Array, Object(Brizy_Content_Context)) #1 wp-includes/plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 /verymedesigns/wp-content/plugins/brizy/content/main-processor.php(41): apply_filters('brizy_content_p...', Array, Object(Brizy_Content_Context)) #3 /verymedesigns/wp-content/plugins/brizy/public/main.php(347): Brizy_Content_MainProcessor->__construct(Object(Brizy_Conte in /verymedesigns/wp-content/plugins/brizy-pro/main.php on line 126

**Comment by PriitGit** [comment]
An I newer updated Brizy free to 1.0.44????

**Comment by NataliaBB** [comment]
Hello @PriitGit Priit

Natalia here,
As we spoke on the chat, in the new update this issue will be fixed.

Thank you
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
