### ISSUE TITLE
Can't edit slider in mobile view

### ISSUE THREAD

**Issue by SzymonG4** [ThemeFuse/Brizy#839]
Hello,
When i swich to mobile view and i try to edit slider i got error:
An error happened while trying to display this block
You canopen an issueorremove this block

When i open console i got many errors like:

DOMException: "Node was not found" editor.vendor.js:53:71977
qi
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:71977
Ki/n.callback
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:75023
Wo
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:52843
Ho
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:53306
Xa
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:84713
Ga
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:81010
Va
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:80509
Ha
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:80335
Ba
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:79708
ma
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:78940
enqueueSetState
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:53:54476
_.prototype.setState
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:45:1267
_/</a</a.prototype.onStateChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:25:10830
y
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:32:219163
O/</</<
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:460384
b/</<
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:459339
r/</</<
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.vendor.js:37:79673
this.handlePageChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:1123408
handleValueChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:14573
patchValue
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:14447
onChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:15276
handleValueChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:14573
updateItem
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:21315
h
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:22339
handleValueChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:14573
handleValueChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:1165646
patchValue
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:14447
onChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:15276
handleValueChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:14573
updateItem
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:21315
h
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:22339
handleValueChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:14573
patchValue
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:14447
bindToolbarItems/</e.onChange
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:16454
T/this.handleChangePosition
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:1127603
v/this.onDrag
http://www.mindness.usermd.net/wp-content/plugins/brizy/public/editor-build/editor/js/editor.js:1:1126195
dispatch
http://www.mindness.usermd.net/wp-includes/js/jquery/jquery.js:3:12392
add/r.handle
http://www.mindness.usermd.net/wp-includes/js/jquery/jquery.js:3:9156

How can i fix it?
Regards,
Szymon

**Comment by nucaica** [comment]
It seems that we are encountering the same problem. I have it not only on trying to edit a slider, but actually on trying to edit any block both in Mobile and on Tablet. https://github.com/ThemeFuse/Brizy/issues/844

**Comment by NataliaBB** [comment]
Hello @SzymonG4 
Please, if you use TheCore theme, update to the latest version. 
If the problem still persists, send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
