### ISSUE TITLE
[Feature Request] column/row backgroud image to dynamic

### ISSUE THREAD

**Issue by PriitGit** [ThemeFuse/Brizy#840]
Can brizy team add column/row background image to dynamic, just like block background image right now.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public https://trello.com/c/voKA4175/132-dynamic-content-column-row-background-image

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
