### ISSUE TITLE
Brizy page not working

### ISSUE THREAD

**Issue by aj0610** [ThemeFuse/Brizy#841]
I re-did my ENTIRE website with brizy which took so much time.  And the pages that I have created are not showing when I go to my website, just the word press pages are showing.  what is happening? how do I fix this?!

**Comment by NataliaBB** [comment]
Hey @aj0610 
Natalia here!

If you use Unyson framework, you need to disable it when you edit Brizy page. 
Send me please a message via our Facebook chat if you need more assistance.


![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
