### ISSUE TITLE
Block Error in Tablet/Mobile View (any change)

### ISSUE THREAD

**Issue by nucaica** [ThemeFuse/Brizy#844]
What started with an error while modifying text (smaller) in Tablet view got worse. The error also happened doing the same action in the Mobile view. But actually, if spend enough time in any block, it will eventually deliver the block error message even if no changes have been attempted. Basically, I cannot edit the Tablet or the Mobile view at all.

An error happened while trying to display this block
You can open an issue or remove this block

![image](https://user-images.githubusercontent.com/1757155/48117505-bc190580-e269-11e8-961f-32c92f88e50e.png)

**Comment by NataliaBB** [comment]
Hi @nucaica 
Natalia here, Brizy team

Please send me a message via our Facebook chat and mention this issue inside - #844 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
