### ISSUE TITLE
Saved blocks dont show

### ISSUE THREAD

**Issue by ZasJaz** [ThemeFuse/Brizy#846]
I'm saving some blocks and they simply dont show. My tab "Saved" is empty.

**Comment by Ravisi** [comment]
I have the same problem! Also with the Global Blocks. I save them, i get the message "saved" but in the Add Block Menu, the Tabs Saved and Global are empty, and also not showing the global blocks i am using in the web, but luckily they still in the Web.

**Comment by NataliaBB** [comment]
Hi Everyone! @ZasJaz @Ravisi 
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by havequestions** [comment]
Same here.

**Comment by jmald91** [comment]
Having the same issue with saved blocks not showing

**Comment by wtassis** [comment]
Same here.

**Comment by bagrinsergiu** [comment]
Hi all,

Saved and Global Blocks issue was released in 1.0.45 version. 

Thanks for reporting and sorry for the inconvenience.
Sergiu
