### ISSUE TITLE
PopUp (default popup block not showing on my website)

### ISSUE THREAD

**Issue by mindandflex** [ThemeFuse/Brizy#847]
Please see FB group for more info. But long story short, I am having an issue with embeding code to the button on my website. I tried to clear cache and so on, plugins are up to date. And default popup block is not showing. Please see the video: https://cl.ly/a503e6c67761

Thanks

**Comment by mindandflex** [comment]
New update, completely fixed my problem! Thank you :)

**Comment by haroonshaikh** [comment]
Having exactly same issue with me, Tried deleting and re-installation brizy and brizy pro (v11) as well but issue still persists.
