### ISSUE TITLE
WP post block not rendering

### ISSUE THREAD

**Issue by elementdave** [ThemeFuse/Brizy#848]
I just updated Brizy to Version 1.0.44 and I am also running Brizy Pro Version 0.0.11. When I updated to 1.0.44 my recent posts (WP post block) stopped rendering on the front-end of my site. The block is still there and everything appears to be okay. I actually didn't touch the block or add any other plugin. Everything was working correctly until I upgraded to 1.0.44. Any help would be appreciated.

![image 11-7-18 at 10 20 am](https://user-images.githubusercontent.com/4204990/48152047-bde9c580-e277-11e8-82b2-b9aa87e358a5.jpg)

![image 11-7-18 at 10 21 am](https://user-images.githubusercontent.com/4204990/48152064-c2ae7980-e277-11e8-9ea4-d458ca97f963.jpg)

**Comment by PriitGit** [comment]
Pro Version 0.0.12 resolve that bug.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
