### ISSUE TITLE
Tablet and Mobile editing

### ISSUE THREAD

**Issue by krol1k** [ThemeFuse/Brizy#849]
When I am trying to edit something on tablet or mobile view, I recieve "An error happened while trying to display this block" and this: 
![brizy_bug](https://user-images.githubusercontent.com/12499921/48186176-52235d80-e348-11e8-8dfc-51ab35a91b56.png)

**Comment by krol1k** [comment]
if I switch to an empty template, then everything works fine. Theme - The Core.

**Comment by NataliaBB** [comment]
Hi @krol1k 

Update The Core. Send me a short notification if it's fixed.

Regards, Natalia

**Comment by krol1k** [comment]
Yes, it works. Thanks.
