### ISSUE TITLE
Website using Brizy not optimizing on safari browser

### ISSUE THREAD

**Issue by parth1117** [ThemeFuse/Brizy#85]
I am using brizy to make a website on chrome. However when I view the website on safari the website have random unwanted gaps and spaces. It is not optimized properly and unwanted widgets can be seen.

What could be the issue???

**Comment by bagrinsergiu** [comment]
Hi @parth1117 

I made a lot of tests on safari + mac this week and i can't reproduce this issue. 

1. https://prnt.sc/jrmfav
2. https://prnt.sc/jrmfwm

Can you give me a page screen or video with more details?

Thanks 
Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
