### ISSUE TITLE
Dynamic Posts Issues (Follow up)

### ISSUE THREAD

**Issue by peleroberts** [ThemeFuse/Brizy#850]
Ok so its been almost a month now and no joy in solving the dynamic post issue which is reducing the dynamic posting capabilities (not full dynamic).

Ok so I spoke to dimi briefly via brizy facebook community.

1. I need a dev to revert the text color changes that they made which makes the **dynamic content text #000**

2. I found the problem to my issue which is when i add **< br >** between paragraphs which is missing to the **TEXT EDITOR** not the **VISUAL EDITOR** it solves the problem.

I'm not sure if this helps or if there is anything you can do with that finding to resolve this long standing issue.

See attached images below showing where i added the break in text editor

![screenshot 2018-11-08 at 15 58 41](https://user-images.githubusercontent.com/1058238/48210512-5e6ee100-e36f-11e8-8ee0-65b034678619.png)
![screenshot 2018-11-08 at 15 57 56](https://user-images.githubusercontent.com/1058238/48210513-5e6ee100-e36f-11e8-8cde-915f3fc89009.png)

**Comment by peleroberts** [comment]
....

**Comment by peleroberts** [comment]
Yay! 👍 

Excellent news! Look forward to it

Thank you so much for letting me know Sergiu.

**Comment by peleroberts** [comment]
Though Sergiu, one of the devs who had access to the back end has disabled the ability to change text color on one of my sites >_<

**Comment by peleroberts** [comment]
Sergiu,

I see you added some labels [dynamic content / 0.0.13]. Can you shed some light on what this means please. Thanks.

**Comment by peleroberts** [comment]
nope not working....

**Comment by EdwinDJanssen** [comment]
@peleroberts @bagrinsergiu I can also confirm that all font-styling is gone w/ Brizy templates. I also reported this 7 weeks ago...

**Comment by peleroberts** [comment]
@bagrinsergiu All is working well. Ill close this also. Thank you.

**Comment by bagrinsergiu** [comment]
Hi @EdwinDJanssen 

Sorry for the delay. I contacted you via facebook. Can you give me WP credentials in order to investigate this issue on your side.

Thanks
Sergiu
