### ISSUE TITLE
Favorite's thumb preview

### ISSUE THREAD

**Issue by havequestions** [ThemeFuse/Brizy#851]
Hi,

Could you please make so when I save an element to favorites I can see the saved block correctly in favorites. Right now it just shows the original element it was modified from not the way the element looks now.

Thank you,
Lana

**Comment by bagrinsergiu** [comment]
Hi Lana, 

Sorry for the inconvenience. Is a known issue. It is in our doing list. Fix is planed in 2-4 weeks.

Thanks for reporting
Sergiu

**Comment by havequestions** [comment]
Thank you

**Comment by havequestions** [comment]
Hi, How's the fix is going?
