### ISSUE TITLE
email hyperlink

### ISSUE THREAD

**Issue by kguldent** [ThemeFuse/Brizy#853]
When in CORE theme (themefuse) and adding a text block with in example E:office@office.com and then create a hyperlink mailto:office@office.com -> it doesn't take it / doesn't save it. Also once you are in the box of the hyperlink and typing the email address, you'll notice that your cursor jumps to the beginning of the text block ... weird stuff ...

**Comment by bagrinsergiu** [comment]
Hi 

Sorry for the inconvenience. Is a known issue. A fix for this issue is planned in next version 1.0.46.

Thanks for reporting. 
Sergiu
