### ISSUE TITLE
Post Archive Template - Post Content Field Not Working Correctly

### ISSUE THREAD

**Issue by dmccan** [ThemeFuse/Brizy#854]
I set the dynamic field to Post Content in the Archives Element. The post content for the first post is displayed for all posts.  You should test all of the dynamic fields so they display correctly. 

I have Brizy 1.0.45 and Brizy Pro 0.0.12 installed. 

It looks like this is related to #732 

![brizy-post-content-1](https://user-images.githubusercontent.com/2622805/48267981-5c516480-e3f9-11e8-8fef-3a5cd810dec7.png)

![brizy-post-content-2](https://user-images.githubusercontent.com/2622805/48267988-61aeaf00-e3f9-11e8-94a8-be332618f9ea.png)

**Comment by bagrinsergiu** [comment]
Hi @dmccan 

We are preparing a new update (0.0.13) this week with some dynamic content improvements and fixes. 

Thanks for reporting
Regards, Sergiu

**Comment by dmccan** [comment]
I tested 1.0.47 with 0.0.13 - Post Content is now working.

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
