### ISSUE TITLE
Portfolio link disabled 

### ISSUE THREAD

**Issue by cindy046** [ThemeFuse/Brizy#855]
I disabled Unyson on wordpress because of a bug and reinstalled it -- now Brizy editor doesn't recognize any of the original portfolio items or links -- the page is disabled and I'm unable to edit it with Brizy -it doesn't recognize its own code settings and asks to build a new page even though content is already there.

 
https://drive.google.com/file/d/1425iGRgoMEL44wEdD3IZ_wBLYclw4Ein/view

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
