### ISSUE TITLE
Multiple Galleries in Tabs not working

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#856]
I have a Tab on the page and in 2 of the tabs I have separate galleries. 
I can see both fine while editing, but when I view the page, Only the gallery in the active tab can be seen. 

example: https://creekside.mywebkit.ca/ the active tab has 3 photos, but when you go to the Gallery Tab there is only 1 (all of the photos are stacking on top of each other)

it should look like the attached image

![image](https://user-images.githubusercontent.com/11094497/48285841-d56cae00-e431-11e8-93e9-edb5ca7690c3.png)

**Comment by maxval94** [comment]
Hi @curiousprojects!

This has been fixed and will be included in the next update. I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Maxim
