### ISSUE TITLE
Pop Up

### ISSUE THREAD

**Issue by AntonKing60** [ThemeFuse/Brizy#858]
Request

The ability to re-position the 'close' button

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/FeuO2mWT/174-popup-the-ability-to-re-position-the-close-button

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
