### ISSUE TITLE
Themefuse Settings for core broken can no longer change  theme settings  after update 

### ISSUE THREAD

**Issue by techguy76** [ThemeFuse/Brizy#859]
After updating to brizy pro .12 and the free to the latest I can no longer change theme settings in the themefuse core.  It will not load the page. You can still edit pages on the website with brizy but it isn't pulling in images. Causing lots of 500 server errors depending on what you try to do. 

![image](https://user-images.githubusercontent.com/31962606/48314212-44faae80-e594-11e8-8935-5f9dcb71180d.png)

**Comment by NataliaBB** [comment]
Hello @techguy76 
Natalia here, Brizy team
Please send us your wp credentials and ftp credentials in a message via our Facebook chat. Please mention this issue number inside - #859

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia
Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
