### ISSUE TITLE
Can´t save, every page lost

### ISSUE THREAD

**Issue by test3141592** [ThemeFuse/Brizy#861]
Hello everybody, I created a website with about 10 Sites (not that much) and edit it with brizy. It was working quite good but one evening, when I tried to add some informations, I clicked on "update" at the brizy editor and it showed me the wheel spinning but nothing happend. I tried it a couple of times, didnt work. So i clicked on "preview" but I couldnt see any change. I thought "ok lets give brizy an update, maybe it will work after that", but once the update was finished, i lost EVERY single SITE! They are now blank. I couldnt restore anything. So now i tried to start again but i still cant save any changes i do in brizy... I´m getting desperate. Thankfull for any kind of help!!
I´m using a WP-ZOOM Theme if this matters.

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
