### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by estraatios** [ThemeFuse/Brizy#862]
I would realy like to be able to design my own menu with the submenu. As it is now I can only add the menu and make some chances in the main menu. I would like to create a template for one of the links and add it to the link I want.
You can take an idea of a menu I like in the website archiproducts.com
If you hover over any link you will see submenu with columns, pictures, woo products counter etc.
I think it is something that no pagebuilder has right now.
Thank you

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/poyG4SPN/73-megamenu

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
