### ISSUE TITLE
My page is broken after the update

### ISSUE THREAD

**Issue by ordastrategic** [ThemeFuse/Brizy#863]
I'm not sure what how or why but my pages are no longer responsive, no longer full width, there's an annoying header and title page on all my pages. It looks absolutely awful. Can someone please help.

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
