### ISSUE TITLE
Brizy Data Storage

### ISSUE THREAD

**Issue by mktngtech** [ThemeFuse/Brizy#865]
I am using a free version of Brizy page builder. However, I could not find any data stored on the WordPress cloud storage. Where is the data stored by default, if one is using Brizy page builder. 

Also, if we want the data to be saved on our company server then what needs to be done?

TIA

**Comment by bagrinsergiu** [comment]
Hi TIA,

Sergiu from Brizy here.

All data added via WP is stored in WP_POSTS and WP_POSTMETA tables in your wordpress install. In the past Brizy stored some data on our cloud servers but we migrated all data to WP

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Best Regards, Sergiu
