### ISSUE TITLE
Dynamic Content

### ISSUE THREAD

**Issue by mktngtech** [ThemeFuse/Brizy#866]
Hi Team, 
We have initiated building our website via Brizy Page builder(Free version) on WordPress. What limitations will we face in terms of Dynamic content with this version? Our website would have a couple of pages with dynamic content such as Blogs posts, ebooks, job openings, maps etc. 

Please recommend if it would be a safe bet to go ahead with Brizy Free version or should we switch to pro. What specific limitations will we have with Brizy free that the pro will solve? 

Kindly do not the share the detail links available across the web because I have gone through them all. It would be great if someone could give specific answers to my question. 

TIA

**Comment by bagrinsergiu** [comment]
Hi TIA, 

Dynamic content is available only on Pro version. Free version include only 5 elements for WooCommerce plugin. With Pro version is possible to build Posts, Archives, Galleries, Carousell, Popup ( in 2-3 weeks we plan to add Menu Pro )

Sergiu
