### ISSUE TITLE
Unable to Delete a block

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#867]
Looks like I am no longer able to click the X to delete a custom block:
![image](https://user-images.githubusercontent.com/11094497/48363673-7ba7f600-e674-11e8-98ea-256784450604.png)

**Comment by maxval94** [comment]
Hi @curiousprojects!

This has been fixed and will be included in the next update. I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Maxim
