### ISSUE TITLE
Brizy pages show 500 error

### ISSUE THREAD

**Issue by imranpatel4444** [ThemeFuse/Brizy#868]
Hello,

Brizy plugin auto updated and my website showing 500 error on every pages which was build with Brizy page builder.

Can you please help me regarding this issue.

Thank you

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by imranpatel4444** [comment]
Thank you for your response.

I share Wp-admin access on facebook chat.

Please check

**Comment by danielollie** [comment]
I have the same problem here. 
When I try to create a page with a Brizy template, I'm getting the 500 internal server error on some pages. I can edit but I can't access the final page.
