### ISSUE TITLE
Blank Page in preview

### ISSUE THREAD

**Issue by mktngtech** [ThemeFuse/Brizy#869]
Hi Team,

We are working on our new website & lately when we tried adding new pages we were unable to see the preview. 
I am attaching the screenshot of the page in edit mode as well as in preview mode for your reference.

![screencapture-192-168-2-139-synovergetechnologies-demo3-2018-11-13-13_02_09](https://user-images.githubusercontent.com/44965373/48398150-f7be3e80-e745-11e8-9875-a5c54cdd1fac.png)

![screencapture-192-168-2-139-synovergetechnologies-demo3-2018-11-13-13_02_25](https://user-images.githubusercontent.com/44965373/48398151-f856d500-e745-11e8-908b-60567725ab6d.png)

Kindly let us know how this problem can be resolved & why is this issue arising?

An early response will be appreciated!

Thanks
Juhi

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by mktngtech** [comment]
> Hi,
> Please send me a message via our Facebook chat and mention this issue inside.
> 
> ![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)
> 
> Thank you!
> Regards, Sergiu

Hi, have sent you the same over messenger. Looking forward to your reply:)
