### ISSUE TITLE
Would love to see Marketo form integration.

### ISSUE THREAD

**Issue by andrew-lof** [ThemeFuse/Brizy#87]
It be great if the Pro version of advance forms had built in support for Marketo forms with the option to style them.

**Comment by kb08807** [comment]
I would also love to have Marketo form integration in Pro version

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/SJcFPC1Y/35-form-integrations

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
