### ISSUE TITLE
Emoji are MASSIVE in editor

### ISSUE THREAD

**Issue by TheCrucible** [ThemeFuse/Brizy#872]
I added emoji to a clients page, they look fine in live mode and public page, but when I went back into the editor the emoji are MASSIVE in size. Definitely a bug. I'm using Chrome browser. See example here https://screencast.com/t/mJAdW7lx

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
