### ISSUE TITLE
[Feature Request] Smooth Scroll Support

### ISSUE THREAD

**Issue by cuongtalentccc** [ThemeFuse/Brizy#875]
Hi team,

I love seeing Smooth Scroll Feature on Brizy as Beaver Builder does.
At the moment, Brizy didn't support CSS ID (CSS class support only) in the block section.
Smooth Scroll is important for a one-page design.

**Comment by bagrinsergiu** [comment]
HI 

Smooth Scroll support is available from the beginning. https://jmp.sh/lSEF67b

Thank you!
Regards, Sergiu

**Comment by edugsdf** [comment]
I have the latest version of Brizy, but the soft rolling does not happen.
Could thema be influencing Smooth Scroll?

See in the video that clicking the button does not work well. But clicking the back button to the TOP (which is of thema) makes it smooth.

https://jmp.sh/v/OBuGZLBVdzy2t3kIVBeT

**Comment by maxval94** [comment]
Hi @edugsdf 
Can you give me link to the demo ?

**Comment by edugsdf** [comment]
> Hi @edugsdf
> Can you give me link to the demo ?

After a new update, Brizy returned to work.

Thank you very much for your attention!

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
