### ISSUE TITLE
Brizy error using seline theme

### ISSUE THREAD

**Issue by bembem92** [ThemeFuse/Brizy#876]
Hi

I am using the selin
<img width="1275" alt="screen shot 2018-11-14 at 11 56 05" src="https://user-images.githubusercontent.com/39843554/48481116-58ac4c00-e804-11e8-9038-1ed5afc721a0.png">
<img width="1278" alt="screen shot 2018-11-14 at 11 56 00" src="https://user-images.githubusercontent.com/39843554/48481117-58ac4c00-e804-11e8-9051-d995b1288d3d.png">

e theme for liight.ca  however every time it updates it keeps realigning my website pictures and texts.

Is there a way for you to turn off autoupdates on my website or fix the fatal error in Brizy latest update with the Seline theme

Please contact back ASAP

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
