### ISSUE TITLE
Not Able to Edit the Content in Page. Infinite Loading

### ISSUE THREAD

**Issue by akashpatel91** [ThemeFuse/Brizy#879]
I am not able to edit any content in the site. its just infinite loading when i hit update button

**Comment by ouime** [comment]
same problem here

**Comment by NataliaBB** [comment]
Hi @ouime 
Natalia here! 

Please send me your wp credentials on a  message via our Facebook chat and mention this issue inside - #879 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by ouime** [comment]
Hi Natalia,

How can I find the facebook chat. What is the facebook profile I need to search?

**Comment by ouime** [comment]
Hi Natalia,

https://www.facebook.com/brizy.io/

Is that the right place?

**Comment by Botgal** [comment]
Also experiencing infinite loading. Brizy telling me that changes aren't saved, and when I try to preview or view the page in a separate tab, it's true, they are not there. But when I go back into Brizy and Wordpress, the changes I made ARE there.

**Comment by Brielyn144** [comment]
I have been looking for an answer to this issue for a couple of days!

**Comment by Botgal** [comment]
Be great if we could get an answer on this as changes not saving at all when this happens.

**Comment by Brielyn144** [comment]
I am told to deactivate Brizy Pro, then try to upload

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by paritoshpandya2** [comment]
i am not able to edit two pages without closing the first page. When i try to edit the second page than i get two elements columns and cannot save there after.
