### ISSUE TITLE
Brizzy Team Test Pages indexed in Google

### ISSUE THREAD

**Issue by Ravisi** [ThemeFuse/Brizy#881]
Hi, it would be nice if you erase the pages you create to test the Brizy issues, Google indexed two pages you created in my website to test my issues. Thanks!

![google indexation](https://user-images.githubusercontent.com/41541108/48550514-46e5aa00-e8d3-11e8-88b1-847d4f3be8be.jpg)

**Comment by bagrinsergiu** [comment]
Hi @Ravisi 

I apologize. We will clean it in the future. Thanks for reporting.

Sergiu
