### ISSUE TITLE
Global Blocks Keep Disappearing 

### ISSUE THREAD

**Issue by accessdevicesasia** [ThemeFuse/Brizy#883]
I've created a few global blocks, e.g. Header, Menu, content and they have started to display

An error happened while trying to display this block
You can open an issue or remove this block

Loosing all of the content within them.

I'm not sure if it has something to do with adding the blocks as global, then disabling global and modifying the content.

Brizy Version 1.0.46
Brizy Pro Version 0.0.12

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
