### ISSUE TITLE
An error happened while trying to display this block 

### ISSUE THREAD

**Issue by grzeche** [ThemeFuse/Brizy#884]
HelIo,
I have version 1.0.46 and have this same problem. All plugins was updated, any others were disabled - unfortunatelly nothing better. I found one error in console:

> editor.vendor.js?ver=1.0.72:53 TypeError: Cannot read property 'type' of undefined

Could you help me?
Thank you in advance
Greetings

![image](https://user-images.githubusercontent.com/45048012/48507707-f461aa80-e84c-11e8-8522-f085b4ef4ebf.png)

_Originally posted by @grzeche in https://github.com/ThemeFuse/Brizy/issues/738#issuecomment-438791029_

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by grzeche** [comment]
Hello. Thank for you reply.
Could you help me here? Maybe this help also other people - i see many issues about this problem.. I don't have PRO version, so You recommend to ask here - I know that you have a lot of work, but I wait on Your facebook chat since 1 hour.
Thank you

**Comment by estraatios** [comment]
Hi

I have the same problem.

After migrating to a new domain I got this error. Every time I try to edit a block
![error](https://user-images.githubusercontent.com/34076187/55274475-92787d80-52e1-11e9-91cf-0c4e5710f803.JPG)

The https in settings url are set ok

Also the migration with all in one migration does not updates the buttons urls. All other urls are update but the buttons stayed with old url 

karavarakis@gmail.com

Brizy installed 1.0.66 and Pro intalled 0.0.18

**Comment by NataliaBB** [comment]
Fixed in 0.0.19 PRO version


I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
