### ISSUE TITLE
Some ideas

### ISSUE THREAD

**Issue by theraidens** [ThemeFuse/Brizy#885]
- Sitcky Menu (Needed)
- Tooltip hover (Needed)
- TripAdvisor icon (Needed)
- Use your own icon

**Comment by bagrinsergiu** [comment]
Hi 

Thanks for reporting. 

1. Sitcky Menu is planned for next big Pro update 0.0.14
2. Tooltip hover - Can you give me more details about Tooltip Hover (ex: screenshot) ? 
3. TripAdvisor icon - :) It is very important but i'm now sure how much time it will take.
4. Use your own icon - https://trello.com/c/wrfhV9sj/7-image-svg-support

Thank you!
Best Regards, Sergiu

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
