### ISSUE TITLE
Feature Request: Image module sizing enhancement

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#887]
Hi there,

I would like to request an enhancement feature for the image module.
There are cases when I would like images to be responsive but have a maximum width.

For this reason it would be great if the Brizy Image module could have a 'max-width' property.
This way I could set up an image to be 100% width and set the max-width to for example: 220px.
So the image doesn't take up more space.

Best regards,

Christiaan

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/gHZjCGHO/186-image-module-sizing

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
