### ISSUE TITLE
Feature Request: Line module sizing enhancement

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#888]
Hi there,

I would like to request an enhancement feature for the Line module.
There are cases when I would like lines to be responsive but have a maximum width.

For this reason it would be great if the Brizy Line module could have a 'max-width' property.
This way I could set up a Line to be 100% width and set the max-width to for example: 100px.
So the Line doesn't take up more space than 100px.

Best regards,

Christiaan

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/icLg4xE0/188-line-module-sizing

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
