### ISSUE TITLE
Clicking on a button in editor mode leads to a blank screen

### ISSUE THREAD

**Issue by flavienb** [ThemeFuse/Brizy#890]
When I add a simple button and I want to click on it to edit its parameters, the whole page becomes blank.
It is as if it was following the button link, but the link should be disabled in editor mode.
I think (but not sure) that the problem appeared in 1.0.45

**Comment by flavienb** [comment]
The same goes with clicking on a link actually

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
