### ISSUE TITLE
Incopatibility with bbPress and Autoptimize

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#891]
There is an issue when bbPress and Autoptimize are installed. When trying to create or view a bbPress topic with Autoptimize installed, I get the following error:

`Fatal error: Uncaught Brizy_Editor_Exceptions_UnsupportedPostType: Brizy editor doesn't support 'topic' post type in /SITEROOT/wp-content/plugins/brizy/editor/post.php:170 Stack trace: #0 /SITEROOT/wp-content/plugins/brizy/editor/post.php(97): Brizy_Editor_Post::checkIfPostTypeIsSupported(3050) #1 /SITEROOT/wp-content/plugins/brizy/editor/post.php(149): Brizy_Editor_Post->__construct(3050) #2 /SITEROOT/wp-content/plugins/brizy/compatibilities/autoptimize.php(21): Brizy_Editor_Post::get(3050) #3 /home/brizycom/public_html/wp-includes/class-wp-hook.php(286): Brizy_Compatibilities_Autoptimize->disable_js_optimize(Object(WP)) #4 /SITEROOT/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #5 /SITEROOT/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #6 /SITEROOT/wp-includes/class-wp.php(726): do_action_ref_array('wp', Array) #7 /SITEROOT/wp-includes/functions.php(96 in /SITEROOT/wp-content/plugins/brizy/editor/post.php on line 170`

When I disable Autoptimize or Brizy, it works fine and I can view and create topics. The only way to make it work is to tell Brizy to add the bbPress "Topic" support in the settings but that seems to have no logic so I believe it's a bug. Another solution could be to exclude the Brizy scripts from Autoptimize but I am not sure which scripts need exclusion and I was under the impression that Brizy had added compatibility with Autoptimize.

**Comment by quantumleap33** [comment]
To add to that, there seems to be a problem all ALL post types. For example, if I don't add support for the normal WordPress post type on the Brizy settings and have Autoptimize activated, I will get a similar error with the above.

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by quantumleap33** [comment]
I think there is no need for that. Have you actually tried it yourselves? It's very easy. Just spin a local WP install, add Brizy and Autoptimize, go to Brizy settings, disable support for Posts and try to view the default hello post that WordPress has created during install. You will see the error. The same thing will happen for other post types.

**Comment by ViorelEremia** [comment]
There is a fix here: https://github.com/ThemeFuse/Brizy/pull/933
The next update will have it.
