### ISSUE TITLE
Site simply got disconfigured after updating the Brizy PLugin 

### ISSUE THREAD

**Issue by Voltsite** [ThemeFuse/Brizy#892]
I updated the Brizy plugin and all the work done on the non-profit website got misconfigured. Please, can you look into this issue as soon as possible because it is extremely critical for the organization?

LittleCrowns.org

**Comment by Voltsite** [comment]
updated it, working now

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
