### ISSUE TITLE
[Feature Request] ACF Dynamic Content support for Google Maps

### ISSUE THREAD

**Issue by pilpfiction** [ThemeFuse/Brizy#894]
I have a custom fields in ACF (Advanced Custom Fields) which holds an address.

I wanted to use this address in the Brizy Goggle maps module. Howeverthis module doesn't work yet with Dynamic Content.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/W8NyetMS/184-acf-dynamic-content-support-for-google-maps

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
