### ISSUE TITLE
[FEATURE REQUEST] METABOX

### ISSUE THREAD

**Issue by sondreal** [ThemeFuse/Brizy#895]
I use metabox a lot and I guess a lot of other people that make custom wordpress sites use it a lot, and I would love to see an integration with it.

https://metabox.io

**Comment by bagrinsergiu** [comment]
Hi, 

Sergiu from Brizy here.

I added this suggestion in our public roadmap: https://trello.com/c/Or4i8sKo/182-dynamic-content-metabox

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
