### ISSUE TITLE
Feature Request: Setup Popups to be able to load sitewide based on various conditions

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#896]
Hi there,

I would like to make a feature request regarding Popups.
At the moment we can setup popups when a user clicks on a button or element.

However it would be even greater if we were able to setup a popup and make it display based on dynamic conditions and make it show anywhere on the website. For example:

It would be great if we could setup a popup and make it appear when a user visits a certain page or post. Or perhaps show a popup on the homepage but only when a user visits the page between a specified time or date.

Until now I used this plugin to create popups: https://nl.wordpress.org/plugins/popup-builder/
This plugin is compatible with the Divi Builder but unfortunately not with Brizy.

But since Brizy's popup builder way better in terms of ease of building and customization it would be awesome if Brizy would get it's own popup builder that can show it's popups sitewide based on various conditions such as date/time, page name/type etc.

Best regards,

Christiaan

**Comment by bagrinsergiu** [comment]
Hi Christiaan,

Sergiu from Brizy here.

I added this suggestion in our public roadmap: https://trello.com/c/zUS41MkD/92-onclick-popup

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
