### ISSUE TITLE
change global link color from light blue 

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#899]
Is there a way to change the general blue link color within Brizy? I can change it in css but am I missing this option?

**Comment by bagrinsergiu** [comment]
Hi 

Sergiu from Brizy here.

This option is not available right now. 

I added this suggestion in our public roadmap: https://trello.com/c/abkAqzvg/102-text-link-color-hover-color

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
