### ISSUE TITLE
Suggestion: Add ONTRAPORT Integration

### ISSUE THREAD

**Issue by Emrys2020** [ThemeFuse/Brizy#90]
Hi there, 
Looking forward to Pro coming out. 
Adding ONTRAPORT for your form integrations as well. 
Thanks.

**Comment by bagrinsergiu** [comment]
Hi @Emrys2020,

Thank you for suggestion. Added to our to do list. 

Sergiu

**Comment by bagrinsergiu** [comment]
Brizy Roadmap Link: https://trello.com/c/SJcFPC1Y/35-form-integrations

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
