### ISSUE TITLE
Feature Request: When Adding An URL, Display Menu Of All Internal Pages

### ISSUE THREAD

**Issue by bytesource** [ThemeFuse/Brizy#901]
Right now it seems when adding a link, e.g. to a button, I need to paste in the exact URL even if I only want to link to an internal page on the site (About US, Contact etc.). 

Instead I suggest displaying a searchable dropdown with all available pages on the site, so that I just need to click on the one I want. Also, if you store the page by its ID internally, changing a page's slug later would prevent all links pointing to that page to suddenly return a 404 error.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/3WIkCKX7/183-link-internal-pages

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
