### ISSUE TITLE
Tag <a> break the line

### ISSUE THREAD

**Issue by cTraderGURU** [ThemeFuse/Brizy#902]
Hi all,
have a big problem, in this image u can see how links appear in my page, break the line and this is wrong

![screenshot 2018-11-20 13 11 00](https://user-images.githubusercontent.com/41258919/48773120-bccc8580-ecc6-11e8-94de-8765909ed989.jpg)

Page : https://ctrader.guru/downloads/cbot-base/

**Comment by bagrinsergiu** [comment]
Hi @cTraderGURU 

Sergiu from Brizy here. 

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by bagrinsergiu** [comment]
Editor is adding <br> elements in each <a> tag. Can you give e WP Credentials via Brizy Chat from Our site: Brizy.io

Thanks 
Sergiu

**Comment by ViorelEremia** [comment]
@cTraderGURU can you try this pull request: https://github.com/ThemeFuse/Brizy/pull/927
It is an incompatibility with Gutenberg plugin
