### ISSUE TITLE
Rename Blocks

### ISSUE THREAD

**Issue by curiousprojects** [ThemeFuse/Brizy#903]
Renaming Blocks would be handy for organization and well as the anchor tag naming. (.com/#zmiavbwhqc)

**Comment by bagrinsergiu** [comment]
Hi, 

Sergiu from Brizy here.

I added this suggestion in our public roadmap: https://trello.com/c/oXf1o2Jg/168-anchor-link

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
