### ISSUE TITLE
Icons are not showing in live editor

### ISSUE THREAD

**Issue by SzymonG4** [ThemeFuse/Brizy#904]
Hello, after moving my website to another server svg icons in Brizy's live editor are not showing. I got errors in console like: 
editor.vendor.js?ver=1.0.72:53 Unsafe attempt to load URL https://www.lepszyhotel.pl/wp-content/plugins/brizy/public/editor-build/editor/icons/icons.svg from frame with URL https://lepszyhotel.pl/?brizy-edit-iframe. Domains, protocols and ports must match.
How can i fix it?
Thanks,
Szymon

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
