### ISSUE TITLE
I bought the pro version.. Now where is it?

### ISSUE THREAD

**Issue by ericabrom** [ThemeFuse/Brizy#906]
I bought the pro version. Logged in to your website. Where is the pro version download?

**Comment by NataliaBB** [comment]
Hey @ericabrom 
Natalia here.
You need to log in into your Brizy account, via www.brizy.io - https://jumpshare.com/v/sqVC9tFEvHsFO9rCOcv3 

From your account download the zip file PRO 0.0.12. Install and activate the plugin in your WordPress dashboard.  You need to have Brizy Free Version installed and enabled. 

If you have any other questions, please send us a message via our Facebook chat.

Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
