### ISSUE TITLE
ACF fields not showing on a wordpress custom taxonomy page

### ISSUE THREAD

**Issue by crodesign** [ThemeFuse/Brizy#907]
Website: https://activitiesbuilder.com/activities 

This page works as expected, which is great. The issue comes in selecting any of the custom taxonomies to display its archive page (location or type). The same archive template is used for both pages. The page does display all of the default page related information in the columns except for the ACF data.

Hopefully, it's a mater of I have setup something wrong. Thanks!

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by crodesign** [comment]
I have posted this to the Messenger tool on your website a couple days ago. I am still hoping for feedback. Thank you.

**Comment by ViorelEremia** [comment]
The issue was fixed in the latest update of both plugins free and pro. @crodesign please open a new issue if it still exists.

**Comment by crodesign** [comment]
Thank you. I discovered this today. It works wonderfully.

Denis Crowder
CroDesign
808-741-1514
