### ISSUE TITLE
Feature Request: Ability to Edit / Customize WooCommerce Cart & Checkout pages. Including creating one click upsells!

### ISSUE THREAD

**Issue by DavidPaul1** [ThemeFuse/Brizy#908]
Important New Feature Request:

Please give us the power to modify not just WooCommerce product pages but the WooCommerce Cart and Checkout page as well!

This is becoming such an important topic and issue, which can add so much value to Brizy if it is incorporated into the builder or as a Pro addon feature.

For example being able to customize the Cart and Checkout pages by adding social proof, testimonials, and reducing or adding form options. As well as being able to design One-Click upsells and custom thank you pages using Brizy, and assigning them as WooCommerce templates.

This is sooooo important to web designers and developers because the regular WooCommerce Cart / Checkout pages/templates are not optimized or easily changed. Please be aware of the value and true power this would bring Brizy.

I welcome others to give their advice, ideas, and input!

For further info please reach out to me,
Thanks,

David Paul

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/2rIH83hY/181-dynamic-content-woocommerce

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
