### ISSUE TITLE
Brizy page is not showing on live

### ISSUE THREAD

**Issue by Giovanni55913** [ThemeFuse/Brizy#909]
Hi, 

So I installed Brizy a couple of months back, but stopped working on my website for a while. After I came back all of my created brizy pages were gone. I tried to re do them, but it will not pop up on live. I checked multiple threads regarding this issue, but found non that were helpfull. Could you help me with this issue, brizy is really handy with building a website. 

I attached two files in this thread. The first one is the one from the editor the second one is the one from the live preview. 
![brizy2](https://user-images.githubusercontent.com/45241399/48860707-f2a26480-edc1-11e8-97cf-0da72188819c.PNG)
![brizy1](https://user-images.githubusercontent.com/45241399/48860709-f2a26480-edc1-11e8-82df-cc587c139282.PNG)

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
