### ISSUE TITLE
When using the Brizy template, the page address of the browser tab is displayed.

### ISSUE THREAD

**Issue by Maxim850** [ThemeFuse/Brizy#91]
When using the Brizy template, the page address of the browser tab is displayed. Instead of the title / title of the page (Home, Porpholil, Contacts), the page addresses are displayed. How to make it so that the browser displays the name of the pages, as it happens with other templates, without using Brizy.
I apologize for my English. Google translates.

**Comment by bagrinsergiu** [comment]
Hi @Maxim850 

Thanks for letting us know, we are looking into it.

Sergiu

**Comment by bagrinsergiu** [comment]
Hi @Maxim850 

In Preview mode Brizy Page Title it is the same as default WP editor Page title.
In Editor mode:
1. Brizy: http://dl3.joxi.net/drive/2018/06/10/0028/0732/1860316/16/d74ec26d41.jpg
2. WP: http://joxi.net/LmG96ZQIeJql4A.jpg

But in both case it is different than ( Home, Porpholil, Contacts ).

Can you give me a page screen/ video with more details?

Thanks for reporting 
Sergiu

**Comment by Maxim850** [comment]
https://youtu.be/v9Cc7L1_A3I 
I hope the video will help. Maybe I'm doing something wrong.

**Comment by bagrinsergiu** [comment]
Thank you for details

**Comment by bagrinsergiu** [comment]
Hi Maxim

In last update 1.0.14 we added a fix for this issue. Can you confirm if it is working with last changes?

Thanks for reporting
Sergiu

**Comment by Maxim850** [comment]
The editor now displays a title. And on the finished page, the site address remains the same, instead of the title.

**Comment by Maxim850** [comment]
1. After the editing is finished and the editor is exited, the title is replaced with text of the form "Brizy # 1891"
2. Instead of the page name (title) (in the browser tab) Brizy # 1891 is displayed.

**Comment by NataliaBB** [comment]
Hi @Maxim850 
Natalia here, Brizy team

Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
