### ISSUE TITLE
Html Export

### ISSUE THREAD

**Issue by trueman61** [ThemeFuse/Brizy#910]
Hi,

**Html export** function in pro version?

**Comment by bagrinsergiu** [comment]
Hi,

We don't plan to add HTML export in Wordpress Plugin. Can yuo give me more details why you need it?

I added this suggestion in our public roadmap: https://trello.com/c/P7fCwP1T/157-save-to-html

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
