### ISSUE TITLE
Feature Request: Assign Global Color to Typography Presets

### ISSUE THREAD

**Issue by bytesource** [ThemeFuse/Brizy#911]
I think it would be great if we could assign a global color to any of the typography presets (h1, h2, h3, subtitle, paragraph, etc.) 

This is what the options menu currently looks like:
![brizy - style options menu](https://user-images.githubusercontent.com/610307/48881074-58d4c900-ee4e-11e8-842f-f99d17f8e09b.png)

I'd like to have the option to choose a global colors as a default here.

Right now when I import a block, different blocks sometimes use different colors for the same typography (e.g. different shades of grey for the same paragraph text). It's time consuming to manually adjust all colors, and if later I decide to change the color of a given typography, I'd have to do the work all over again. 

Therefore, I my opinion, being able to assign a global color to a typography preset could save a lot of time and would result in a more consistent use of colors.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/pqDCZVfZ/187-assign-global-color-to-typography-presets

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
