### ISSUE TITLE
[Feature Request] Accordion Element: Re-Order Items With Drag & Drop

### ISSUE THREAD

**Issue by bytesource** [ThemeFuse/Brizy#912]
I think it would be great if we could re-arrange the order of accordion items via drag & drop. 

Right now I need to know the exact order of all items (e.g. questions and answers of a FAQ section) in advance, or be faced with the boring and time-consuming task of cutting and pasting content later on.

Being able to just drag & drop items would make this workflow much more convenient and enjoyable.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/9HrtnkFu/130-dnd-for-tabs-accordions-form-fileds

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu

**Comment by UniversalDesignz** [comment]
Hi @bagrinsergiu 

1. Can you please add an ability to copy and pate with styling ctrl+v and plain text ctrl+shift+v on as well at the moment it is a mission we have to retype everything in the titles. also please consider something like documentor. 
2. We need all the tabs/bars close on page load.
3. we need to add animated icons on the end of the tabs/bars open and close.
4. different animations and action onhover on click etc.

**Comment by UniversalDesignz** [comment]
@bagrinsergiu 

1. Can you please add an ability to copy and paste with styling and plain text as well; at the moment it's a mission we can't paste on the heading/title.
2. We have to retype everything in the titles. also please consider something like documentor plugin.
3. We need all the tabs/bars close on page load.
4. We need to add animated icons on the end of the tabs/bars open and close.
5. Different animations and action onhover on click etc.
