### ISSUE TITLE
ACF fields not showing up in Brizy editor; existing fields in use are broken on 0.13 update

### ISSUE THREAD

**Issue by jakebarry** [ThemeFuse/Brizy#913]
After updating to 0.13, ACF fields no longer show up in the editor after typing `#` as they did in the previous version:
![brizy-pro-0 0 13 - acf edit](https://user-images.githubusercontent.com/3142587/48959478-a9722200-ef33-11e8-8933-0e31d36cc00b.png)

Additionally, existing ACF fields are rendered with what appear to be Twig shortcodes on the front-end:
![brizy-pro-0 0 13 - acf live](https://user-images.githubusercontent.com/3142587/48959482-abd47c00-ef33-11e8-890a-6edd719b6b69.png)

I am using the most recent version of ACF Pro (5.7.7) and have not updated it between Brizy version changes.

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by bagrinsergiu** [comment]
Hi 

I made a new test free 49 pro 13: https://jmp.sh/wUW478U

Editor Dynamic Content Fields: https://jmp.sh/bjMOyNG  :: https://jmp.sh/Agg9j41 :: https://jmp.sh/qBj3xLJ

Page Preview: https://jmp.sh/5GwKXRR

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
