### ISSUE TITLE
Editing WP pages with Brizy is breaking the site formatting

### ISSUE THREAD

**Issue by anzafrika** [ThemeFuse/Brizy#914]
Using Philanthropy theme, and editing the theme with Brizy:
Whatever editing I do it breaks the formatting of my website

**Comment by anzafrika** [comment]
I am also losing previous edits

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by CGoal12** [comment]
I am in the same boat.  When I go through the messanger on Facebook, I get  directed back to here.
Anyone get a resolution yet ?

**Comment by lolaso81** [comment]
same here. It breaks the design

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
