### ISSUE TITLE
menu diappeared on a page.

### ISSUE THREAD

**Issue by dnvegas** [ThemeFuse/Brizy#915]
http://apt.digidezine.com/apartments/
I downloaded demo data and heve been trying brizy pro out. During edit process on the page link provided the menu and logo area is missing.

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
