### ISSUE TITLE
New post update does not complete - runs circle

### ISSUE THREAD

**Issue by rampisad** [ThemeFuse/Brizy#918]
Cannot update or preview - but the page is there.  I can close and re-open and any changes I made are included. I tried deactivating/activating Brizy, and installed the newest version.

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu
