### ISSUE TITLE
Error multisite wp - images not visible on the editor brizy

### ISSUE THREAD

**Issue by kamyp** [ThemeFuse/Brizy#919]
Hello.

We have install Brizy Free & Pro on multisite Wordpress and we have an error with the images while we're in the editor. We don't have console log error, but the images (when we edit or upload new) is not visible (with http or https...). We see only the result when we save the page and we see the preview. I think it's because it's in a multisite because brizy on local "one site" work.

When we look the "network tool" of the inspector dev, the images are are not response.
`?brizy_media=wp-9602adeab81133e3733494fc557fa733&brizy_crop=iW%3D5000%26iH%3Dany&brizy_post=2
`
`The request has no response data available`
Please we must to see the images in the editor to edit, focus,etc. the images. Help us :)

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by kamyp** [comment]
"Hi,
Please send me a message via our Facebook chat and mention this issue inside. »

I don’t find your « WP Crendentials » button and I don’t want use Facebook chat sorry But I can give u the order payment of Brizy Pro and licence.

We need help to fix this bug. Thx.
Meilleures Salutations - Kind Regards - Mit freundlichen Grüssen - Atento Saludo

CAMILLE-F. 
PASCHE 
Project Manager



Route d'Yverdon 15, 1040 Echallens, Suisse
021 881 22 28 | 078 344 62 62
www.bvisible.ch <https://www.bvisible.ch/> | camille@bvisible.ch <mailto:camille@bvisible.ch> | info@bvisible.ch <mailto:info@bvisible.ch>
Confidentiality Note: This message and any attachments are confidential and intended for the named addressee(s) only. If you have received this message in error, please notify immediately the sender, then delete the message. Any unauthorized modification, edition, use or dissemination is prohibited. The sender shall not be liable for this message if it has been modified, altered, falsified, infected by a virus or even edited or disseminated without authorization.

**Comment by NataliaBB** [comment]
Hi!
Natalia here!
Checked pages and no errors were found on the main page or on new created one. 
please check your server configurations. If the issue will appear again, please send us a message via our facebook chat or on natalia@brizy.io

Thank you!
