### ISSUE TITLE
Reorder Tabs

### ISSUE THREAD

**Issue by gitcent** [ThemeFuse/Brizy#92]
Enhancement request to be able to reorder tabs in accordion.

**Comment by bagrinsergiu** [comment]
@gitcent 

Hi Nick,

Thank you for suggestion. We have this feature in our to do list for form fields, buttons, icons, tabs, accordions, ...

Sergiu

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/9HrtnkFu/130-dnd-for-tabs-accordions

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
