### ISSUE TITLE
Animations not working on update to 1.0.47 - issue still with 1.0.48

### ISSUE THREAD

**Issue by epubpress** [ThemeFuse/Brizy#920]
Animations no longer working.

**Comment by GodlessGlen** [comment]
This is very annoying that they are breaking things completely that were working, while supposedly fixing an existing issue. I am tempted to request a refund a move along.

**Comment by bagrinsergiu** [comment]
Hi @epubpress, @GodlessGlen 

Sorry for the inconvenience. This issue  will be fixed in the next version.

Sergiu

**Comment by bagrinsergiu** [comment]
1.0.49 is planned in maxim 3 hours. Sorry for the inconvenience.

**Comment by Ravisi** [comment]
I have the same problem, and also my Slider is not working, the Slider arrows disapeared, and i have now a white border (like 5px) under it!!

**Comment by bagrinsergiu** [comment]
1. Animation fix was released in 1.0.49 8 min ego: https://jmp.sh/OeRCqk2

Regarding slider issue: 
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by epubpress** [comment]
thanks guys

**Comment by Ravisi** [comment]
Animations working again! Thanks! I build again my Slider and now is working, now i get 2 white lines (1 or 2 px) over and under, but i will let it like so.

**Comment by GodlessGlen** [comment]
Animations are working but not correctly. Images are displayed in ending position before animation starts. Then it disappears and the animation goes through its process. Can you guys please fix.

**Comment by kdub718** [comment]
Also is it possible to change the animations to not be in the row and controlled by each element?

For example if I have multiple icon elements in a row (ie social icons) they all have to use the same animation.  Can we have those animations for each individual icon?

**Comment by maxval94** [comment]
Hi, @GodlessGlen 
I have tested the animations with delay and it seems to work fine, can you please make a little screencast so I can reproduce the exact steps ?

**Comment by bagrinsergiu** [comment]
Hi!

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Sergiu
