### ISSUE TITLE
Contact form Only works in desktop - not in mobile or table

### ISSUE THREAD

**Issue by surquillo** [ThemeFuse/Brizy#921]
Im using the pro
Contact form in table and mobile they don't work.  Not even an error message.
it shows a red border on the number input and email inputs. 
it does work fine in desktop. it sends the email  fine.

I'm using Flatsome theme

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by surquillo** [comment]
i did send a message but no answer yet
