### ISSUE TITLE
my home page is blank 

### ISSUE THREAD

**Issue by suleimaan** [ThemeFuse/Brizy#929]
the home page of this website bitly:45edasw created with brizy is blank on preview and live mode. 
Resolved after manually updating the page. the other pending issue about the site is that, the nav bar is not collapsing on mobile preview. how would someone resolve this?

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
