### ISSUE TITLE
Tablets and Phablets Viewport editing

### ISSUE THREAD

**Issue by gitcent** [ThemeFuse/Brizy#93]
Enhancement request to provide responsive editing capabilities for medium class viewport sizes @768 and landscape viewing on mobile.

**Comment by bagrinsergiu** [comment]
@gitcent 

Hi Nick,

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by bagrinsergiu** [comment]
Added to our roadmap: https://trello.com/c/jluZ6ps3/29-responsive-tablet

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
