### ISSUE TITLE
Brizy will not update pages that have already been saved.

### ISSUE THREAD

**Issue by brandonssmith** [ThemeFuse/Brizy#931]
I have been working on a page that I needed to update but when I went back into the apge to make more changes it is not giving me the option to update.  Clicking on the UPDATE button does nothing and I have verified that by checking the page in another browser.

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by lbiru** [comment]
I also have the same experience. 
In my case I have to return to wordpress editor and back again to Brizy to get the expected result.

**Comment by brandonssmith** [comment]
I tried to reproduce this and eventually found that if more than one user was logged into the site it would not allow me to update the page.  In my case this is not a game stopper as very few people have access. I'll close this as I found a solution and workaround.
