### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by faitdumal** [ThemeFuse/Brizy#932]
Hi, I am trying to clone an existing installation (WP) to a new domain and am receiving the following error: 

**Fatal error: Call to a member function getVersion() on array in /home/---/public_html/[my domain].com/wp-content/plugins/brizy/admin/migrations.php on line 39**

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by faitdumal** [comment]
I don’t know how to do that. Your messenger chat uses predefined buckets and when I click on bug reporting it pulls up the github site where I already posted. Posting the issue into the chat does nothing - I’m just being prompted again to go through the robo-buckets, which leads me back to github. Please advise as to where exactly you want me to post this. I’m not a pro customer, so I cannot post to that bucket.

**Comment by NataliaBB** [comment]
Hi Patrick!
Natalia here!

Yes, we use some bot messages in order to help us with questions which we receive during a day. That's why, we ask you to send a message and mention this issue (the problem) inside. 
I've received your notification, let's continue on the chat.

Regards, Natalia

**Comment by ViorelEremia** [comment]
How did you move the installation to a new domain? 
With a wp plugin or manually?
What plugin did you use?
Where is this error?

**Comment by ViorelEremia** [comment]
Closed due to inactivity.
