### ISSUE TITLE
Anchor Links 

### ISSUE THREAD

**Issue by purewaterman** [ThemeFuse/Brizy#94]
Hello, 
how can I anchor link Wordpress menu items to sections of the page. One page navigation. 
I saw that I can anchor link elements within the page.

**Comment by cdm-mobo** [comment]
Hi sorry if this has been covered. I'm wondering how to do the above. I have a page with About, classes etc. on one page. Want to add these as sub menus to top nav. thanks

**Comment by Aydarams** [comment]
This is how i achieved mine. I created a button , then link it up to the section of the page. When i clicked on the button it worked, linking to the section of the page. so i copied the URL (eg. www.example.com/about/#Ub2h364).  I then paste it in URL portion of the menu i wish to link up with the page section. It worked for me.

**Comment by cdm-mobo** [comment]
Thanks yes I've done this before, but previously I could name the sections - can't see where to do this now! Sorry probably missing something obvious...

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: doing list https://trello.com/c/oXf1o2Jg/168-anchor-link

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu

**Comment by MaxZiebell** [comment]
**Please allow us to name the anchors on the sections so we can create human readable links from on page to another** referencing an anchor OR some visual way to choose anchors from another page. 

_Also fix choosing pages that exist as currently I need to know the page name and don't get suggestion (and ideally internally a reference by ID so I can update the name later)._
