### ISSUE TITLE
the website is not strechable

### ISSUE THREAD

**Issue by manutech339** [ThemeFuse/Brizy#940]

**Comment by bagrinsergiu** [comment]
Hi

Can you give me more details? 

Thanks for reporting
Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.
Also, you can submit a ticket here: https://support.brizy.io/hc/en-us

Regards. Natalia
