### ISSUE TITLE
Updated Brizy to latest version just to find out it  was stuck on loading screen

### ISSUE THREAD

**Issue by mumualpaka** [ThemeFuse/Brizy#941]
Greetings,

Is there any temporary solution or quick fix for this issue? 

![brizy_issue](https://user-images.githubusercontent.com/36689272/49429164-d56a8e80-f7e2-11e8-96a2-8227cb5cb9c7.png)

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by mumualpaka** [comment]
This issue is resolved by Brizy staff, many thanks!
