### ISSUE TITLE
[Feature Request] Dynamic Content in CSS Classes

### ISSUE THREAD

**Issue by KyleAtDND** [ThemeFuse/Brizy#945]
So currently Brizy let's me use things like custom fields in URLs, featured images, etc. I was wondering if it would be possible so that if I'm in a section that allows dynamic content, I could insert dynamic content as a CSS class.

This would drastically impact the ability to customize things. For instance, I could write different custom CSS for various classes, and make a custom field that is a SELECT list of those classes. Then have a container call that custom field as part of the Advanced Settings Class configuration. Does that make sense? The main thing I'm asking for is that if I click a container -> click the gear for settings -> select advanced -> and now that I’m at the field to add a class(es), I am able to do dynamic content such as an ACF field "#My ACF Field That Is Also A Class Name"

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/xUknfhZj/194-dynamic-content-in-css-classes

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
