### ISSUE TITLE
An error occurred while updating Brizy Pro: Empty License Key Submitted

### ISSUE THREAD

**Issue by colla9e** [ThemeFuse/Brizy#947]
While upgrading from 0.0.13 -> An error occurred while updating Brizy Pro: Empty License Key Submitted

**Comment by Coderewe** [comment]
I also have an issue with the Brizy > Licence page not found. 

@colla9e  You should be able to manually install the zip that you download from your Brizy account (just in case you haven't got around the update issue).

**Comment by colla9e** [comment]
That's exactly what I did (deactivate/uninstall/install/activate) works fine

**Comment by MaxZiebell** [comment]
Wasn't the whole point that we can update. BTW the "Empty License Key Submitted" still appears when trying to deactivate a license.

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
