### ISSUE TITLE
[Feature Request] Switch between other pages while in brizy

### ISSUE THREAD

**Issue by kdub718** [ThemeFuse/Brizy#949]
With all this hoopla about 5.0 taking away the brizy button and users not installing the classic editor to find it.  Got me thinking.  Since the future of wordpress is a visual builder.  What if we didn't have to access brizy through wp pages.  What if we could launch brizy builder through the brizy menu (templates, role manager, license) and than launch it from there.  (eventually I vision some sort of brizy dashboard that would be cool).  Anyway...

Then while we are in the brizy builder we can switch between pages.  (screenshot attached).
![brizy-pages-idea](https://user-images.githubusercontent.com/19559355/49625972-8fe9c500-f98c-11e8-9d17-8542abb1a931.jpg)

Maybe down the road even a create new page or clone/duplicate would be nice also.

**Comment by Ravisi** [comment]
It would be a good feature! I use to preview the page i'm editing in Brizy, then i go to the page i want to edit and then i clck on "edit page with Brizy" for me is the fastest way to do it right now.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/tIHXlph1/196-switch-between-other-pages-while-in-brizy

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
