### ISSUE TITLE
Mobile view isnt working for me

### ISSUE THREAD

**Issue by kilimats** [ThemeFuse/Brizy#95]
Not sure if i missed a setting somewhere but the page i built with your templates arent being responsive in mobile view, take a look https://www.1stsupport.com/test/

**Comment by bagrinsergiu** [comment]
Hi @kilimats 

Theme iincluded an external CSS File where html tag is min-width: 910px: https://prnt.sc/jrkyom

It is possible to change theme with The Core by ThemeFuse, OceanWP, Astra WP or check and disable CSS file with mobile view port 910 px

I'm closing this issue to keep the issue database slim. Feel free to re-open if I've misunderstood you.

Thanks for reporting
Sergiu
