### ISSUE TITLE
Cannot Reorder Block, It Always Jumps Back

### ISSUE THREAD

**Issue by bytesource** [ThemeFuse/Brizy#952]
After adding one of the header blocks right below the first block and moving it up to the top, I realized that the former top block (the hero section) had been moved far down the page. 

It has been impossible to move (reorder) the hero section back up again because it always gets pushed back again. It's really frustrating. 

Any ideas what might cause this issue? I purged the cache, but to no avail.

Brizy Version 1.0.52
Brizy Pro Version 0.0.14
Wordpress 5

**Comment by maxval94** [comment]
Hi, @bytesource
Can you please make a little screencast so I can reproduce the exact steps ?

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
