### ISSUE TITLE
[Feature Request] : ability to save custom blocks

### ISSUE THREAD

**Issue by nicodweb** [ThemeFuse/Brizy#953]
I'm not sure it's possible or not yet: but if we have the ability to save custom blocs or templates in order to have them in the "blocs" library (like premade-blocks), it must be very powerful !
Replace defaults block by custom blocks must be usefull too
What do you think?

**Comment by Coderewe** [comment]
If you modify an existing block and then hit the heart option in the block settings menu bar, that saves it in the block selecter for reuse. Is that the kind of custom block you are thinking of?

The only problem I can see with the existing feature is that you don't get a preview thumbnail for that saved block. So it's not easy to know what you saved.

**Comment by nicodweb** [comment]
Hey Coderewe. 

> If you modify an existing block and then hit the heart option in the block settings menu bar, that saves it in the block selecter for reuse. Is that the kind of custom block you are thinking of?
That's it ! 
But yes I need to attach image with it (or an automatic thumb generation)  !

**Comment by bagrinsergiu** [comment]
Hi,

Thumb auto generator feature is planned in ~ 10 days. 

Sorry for the delay. 


I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu

**Comment by nicodweb** [comment]
Sergiu, do you know if a fonction to replace the default library (blocks and pages) is planned too?(perhaps it's possible yet?)

**Comment by bagrinsergiu** [comment]
Hi @nicodweb 

I added a new feature request on our Trello to do list: https://trello.com/c/uycB85MH/200-replace-the-default-library-blocks-and-pages

Can you give me more details why you need a block library and pages replacer?

Thanks
Sergiu

**Comment by nicodweb** [comment]
> Can you give me more details why you need a block library and pages replacer?
Yes: actually when I design websites for customers, I use beaver builder Agency version. 
With this plugin I can save each page and each row that I have designed (I can save theme to a library  and assign them  a thumb) .Then when the site owner edit is website he can drag and drop each element that I have saved (beaver builder have default templates ans rows but we can disable them-"it's a more white label solution" ) to compose his page.
Do you understand?

https://kb.wpbeaverbuilder.com/article/100-categorize-and-add-thumbnails-to-saved-templates-list

**Comment by bagrinsergiu** [comment]
1. Save your custom blocks option is available from the beginning: https://jmp.sh/S9hqdUg
2. Block thumbnail - we plan to add feature in 1-2 weeks maxim 

--- 

Save your page and Page thumbnail also will be available soon.

Thansk for details
Sergiu
