### ISSUE TITLE
[Feature Request] Sass licence 

### ISSUE THREAD

**Issue by nicodweb** [ThemeFuse/Brizy#954]
A licence for a Saas multiste service must be cool ! (perhaps an annual payment like beaver builder agency?).
I have a wordpress multiste install.My clients can pay with stripe and it will duplicate a website on the network. Then they edit the website alone or with a support. For now my solution is based on beaver builder but i'm interested to switch to Brizy..
So it's not possible if I understand your licence?

**Comment by DimiBaitanciuc** [comment]
Hi, right now it is not possible with Brizy but we are thinking and discussing the possibility to have that option.

Not sure you are familiar with our Theme Author Program: we want to let theme authors bundle Brizy PRO with the commercial themes they sell on Envato: https://brizy.io/theme-author-program/ 

A Brizy PRO SaaS Program most likely will be based on, and work similar to the theme author program, where a few will be paid for every license used. 

We are still discussing it and want to launch the Theme Author Program first and then most likely extended for SaaS. 

Hope this makes sense. 

If you are a member of our Facebook community you'll be up to date on when and if will make the announcement. Cheers.

**Comment by nicodweb** [comment]
> A Brizy PRO SaaS Program most likely will be based on, and work similar to the theme author program, where a few will be paid for every license used.

Why not it's a good idea ! 
Thanks for the answer and I hope you will do something for users who's need a Sass licence for small businesses !
Cheers (and impressive work with brizy !!)

**Comment by DimiBaitanciuc** [comment]
We had a lot of requests for a Saas Brizy license and we take them very seriously.
Will take it one at a time, authors first, Saas next.

I'll close this issue, for now, to keep the issue list as slim as possible. Feel free to just reopen it if you need to add anything else.
