### ISSUE TITLE
Swap slides feature

### ISSUE THREAD

**Issue by krol1k** [ThemeFuse/Brizy#955]
Please add the possibility to change order of slides in slider.

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/QMIrNXm9/195-slider-order-of-slides-in-slider

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
