### ISSUE TITLE
Unable to set custom negative margins

### ISSUE THREAD

**Issue by sunnyt7** [ThemeFuse/Brizy#956]
It looks like we can't have a negative margin of more than -100px, even if you type -200px in manually. It just jumps back to -100px. Being able to set a custom value would be essential for full design control, of course.

![image](https://user-images.githubusercontent.com/5510344/49668659-d42ca200-fa2c-11e8-9ba5-de4d56839e2d.png)

**Comment by bagrinsergiu** [comment]
Hi,

Right now it is working. Thanks for reporting: https://jmp.sh/kGFabdd
 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
