### ISSUE TITLE
[BUG]  Some Gyphs not working

### ISSUE THREAD

**Issue by kdub718** [ThemeFuse/Brizy#957]
I haven't tried them all but I'm working on a little sample project and just discovered these arn't working as glyphs...  they do work as outline...  I assume there could be others

![brizy-glyphs](https://user-images.githubusercontent.com/19559355/49671789-d89d8e80-fa1d-11e8-9557-07b08971fd82.jpg)

**Comment by Coderewe** [comment]
I've had the same issue. It seems that when you choose a Glyph, the Outline version of that icon doesn't work after it. If you first choose the Outline version, then the Glyph version doesn't work.

**Comment by bagrinsergiu** [comment]
Thanks for reporting.

**Comment by NataliaBB** [comment]
Hi! 
Issue fixed.
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
