### ISSUE TITLE
[Feature Request] Icon Request Thread

### ISSUE THREAD

**Issue by kdub718** [ThemeFuse/Brizy#958]
Wondering if we can start a thread on Trello or even here where users can request new icons?  I love how there are so many icons but there are a ton of popular ones that can still be added.  And maybe they can be added periodically with updates.

There are a few I'm looking for and would love to use without making my own images (its just not as nice and clean).

https://anchor.fm
https://play.google.com/store/apps/details?id=com.google.android.apps.podcasts
https://castbox.fm
https://www.stitcher.com

ps. can you tell I'm working on a podcast site lol

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/cMAJp1rZ/193-icon-request-thread

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
