### ISSUE TITLE
Dynamic Posts (Post Content Color not changing)

### ISSUE THREAD

**Issue by peleroberts** [ThemeFuse/Brizy#960]
I created a video to show this highlighted issue.  

When creating a template and using #post_content I am unable to change the color, or should i say the color option is not working.  See video below : 

https://www.useloom.com/share/27323c12d246451d9690e039ebb402ce

Thanks, let me know if you need any more details.

**Comment by peleroberts** [comment]
Video provided 👍

*Font Colour

**Comment by bagrinsergiu** [comment]
Hi Pele, 

Sorry for the delay. I made a test on my local instance: https://jmp.sh/zwjizTZ  

We made some changes in Richtext in order to improve Dynamic content feature (The Content). 

Can you confirm if it is working for you?

Thanks for reporting
Sergiu

**Comment by peleroberts** [comment]
Hi Sergiu, np and thanks for getting back to me.

I just watched your video and double checked and followed for you did, and no its still not working, my font remains #000 no matter what color i choose for #Post_Content

Thanks
