### ISSUE TITLE
Unable to edit pages made with Brizy anymore

### ISSUE THREAD

**Issue by rahulkmx** [ThemeFuse/Brizy#962]
Hi, I have created a page way back before Gutenberg exsist. On november I tried changing a bit of blocks using brizy editor, that works.
After that, I have to remove a block made with brizy but I accidently clicked on classic editor and every single brizy blocks convert into text. Now, the blocks are not showing when I click "edit with brizy" and showing default page instead./
please check the link, 
Link : [link](http://envytechblog.com/google-play-developer-registration-india)

I have to remove that Diwali offer section, and have to edit the price, if possible via classic editor.'

One more issue, 
When I tried to create a new page using brizy editor, it does not load any of the block made by brizy editor, 
I am using Justwrite theme, previously and still too. 

Please try to resolve this issue.
I have read few other issues here on github but that does not match my query.

Thanks & Regards.

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
