### ISSUE TITLE
Sticky Header/Menu: Initial page load displays all submenu items

### ISSUE THREAD

**Issue by jlydia** [ThemeFuse/Brizy#963]
Absolutely love the long-awaited new menu options! Great job guys!
However, after adding a sticky header to page the initial load of the page does a quick display of all submenu items. Tried this in multiple browsers which produced the same outcome.

![menu-flash](https://user-images.githubusercontent.com/43318108/49710427-4953cf00-fc07-11e8-9375-5edfa2f312c1.png)

-JL

**Comment by wtassis** [comment]
I have the same problem

**Comment by maxval94** [comment]
Hi!
This has been fixed and will be included in the next update. I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Maxim
