### ISSUE TITLE
Problems showing sub menu items from Astra theme (Pro) in Mobile

### ISSUE THREAD

**Issue by Ravisi** [ThemeFuse/Brizy#964]
I´m having a problem with the sub menu items in Mobile version. I use the page template, build with Astra Pro. The Menu items are looking good, but the sub menu items appear above the Menu Items
![menu brizy](https://user-images.githubusercontent.com/41541108/49735322-3d0f5680-fc87-11e8-90a8-96dfe1f736df.jpg)
![sub menu problem](https://user-images.githubusercontent.com/41541108/49735325-3f71b080-fc87-11e8-9e34-4e848bbdf8dd.jpg)

**Comment by Ravisi** [comment]
If i deactivate Brizy & Brizy Pro Plugins is looking good

**Comment by Ravisi** [comment]
You can check it here: http://tecneoservices.com

**Comment by maxval94** [comment]
Hi @Ravisi
This has been fixed and will be included in the next update. I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Maxim
