### ISSUE TITLE
How to add text, buttons and logo images on a background image?

### ISSUE THREAD

**Issue by mxpweb** [ThemeFuse/Brizy#965]
Hi,
I was trying to create a landing page from scratch, 
the background will be an image (my image) then need to add some text on it, and a button CTA,
I tried to drag and drop, but always slides to above or under, never fixed on the image space where I need to put the new content,
how to fix this issue?
please help, thanks

**Comment by jlydia** [comment]
Sounds as if you may have dragged an image onto the block as opposed to the background of the block.
You should first click the "up-arrow" at the top left or right corner of the empty block, then select the background icon to add an image. Drag a couple of spacers onto the block, the drag a text and button in the middle of the spacers.
![background-image](https://user-images.githubusercontent.com/43318108/49744823-a97c5c80-fc6b-11e8-9c08-e865d880d15c.png)
![background-image-2](https://user-images.githubusercontent.com/43318108/49744825-a97c5c80-fc6b-11e8-8ee5-eeaf215f3207.png)

**Comment by bagrinsergiu** [comment]
Hi jlydia,

Thanks for your help. 

Video demo link: https://jmp.sh/MNUjgqg


I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
