### ISSUE TITLE
[Feature Request] BrizyBoard - Cross-Managing Brizy pages

### ISSUE THREAD

**Issue by rorar** [ThemeFuse/Brizy#967]
As discussed here on the [FB Communty](https://www.facebook.com/groups/brizy/permalink/349096705854208/) Brizy with an Dashboard for several Brizy build pages would be nice. 👍 
As not seeing it on your Trello Board, I'll resuggest you this feature
--------

Hi Brizy Community and Developers,
Managing sites getting harder with a growing number of sites.
That's why we need a Brizy Dashboard [BrizyBoard]:
- For own projects you need to put in an imprint/privacy statement. If needed you have to update it on every website.
>Why not managing from one Dashboard and sync it?<
- Is every website up2date (plugins, themes, WP)? Is the page running (health check)?
>Check it from a Dashboard (from your agency site)<
What else can we do?:
- See visitor counter (monthly, weekly, daily)
- Sync typography to every project
- Sync your Stock Photos
- Sync your favorite Menu order and site links
- Automaticaly push files and get acces from your agency site / ftp
- automaticaly install your favorite plugin with one click on a new project
- See / write ToDo's on Dashboard for a project
- automaticaly add pro feautures for Brizy Lifetime Deal OR One Click buy Pro for a website

![brizyboard](https://user-images.githubusercontent.com/44790144/49748663-a2bf0b00-fca6-11e8-993a-48cbb6082772.jpg)

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/8vsGepoe/192-brizyboard

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
