### ISSUE TITLE
Important BUG on Mobile Device/s

### ISSUE THREAD

**Issue by mikes1991** [ThemeFuse/Brizy#968]
Hi guys, I have very strange problem with Brizy websites on my iPhone X (it happens on two different domains). Scrolling on page occasionally breaks pictures. **There are various defects and a mixture of broken images.** It happens only occasionally, and the defects are random. See exaples on pictrures. Please pay attention to this problem. Thank you!

**Non-customization of the web for rounded displays is another topic.**

![bug-1](https://user-images.githubusercontent.com/41758560/49753498-e9ffc880-fcb3-11e8-9063-c474a20c7912.jpg)
![bug-2](https://user-images.githubusercontent.com/41758560/49753499-e9ffc880-fcb3-11e8-919c-627530273cca.jpg)
![bug-4](https://user-images.githubusercontent.com/41758560/49753916-0bad7f80-fcb5-11e8-947a-6df696d4112d.jpg)

**Comment by mikes1991** [comment]
And here from tablet... It looks very bad.

![bug-5](https://user-images.githubusercontent.com/41758560/49757548-f3416300-fcbc-11e8-8fc1-77c322d81844.jpg)

**Comment by maxval94** [comment]
Hi @mikes1991!
Can you give me link to the project?

Thank you!
Maxim

**Comment by bagrinsergiu** [comment]
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
