### ISSUE TITLE
Woocommerce - Sorry, Brizy could not load

### ISSUE THREAD

**Issue by robsonet** [ThemeFuse/Brizy#969]
On a brand new WorPress install using OceanWP - When I try to edit the woo shop page with Brizy I get this message:
Sorry, Brizy could not load - Your theme must use the the_content filter in order for Brizy to work.

**Comment by iangdesign** [comment]
I am running into this same issue. Has there been any efforts to fix it?

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
