### ISSUE TITLE
content source

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#97]
It might be better to keep simpler html in wp_posts table.
Beaver Builder and Elementor doesn't keep most structural tags(like div) in wp_posts table.
That may be more SEO plugin friendly and  safer when deactivate Brizy.

**Comment by bagrinsergiu** [comment]
Hi @ash-f,

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by bagrinsergiu** [comment]
Added to Brizy Roadmap: https://trello.com/c/08P0mGyu/99-doesnt-keep-most-structural-tagslike-div-in-wpposts-table

Thanks for suggestion.

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
