### ISSUE TITLE
Feature request: Auto-responder for Brizy Contact Form

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#973]
Hi there,

I would like to make a feature request for Brizy's contact form:

When a user submit's a contactform I would like to setup a auto-responder that sends an e-mail notifying that their e-mail is sent succesfully.

For this functionality I am now using Caldera Forms, however it would be great if Brizy has this too.
This way I can skip Caldera Forms completely for a lot of websites. Plus in my opinion this is a must-have for every contact form. I know you guys are already working hard but if this could be added to the Trello for the future that would be really nice.

Best regards,

Christiaan

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/RHhdPInk/198-form-auto-responder

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
