### ISSUE TITLE
Bug - Can't reorder icons and buttons

### ISSUE THREAD

**Issue by Infusednl** [ThemeFuse/Brizy#974]
Hi there,

I have problem regarding Brizy's Icon and Button modules.

When I have two or more icons or buttons sitting next to eachother I can't change their order.
When I click and drag a button or icon I can only place them above or below the others.

This means if my clients wants the order different I have to delete my icons or buttons and create them again in the new order. Here is a screenshot of what my icons. Let's say I want to move the Google+ icon at the end to the beginning:

![schermafbeelding 2018-12-11 om 17 26 02](https://user-images.githubusercontent.com/6600256/49814611-4a514180-fd6a-11e8-9de0-e719049f8f86.png)

If I drag the Google+ icon I can only place it above or below the other icons. The same applies also to buttons that are grouped and is very frustrating.

![schermafbeelding 2018-12-11 om 17 26 26](https://user-images.githubusercontent.com/6600256/49814655-6228c580-fd6a-11e8-9e1e-1f6804ddbb34.png)

I really hope this is easily fixable as it often drives me nuts. 

Best regards,

Christiaan

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/9HrtnkFu/130-dnd-for-tabs-accordions-form-fileds

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
