### ISSUE TITLE
Menu Error: Could not find the menu. It was probably deleted.

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#975]
Hello, 

I was testing 0.0.14 and am getting this bug on headers 

https://screen.maxziebell.de/20181211-f6vqa.png

The menu also cannot be edited.

**Comment by bagrinsergiu** [comment]
Hi @MaxZiebell 

Can you choose a different menu?  : https://jmp.sh/JQhK7ok

Is a known issue. We plan to fix it in next update.

Thanks for reporting
Sergiu

**Comment by MaxZiebell** [comment]
Oh I didn't find the menu, Thanx

**Comment by maxval94** [comment]
Hi @MaxZiebell

This has been fixed and will be included in the next update.

Thank you!
Maxim
