### ISSUE TITLE
[Feature Request] Templates and/or global blocks by site languages

### ISSUE THREAD

**Issue by PriitGit** [ThemeFuse/Brizy#976]
Ability to display global blocks and templates according to the languages of the website in multilingual site.
Have not seen that feature any other page builders.. Be first Brizy team :)
All Best!

**Comment by bagrinsergiu** [comment]
I added this suggestion in our public roadmap: https://trello.com/c/aFs6my4B/199-templates-and-or-global-blocks-by-site-languages

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Best Regards, Sergiu
