### ISSUE TITLE
colorpicker broken for HREF

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#979]
I can't seam to set a global color for links and when choosing them manually I can't choose global colors. Setting them manually works but is very buggy (copy&paste etc.).

https://screen.maxziebell.de/20181213-6vztz.jpg

**Comment by maxval94** [comment]
Hi @MaxZiebell !

This has been fixed and will be included in the next update. I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thank you!
Maxim
