### ISSUE TITLE
lazy load(it's rather load on click) for videos

### ISSUE THREAD

**Issue by ash-f** [ThemeFuse/Brizy#98]
Please add load on click function to video element.
Means video source won't be loaded(including js/css) until it's clicked and show preview picture instead.
Because embedded video has huge impact on page loading speed.
Load on click improve this very well.

**Comment by mjunaidit** [comment]
+1

Have you found any workarounds for it meanwhile? I currently use Elementor with Astra and THIS EXACT thing has been bugging me SO MUCH!

**Comment by ash-f** [comment]
Easy way is to use dedicated plugin for it I think.
https://wordpress.org/plugins/lazy-load-for-videos/

But built-in would be nice.

**Comment by bagrinsergiu** [comment]
Hi @ash-f, @mjunaidit, 

Thanks for letting us know, we are looking into it.
Sergiu

**Comment by bagrinsergiu** [comment]
Added in 1.0.20
I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Thanks for suggestion
Sergiu
