### ISSUE TITLE
Whitespaces around links

### ISSUE THREAD

**Issue by MaxZiebell** [ThemeFuse/Brizy#980]
Adding links sometimes produces weird whitespaces around links

https://screen.maxziebell.de/20181213-x3dv9.png

the code Brizy produces contain additional `&nbsp;` at the end of span and also at the beginning or extra spans with a `&nbsp;` and a color. In that case I must admit that I change the color of the link, though.

**Comment by NataliaBB** [comment]
Hey @MaxZiebell
Natalia here!

I've created an issue for the team with this bug already. 


My Best Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
