### ISSUE TITLE
[Bug] One of the Pricing Table Elements Works Inconsistently

### ISSUE THREAD

**Issue by KyleAtDND** [ThemeFuse/Brizy#981]
You should be able to see here: http://cloud.designanddevelop.io/2e1360a3cd94

In this video, when I created the Pricing block with a bare-bones OceanWP template, it started off with some of the rows misaligned.

But the bigger problem is that if I copy all the elements in a row (as the video shows), the new row isn't lined up correctly. It is usually off by 1-2px at some point everytime I try to copy a row.

**Comment by NataliaBB** [comment]
Hi Kyle @KyleAtDND!

Natalia here,
I can not see the video, I see only a png image. 
Could you please give me more details on our Facebook chat, via www.brizy.io?

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
