### ISSUE TITLE
[BUG] Carousel didn't display in front-end (Brizy Pro 0.0.14)

### ISSUE THREAD

**Issue by cuongtalentccc** [ThemeFuse/Brizy#983]
The Carousel didn't display again with the latest update (Brizy Pro 0.0.14). The back-end work normally.

I am in Wordpress 5.0.1 Gutenberg.

Please help me check!

**Comment by bagrinsergiu** [comment]
Hi,
Please send me a message via our Facebook chat and mention this issue inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Sergiu

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
