### ISSUE TITLE
Error: Your theme must use the the_content filter in order for Brizy to work

### ISSUE THREAD

**Issue by Daohannce** [ThemeFuse/Brizy#984]
Excuse me. After I update in DEC 7th , I find that any new page I create can't edit by Brizy, because there is no item to choose, Besides, when I edit the page I created by Brizy, it redirect to an error page like

> Your theme must use the the_content filter in order for Brizy to work

But when I edit some special page I edited by Brizy, all things is well. Can you tell me how I fix the "Your theme must use the the_content filter in order for Brizy to work" error please?

**Comment by Daohannce** [comment]
Yes, I think I found the problem.After I add the plugin *Classic Editor*
,it gets well. I think maybe  Brizy is not compatiable with *Gutenberg
Editor *in Wordpress 5.0 .I dont kown that my site auto update to wordpress
5.0, I think I shoud turn off the auto update.
Thank you!

**Comment by stellarmadison** [comment]
I'm having the same problem, but I've had Classic Editor installed for awhile. All my pages are set up the same way with the "Brizy Template" but only some pages are giving me the "the_content" error when I try to edit the page. I've tried everything to fix the problem with no results. I'd appreciate some help!
