### ISSUE TITLE
two edit bars appear

### ISSUE THREAD

**Issue by robsonet** [ThemeFuse/Brizy#988]
When I edit a page with Brizy, then click to go to a new page, and then decide to edit it again with Brizy, two edit bars appear on the left side, instead of one (the first one is inactive). I can actually get even more of them if I keep going to different pages and editing them. Fresh install WP 4.9.9 - Astra Site.

**Comment by NataliaBB** [comment]
Hi @robsonet 
Natalia here!
Can you give me some screenshots of those edit bars? What Brizy versions do you have installed?
Please, send me more details on our facebook chat: 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Please, mention this issue inside your message - #988 

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
