### ISSUE TITLE
edit page doesn't load

### ISSUE THREAD

**Issue by Funnyboy363** [ThemeFuse/Brizy#989]
I click on Edit with brizy on page I want to edit. The only thing it does at that point is continuously do the loading circles. Nothing after that. I have updated brizy and uploaded the php for the wordpress as well.

**Comment by NataliaBB** [comment]
Hi @Funnyboy363 
Natalia here, Brizy team
Please, send us your wp credentials via our facebook chat, and mention this issue inside #989. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
