### ISSUE TITLE
tablet mode

### ISSUE THREAD

**Issue by Aulez** [ThemeFuse/Brizy#99]
hi,
any tablet mode in brizy free version?
tablet mode is it integrate into Pro pay version?
Benny

**Comment by bagrinsergiu** [comment]
Hi Benny,

Tablet mode is a Free feature. It is in work right now. We don't have an eta but we plan to add it soon 

Thank you for suggestion 
Sergiu

**Comment by bagrinsergiu** [comment]
Added to our roadmap: https://trello.com/c/jluZ6ps3/29-responsive-tablet

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Sergiu
