### ISSUE TITLE
Image and image directory not wokring 

### ISSUE THREAD

**Issue by udaysarkarud** [ThemeFuse/Brizy#990]
well i'm using two different  WordPress site, i installed brizy on both , but the problem is that there is one site it's working perfectly and another on is not. i'm talking about image and embed options. then i start tracking the image link and i got the image directory not working after publish , when i design the page i can see all images but after publish images are not in there . 

can you guys help me please , thanks

**Comment by NataliaBB** [comment]
Hi @udaysarkarud 
Natalia here, Brizy team!

Please send me a message via our Facebook chat and mention this issue #990 inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
