### ISSUE TITLE
Global block link not saving

### ISSUE THREAD

**Issue by jonbonnar** [ThemeFuse/Brizy#995]
I have designed a footer and made it a global block. When I deploy it onto a new page, the links I have saved on the original global block for mailto: and tel: do not copy

Also the formatting of these items is not consistent

**Comment by NataliaBB** [comment]
Hello Jon! @jonbonnar 
Natalia here, Brizy team!

Please send me a message via our Facebook chat and mention this issue number - #995 inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
