### ISSUE TITLE
Mobile Image Size in Astra Templates are different in Brizy Screen and real navigator

### ISSUE THREAD

**Issue by falecomcarlito** [ThemeFuse/Brizy#996]
When I set an image in a mobile simulator in Brizy (using Astra template) it shows an image size. But when I open the website in the navigator, it turns in a very smaller image, very flat, imcompatible with the image set to the desktop. 
![captura de tela 2018-12-17 as 21 51 10](https://user-images.githubusercontent.com/19910927/50123186-dec61300-0246-11e9-967d-68baad7736fb.png)
![img_0815](https://user-images.githubusercontent.com/19910927/50123232-16cd5600-0247-11e9-955a-a9b3322d9bea.PNG)

**Comment by NataliaBB** [comment]
Hello @falecomcarlito 
Natalia here, Brizy team

Please send me a message via our Facebook chat and mention this issue number  #996 inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
