### ISSUE TITLE
Can not overlap, resize image and colors changes 

### ISSUE THREAD

**Issue by falecomcarlito** [ThemeFuse/Brizy#998]
This are two different issues.

1. Can`t resize image and overlap images and bloks

2.Colors keep changing automatically. I am using an Astra Template that was green. I have changed all the color to blue and the website was. The next day it became green again. And sometimes it is blue at paga builder screen and green at live website.

I made a video to describe the issues.

https://youtu.be/jkM4uLHd5Fg

**Comment by NataliaBB** [comment]
Hey @falecomcarlito 
Let me do some tests please on your page. 

Please send me a message via our Facebook chat and mention this issue number #998 inside. 

![3uoxxwmt5_xnebnahzajyryju-adbjy_yhjv8qowlgwwvtnzacxwfnphxc42yneuwjulaahef8s6hqr82ahvdd0iq-_zmiwljnqsu6s4bo0f1kr3dmujedqc16ubuu85](https://user-images.githubusercontent.com/36154919/45820983-c6e6fd80-bcf0-11e8-9c46-bf7d00172c43.png)

Thank you!
Regards, Natalia

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
